- .github/actions/build/action.yml
- .github/actions/check/action.yml
- .github/actions/test_unit/action.yml
- .github/grcov.yml
- .github/workflows/ci.yml
- .licenserc.yaml
- rust-toolchain.toml
- src/readers/callback.rs
- src/readers/seekable.rs
- tests/it/layer.rs
- tests/it/services/fs.rs
- tests/it/services/s3.rs
- tests/it/wraps.rs
> ci: Add github action CI support

- .github/actions/test_fs/action.yml
- .github/workflows/ci.yml
- Cargo.toml
- rustfmt.toml
- tests/it/services/behavior.rs
- tests/it/services/fs.rs
- tests/it/services/mod.rs
Fix https://github.com/datafuselabs/opendal/issues/8
> tests: Implement behavior tests

- src/services/s3.rs
Fix https://github.com/datafuselabs/databend/issues/4153
> services/s3: Add support for endpoints without scheme

- src/services/s3.rs
This PR will fix default endpoint and region can't works.
> services/s3: Allow set endpoint and region while input value is valid

- Cargo.toml
- benches/s3.rs
- src/services/s3.rs
> services/s3: Don't load_from_env if users already inputs

- src/readers/seekable.rs
This PR intends to improve the seekable reader's performance by introducing chunked read.
> readers: Improve seekable performance

- Cargo.toml
- benches/ops/fs.rs
- benches/ops/main.rs
- benches/ops/ops.rs
- benches/ops/s3.rs
This PR adds benches for read op, we will extend the benchmark to all core ops.
> benches: Implement benches for read op

- benches/ops/ops.rs
- src/readers/seekable.rs
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/.
The default prefetch may not be suitable for every use case. Allowing config prefetch size will make the seekable reader more tunable.
> readers: Allow config prefetch size

- Cargo.toml
- benches/ops/ops.rs
- src/services/fs.rs
This PR intends to replace the `tokio::fs`, see benchmark in https://github.com/datafuselabs/opendal/issues/40.
In general, we will set up a separate thread pool to do blocking IO instead of relying on `tokio`'s.
In the future, we will implement a real async fs backend support based on `io_uring` or `aio`, please keep tuned.
---
Current PR benchmark:
`main` branch:
> services/fs: Use separate dedicated thread pool instead

- Cargo.toml
- docs/rfcs/0044-error-handle.md
- src/error.rs
- src/io.rs
- src/scheme.rs
- src/services/fs.rs
- src/services/s3.rs
- tests/it/services/behavior.rs
RFC: https://github.com/datafuselabs/opendal/pull/44
This PR will refactor OpenDAL error handle logic.
Fix: #24,#29
> error: Implement RFC-0044 Error Handle

- docs/rfcs/0000-auto-region.md
- docs/rfcs/0057-auto-region.md
Address #56 
[rendered](https://github.com/Xuanwo/opendal/blob/rfc_auto_region/docs/rfcs/0057-auto-region.md)
> RFC-0057: Auto Region

- Cargo.toml
- src/services/s3.rs
Change to once_cell from lazy_static
> refactor: Change to once_cell

- src/object.rs
- src/services/fs.rs
- src/services/s3/backend.rs
- src/services/s3/error.rs
- src/services/s3/mod.rs
- src/services/s3/object_stream.rs
- tests/behavior/behavior.rs
> services/s3: Implement List support

- src/credential.rs
- src/services/s3.rs
Add Plain variant to allow more input.
fix #77 
Databend will pass users' input directly without checking:
https://github.com/datafuselabs/databend/blob/f76e4756f859abf697c4a405c01f85621227904c/query/src/sessions/session_mgr.rs#L284-L288
We should check the empty credential and fall back to default logic instead.
> credential: Add Plain variant to allow more input

- README.md
- benches/ops/ops.rs
- docs/rfcs/0090-limited-reader.md
- examples/basic.rs
- src/io.rs
- src/object.rs
- src/tests/io.rs
- tests/behavior/behavior.rs
Fix #86 
Rendered RFC: https://github.com/datafuselabs/opendal/blob/fix-reader/docs/rfcs/0090-limited-reader.md
> RFC and implementations for limited reader

- src/readers/mod.rs
- src/readers/observer.rs
- src/tests/readers.rs
Address https://github.com/datafuselabs/opendal/issues/84
> readers: Implement observe reader support

- benches/ops/ops.rs
> Bench: Add parallel_read bench

- docs/rfcs/0000-path-normalization.md
- docs/rfcs/0112-path-normalization.md
- src/services/fs.rs
- src/services/s3/backend.rs
- src/services/s3/object_stream.rs
- tests/behavior/behavior.rs
> RFC-112: Path Normalization

- .github/workflows/ci.yml
- Cargo.toml
- examples/basic.rs
- src/object.rs
- tests/behavior/behavior.rs
object: Refactor ObjectMode into enum
> object: Refactor ObjectMode into enum

- examples/fs.rs
- examples/list.rs
- examples/metadata.rs
- examples/read.rs
- examples/s3.rs
- examples/write.rs
examples: Add more examples for services and operations
Based on #114
> examples: Add more examples for services and operations

- README.md
> docs: Enrich README

- .env.example
- .github/workflows/service_test_memory.yml
- benches/ops/utils.rs
- opendal_test/src/services/memory.rs
- opendal_test/src/services/mod.rs
- src/services/memory/backend.rs
- src/tests/io.rs
- tests/behavior/fs.rs
- tests/behavior/main.rs
- tests/behavior/memory.rs
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/.
This PR intends to add essential memory support to have a baseline to get started.
We have a simple memory backend support via `HashMap<String, bytes::Bytes>` based on @sundy-li 's work.
- Behavior tests have been passed.
- Benches have been set up.
- CI has been set up (a good start for the future enhancement)
> services: Add full memory support

- Cargo.toml
- src/operator.rs
- src/services/fs/backend.rs
- src/services/fs/object_stream.rs
- src/tests/readers.rs
Refactor via tokio::fs to fix #141
> services/fs: Refactor via tokio::fs

- .github/workflows/ci.yml
- .github/workflows/service_test_fs.yml
- .github/workflows/service_test_memory.yml
- .github/workflows/service_test_s3.yml
- src/accessor.rs
- src/services/memory/backend.rs
- src/services/s3/backend.rs
- tests/behavior/behavior.rs
fix: Stat root should return a dir object
> fix: Stat root should return a dir object

- src/services/s3/object_stream.rs
docs: Remove not need comments anymore
> docs: Remove not need comments anymore

- README.md
> docs: Fix wrong URL in README

- tests/behavior/behavior.rs
test: Add behavior test for not exist object
> test: Add behavior test for not exist object

- src/services/s3/backend.rs
> feat: Improve error handle for s3 service

- examples/s3.rs
>  examples: Improve examples for s3

- src/services/s3/backend.rs
fix(service/s3): Endpoint template should be applied if region exists
> fix(service/s3): Endpoint template should be applied if region exists

- src/io_util/mod.rs
- src/io_util/sink_observer.rs
- src/io_util/stream_observer.rs
feat(io_util): Implement observer for sink and stream
Part of #190
> feat(io_util): Implement observer for sink and stream

- .github/actions/check/action.yml
- opendal_test/src/services/azblob.rs
- opendal_test/src/services/fs.rs
- opendal_test/src/services/memory.rs
- opendal_test/src/services/s3.rs
- src/accessor.rs
- src/error.rs
- src/io.rs
- src/io_util/http_body.rs
- src/io_util/into_reader.rs
- src/io_util/into_sink.rs
- src/io_util/into_stream.rs
- src/io_util/into_writer.rs
- src/io_util/seekable_reader.rs
- src/io_util/sink_observer.rs
- src/io_util/stream_observer.rs
- src/layer.rs
- src/lib.rs
- src/object.rs
- src/operator.rs
- src/scheme.rs
- src/services/azblob/backend.rs
- src/services/azblob/object_stream.rs
- src/services/fs/backend.rs
- src/services/fs/error.rs
- src/services/fs/object_stream.rs
- src/services/memory/backend.rs
- src/services/s3/backend.rs
- src/services/s3/object_stream.rs
- tests/behavior/behavior.rs
refactor: Adopt io::Result instead
> refactor: Adopt io::Result instead

- src/object.rs
- src/services/azblob/backend.rs
- src/services/fs/backend.rs
- src/services/s3/backend.rs
fix: Object last_modified should carry timezone
> fix: Object last_modified should carry timezone

- README.md
- examples/basic.rs
- examples/list.rs
- src/lib.rs
- src/object.rs
- src/operator.rs
- src/ops.rs
- src/services/fs/backend.rs
- tests/behavior/behavior.rs
refactor: Move op.objects() to o.list()
> refactor: Move op.objects() to o.list()

- docs/rfcs/0221-create-dir.md
- src/object.rs
- tests/behavior/behavior.rs
> feat: Simplify create API

- .github/workflows/service_test_azblob.yml
ci: Enable behavior test for azblob
> ci: Enable behavior test for azblob

- .github/workflows/service_test_azblob.yml
- README.md
- src/lib.rs
- src/services/azblob/backend.rs
- src/services/azblob/mod.rs
- src/services/azblob/object_stream.rs
docs: Add docs for azblob's public structs
> docs: Add docs for azblob's public structs

- tests/behavior/behavior.rs
refactor: Improve behavior_tests so that cargo test works without --all-features
> refactor: Improve behavior_tests so that cargo test works without --all-features

- src/services/fs/backend.rs
- tests/behavior/behavior.rs
fix(services/fs): Create on existing dir should succeed
> fix(services/fs): Create on existing dir should succeed

- Cargo.toml
- src/services/azblob/backend.rs
- src/services/memory/backend.rs
- src/services/s3/backend.rs
refactor(services): Convert all expect to errors instead
> refactor(services): Convert all expect to errors instead

- src/scheme.rs
> feat: Add hdfs scheme

- src/services/azblob/backend.rs
fix(azblob): Request URL not construct correctly
> fix(azblob): Request URL not construct correctly

- src/accessor.rs
- src/io_util/compress.rs
- src/lib.rs
- src/object.rs
- src/operator.rs
- src/scheme.rs
- src/services/azblob/backend.rs
- src/services/fs/backend.rs
- src/services/hdfs/backend.rs
- src/services/memory/backend.rs
- src/services/s3/backend.rs
- tests/behavior/behavior.rs
feat: Implement operator metadata support
Fix #130
> feat: Implement operator metadata support

- src/lib.rs
- src/object.rs
- src/services/memory/backend.rs
- tests/behavior/behavior.rs
refactor(object): Make Metadata::name() return &str
> refactor(object): Make Metadata::name() return &str

- Cargo.toml
- src/object.rs
- src/services/azblob/object_stream.rs
- src/services/hdfs/backend.rs
- src/services/memory/backend.rs
- src/services/s3/object_stream.rs
- tests/behavior/behavior.rs
fix(s3): List empty dir could return itself
> fix(services/s3,hdfs): List empty dir should not return itself

- src/accessor.rs
- src/io_util/seekable_reader.rs
- src/layers/retry.rs
- src/lib.rs
- src/object.rs
- src/services/azblob/backend.rs
- src/services/fs/backend.rs
- src/services/hdfs/backend.rs
- src/services/memory/backend.rs
- src/services/s3/backend.rs
refactor: Rename Metadata to ObjectMetadata for clearify
> refactor: Rename Metadata to ObjectMetadata for clearify

- docs/SUMMARY.md
- docs/examples/README.md
- docs/examples/decompress-read.md
- docs/examples/remove_all.md
- docs/examples/server-side-encryption.md
- docs/examples/walk.md
- src/io_util/walk.rs
docs: Aad docs for batch operations
> docs: Aad docs for batch operations

- Cargo.toml
- benches/ops/read.rs
- benches/ops/write.rs
This simplifies the formatting code and removes the old transitive dependencies
of `size` 0.2 (as `size` 0.4 is dependency-free).
It was previously required to explicitly specify the base and unit display style
despite the previous values matching `Size::to_string()`'s defaults (base-2
units and abbreviated names).
Closes #391
> Upgrade dev-dependency `size` to 0.4

- .github/workflows/ci.yml
- .github/workflows/service_test_azblob.yml
- .github/workflows/service_test_fs.yml
- .github/workflows/service_test_hdfs.yml
- .github/workflows/service_test_memory.yml
- .github/workflows/service_test_s3.yml
ci: Don't run CI on not needed push
> ci: Don't run CI on not needed push

- src/io_util/http_client.rs
- src/operator.rs
- tests/behavior/behavior.rs
refactor: Use list for check instead of stat
> refactor: Use list for check instead of stat

- src/object.rs
we could pre-allocate the memory if we know the data size
fixes: https://github.com/datafuselabs/opendal/issues/424
> feat: optimaze range read

- src/ops.rs
feat: BytesRange supports parsing from range and content-range
Fix #446
> feat: BytesRange supports parsing from range and content-range

- src/ops.rs
- src/services/http/backend.rs
- src/services/memory/backend.rs
- tests/behavior/behavior.rs
fix: Service HTTP deosn't handle dir correctly
> fix: Service HTTP deosn't handle dir correctly

- src/io_util/http_client.rs
Related to https://github.com/datafuselabs/opendal/issues/473
> fix: Disable connection pool as workaround for async runtime hang

- oay/Cargo.lock
- oli/Cargo.lock
> chore: Fix oay and oli Cargo.lock not updated

- src/services/s3/backend.rs
fix: Uri encode continuation-token before staring signing
> fix: Uri encode continuation-token before signing

- Cargo.toml
- oay/Cargo.toml
- oli/Cargo.toml
deps: Lower the requirement of deps
> deps: Lower the requirement of deps

- src/http_util/error.rs
> fix: Make ProtocolViolation a retryable error

- src/http_util/header.rs
- src/io_util/into_sink.rs
- src/io_util/into_stream.rs
- src/io_util/seekable_reader.rs
- src/lib.rs
- src/services/azblob/backend.rs
- src/services/gcs/backend.rs
- src/services/http/backend.rs
- src/services/memory/backend.rs
- src/services/s3/backend.rs
Remove all unused qualifications.
Fix #529
> refactor: Remove all unused qualifications

- src/lib.rs
test: Add assert of public struct size
> test: Add assert of public struct size

- .env.example
- examples/ipfs.rs
- src/operator.rs
- src/scheme.rs
- src/services/ipfs/backend.rs
- src/services/ipfs/builder.rs
- src/services/ipfs/dir_stream.rs
- src/services/ipfs/error.rs
- src/services/ipfs/mod.rs
- src/services/ipfs/rpc.rs
- tests/behavior/behavior.rs
Adds a new backend service provider - IPFS
> feat: Add IPFS backend

- src/services/s3/backend.rs
fix(services/s3): If input range is `0..`, don't insert range header
> fix(services/s3): If input range is `0..`, don't insert range header

- src/services/ftp/backend.rs
- src/services/ftp/mod.rs
- src/services/ftp/util.rs
Fix: #638 
**"src/services/ftp/backend.rs"**:
Specify the transfer type to be bianry.
**"src/services/ftp/util.rs"**:
Create a struct wrapper `FtpReader` for ftp data stream and command stream. 
Implement `AsyncRead` trait for `FtpReader`. `poll_read()` will generate a **tokio task** that close both data stream and command stream when we hit `Err` or `EOF`(0-byte read). In other situations, it would just call the default `poll_read()` method of `reader` field.
**Note**: it only works under tokio runtime.
It is workable, but there might exist better solutions (I am reading through this [post](https://internals.rust-lang.org/t/asynchronous-destructors/11127) to find out if there exists a more elegant …
> Finalize FTP read operation 

- .github/workflows/service_test_ftp.yml
- src/services/ftp/backend.rs
- src/services/ftp/dir_stream.rs
- src/services/ftp/mod.rs
- src/services/ftp/util.rs
- src/services/ipfs/backend.rs
- src/services/ipfs/ipld.rs
- tests/behavior/list_only.rs
Fix https://github.com/datafuselabs/opendal/issues/626
> feat(services/ftp): Setup integration tests

- .github/workflows/ci.yml
- Cargo.toml
In the recent changes of switch hyper to reqwest/ureq, the rustls feature is broken for having openssl included. This patch rearranges our feature set, by:
- ~introducing `native-tls` feature that enabled by default, it uses openssl for reqwest (ureq has no openssl support unfortunately)~
- removing `rustls-tls` from `reqwest` because it's already included in `rustls-tls-native-roots`
- turning off default features for `reqwest` to avoid openssl dependencies when using `rustls`
> feat: make rustls the default tls implementation

- src/services/fs/backend.rs
… properly.
Fixes #668.
SeeAlso: https://github.com/datafuselabs/opendal/issues/668#issuecomment-1251508638
> fix(services/fs): Handle slash normalized false positives properly

- oli/Cargo.lock
- oli/Cargo.toml
- oli/src/bin/oli.rs
- oli/src/commands/cli.rs
- oli/src/commands/cp.rs
- oli/src/commands/mod.rs
- oli/src/commands/profile.rs
- oli/tests/cp.rs
- src/services/azblob/backend.rs
Related to #675
Implement basic `cp` for oli:
```
oli cp <source_file> <target_file>
```
> oli: Implement basic cp command

- src/scheme.rs
`FTPS` is a TLS extension to FTP and `OpenDAL` supports it. But the `Scheme` can only be parsed from "FTP"
> chore: also parse 'FTPS' to Scheme::Ftp

- src/services/ftp/backend.rs
When FTP connect failed, the failed operation in message will always be `Delete`
> chore: fix error message

- src/services/ftp/backend.rs
This PR will suffix FTP endpoints with the default port number 21.
Endpoint in `Builder`: `my_ftp.local`
will be:
Endpoint in `Backend`: `ftps://my_ftp.local:21`
> fix(services/ftp): Suffix endpoints with default port

- src/error.rs
- src/http_util/error.rs
- src/layers/retry.rs
- src/object.rs
- src/operator.rs
- src/services/azblob/backend.rs
- src/services/azblob/dir_stream.rs
- src/services/fs/backend.rs
- src/services/ftp/backend.rs
- src/services/ftp/err.rs
- src/services/ftp/util.rs
- src/services/gcs/backend.rs
- src/services/gcs/dir_stream.rs
- src/services/hdfs/backend.rs
- src/services/http/backend.rs
- src/services/ipfs/backend.rs
- src/services/ipmfs/backend.rs
- src/services/ipmfs/dir_stream.rs
- src/services/memory/backend.rs
- src/services/obs/backend.rs
- src/services/obs/dir_stream.rs
- src/services/redis/backend.rs
- src/services/redis/error.rs
- src/services/s3/backend.rs
- src/services/s3/dir_stream.rs
Signed-off-by: STRRL <im@strrl.dev>
close: https://github.com/datafuselabs/opendal/issues/563
- I created 2 functions `new_other_object_error` and `new_other_backend_error` which could return a `io:Error` diectlly.
> refactor: replace error::other with new_other_object_error

- src/accessor.rs
- src/scheme.rs
feat: Make AccessorMetadata public so outer users can use
part of https://github.com/datafuselabs/opendal/issues/744
> feat: Make AccessorMetadata public so outer users can use

- .github/actions/check/action.yml
- src/accessor.rs
- src/io_util/walk.rs
- src/layers/immutable_index.rs
- src/lib.rs
- src/object.rs
- src/services/azblob/backend.rs
- src/services/azblob/dir_stream.rs
- src/services/fs/backend.rs
- src/services/fs/dir_stream.rs
- src/services/ftp/backend.rs
- src/services/ftp/dir_stream.rs
- src/services/gcs/backend.rs
- src/services/gcs/dir_stream.rs
- src/services/hdfs/backend.rs
- src/services/hdfs/dir_stream.rs
- src/services/http/backend.rs
- src/services/ipfs/backend.rs
- src/services/ipmfs/backend.rs
- src/services/ipmfs/dir_stream.rs
- src/services/memory/backend.rs
- src/services/obs/backend.rs
- src/services/obs/dir_stream.rs
- src/services/redis/backend.rs
- src/services/redis/dir_stream.rs
- src/services/s3/backend.rs
- src/services/s3/dir_stream.rs
- tests/behavior/blocking_list.rs
- tests/behavior/list.rs
feat: Implement cached metadata for ObjectEntry
After this PR, our users can full use our metadata stored during list.
> feat: Implement cached metadata for ObjectEntry

- src/services/memory/backend.rs
Fix https://github.com/datafuselabs/opendal/issues/767
Use memory addr instead uuid.
> feat: Assign unique name for memory backend

- docs/comparisons/README.md
docs: Fix wrong link to object_store
> docs: Fix wrong link to object_store

- src/services/s3/dir_stream.rs
fix(services/s3): Content MD5 not set during list
> fix(services/s3): Content MD5 not set during list

- .github/workflows/service_test_ipfs.yml
- src/services/ipfs/error.rs
> ci: Enable IPFS NoFecth to avoid networking timeout

- .github/workflows/ci.yml
ci: Build all feature in release to prevent build failure under release profile
> ci: Build all feature in release to prevent build failure under release profile

- .github/workflows/service_test_ipfs.yml
- src/services/ipfs/backend.rs
fix(services/ipfs): Use ipfs files API to copy data
> fix(services/ipfs): Use ipfs files API to copy data

- src/layers/retry.rs
feat: Convert interrupted error to permanent after retry
> feat: Convert interrupted error to permanent after retry

- .github/workflows/service_test_ftp.yml
- src/services/ftp/err.rs
- tests/behavior/list.rs
Initialization of the test is too slow, this PR saves time by fully parallelise creating procedure.
That's why we introduce async/await, isn't it?
- before
elapsed: 43.692s
- after
elapsed: 24.249s
> test: accelerate behaviour test `test_list_rich_dir`

- src/io_util/walk.rs
- src/operator.rs
fix: ObjectEntry returned in batch operator doesn't have corrent accessor
> fix: ObjectEntry returned in batch operator doesn't have corrent accessor

- src/adapters/kv/api.rs
- src/adapters/kv/backend.rs
- src/services/memory/backend.rs
- src/services/redis/backend.rs
feat: Allow kv services implemented without list support
Fix https://github.com/datafuselabs/opendal/issues/847
> feat: Allow kv services implemented without list support

- docs/comparisons/object_store.md
- src/layers/content_cache.rs
- src/layers/mod.rs
Access the cache on read only, and write to the cache if it is not hit but the data exists in underlying.
Something that needs further consideration is to limit the space available for caching and to provide a suitable cache eviction policy.
> feat(experiment): add a basic content data cache layer

- src/layers/retry.rs
- src/services/obs/error.rs
fix: Retry for wirte is not implemented correctly
Related to https://github.com/datafuselabs/databend/issues/8188
> fix: Retry for wirte is not implemented correctly

- Cargo.toml
- oay/Cargo.lock
- oli/Cargo.lock
- src/services/s3/backend.rs
A very small change. However, md5 has not been updated for many years.
> refactor: replace md5 with md-5

- Cargo.toml
- oay/Cargo.lock
- oli/Cargo.lock
- src/http_util/client.rs
Use feature to control whether `trust-dns` is enabled or not .
Fixes: #874
> feat: add a feature named trust-dns

- Cargo.toml
- src/object/object.rs
- src/ops/op_write.rs
- src/services/azblob/backend.rs
- src/services/gcs/backend.rs
- src/services/obs/backend.rs
- src/services/oss/backend.rs
- src/services/s3/backend.rs
1. implement sync blocking_write_with
2. implement async write_with
3. implement content_type for OpWrite
fix: #875
> feat: `content-type` configuration

- CHANGELOG.md
- Cargo.toml
- oay/Cargo.lock
- oay/Cargo.toml
- oli/Cargo.lock
- oli/Cargo.toml
> Bump to version 0.19.5

- src/layers/metrics.rs
fix: Metrics blocking reader doesn't handle operation correctly
> fix: Metrics blocking reader doesn't handle operation correctly

- src/layers/metrics.rs
refactor(layers/metrics): Holding all metrics handlers to avoid lock
> refactor(layers/metrics): Holding all metrics handlers to avoid lock

- .github/workflows/service_test_ipfs.yml
ci: Debug ipfs integration tests
> ci: Disable ipfs's compress integration tests

- src/services/moka/backend.rs
- [refactor: use moka::sync::SegmentedCache](https://github.com/datafuselabs/opendal/commit/588360c756a32177bb5a763c4c9f636ab3fc73af)
- [feat(services-moka): add option thread_pool_enabled](https://github.com/datafuselabs/opendal/commit/775770fa9f05c0f410fcca8d535d413a38194c50)
- [refactor(services-moka): make num_segments option](https://github.com/datafuselabs/opendal/commit/e4f9fb9de8b0f2f704af2c34529a513a857a1a8f)
Related: https://github.com/datafuselabs/databend/issues/8744
> refactor: use moka::sync::SegmentedCache

- src/accessor.rs
- src/adapters/kv/backend.rs
- src/io_util/seekable_reader.rs
- src/layers/concurrent_limit.rs
- src/layers/content_cache.rs
- src/layers/logging.rs
- src/layers/metrics.rs
- src/layers/retry.rs
- src/layers/subdir.rs
- src/layers/tracing.rs
- src/object/reader.rs
- src/services/azblob/backend.rs
- src/services/fs/backend.rs
- src/services/ftp/backend.rs
- src/services/gcs/backend.rs
- src/services/hdfs/backend.rs
- src/services/http/backend.rs
- src/services/ipfs/backend.rs
- src/services/ipmfs/backend.rs
- src/services/obs/backend.rs
- src/services/oss/backend.rs
- src/services/s3/backend.rs
refactor: Return ObjectReader in Accessor::read
> refactor: Return ObjectReader in Accessor::read

- oay/Cargo.toml
- oli/Cargo.toml
Cargo is smart enough to handle [multiple locations](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations).
> refactor(oay,oli): drop unnecessary `patch.crates-io` from `Cargo.toml`

- Cargo.toml
Add `native-tls` and `native-tls-vendored` features, just like [the way `reqwest` does](https://github.com/seanmonstar/reqwest/blob/81fc85a68949bd0ff73cfd9f292393b5c5ed42ed/Cargo.toml#L35-L38).
While `rustls` is great, it's dependency on `ring` makes it unfit for architectures like powerpc64le, s390x and MIPS because `ring` lacks support for them ATM.
See also https://github.com/rustls/rustls/issues/521
> feat: Allow using opendal with native tls support

- src/adapters/kv/backend.rs
- src/http_util/header.rs
- src/http_util/mod.rs
- src/layers/content_cache.rs
- src/object/object.rs
- src/object/reader.rs
- src/ops/bytes_range.rs
- src/services/azblob/backend.rs
- src/services/fs/backend.rs
- src/services/ftp/backend.rs
- src/services/ftp/err.rs
- src/services/gcs/backend.rs
- src/services/hdfs/backend.rs
- src/services/http/backend.rs
- src/services/ipfs/backend.rs
- src/services/ipmfs/backend.rs
- src/services/obs/backend.rs
- src/services/oss/backend.rs
- src/services/s3/backend.rs
- tests/behavior/read_only.rs
- tests/behavior/write.rs
feat: Make ObjectReader content_length returned for all services
- fix https://github.com/datafuselabs/opendal/issues/952
- fix https://github.com/datafuselabs/opendal/issues/948
- fix https://github.com/datafuselabs/opendal/issues/947
> feat: Make ObjectReader content_length returned for all services

- src/services/redis/backend.rs
fix: Use std Duration as args instead
> fix: Use std Duration as args instead

- src/layers/content_cache.rs
- src/object/stream.rs
build: Make opendal buildable on 1.60
We don't have a strong declear on the msrv about opendal, but we can make our users lives a bit easier.
fix https://github.com/datafuselabs/opendal/issues/967
> build: Make opendal buildable on 1.60

- .env.example
- src/services/fs/backend.rs
Try to impl #788 .
Run the behaviour test with `.env`:
```shell
OPENDAL_FS_TEST=true
OPENDAL_FS_ROOT=/tmp/opendal
OPENDAL_FS_ATOMIC_WRITE_DIR=/tmp/opendal/tmp
```
```sh
$ cargo test fs
....
test result: ok. 172 passed; 0 failed; 0 ignored; 0 measured; 516 filtered out; finished in 0.94s
```
> feat: impl atomic write for fs service

- .github/workflows/service_test_azdfs.yml
- src/operator.rs
- src/scheme.rs
- src/services/azdfs/backend.rs
- src/services/azdfs/dir_stream.rs
- src/services/azdfs/error.rs
- src/services/azdfs/mod.rs
- src/services/mod.rs
- tests/behavior/main.rs
Fix https://github.com/datafuselabs/opendal/issues/993
> feat: Add azdfs support

- Cargo.toml
- src/services/fs/backend.rs
Under the current implementation, it will create many unnecessary temp folders when enabling atomic write in fs service.
So in this PR, I removed these temp folders, all temp files will be created in `atomic_write_path` folder but using a temp file name.
> feat: improve temp file organization when enable atomic write in fs

- src/object/object.rs
- src/ops.rs
- src/services/oss/backend.rs
- src/services/s3/backend.rs
- tests/behavior/presign.rs
This pull request adds support for generating pre-signed URLs for the HEAD method on Amazon S3 and Aliyun OSS (Object Storage Service) objects. 
This allows clients to perform presign head operation on s3 or oss, as an example:
```rust
use anyhow::Result;
use futures::io;
use opendal::services::memory;
use opendal::Operator;
use time::Duration;
#[tokio::main]
async fn main() -> Result<()> {
let op = Operator::from_env(Scheme::Memory)?;
let signed_req = op.object("test").presign_stat(Duration::hours(1))?;
let req = http::Request::builder()
.method(signed_req.method())
.uri(signed_logreq.uri())
.body(())?;
Ok(())
}
```
This pull request has passed all the necessary checks and tests, including static …
> feat(presign): support presign head method for s3 and oss

- src/services/moka/backend.rs
fix(services/moka): Don't print all content in cache
> fix(services/moka): Don't print all content in cache

- src/object/object.rs
- tests/behavior/blocking_write.rs
- tests/behavior/write.rs
Close #943 fix error if block range read with a large range and add test for it.
> fix: read a large range without error and add test

- benches/ops/read.rs
- src/object/object.rs
1. fix a bug in bench
2. use `read_to_end` instead of `std::io::copy`
> improve blocking read use read_to_end

- src/services/fs/backend.rs
closing #1056 , avoid seek if offset is 0
> feat(fs): skip seek if offset is 0

- src/layers/cache/accessor.rs
- src/layers/cache/policy.rs
- src/layers/concurrent_limit.rs
- src/layers/logging.rs
- src/layers/metrics.rs
- src/layers/retry.rs
- src/layers/subdir.rs
- src/layers/tracing.rs
- src/object/reader.rs
- src/raw/accessor.rs
- src/raw/adapters/kv/backend.rs
- src/raw/http_util/body.rs
- src/raw/io.rs
- src/raw/io_util/seekable_reader.rs
- src/raw/mod.rs
- src/raw/wrappers/error_context.rs
- src/services/azblob/backend.rs
- src/services/azdfs/backend.rs
- src/services/fs/backend.rs
- src/services/ftp/backend.rs
- src/services/ftp/util.rs
- src/services/gcs/backend.rs
- src/services/hdfs/backend.rs
- src/services/http/backend.rs
- src/services/ipfs/backend.rs
- src/services/ipmfs/backend.rs
- src/services/obs/backend.rs
- src/services/oss/backend.rs
- src/services/s3/backend.rs
feat: Split bytes reader into input and output
We have different requirement for user input and opendal's output.
> feat: Split bytes reader into input and output

- Cargo.toml
- src/services/azblob/backend.rs
See https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview for more info.
This change builds on the SAS token support added in https://github.com/Xuanwo/reqsign/pull/215
> Add support for SAS tokens in Azure blob storage

- src/error.rs
- src/object/object.rs
- src/raw/http_util/client.rs
fix: Allow range_read to be retired
> fix: Allow range_read to be retired

- src/error.rs
- src/services/ghac/error.rs
fix: ghac shall return ObjectAlreadyExists for writing the same path
fixed https://github.com/datafuselabs/opendal/issues/1155
> fix: ghac shall return ObjectAlreadyExists for writing the same path

- .github/workflows/service_test_memcached.yml
- src/services/memcached/backend.rs
fix(services/memcached): TcpStream should only accept host:port
> fix(services/memcached): TcpStream should only accept host:port

- Cargo.toml
- src/object/reader.rs
> feat: implement tokio::io::{AsyncRead, AsyncSeek} for ObjectReader

- README.md
This `PR` fix function name change in README quick start.
also change dir to  `/tmp/test_file`(like examples) because when use `mac` may cause 
`read-only filesystem or storage medium, source: Read-only file system (os error 30)` problem.
its a little confusion for new users to use `quick start`
> doc: fix name change in README

- Cargo.toml
- benches/layers.rs
- benches/ops/utils.rs
- examples/tracing_layer.rs
- tests/behavior/utils.rs
+ Removes the `dotenv` dependency since it is not used anywhere.
+ Replaces the `dotenv` dev-dependency with `dotenvy`.
+ Resolves #1186
> chore(deps): replace dotenv with dotenvy

- src/raw/http_util/client.rs
- src/services/azblob/backend.rs
- src/services/azdfs/backend.rs
- src/services/gcs/backend.rs
- src/services/ghac/backend.rs
- src/services/http/backend.rs
- src/services/ipfs/backend.rs
- src/services/ipmfs/builder.rs
- src/services/obs/backend.rs
- src/services/oss/backend.rs
- src/services/s3/backend.rs
feat: Allow setting http client that built from external
> feat: Allow setting http client that built from external

- Cargo.toml
This PR ensures the library is buildable with cargo `-Z minimal-versions` enabled
Signed-off-by: 蔡略 <cailue@bupt.edu.cn>
> chore: ensure minimal version buildable

- src/layers/metrics.rs
Unlike `request_total` and `bytes_total`, not all operation will hit errors. So it's better to defer the initiation of error counters until we really need them.
Fix https://github.com/datafuselabs/opendal/issues/1231
> refactor(layers/metrics): Defer initiation of error counters

- src/services/ghac/backend.rs
Signed-off-by: Rajiv Shah <rajivshah1@icloud.com>
If an error with `ghac_upload` occurs in the `write` function, it is actually logged as an error with `ghac_commit`
> fix(services/ghac): Fix log message for `ghac_upload` in `write`

- src/object/object.rs
- src/ops.rs
- src/services/oss/backend.rs
Currently, there's no content-type header at all in the current presign operation. However, browsers have a limit about there's no way to NOT passing Content-Type on a `fetch()` operation. Thus it's hard to do upload presigned urls in a website.
This PR allows passing content-type on presign write operations:
- addes `presign_write_with` method to Object
- passes the content_type argument on presigning write operations
fixes #421
> feat: Allow passing content_type to OSS presign

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .licenserc.yaml
Signed-off-by: Chojan Shang <psiace@outlook.com>
Close: #925
> feat: add dev container

- src/builder.rs
- src/error.rs
- src/lib.rs
- src/operator.rs
> docs: fix typo

- bindings/nodejs/src/lib.rs
- bindings/object_store/src/lib.rs
- bindings/python/src/lib.rs
- src/layers/chaos.rs
- src/layers/concurrent_limit.rs
- src/layers/logging.rs
- src/layers/metrics.rs
- src/layers/retry.rs
- src/layers/tracing.rs
- src/raw/io/output/into_reader/by_range.rs
- src/raw/layer.rs
fix: FsBuilder can't be used with empty root anymore
> fix: FsBuilder can't be used with empty root anymore

- CHANGELOG.md
- Cargo.toml
- binaries/oay/Cargo.lock
- binaries/oli/Cargo.lock
- src/scheme.rs
- src/services/hdfs/backend.rs
- src/services/webhdfs/backend.rs
> Bump to version 0.26.2

- src/services/oss/backend.rs
> chore: fix name typo in oss backend

- CHANGELOG.md
- Cargo.toml
- binaries/oay/Cargo.lock
- binaries/oay/Cargo.toml
- binaries/oli/Cargo.lock
- binaries/oli/Cargo.toml
- bindings/nodejs/Cargo.toml
- bindings/object_store/Cargo.toml
- bindings/python/Cargo.toml
- src/docs/upgrade.md
> Bump to version 0.27

- src/services/webdav/backend.rs
This PR adds username and password support forWebDAV
Please review the changes, if it's ok I will do the same for `HttpBuilder`
#1319 #1237
> feat: Add username and password support for WebDAV

- .github/workflows/service_test_webdav.yml
- .licenserc.yaml
- src/services/webdav/fixtures/htpasswd
- src/services/webdav/fixtures/nginx-with-basic-auth.conf
- src/services/webdav/fixtures/nginx.conf
ci: Add test case for webdav with basic auth
> ci: Add test case for webdav with basic auth

- src/services/oss/dir_stream.rs
- src/services/s3/dir_stream.rs
fix(services/{oss,s3}): Metadata should be marked as complete
> fix(services/oss,s3): Metadata should be marked as complete

- src/lib.rs
- src/object/metadata.rs
- src/ops.rs
1. add Content-Disposition support for ObjectMetadata
2. add Content-Disposition support for OpWrite
> feat: add Content-Disposition for inner API

- src/raw/http_util/header.rs
- src/raw/http_util/mod.rs
- src/services/azdfs/backend.rs
- src/services/ipfs/backend.rs
- src/services/oss/backend.rs
- src/services/s3/backend.rs
- src/services/webdav/backend.rs
added support for:
1. azdfs    write   stat
2. ipfs             stat
3. ali oss  write   stat
4. aws s3   write   stat
5. webdav   write   stat
for other services, if the HTTP response includes `Content-Disposition`, the ObjectMetadata will got it.
solves: #1346
> feat: add content-disposition support for services

- src/services/webdav/backend.rs
if username and password aren't set, the http request needn't authorization
> refactor: Authorization logic for WebdavBackend

- src/services/http/backend.rs
- src/services/webdav/backend.rs
add Basic and Bearer authorization support for `HttpBackend`
#1237
> feat: support auth for HttpBackend

- Cargo.toml
ci: Pin time <= 0.3.17 until we decide to bump MSRV
Related to https://github.com/time-rs/time/issues/551
> ci: Pin time <= 0.3.17 until we decide to bump MSRV

- src/raw/http_util/header.rs
- src/raw/http_util/mod.rs
- src/services/webhdfs/backend.rs
- src/services/webhdfs/message.rs
OpenDAL will handle all redirections, and auto redirection of client is not taken into considerations. So for WebHDFS, handler redirections directly instead of `noredirect=true`. This also offers better compatibility.
fixes: #1355
> refactor(webhdfs): handle 307 redirection instead of noredirect

- .config/nextest.toml
- .github/workflows/ci.yml
`nextest` is fast, but not particularly improved, especially if we have to doctests separately.
But an interesting thing is that `nextest` needs to run 1286 tests, while `test` needs to run 1200 + 87(docs) tests.
For services, I have not added `nextest` because the number of tests that need to be run is too small.
Closes: #1360
> ci: run tests with nextest

- CHANGELOG.md
- Cargo.toml
- binaries/oay/Cargo.lock
- binaries/oli/Cargo.lock
> Bump to version 0.27.2

- .github/workflows/service_test_dashmap.yml
- Cargo.toml
- README.md
- src/scheme.rs
- src/services/dashmap/backend.rs
- src/services/dashmap/mod.rs
- src/services/mod.rs
- tests/behavior/main.rs
Refer to the moka and memory implementations.
Tests failure is encountered when the environment variable `OPENDAL_DASHMAP_TEST=on`
```
---- services_dashmap_list::test_list_dir stdout ----
Error: Unsupported (persistent) at scan, context: { called: kv::Adapter::scan, service: dashmap, path: / } => kv adapter doesn't support this operation
failures:
services_dashmap_list::test_check
services_dashmap_list::test_list_dir
services_dashmap_list::test_list_dir_metadata_cache
services_dashmap_list::test_list_empty_dir
services_dashmap_list::test_list_nested_dir
services_dashmap_list::test_list_non_exist_dir
services_dashmap_list::test_list_rich_dir
services_dashmap_list::test_list_sub_dir …
```
> feat: add dashmap support

- src/layers/complete.rs
- src/object/metadata.rs
- src/object/object.rs
refactor: Store complete inside bits  and add more examples
> refactor: Store complete inside bits  and add more examples

- binaries/oay/src/services/http/mod.rs
- binaries/oli/src/commands/cp.rs
- bindings/object_store/src/lib.rs
- src/layers/complete.rs
- src/layers/immutable_index.rs
- src/lib.rs
- src/object/metadata.rs
- src/object/mod.rs
- src/object/object.rs
- src/object/reader.rs
- src/operator.rs
- tests/behavior/blocking_write.rs
- tests/behavior/list.rs
- tests/behavior/write.rs
refactor: Polish the implement of Query Based Metadata Cache
> refactor: Polish the implement of Query Based Metadata Cache

- src/docs/features.md
add services-dashmap to `opendal::docs::features`
Closes: #1403
> docs: Add services-dashmap feature

- src/services/oss/backend.rs
close #1430
oss backend support http protocol instead of just allow https.
> feat: oss backend support http protocol

- src/object/metadata.rs
- src/object/object.rs
- src/object/writer.rs
- src/raw/accessor.rs
- src/raw/http_util/bytes_content_range.rs
- src/raw/http_util/dns.rs
- src/raw/oio/into_reader/by_range.rs
- src/raw/oio/into_streamable.rs
- src/raw/oio/read.rs
- src/raw/oio/to_hierarchy_pager.rs
- src/raw/oio/write.rs
- src/raw/rps.rs
- src/services/fs/backend.rs
- src/services/gcs/backend.rs
- src/services/moka/backend.rs
Corrected the vast majority of typos in the project.
> chore: fix typo

- benches/ops/utils.rs
- benches/ops/write.rs
benches: Generate into Bytes instead
> benches: Generate into Bytes instead

- src/object/list.rs
- src/object/object.rs
- src/operator/builder.rs
- src/operator/operator.rs
- src/raw/oio/entry.rs
refactor: Split operator APIs into different part
> refactor: Split operator APIs into different part

- src/docs/rfcs/0429_init_from_iter.md
- src/docs/rfcs/0977_refactor_error.md
- src/docs/rfcs/1391_object_metadataer.md
- src/docs/rfcs/1398_query_based_metadata.md
- src/docs/rfcs/1420_object_writer.md
- src/layers/retry.rs
- src/raw/oio/entry.rs
- src/services/s3/writer.rs
- src/services/webhdfs/error.rs
- src/types/entry.rs
- src/types/operator/builder.rs
- src/types/operator/operator.rs
> chore: typo

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/service_test_rocksdb.yml
- Cargo.lock
- Cargo.toml
- src/services/rocksdb/backend.rs
- src/services/sled/backend.rs
ci: Improve rocksdb build speed by link dynamic libs
> ci: Improve rocksdb build speed by link dynamic libs

- src/services/ftp/backend.rs
- src/services/ftp/pager.rs
It closes #1438.
We merge the functionality of `services::ftp::ReadDir` into `FtpPager`, and use `std::vec::IntoIter` for more compact code.
> refactor: remove ReadDir in FTP service

- src/services/webdav/writer.rs
- src/types/operator/blocking_operator.rs
- src/types/operator/operator.rs
- tests/behavior/blocking_list.rs
- tests/behavior/blocking_write.rs
- tests/behavior/list.rs
- tests/behavior/write.rs
> refactor: rename public api `create` to `create_dir`

- bindings/nodejs/__test__/index.spec.ts
- bindings/nodejs/src/lib.rs
Adding support for String can be more convenient.
> feat(bindings/nodejs): write support string

- bindings/python/src/lib.rs
- bindings/python/tests/test_core.py
Add support for services that opendal enables by default, thanks to Copilot!
> feat(bindings/python): add support for services that opendal enables by default

- bindings/nodejs/__test__/index.spec.ts
- bindings/nodejs/src/lib.rs
remove `Operator.writer` until we are ready
> feat(bindings/nodejs): Remove `Operator.writer` until we are ready

- bindings/nodejs/__test__/index.spec.ts
- bindings/nodejs/src/lib.rs
Support `Operator.create_dir`
with
- `Metadata.isDirectory()`
- `Metadata.isFile()`
> feat(bindings/nodejs): Support `Operator.create_dir`

- src/raw/oio/entry.rs
- src/types/entry.rs
- src/types/operator/blocking_operator.rs
- src/types/operator/operator.rs
- tests/behavior/blocking_list.rs
- tests/behavior/list.rs
> feat: Entry refactoring to allow external creation

- bindings/nodejs/__test__/index.spec.ts
- bindings/nodejs/src/lib.rs
Support `Operator.scanSync` & `Operator.listSync`
> feat(bindings/nodejs): Support `Operator.scanSync` & `Operator.listSync`

- bindings/nodejs/__test__/index.spec.ts
- bindings/nodejs/src/lib.rs
refactor(bindings/nodejs): Remove scheme from bindings
> refactor(bindings/nodejs): Remove scheme from bindings

- src/types/builder.rs
- src/types/operator/builder.rs
docs: Fix `Operator::create()` has been removed
> docs: Fix `Operator::create()` has been removed

- src/types/reader.rs
a following `seek` will error with `another search is in progress`
> fix: reset Reader::SeekState when poll completed

- .asf.yml
- .github/workflows/docs.yml
> ci: Use gh-pages instead

- .asf.yaml
* I think it would be better to set the main branch to be protected
> ci: set main branch to be protected

- .github/PULL_REQUEST_TEMPLATE.md
This project has been donated to the ASF. Also, the "summary" section becomes redundant after we remove the CLA part.
> chore: remove PULL_REQUEST_TEMPLATE

- website/docusaurus.config.js
Currently, the website only had one link to the project's GitHub address at the bottom, which was not very prominent.
I restored the GitHub link button in the nav bar for user convenience.
> website: Add GitHub entry

- Cargo.toml
- README.md
- binaries/oli/Cargo.toml
- bindings/c/Cargo.toml
- bindings/c/cbindgen.toml
- bindings/nodejs/Cargo.toml
- bindings/nodejs/package.json
- bindings/object_store/Cargo.toml
- bindings/python/Cargo.toml
Drop "Databend Authors" metadata;
~~Organize metadata in hierarchy.~~ See https://github.com/apache/incubator-opendal/pull/1666#issuecomment-1473759054
> chore: Update metadata

- .github/workflows/docs.yml
- bindings/python/src/asyncio.rs
- bindings/python/src/lib.rs
- website/docusaurus.config.js
* Use `pdoc` to generate API docs.
> feat(bindings/python): add auto-generated api docs

- bindings/python/Cargo.toml
- bindings/python/pyproject.toml
See https://pyo3.rs/v0.18.1/faq#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror
`maturin` has changed the default project layout generated from `maturin new` to exactly this to avoid such issue.
Fixes #1675
> refactor(bindings/python): only enable `pyo3/entension-module` feature when building with maturin

- bindings/python/src/asyncio.rs
- bindings/python/src/lib.rs
It's nice to have these.
```python
>>> import opendal
>>> op = opendal.Operator("memory")
>>> op
Operator("memory", root="/", name="0x6000008c4050")
```
> feat(bindings/python): add `__repr__` to `Operator` and `AsyncOperator`

- core/src/types/operator/operator.rs
we should not comment out the `use` expr as it is used explicitly in examples.
especially the `futures::TryStreamExt`, it was not mentioned in docs, but has to be added to make `try_next` work.
> doc: uncomment the use expr for operator example

- bin/oli/Cargo.toml
- bin/oli/src/config/mod.rs
Ref #422 
Now with the following config:
```
[profiles.redis]
type = "redis"
[profiles.ustcmirror]
type = "http"
endpoint = "https://mirrors.ustc.edu.cn"
```
and compile `oli` with the following command
```
cargo build -p oli -F services-redis
```
`oli` could download a file from a website and save it to redis 🚀 
```
$ ./target/debug/oli cp ustcmirror://archlinux/lastupdate redis://oli:lastsync
$ redis-cli get "oli:lastsync"
"1679393591\n"
```
> feat: make oli support more services

- core/src/docs/rfcs/0000_operation_extension.md
- core/src/docs/rfcs/1735_operation_extension.md
- core/src/docs/rfcs/mod.rs
Addressing the feautres requested by:
- https://github.com/apache/incubator-opendal/issues/892 wants [Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control): Allow users to specify the cache control headers for the uploaded files.
- https://github.com/apache/incubator-opendal/issues/825 wants [If-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match) and [If-None-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match): Allow users to makes a request conditional.
- https://github.com/apache/incubator-opendal/issues/1726 wants [response-content-disposition](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html): Allow users to specify the content disposition for the downloaded files.
> RFC-1735: Operation Extension

- bin/oli/src/commands/cp.rs
- bin/oli/src/config/mod.rs
Per [RFC](https://github.com/apache/incubator-opendal/blob/main/core/src/docs/rfcs/0423_command_line_interface.md):
```
Besides, `oil` will read profile from env like `cargo`:
- `OIL_PROFILE_TEST_TYPE=s3`
- `OIL_PROFILE_TEST_ENDPOINT=http://127.0.0.1:1090`
- `OIL_PROFILE_TEST_BUCKET=test_bucket`
- `OIL_PROFILE_TEST_ACCESS_KEPT_ID=access_key_id`
- `OIL_PROFILE_TEST_SECRET_ACCESS_KEY=secret_access_key`
```
`oli` should be able to be configured by environment variables.
> feat(oli): load config from both env and file

- bindings/nodejs/tests/binding.js
- bindings/python/tests/steps/binding.py
- bindings/ruby/src/lib.rs
- bindings/ruby/tests/steps/binding.rb
- bindings/tests/features/binding.feature
```
2 scenarios (1 pending, 1 passed)
12 steps (5 skipped, 1 pending, 6 passed)
0m0.009s
```
> feat(bindings/ruby): support stat, and pass all blocking bdd test

- bindings/ruby/src/lib.rs
- bindings/ruby/tests/steps/binding.rb
ref https://github.com/matsadler/magnus/issues/68
> feat(bindings/ruby): add namespace

- core/src/services/s3/backend.rs
- core/src/types/operator/operator.rs
- core/src/types/ops.rs
Adds the `override_content_disposition` field as described in #1735 
Fix https://github.com/apache/incubator-opendal/issues/1739
> feat: Add override_content_disposition for OpRead

- .gitignore
- Cargo.lock
- bindings/java/Cargo.toml
- bindings/java/pom.xml
- bindings/java/readme.md
- bindings/java/src/lib.rs
- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/test/java/org/apache/opendal/operator/OperatorTest.java
Explanation:
* Mutex lock free: in Java, class constructor is thread-safe so calling native method doesn't need a lock.
* Holding pointer of operator in ``Operator.java`` and free it when Java instance be destroyed by GC.
* Java doesn't native support async/await, maybe we can try Kotlin.
> feat(bindings/java): add java binding

- bin/oli/src/bin/oli.rs
- bin/oli/src/commands/cli.rs
- bin/oli/src/commands/ls.rs
- bin/oli/src/commands/mod.rs
Fix #1740 
Output:
```
$ ./target/debug/oli ls s3://prod/
20230310/
20230313/
$ ./target/debug/oli ls s3://prod/ -r
prod/20230310/material_asset.txt
prod/20230310/model_asset.txt
prod/20230313/material_asset.txt
prod/20230313/model_asset.txt
```
> feat(oli): implement `oli ls`

- bin/oli/src/commands/cat.rs
- bin/oli/src/commands/cp.rs
- bin/oli/src/commands/ls.rs
- bin/oli/src/config/mod.rs
Per https://github.com/apache/incubator-opendal/discussions/1765#discussioncomment-5425812:
>  Instead, all serivces should stick to / as root to make the internal logic cleaner.
> fix(oli): set the root of fs service to '/'

- bindings/python/Cargo.toml
- bindings/python/pyproject.toml
See https://github.com/PyO3/maturin/releases/tag/v0.14.16
> chore(bindings/python): update maturin to 0.14.16

- bin/oli/src/bin/oli.rs
- bin/oli/src/commands/cli.rs
- bin/oli/src/commands/mod.rs
- bin/oli/src/commands/stat.rs
Fix #1775 
Output:
```
$ ./target/debug/oli stat s3://prod/20230313/model_asset.txt
Path: prod/20230313/model_asset.txt
Size: 85248
Etag: "44739e04cf530998004923a11a981728"
Type: file
Content-Type: binary/octet-stream
LastModified: 2023-03-13 2:42:28.0 +00:00:00
$ ./target/debug/oli stat s3://prod/20230313/
Path: prod/20230313/
Size: 0
Type: dir
$ ./target/debug/oli stat ./Cargo.toml
Path: github/opendal/Cargo.toml
Size: 990
Type: file
LastModified: 2023-03-24 15:24:29.749171368 +00:00:00
```
> feat(oli): implement `oli stat`

- .github/workflows/bindings_nodejs.yml
- bindings/nodejs/index.d.ts
- bindings/nodejs/npm/darwin-arm64/README.md
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/package.json
append support of aarch64-apple-darwin
> ci(bindings/nodejs): Support aarch64-apple-darwin

- bin/oli/src/commands/cat.rs
- bin/oli/src/commands/cli.rs
- bin/oli/src/commands/cp.rs
- bin/oli/src/commands/ls.rs
- bin/oli/src/commands/rm.rs
- bin/oli/src/commands/stat.rs
Use `env!` to get the package version in compiling time
> chore(bin/oli): Set oli version from package version

- core/src/types/operator/operator.rs
Implements `reader_with` and `writer_with`.
Fixes https://github.com/apache/incubator-opendal/issues/1750
> feat: reader_with and writer_with

- core/src/services/s3/backend.rs
- core/src/services/s3/writer.rs
- core/src/types/ops.rs
Adds `cache_control` to `OpWrite`.
Fixes: https://github.com/apache/incubator-opendal/issues/1747
> feat: add cache_control to OpWrite

- core/src/layers/retry.rs
- core/src/raw/rps.rs
Also added a test for retry on batch operation.
This implementation works as expected but is not so elegant as far as I'm considering. Batch operation could possibly be retried even when result is `Ok`. So I had to wrap it in a `Result<(), Result<RpBatch>>` type. And the `errors` method on `BatchedResults` requires dynamic dispatching.
Regarding the issue mentioned above, would you be able to suggest any better solutions or provide further guidance?
> feat: Retry when some of batch operations are failing

- core/src/docs/internals/accessor.rs
- core/src/docs/internals/layer.rs
I have found several typos along reading the developer documentations.
> docs: fix several typos in the documentation

- bindings/c/Makefile
Fixed the OBJDIR creation and library link flag
* The library created by cbindgen is called libopendal_c instead of libopendal, so the original `-lopendal` does not work
* At least on my machine, the `OBJDIR` is not created by the Makefile, so this change make sure that the directory is created.
> feat(bindings/c): fix c bindings makefile

- bindings/c/Makefile
1. `make build` will do nothing if `build` dir existed without `.PHONY`
2. only `make build` should create the `build` dir, so keep it under `make build`
3. we should be careful to `rf -rf`, so added a quote and `./`
> binding/c: build: add phony to makefile, and some improve

- core/src/services/s3/backend.rs
- core/src/services/s3/writer.rs
- core/src/types/ops.rs
Fix #1751 
This PR adds `storage_class` option to `OpWrite` and enables users to specify  default `storage_class` or override it when using `s3` backend.
> feat(s3): allow users to specify storage_class

- core/src/services/fs/backend.rs
- core/src/services/s3/backend.rs
- core/tests/behavior/copy.rs
> fix(core): S3 Copy should set SSE headers

- core/src/services/s3/backend.rs
For issue https://github.com/apache/incubator-opendal/issues/1375, changes include:
- Add a helper function `is_valid_bucket`, combine non empty check and `enable_virtual_host_style` check for bucket name
- Update `build_endpoint` and `build` functions to apply the helper
- Add unit tests
> Add check for s3 bucket name

- bindings/nodejs/index.d.ts
- bindings/nodejs/src/lib.rs
- core/tests/behavior/blocking_copy.rs
- core/tests/behavior/copy.rs
- core/tests/behavior/rename.rs
Sync `copy` and `rename` to nodejs binding.
> feat(bindings/nodejs): add `copy` and `rename`

- core/src/services/azblob/backend.rs
> feat(azblob): Support copy

- core/src/services/webdav/backend.rs
- core/src/services/webdav/fixtures/nginx-with-basic-auth.conf
- core/src/services/webdav/fixtures/nginx.conf
> feat(webdav): support copy

- core/src/services/oss/backend.rs
> feat(services/oss): Add Copy Support

- bindings/python/benchmark/async_opendal_benchmark.py
- bindings/python/python/opendal/__init__.py
- bindings/python/python/opendal/__init__.pyi
- bindings/python/tests/steps/binding.py
I format all Python code by using black tools in this PR
> binding(python): Format python code in binding

- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/types.rs
- bindings/c/tests/basicio.c
* Add the freeing of the operator
* Modify the test to free the operator after the test
> feat(bindings/c): add support for free heap-allocated operator

- core/Cargo.toml
- core/src/raw/http_util/body.rs
- core/src/raw/http_util/client.rs
- core/src/raw/http_util/mod.rs
- core/src/raw/rps.rs
- core/src/services/azblob/backend.rs
- core/src/services/azblob/writer.rs
- core/src/services/azdfs/backend.rs
- core/src/services/azdfs/writer.rs
- core/src/services/gcs/backend.rs
- core/src/services/gcs/writer.rs
- core/src/services/ghac/backend.rs
- core/src/services/ghac/writer.rs
- core/src/services/http/backend.rs
- core/src/services/ipfs/backend.rs
- core/src/services/ipmfs/backend.rs
- core/src/services/obs/backend.rs
- core/src/services/obs/writer.rs
- core/src/services/oss/backend.rs
- core/src/services/oss/writer.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/writer.rs
- core/src/services/webdav/backend.rs
- core/src/services/webhdfs/backend.rs
- core/src/services/webhdfs/writer.rs
We will not relay on blocking http client for signing.
> refactor: Remove not used blocking http client

- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/result.rs
- bindings/c/src/types.rs
* Add `is_exist` operation to check whether the path exists, which is required in BDD tests.
*  The test for `is_exist` will be added when we support the `Fs` backend.
> feat(binding/c): add is_exist to operator

- bindings/c/src/lib.rs
- bindings/c/src/result.rs
- bindings/nodejs/src/lib.rs
- core/src/layers/error_context.rs
- core/src/layers/logging.rs
- core/src/layers/metrics.rs
- core/src/layers/tracing.rs
- core/src/raw/accessor.rs
- core/src/raw/layer.rs
- core/src/services/oss/backend.rs
- core/src/services/s3/backend.rs
- core/src/types/operator/operator.rs
- core/tests/behavior/presign.rs
In the future:
- `reqsign` will be async
- there may have `blocking_presign`
> refactor: Change presign to async for future refactor

- bindings/python/README.md
> docs: Adding docs link to python binding

- core/tests/behavior/blocking_copy.rs
- core/tests/behavior/blocking_rename.rs
- core/tests/behavior/copy.rs
- core/tests/behavior/rename.rs
Since some backends may need to create parent directories one layer at a time, increase the nested depth to cover this scenario.
> test: Increate copy/move nested path test depth

- Cargo.lock
- core/Cargo.toml
- core/src/layers/minitrace.rs
- core/src/layers/mod.rs
It simply works and needs to consider how to properly reflect the parent-child relationship of the call.
Fix #691
> feat(layers): add a basic minitrace layer

- core/src/layers/concurrent_limit.rs
- core/src/layers/error_context.rs
- core/src/layers/logging.rs
- core/src/layers/metrics.rs
- core/src/layers/minitrace.rs
- core/src/layers/prometheus.rs
- core/src/layers/retry.rs
- core/src/layers/tracing.rs
- core/src/raw/adapters/kv/backend.rs
- core/src/raw/oio/write.rs
- core/src/services/azblob/writer.rs
- core/src/services/azdfs/writer.rs
- core/src/services/fs/writer.rs
- core/src/services/ftp/writer.rs
- core/src/services/gcs/writer.rs
- core/src/services/ghac/writer.rs
- core/src/services/hdfs/writer.rs
- core/src/services/ipmfs/writer.rs
- core/src/services/obs/writer.rs
- core/src/services/oss/writer.rs
- core/src/services/s3/core.rs
- core/src/services/s3/writer.rs
- core/src/services/webdav/writer.rs
- core/src/services/webhdfs/writer.rs
This PR:
- adds `oio::Write::abort` API to allow cancellation of an on-going append writer
- for those writers do not support `append`, adds a `Write::abort` implementation that simply return `Ok(())`
- adds delegated implementations of `oio::Write::abort` for all layers
- adds `oio::Write::abort` implementation for `S3Writer` as an example
This PR does not add an equivalent API in `oio::BlockingWrite`, since we can always add a `Drop` implementation for blocking writers and delete partial objects in `Drop::drop`.
#1607
> feat: add Writer::abort method

- core/src/services/http/backend.rs
- core/src/types/operator/operator.rs
Fix https://github.com/apache/incubator-opendal/issues/1975
> feat: add http if_none_match support

- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
Fix https://github.com/apache/incubator-opendal/issues/1983
> feat(services/gcs): Allow setting default storage_class

- core/src/services/azblob/core.rs
fix #1999 
It looks like the image `mcr.microsoft.com/azure-storage/azurite` is slightly different from the production service. 
This problem has also been seen on the `azdfs` service.
cc @Xuanwo
> fix(services/azblob): fix copy missing content-length

- core/src/services/memory/backend.rs
As seen in [https://github.com/apache/incubator-opendal/blob/aa8b9e52801947c1799a5efa7107c14e94ec300a/core/src/services/memory/backend.rs#L80](https://github.com/apache/incubator-opendal/blob/aa8b9e52801947c1799a5efa7107c14e94ec300a/core/src/services/memory/backend.rs#L80) It is implemented based on BTreeMap, rather than HashMap.
And Most key values are paths. Will it become better to use TrieTreeMap?
> docs(services/memory): Fix wrong explanation

- .github/workflows/service_test_fs.yml
- core/tests/behavior/README.md
- core/tests/behavior/read_only.rs
- website/docs/vision.md
Add some tips for behavior tests.
> doc: update VISION and behavior tests doc

- bin/oli/src/bin/oli.rs
This PR just polish the output of oli command line when no subcommand was input.
Before:
```bash
Error: not handled
```
After:
```bash
OpenDAL Command Line Interface
Usage: oli [OPTIONS] <COMMAND>
Commands:
cat   display object content
cp    copy
ls    ls
rm    remove object
stat  show object metadata
help  Print this message or the help of the given subcommand(s)
Options:
--config <config>  Path to the config file [default: /root/.config/oli/config.toml]
-h, --help             Print help
-V, --version          Print version
```
> feat: improve the readability of oli command line error output

- core/src/types/ops.rs
close #1966 
This PR introduces `if_match: Option<String>` for structs `OpRead`, `OpWrite` and `OpStat`
> feat: add If-Match Support for OpRead, OpWrite, OpStat

- core/src/services/s3/writer.rs
- core/src/types/writer.rs
- core/tests/behavior/write.rs
This PR:
- adds `abort` API for `opendal::types::writer::Writer`
- adds behavioral test for abort
> feat: add behavioral test for Write::abort

- core/src/services/obs/backend.rs
- core/src/services/obs/core.rs
- core/src/services/obs/writer.rs
> feat: add if-match support for obs

- core/src/services/s3/core.rs
Services like cos can't handle empty query correctly:
```shell
[2023-04-18T11:15:03Z ERROR opendal::services] service=s3 operation=scan path=x/ -> failed: Unexpected (permanent) at Pager::next => S3Error { code: "InvalidArgument", message: "Invalid Argument", resource: "/", request_id: "NjQzZTdiYjdfMTQ5MDBjMGJfMjZjMmRfMThhM2NkOQ==" }
Context:
response: Parts { status: 400, version: HTTP/1.1, headers: {"content-type": "application/xml", "content-length": "411", "connection": "keep-alive", "date": "Tue, 18 Apr 2023 11:15:03 GMT", "server": "tencent-cos", "x-amz-request-id": "NjQzZTdiYjdfMTQ5MDBjMGJfMjZjMmRfMThhM2NkOQ==", "x-amz-trace-id": "OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODczNTBmNjMwZmQ0MTZkMjg0NjlkNTYyNmY4ZTRkZTk0N2U1NmFlOGIyM2Y0NWQyNTA2YzEzYjVkZDExYzhhNmI2YzU0MTZkYTQxZDQwYWU2ODNmMD …
```
> fix(services/s3): Ignore empty query to make it more compatible

- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
close #1972 
In the Amazon S3 API reference, it seems that the putObject operation does not require the if-match request header, so I did not add the if-match property in the s3/writer file (like in obs/writer). However, I may be wrong.
> feat(services/s3): Add if-match support

- core/src/services/azblob/backend.rs
- core/src/services/azblob/core.rs
> feat: add if_none_match support for azblob

- core/src/services/oss/backend.rs
- core/src/services/oss/core.rs
close #1980 
Hello, I have a little question. Is it necessary to extract constants like response-content-disposition in OSS and S3 into a common mod?
> feat(services/OSS): Add override_content_disposition support

- .github/workflows/bindings_nodejs.yml
Use provenance for release.
- https://github.blog/2023-04-19-introducing-npm-package-provenance/
- https://docs.npmjs.com/generating-provenance-statements
> feat(bindings/nodejs): publish support `--provenance`

- bindings/c/Makefile
- bindings/c/README.md
- bindings/c/build.rs
- bindings/c/include/opendal.h
Ignore the formatting of opendal.h, since it is auto generated.
Fixes: #2050
Signed-off-by: Ji-Xinyou <jerryji0414@outlook.com>
> chore(bindings/C): ignore the formatting of auto-generated opendal.h

- bindings/python/examples/object.ipynb
> docs(bindings/python): ipynb examples for users

- core/src/services/s3/core.rs
Services like cos doesn't support empty query values. It's better to ignore them.
> fix(services/s3): Ignore prefix if it's empty

- core/src/services/azblob/backend.rs
- core/src/services/azblob/core.rs
closes #1979 **should all CI tests pass**.
**A potential caveat**: I am not sure whether Azure Blob supports overriding content-disposition from get request headers. Can you take a look?
Description:
The support for overriding content disposition is not clearly stated in the Azblob REST API DOC, as `x-ms-blob-content-disposition` is not listed in the supported request headers. I added this header as implied here:
I am worried that the `x-ms-blob-content-disposition` might not work as expected , as the header is actually described in [set-blob-properties#request-headers-all-blob-types](https://learn.microsoft.com/en-us/rest/api/storageservices/set-blob-properties?tabs=azure-ad#request-headers-all-blob-types).
> feat(azblob): Add override_content_disposition support

- core/src/services/azblob/backend.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/types/capability.rs
- core/src/types/operator/metadata.rs
- core/tests/behavior/write.rs
It's an experimental draft of read_with_some_headers. Do not merge.
Seems that we don't have a way to check the response headers now.
cc @Xuanwo
> feat(core): test for read_with_override_content_composition

- core/src/types/capability.rs
- core/src/types/operator/operator.rs
- core/src/types/ops.rs
Closes #2069
This PR makes following changes:
1. added `start_after` argument for `OpList`.
2. added `list_with` method for `Operator`.
3. added `list_with_start_after` option for `Capability`.
> feat(core): Add `start-after` support for list

- .github/workflows/service_test_http.yml
- .github/workflows/service_test_ipfs.yml
- core/src/layers/retry.rs
- core/src/raw/http_util/body.rs
- core/src/services/ftp/backend.rs
- core/src/services/redis/backend.rs
- core/src/services/webdav/backend.rs
- core/src/services/webdav/pager.rs
- core/src/types/capability.rs
- core/tests/behavior/blocking_copy.rs
- core/tests/behavior/blocking_list.rs
- core/tests/behavior/blocking_read.rs
- core/tests/behavior/blocking_rename.rs
- core/tests/behavior/blocking_write.rs
- core/tests/behavior/copy.rs
- core/tests/behavior/list.rs
- core/tests/behavior/list_only.rs
- core/tests/behavior/main.rs
- core/tests/behavior/presign.rs
- core/tests/behavior/read_only.rs
- core/tests/behavior/rename.rs
- core/tests/behavior/utils.rs
- core/tests/behavior/write.rs
This PR refactor the behavior tests to allow using the same operator.
> refactor: Allow reusing the same operator to speed up tests

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- core/src/docs/upgrade.md
- feat: Add OpenTelemetry Trace Layer (#2001)
- feat: add if_none_match support for azblob (#2035)
- feat: add if_none_match/if_match for gcs (#2039)
- feat: Add size check for sized writer (#2038)
- feat(services/azblob): Add if-match support (#2037)
- feat(core): add copy&rename to error_context layer (#2040)
- feat: add if-match support for OSS (#2034)
- feat: Bootstrap new (old) project oay (#2041)
- feat(services/OSS): Add override_content_disposition support (#2043)
- feat: add IF_MATCH for http (#2044)
- feat: add IF_MATCH for http HEAD request (#2047)
- feat: add cache control header for azblob and obs (#2049)
- feat: Add capability for operation's variant and args (#2057)
- feat(azblob): Add override_content_disposition support (#2065)
- feat(core): test for …
> Bump to version 0.33

- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
> chore(bindings/nodejs): update `package.json` repository info

- core/src/docs/rfcs/0000_writer_sink_api.md
- core/src/docs/rfcs/2083_writer_sink_api.md
- core/src/docs/rfcs/mod.rs
OpenDAL does not support streaming data uploads. Users must first load the data into memory and then send it to the `writer`.
```rust
let bs = balabala();
w.write(bs).await?;
let bs = daladala();
w.write(bs).await?;
...
w.close().await?;
```
There are two main drawbacks to OpenDAL:
- high memory usage, as reported in issue #1821 on GitHub
- low performance due to the need to buffer user data before sending it over the network.
To address this issue, it would be beneficial for OpenDAL to provide an API that allows users to pass a stream or reader directly into the writer.
> RFC-2083: Writer Sink API

- core/tests/behavior/write.rs
`if_match` is one of the Precondition Header Fields. https://www.rfc-editor.org/rfc/rfc7232#section-3.1
This PR adds tests for the `read_if_match` and `stat_if_match` operations/capabilities, which use the `If-Match` request header to test whether an S3 object's version matches a given ETag.
The `If-Match` header allows clients to perform optimistic concurrency control by specifying the expected version of an object before performing a `read` or `stat` operation, and S3 will only return the object or its metadata if the actual version matches the expected version.
> core: Add behavior test for read_with_if_match & stat_with_if_match

- core/src/layers/logging.rs
Two small changes:
* Adds default log level to `LoggingLayer` docs, close #1820 
* Pub use `log::Level` in `layers::logging`. It can simplify the user's dependencies, they don't have to depend on the `log` crate directly when configuring `LoggingLayer`.
> chore: improve LoggingLayer docs and pub use log::Level

- core/src/layers/complete.rs
- core/src/layers/logging.rs
- core/src/services/fs/backend.rs
- core/src/services/gcs/backend.rs
- core/src/services/oss/backend.rs
- core/src/services/s3/backend.rs
- core/src/types/writer.rs
- core/tests/behavior/utils.rs
- core/tests/behavior/write.rs
This PR will add fuzz test for writer without content length.
Fix https://github.com/apache/incubator-opendal/issues/2093
> feat(tests): Add fuzz test for writer without content length

- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/services/s3/pager.rs
- core/tests/behavior/list.rs
Closes #2095
This PR introduces new features:
1. add `list_with_start_after` capability
2. add `test_list_with_start_after` test case
> feat(services/s3): Add `start-after` support for list

- .github/workflows/bindings_nodejs.yml
- bindings/nodejs/index.d.ts
This PR will fix outdated `d.ts` and add a CI task to prevent it.
> fix(bindings/nodejs): Fix index.d.ts not updated

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- feat: Add behavior test for read_with_if_match & stat_with_if_match (#2088)
- feat(tests): Add fuzz test for writer without content length (#2100)
- feat: add if_none_match support for obs (#2103)
- feat(services/oss): Add server side encryption support for oss (#2092)
- feat(core): update errorKind `PreconditionFailed` to `ConditionNotMatch` (#2104)
- feat(services/s3): Add `start-after` support for list (#2096)
- feat: gcs support cache control (#2116)
- fix(services/gcs): set `content length=0` for gcs initiate_resumable_upload (#2110)
- fix(bindings/nodejs): Fix index.d.ts not updated (#2117)
- chore: improve LoggingLayer docs and pub use log::Level (#2089)
- docs(refactor): Add more detailed description of operator, accessor, and builder (#2094)
- chore(bindings/nodejs): update …
> Bump to version 0.33.1

- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
- core/src/services/gcs/pager.rs
- core/src/services/s3/pager.rs
Closes #2106
This PR add a new feature for GCS:
- add `list_with_start_after` capability
> feat(services/gcs): Add start-after support for list

- core/src/services/azblob/backend.rs
- core/src/services/azblob/core.rs
> feat(services/azblob): Add supporting presign

- Cargo.lock
- bindings/java/Cargo.toml
- bindings/java/src/lib.rs
- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/test/java/org/apache/opendal/AsyncStepsTest.java
link to #1572
This is a POC of bring async API for java binding, see https://github.com/apache/incubator-opendal/issues/1572#issuecomment-1519880511 for more details.
I add an `asyncWrite` function and related test for Java binding.
As a result, `asyncWrite` will not block any Java thread and the user could collect results using `thenAccept` function of the `CompletableFuture`.
> feat(java): connect rust async/await with java future

- core/src/services/gcs/core.rs
Close #2125
The url path in presign operation will be signed and put into body part. So it shouldn't do percent encoding.
> fix(services/gcs): Fix invalid url for gcs presign

- .github/workflows/service_test_gcs.yml
- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
Related to https://github.com/apache/incubator-opendal/issues/2125
> ci: Enable native-tls to test gcs presign for workaround

- core/src/lib.rs
- core/src/raw/http_util/header.rs
- core/src/types/metadata.rs
Add `cache-control` to Metadata.
As a header defined in HTTP standard, it will be set when it exists in response headers.
> feat(core): Add `cache-control` to Metadata

- .github/workflows/service_test_gcs.yml
- core/src/services/gcs/backend.rs
Fix https://github.com/apache/incubator-opendal/issues/2125
> fix(services/gcs): Remove HOST header to avoid gcs RESET connection

- core/src/services/azblob/backend.rs
- core/src/services/azblob/core.rs
- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
- core/src/services/gcs/writer.rs
- core/src/services/obs/backend.rs
- core/src/services/oss/backend.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/writer.rs
- core/tests/behavior/write.rs
> test(core): test for `write_with_cache_control`

- core/src/services/gcs/backend.rs
- core/src/services/http/backend.rs
- core/src/services/obs/backend.rs
- core/src/services/oss/backend.rs
- core/src/services/webdav/backend.rs
- core/tests/behavior/read_only.rs
- core/tests/behavior/write.rs
test for `read_with_if_none_match`
Capability-enabled services:
- azblob
- gcs
- obs
- oss
- s3
- http (read_only)
> test(core): test for `read_with_if_none_match`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- feat(core): add test for `stat_with_if_none_match` (#2122)
- feat(services/gcs): Add start-after support for list (#2107)
- feat(services/azblob): Add supporting presign (#2120)
- feat(services/gcs): Add supporting presign support (#2126)
- feat(java): connect rust async/await with java future (#2112)
- docs: add hdfs classpath related troubleshoot (#2130)
- fix(clippy): suppress dead_code check (#2135)
- feat(core): Add `cache-control` to Metadata (#2136)
- fix(services/gcs): Remove HOST header to avoid gcs RESET connection (#2139)
- test(core): test for `write_with_cache_control` (#2131)
- test(core): test for `write_with_content_type` (#2140)
- test(core): test for `read_with_if_none_match` (#2141)
- feat(services/supabase): Add read/write/stat support for supabase (#2119)
- docs: …
> Bump to version 0.33.2

- core/src/services/s3/backend.rs
- core/tests/behavior/write.rs
Add test for `read_with_override_cache_control`
Capability-enabled services:
- s3
> test(core): test for `read_with_override_cache_control`

- core/src/raw/http_util/body.rs
- core/src/raw/http_util/client.rs
- core/src/raw/http_util/mod.rs
- core/src/raw/http_util/multipart.rs
- core/src/services/azblob/backend.rs
- core/src/services/azblob/batch.rs
- core/src/services/azblob/core.rs
- core/src/services/ipmfs/backend.rs
- core/src/services/ipmfs/writer.rs
This PR will add `multipart/mixed` support which makes it easier for developers to build requests with `multipart/mixed` content type.
> feat(http_util): Implement multipart/mixed support

- website/docs/vision.md
The "Good/Bad" aren't very noticeable. I think it might be more clear to highlight what we do/don't.
> doc: update vision to be more clear

- .devcontainer/devcontainer.json
This PR changes the devcontainer to microsoft rust deveconatiner for better experinence
> ci: Use microsoft rust devcontainer instead

- core/src/layers/logging.rs
Attempt to parse `str` as level and parse level must succeed.
fixes: #2090
> refactor(layers/logging): parsing level str

- Cargo.toml
> chore: set workspace default members

- core/src/types/operator/operator.rs
* Fix some grammar errors in the documentation of `Operator`.
-----
Playing with the `Operator` type and I found some documents were a little bit confusing, so here comes the patch
> docs: fix some grammar errors in the doc of Operator

- core/src/raw/adapters/kv/backend.rs
- core/src/services/azblob/backend.rs
- core/src/services/azdfs/backend.rs
- core/src/services/fs/backend.rs
- core/src/services/ftp/backend.rs
- core/src/services/gcs/backend.rs
- core/src/services/ghac/backend.rs
- core/src/services/hdfs/backend.rs
- core/src/services/http/backend.rs
- core/src/services/ipfs/backend.rs
- core/src/services/ipmfs/backend.rs
- core/src/services/obs/backend.rs
- core/src/services/oss/backend.rs
- core/src/services/s3/backend.rs
- core/src/services/supabase/backend.rs
- core/src/services/supabase/core.rs
- core/src/services/supabase/error.rs
- core/src/services/wasabi/backend.rs
- core/src/services/webdav/backend.rs
- core/src/services/webhdfs/backend.rs
- core/tests/behavior/main.rs
- core/tests/behavior/write.rs
* Fix supabase ci
* Add read_with_range capabilities to all kv adapters and all services that support this.
* Skip tests that require range read for those do not support
> fix(services/supabase): Supabase ci fix

- .github/workflows/bindings_java.yml
I notice that we use Temurin JDK 11 in the `publish.yml` workflow, and use the Zulu JDK 8 in the `bindings_java.yml` workflow, I suggest that we unify the JDK version.
- Switch the JDK distribution from Zulu to Temurin
- Use the different version of JDK to build the `bindings-java` module
> ci: use Temurin JDK 11 to build the bindings-java

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- scripts/README.md
- scripts/check.sh
- feat(services/onedrive): Add read and write support for OneDrive (#2129)
- test(core): test for `read_with_override_cache_control` (#2155)
- feat(http_util): Implement multipart/form-data support (#2157)
- feat(http_util): Implement multipart/mixed support (#2161)
- RFC-2133: Introduce Append API (#2133)
- feat(services/sftp): Add read/write/stat support for sftp (#2186)
- feat(services/gdrive): Add read & write & delete support for GoogleDrive (#2184)
- feat(services/vercel): Add vercel remote cache support (#2193)
- feat(tests): Enable supabase integration tests (#2190)
- feat(core): merge scan and list (#2214)
- refactor(java): refactor java code for java binding (#2145)
- refactor(layers/logging): parsing level str (#2160)
- refactor: Move not initiated logic to utils instead …
> Bump to version 0.33.3

- core/src/layers/retry.rs
- core/src/raw/http_util/body.rs
- core/src/raw/oio/into_reader/by_range.rs
- core/src/raw/oio/into_reader/from_fd.rs
- core/src/raw/oio/into_streamable.rs
- core/src/services/ftp/util.rs
- core/src/types/list.rs
- core/src/types/reader.rs
- core/src/types/writer.rs
We could use `std::task::ready` stabilized at 1.64 as `opendal`'s msrv is 1.64.
> refactor: Replace futures::ready with std::task::ready

- core/benches/ops/utils.rs
- core/src/raw/adapters/kv/mod.rs
- core/src/raw/adapters/typed_kv/api.rs
- core/src/raw/adapters/typed_kv/backend.rs
- core/src/raw/adapters/typed_kv/mod.rs
- core/src/raw/oio/cursor.rs
- core/src/services/moka/backend.rs
This PR will close https://github.com/apache/incubator-opendal/issues/1392.
By adding a new typed kv adapter, we can store metadata and bytes in rust containers like moka, dashmap, and avoid the extra cost of ser/de the bytes.
This PR will improve the read perf of `moka` at 1500%, and write perf at 160000% (the best case).
Read Before:
```rust
service_moka_read_full/4.00 KiB
time:   [3.1231 µs 3.1270 µs 3.1312 µs]
thrpt:  [1.2183 GiB/s 1.2199 GiB/s 1.2214 GiB/s]
service_moka_read_full/256 KiB
time:   [67.995 µs 68.043 µs 68.094 µs]
thrpt:  [3.5853 GiB/s 3.5881 GiB/s 3.5906 GiB/s]
service_moka_read_full/4.00 MiB
time:   [127.98 µs 128.19 µs 128.43 µs]
thrpt:  [30.415 GiB/s 30.473 GiB/s 30.522 GiB/s]
service_moka_read_full/16.0 MiB
time:   [731.54 µs 736.31 µs 741.73 µs]
thrpt:  [21.066 …
```
> feat: Add typed kv adapter and migrate moka to it

- core/src/layers/retry.rs
- core/src/types/operator/operator.rs
- core/tests/behavior/write.rs
R2 has strong requirement for Etag:
```shell
[2023-05-07T17:34:30Z ERROR opendal::services] service=s3 operation=read path=df189c54-4664-433d-9c85-ed8f830f55cf range=0- -> failed: Unexpected (permanent) at read => S3Error { code: "InvalidArgument", message: "Invalid Argument: If-Match each ETag must be surrounded by double quotes, got 'invalid_etag'.", resource: "", request_id: "" }
Context:
response: Parts { status: 400, version: HTTP/1.1, headers: {"date": "Sun, 07 May 2023 17:34:30 GMT", "content-type": "application/xml", "content-length": "203", "connection": "keep-alive", "server": "cloudflare", "cf-ray": "7c3b36ce3b1bc729-SEA"} }
service: s3
path: df189c54-4664-433d-9c85-ed8f830f55cf
range: 0-
```
> fix(tests): Etag must be wrapped by `"`

- core/src/raw/adapters/typed_kv/api.rs
- core/src/raw/adapters/typed_kv/backend.rs
- core/src/raw/adapters/typed_kv/mod.rs
- core/src/services/dashmap/backend.rs
- core/src/services/moka/backend.rs
- [feat(typed_kv): add scan support for Typed KV Adapter](https://github.com/apache/incubator-opendal/commit/d45acbc8c72c497b3a8895e6b90198c4de75fba5)
- [feat(services/dashmap): migrate service dashmap](https://github.com/apache/incubator-opendal/commit/5e3e40ec969206c3832f02575bcb6a001323cb60)
Related: #2223
> feat: migrate service dashmap

- core/src/services/dashmap/backend.rs
- core/src/services/memory/backend.rs
- core/src/services/moka/backend.rs
also [docs(typed_kv): update capabilities](https://github.com/apache/incubator-opendal/commit/97ea82cbdae81e6d7cd71b8b6634a531a2e92d9d)
fixes: #2223
> feat(services/memory): migrate service memory 

- .github/workflows/ci.yml
- .github/workflows/service_test_s3.yml
- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- core/src/raw/http_util/error.rs
- core/src/services/azblob/core.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/services/wasabi/backend.rs
- core/src/services/wasabi/core.rs
Fix https://github.com/apache/incubator-opendal/issues/2232
> fix(services/s3): Return error if credential load fail instead skip

- core/src/services/s3/backend.rs
Fix https://github.com/apache/incubator-opendal/issues/2201
> fix(services/s3): Return error if region not set for AWS S3

- Cargo.lock
- core/Cargo.toml
Ref to https://github.com/Xuanwo/reqsign/pull/317
The root cause is not found yet.
> fix(services/gcs): rsa 0.9 breaks gcs presign

- core/src/services/gcs/core.rs
- core/src/services/gcs/writer.rs
> feat(services/gcs): Add abort support for writer

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- core/src/docs/upgrade.md
- feat(writer): configurable buffer size of unsized write (#2143)
- feat(oay): Add basic s3 list_objects_v2 with start_after support (#2219)
- feat: Add typed kv adapter and migrate moka to it (#2222)
- feat: migrate service dashmap (#2225)
- feat(services/memory): migrate service memory  (#2229)
- feat: Add assert for public types to ensure Send + Sync (#2237)
- feat(services/gcs): Add abort support for writer (#2242)
- refactor: Replace futures::ready with std::task::ready (#2221)
- refactor: Use list without delimiter to replace scan (#2243)
- fix(services/gcs): checked_rem_euclid could return Some(0) (#2220)
- fix(tests): Etag must be wrapped by `"` (#2226)
- fix(services/s3): Return error if credential load fail instead skip (#2233)
- fix(services/s3): Return error if region not set …
> Bump to version 0.34.0

- core/src/services/s3/backend.rs
Fixes an outdated doc left behind after the changes made in #2234.
S3 regions are now required to build an S3 backend.
> chore(s3): update builder region doc

- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/result.rs
- bindings/c/src/types.rs
- bindings/c/tests/basicio.c
Currently the Metadata of C binding only has the functions that the BDD tests need. We will add more of them in the future.
After we support stat, we could use this to support BDD tests using GTest. And the `basicio.c` will be replaced by the framework-based tests.
> feat(bindings/C): Initially support stat in C binding

- .github/workflows/bindings_python.yml
- Cargo.lock
- bindings/python/Cargo.toml
- bindings/python/python/opendal/layers.pyi
- bindings/python/src/layers.rs
Fixes #2252
Signed-off-by: Frost Ming <me@frostming.com>
`chrono::Duration <-> pyo3::types::PyDelta` is [not availiable](https://docs.rs/pyo3/0.18.2/pyo3/types/struct.PyDelta.html) under `Py_Limited_API`, so I switch it to float(in seconds) instead.
> feat(bindings/python): Enable `abi3` to avoid building on different python version

- core/src/services/obs/backend.rs
- core/src/services/obs/core.rs
fixes: #2070 
noticed that oss already have the presign support, so this pr only touches obs.
> feat(core): add presign support for obs

- core/src/layers/oteltrace.rs
- core/src/raw/oio/read.rs
- core/src/services/fs/backend.rs
> chore(core): remove unnecessary path prefix

- Cargo.lock
- core/Cargo.toml
- core/src/services/sftp/backend.rs
Update:
- add copyable setting in `SftpBuilder` to make user provide info about remote server extension
- bump `openssh-sftp-client` version to 0.13.5 to fix the bug of `AsyncSeek`
- add `read_can_seek` in `Capability`
> feat(services/sftp): support copy and read_seek

- .github/workflows/docs.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ci: replace set-output for docs

- bindings/nodejs/src/lib.rs
- bindings/python/src/lib.rs
- bindings/ruby/src/lib.rs
- core/benches/ops/utils.rs
- core/src/layers/immutable_index.rs
- core/src/types/builder.rs
- core/src/types/operator/builder.rs
- core/src/types/scheme.rs
This PR also removes not used `from_iter` and `from_env`.
> refactor: Add Operator::via_map to support init without generic type parameters

- .devcontainer/post_create.sh
- bindings/c/CONTRIBUTING.md
- bindings/c/Makefile
This PR adds the contributing doc for C binding.
> docs(bindings/C): C binding contributing documentation

- core/src/types/appender.rs
- core/src/types/mod.rs
- core/src/types/operator/operator.rs
- core/src/types/ops.rs
This PR adds public API of append.
With four methods for the operator:
- append
- appender
- append_with
- appender_with
And async_write.
> feat(core): public API of append

- core/src/services/oss/appender.rs
- core/src/services/oss/backend.rs
- core/src/services/oss/core.rs
- core/src/services/oss/mod.rs
- core/src/types/capability.rs
- core/src/types/operator/operator.rs
- core/tests/behavior/append.rs
> feat(services/oss): add append support

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- core/src/docs/upgrade.md
- feat(services/onedrive): Implement `list`, `create_dir`, `stat` and upload
ing large files (#2231)
- feat(bindings/C): Initially support stat in C binding (#2249)
- feat(bindings/python): Enable `abi3` to avoid building on different python
version (#2255)
- feat(bindings/C): support BDD tests using GTest (#2254)
- feat(services/sftp): setup integration tests (#2192)
- feat(core): Add trait and public API for `append` (#2260)
- feat(services/sftp): support copy and rename for sftp (#2263)
- feat(services/sftp): support copy and read_seek (#2267)
- feat: Add COS service support (#2269)
- feat(services/cos): Add support for loading from env (#2271)
- feat(core): add presign support for obs (#2253)
- feat(services/sftp): setup integration tests (#2192)
- feat(core): add presign support for …
> Bump to version 0.35.0

- core/src/services/supabase/error.rs
* This PR parse the supabase statuscode more detailed and set the retryability correctly.
Closes: #2287
> fix(services/supabase): correctly set retryable

- core/src/services/fs/appender.rs
- core/src/services/fs/backend.rs
> feat(service/fs): add append support for fs

- core/src/docs/rfcs/0000_chain_based_operator_api.md
- core/src/docs/rfcs/2299_chain_based_operator_api.md
- core/src/docs/rfcs/mod.rs
This proposal will add chain based API for Operator and BlockingOperator:
from
```rust
let bs = op.read_with(
"path/to/file",
OpRead::new()
.with_range(0..=1024)
.with_if_match("<etag>")
.with_if_none_match("<etag>")
.with_override_cache_control("<cache_control>")
.with_override_content_disposition("<content_disposition>")
).await?;
```
to
```rust
let bs = op.read_with("path/to/file")
.range(0..=1024)
.if_match("<etag>")
.if_none_match("<etag>")
.override_cache_control("<cache_control>")
.override_content_disposition("<content_disposition>")
.await?;
```
> RFC-2299: Chain based Operator API

- core/src/services/azdfs/backend.rs
- core/src/services/azdfs/docs.md
- website/docs/services/azdfs.mdx
Update https://github.com/apache/incubator-opendal/issues/2304
> docs: add service doc for azdfs

- website/src/components/HomepageFeatures/_feature_languages.mdx
Fixes #2326 
Updates links of supported languages and bindings to open in the same/current tab.
> docs: Fixed links of languages to open in same tab

- .github/workflows/bindings_nodejs.yml
This PR will use `ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian` to build nodejs binding.
> ci(binding/nodejs): Use docker to build nodejs binding

- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/types.rs
- bindings/c/tests/bdd.cpp
Introduce initializing opendal_operator by key-value pairs. With this PR, we can build operator on any scheme theoretically 😆 .
For map construction, I came up with essentially three ideas.
1. Use a `opendal_map` struct, which is essentially a pointer to Rust Hashmap. I did **not** use this because this introduce complexity just like we construct a `opendal_operator_ptr`, users have to pay their extra attention on freeing the heap memory that is even used only once.
```Rust
opendal_map m = opendal_map_new(kvs: opendal_kvs);
opendal_operator_ptr ptr = opendal_operator_from_map(scheme, m);
/* I don't want this since this is not necessary, we are not using this anymore */
opendal_map_free(m);
opendal_operator_ptr_free(ptr);
```
---
2. Use a series of keys and values in the …
> feat(bindings/C): opendal_operator_ptr construction using kvs

- core/tests/behavior/append.rs
- core/tests/behavior/blocking_copy.rs
- core/tests/behavior/blocking_read.rs
- core/tests/behavior/blocking_rename.rs
- core/tests/behavior/blocking_write.rs
- core/tests/behavior/copy.rs
- core/tests/behavior/read_only.rs
- core/tests/behavior/rename.rs
- core/tests/behavior/write.rs
This can help to run an individual test more effectively.
> chore(test): Avoid test names becoming prefixes of other tests

- bindings/c/CONTRIBUTING.md
- bindings/c/tests/bdd.cpp
This PR modify the original bdd tests used in C binding and align it with the unified cucumber bdd tests.
> refactor(bindings/C): align bdd test with the feature tests

- .github/workflows/bindings_java.yml
- bindings/java/README.md
- bindings/java/pom.xml
- bindings/java/src/blocking_operator.rs
- bindings/java/src/main/java/org/apache/opendal/BlockingOperator.java
- bindings/java/src/main/java/org/apache/opendal/Environment.java
- bindings/java/src/main/java/org/apache/opendal/Metadata.java
- bindings/java/src/main/java/org/apache/opendal/NativeObject.java
- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/AsyncStepsTest.java
- bindings/java/src/test/java/org/apache/opendal/BlockingOperatorTest.java
- bindings/java/src/test/java/org/apache/opendal/CucumberTest.java
- bindings/java/src/test/java/org/apache/opendal/StepsTest.java
.. alongside with introduction of spotless plugin.
> docs(bindings/java): for BlockingOperator

- bindings/java/src/error.rs
- bindings/java/src/main/java/org/apache/opendal/BlockingOperator.java
- bindings/java/src/main/java/org/apache/opendal/Environment.java
- bindings/java/src/main/java/org/apache/opendal/Metadata.java
- bindings/java/src/main/java/org/apache/opendal/NativeObject.java
- bindings/java/src/main/java/org/apache/opendal/OpenDALException.java
- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/main/java/org/apache/opendal/exception/OpenDALException.java
- bindings/java/src/main/java/org/apache/opendal/package-info.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/BlockingOperatorTest.java
- bindings/java/src/test/java/org/apache/opendal/OperatorTest.java
- core/src/types/metadata.rs
This refers to https://github.com/apache/incubator-opendal/issues/2339.
It should finish the first subtask.
> feat(bindings/java): implement Operator#delete

- bindings/java/pom.xml
- bindings/java/src/blocking_operator.rs
- bindings/java/src/main/java/org/apache/opendal/BlockingOperator.java
- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/AsyncStepsTest.java
- bindings/java/src/test/java/org/apache/opendal/OperatorTest.java
- bindings/java/src/test/java/org/apache/opendal/StepsTest.java
This refers to https://github.com/apache/incubator-opendal/issues/2339.
> feat(bindings/java): support append

- bindings/java/README.md
- bindings/java/pom.xml
The automation is still at [tisonkun/ci-opendal](https://github.com/tisonkun/ci-opendal). We may add a release manual later and keep the snapshot deploy process unofficial.
The released artifacts can be found at https://repository.apache.org/content/repositories/releases/org/apache/opendal/opendal-java/0.1.0/.
Although, it can take some time to propagate among the network and other mirror sites. Let's keep it as a draft until I can build an application properly. 
This closes https://github.com/apache/incubator-opendal/issues/2339.
> chore(bindings/java): post release 0.1.0

- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/operator.rs
This may not be necessary within single language scope since we can trust the compiler or JIT to inline code as much as possible.
But it's valuable when calls cross language boundaries since no optimization can happen here. Also, obtaining a future and getting it to complete is the hot path for all async ops. Thus I believe it is worth trading off some code style (static method over singleton and then call member method) for efficiency.
> feat(bindings/java): save one jni call in the hot path

- .github/workflows/docs.yml
> chore(docs): split docs build into small jobs

- .asf.yaml
As a source of our site deployments and as a documentation archive for versions, we should protect this branch.
> chore: protect branch gh-pages

- core/Cargo.toml
- core/src/services/azblob/backend.rs
- core/src/services/azblob/core.rs
- core/src/services/s3/core.rs
- related issue: #183
- Reference: https://learn.microsoft.com/en-us/rest/api/storageservices/operations-on-blobs
Add SSE headers into these requests
- *azblob_get_blob_request*
- *azblob_put_blob_request*
- *azblob_init_appendable_blob_request*
- *azblob_append_blob_request*
- *azblob_head_blob_request*
Hi @Xuanwo, what do you think about these two functions? Should we provide them separately or together? (Also, since azblob only support for AES256 as encryption algorithm, do we still need to provide setting options for user?)
```rust
builder.root("/")
.container("test")
.endpoint("http://127.0.0.1:10000/devstoreaccount1")
.account_name("devstoreaccount1")
.account_key("Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==")
// separately …
```
> feat: server side encryption support for azblob

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/c/Cargo.toml
- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/types.rs
- bindings/java/Cargo.toml
- bindings/java/pom.xml
- bindings/java/src/blocking_operator.rs
- bindings/java/src/operator.rs
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- core/src/docs/upgrade.md
- core/src/services/cos/backend.rs
- core/src/services/dashmap/backend.rs
- core/src/services/fs/backend.rs
- feat(service/fs): add append support for fs (#2296)
- feat(services/sftp): add append support for sftp (#2297)
- RFC-2299: Chain based Operator API (#2299)
- feat(services/azblob): add append support (#2302)
- feat(bindings/nodejs): add append support (#2322)
- feat(bindings/C): opendal_operator_ptr construction using kvs (#2329)
- feat(services/cos): append support (#2332)
- feat(bindings/java): implement Operator#delete (#2345)
- feat(bindings/java): support append (#2350)
- feat(bindings/java): save one jni call in the hot path (#2353)
- feat: server side encryption support for azblob (#2347)
- refactor(core): Implement RFC-2299 for stat_with (#2303)
- refactor(core): Implement RFC-2299 for BlockingOperator::write_with (#2305)
- refactor(core): Implement RFC-2299 for appender_with …
> Bump to version 0.36.0

- .devcontainer/post_create.sh
- .github/workflows/bindings_zig.yml
- bindings/zig/.gitignore
- bindings/zig/CONTRIBUTING.md
- bindings/zig/README.md
- bindings/zig/build.zig
- bindings/zig/src/opendal.zig
- [zig 0.11.0 or higher](https://ziglang.org/download)
`@cImport`/`@cInclude` (zig translate-c inside) read `opendal.h` on `<root_dir>/bindings/c/include` to auto-generate a binding.
```
zig build: opendal.zig inside [@cImport(@cInclude("opendal.h"));] => translate-c => (opendal.h => cimport.zig)
zig build: opendal.zig <= cimport.zig
zig build: <your project> <= opendal.zig <= libopendal_c
```
more info:
https://ziglang.org/documentation/master/#cImport-vs-translate-c
cc: @Xuanwo 
- https://github.com/apache/incubator-opendal/discussions/1509
- #1769
> feat: Add Zig Bindings Module

- bindings/zig/build.zig
- bindings/zig/src/opendal.zig
- bindings/zig/test/bdd.zig
cc: @tisonkun @Xuanwo
* Add Zig Error Handler
* Split tests - BDD test with opendal module (sample use)
> refactor(bindings/zig): add errors handler and module test

- core/src/layers/mod.rs
- core/src/layers/timeout.rs
- core/tests/behavior/utils.rs
This PR will add timeout layer for OpenDAL so users can avoid waiting for hang operations.
> feat: Implement Timeout Layer

- bindings/java/README.md
This refers to https://github.com/apache/incubator-opendal/issues/2394.
> docs(bindings/java): do not release snapshot versions anymore

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/java/pom.xml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- feat(services/webdav): support redirection when get 302/307 response during read operation by @Yansongsongsong in https://github.com/apache/incubator-opendal/pull/2256
- feat: Add Zig Bindings Module by @kassane in https://github.com/apache/incubator-opendal/pull/2374
- feat: Implement Timeout Layer by @Xuanwo in https://github.com/apache/incubator-opendal/pull/2395
- refactor(bindings/zig): enable tests and more by @tisonkun in https://github.com/apache/incubator-opendal/pull/2375
- refactor(bindings/zig): add errors handler and module test by @kassane in https://github.com/apache/incubator-opendal/pull/2381
- refactor(http_util): Adopt reqwest's redirect support by @Xuanwo in https://github.com/apache/incubator-opendal/pull/2390
- fix(bindings/zig): reflect C interface changes by …
> Bump to version 0.36.1

- core/src/services/oss/backend.rs
- core/src/services/oss/docs.md
- website/docs/services/oss.mdx
> docs: add service doc for oss

- core/src/services/oss/backend.rs
- core/src/services/oss/core.rs
related issue #2228 
This pr add new batch_max_operations config for oss service and use default value (1000 )if not set.
> fix(services/oss): Fix oss batch max operations

- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
related issue #2228 
close #2354
according to pr #2414
This pr add new batch_max_operations config for s3 service and use default value (1000 )if not set.
> fix(services/s3): Fix s3 batch max operations

- bindings/c/Makefile
- bindings/c/README.md
- bindings/c/examples/basicrw.c
This simple example will be shown in the documentation website.
More examples will be added to the `./example`.
> chore(bindings/C): add one simple read/write example into readme and code

- core/README.md
Before this commit, I got the following error:
```
no function or associated item named `create` found for struct `opendal::Operator` in the current scope
function or associated item not found in `Operator`
```
So, I replaced the `create` method with the `new` method.
> docs: Replace `create` with `new`

- core/src/services/azblob/backend.rs
- core/src/services/azblob/core.rs
Fix azblob service config of batch max operations 
close issue #2228
> fix(services/azblob): Fix azblob batch max operations

- website/docs/services/redis.mdx
close issue #2432 
fix redis via config example by adding more configuration
> docs(services/redis): fix redis via config example

- .github/workflows/service_test_sftp.yml
- core/src/services/sftp/backend.rs
- core/src/services/sftp/docs.md
Previously, sftp root config only supports absolute path. This patch is mentioned in https://github.com/apache/incubator-opendal/pull/2192.
> fix(services/sftp): change default root config to remote server setting

- Cargo.lock
- bindings/ruby/Cargo.toml
I don't dive into details too much. But https://github.com/oxidize-rb/rb-sys/issues/216#issuecomment-1561941332 suggests a newer version may help and it does.
FWIW, without this patch compilation on M1 failed with:
<details>
<summary>console output</summary>
error: failed to run custom build command for `rb-sys v0.9.72`
Caused by:
process didn't exit successfully: `/Users/tison/Brittani/opendal/target/debug/build/rb-sys-817a78bd99051881/build-script-main` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=RUBY
cargo:rerun-if-env-changed=RBCONFIG_ruby_version
cargo:rerun-if-env-changed=RBCONFIG_platform
cargo:rerun-if-env-changed=RBCONFIG_arch
cargo:rerun-if-env-changed=RUBY_ROOT
cargo:rerun-if-env-changed=RUBY_VERSION
cargo:rerun-if-env-changed=RUBY …
> build(bindings/ruby): fix compile rb-sys on Apple M1

- Cargo.lock
- core/Cargo.toml
- core/src/layers/mod.rs
- core/src/layers/throttle.rs
- related issue: #743
> ~~**NOTE: This is still a early stage of this PR, I open this PR for RFC and guidance.**~~
As there's no open-source repository that uses Governor to limit bandwidth so far, it's mostly used to limit the number of requests, e.g. [tower-governor](https://github.com/benwis/tower-governor) (although Governor can theoretically limit [any element](https://docs.rs/governor/latest/governor/_guide/index.html#quotas)). 
There's an [issue](https://github.com/antifuchs/governor/issues/154#issuecomment-1293731081) asked by [Quickwit](https://github.com/quickwit-oss/quickwit)'s author about how to use Governor to **limit IO throughput**, but he ended up using [async-speed-limit](https://github.com/tikv/async-speed-limit) for **Quickwit** …
> feat(layer): add throttle layer

- website/src/components/HomepageFeatures/_feature_languages.mdx
This PR just fixes a small typo on the landing page.
> docs: fix a typo on the landing page

- Cargo.lock
- bindings/haskell/.gitignore
- bindings/haskell/Cargo.toml
- bindings/haskell/README.md
- bindings/haskell/cabal.project.local
- bindings/haskell/haskell-src/OpenDAL.hs
- bindings/haskell/haskell-src/OpenDAL/FFI.hs
- bindings/haskell/opendal-hs.cabal
- bindings/haskell/src/lib.rs
- bindings/haskell/src/result.rs
- bindings/haskell/test/BasicTest.hs
- bindings/haskell/test/Spec.hs
I researched 3 ways to complete haskell bindings.
1. Using [hs-bindgen](https://github.com/yvan-sraka/hs-bindgen)
2. According completed C binding
3. Self exporting C-compatible API
The first way is the simplest way. However, the function of `hs-bindgen` is limited. Moreover, `hs-bindgen` seems still a working experiment. I raised 2 issues about it which did not receive much attention from the author. 
https://github.com/yvan-sraka/hs-bindgen-attribute/issues/2, https://github.com/yvan-sraka/reflexive/issues/1
As for the second way, using the existing C bindings can simplify the process of creating Haskell bindings. However, there are also some potential downsides.
- Some C APIs are difficult to interact with haskell. 
For example, haskell can't deal with returned struct directly. `struct …
> feat(bindings/haskell): init haskell binding

- .devcontainer/post_create.sh
- bindings/haskell/CONTRIBUTING.md
This PR adds the contributing doc for haskell binding.
> feat(bindings/haskell): add CONTRIBUTING.md

- bindings/c/Cargo.toml
- bindings/c/src/types.rs
- bindings/zig/build.zig
Also fix https://github.com/apache/incubator-opendal/issues/2471
> fix(bindings/C): use copy_from_slice instead of from_static in opendal_bytes

- bindings/haskell/CONTRIBUTING.md
- bindings/haskell/haskell-src/OpenDAL.hs
- bindings/haskell/haskell-src/OpenDAL/FFI.hs
- bindings/haskell/opendal-hs.cabal
- bindings/haskell/src/lib.rs
- bindings/haskell/src/result.rs
- bindings/haskell/test/BasicTest.hs
Update:
- support `is_exist` `create_dir` `copy` `rename` `delete`
- fix `ByteSlice` invalid ownership
- refactor `Operation` to `ForeignPtr` to enable haskell GC automatic free
- add `OpenDALError` to provide detailed error info
- add tests about `Fs`
Now we still leave `stat`, `list`, `scan` to complete.
> feat(bindings/haskell): support `is_exist` `create_dir` `copy` `rename` `delete`

- .github/workflows/bindings_zig.yml
Seems zig has removed `-fsummary` flag:
Action log: https://github.com/apache/incubator-opendal/actions/runs/5301725122/jobs/9596187814
```shell
> zig build test -fsummary
Unrecognized argument: -fsummary
Usage: /opt/hostedtoolcache/zig/master/x86_64-linux/zig build [steps] [options]
Steps:
install (default)            Copy build artifacts to prefix path
uninstall                    Remove build artifacts from prefix path
libopendal_c                 Build OpenDAL C bindings
test                         Run OpenDAL Zig bindings tests
General Options:
-p, --prefix [path]          Override default install prefix
--prefix-lib-dir [path]      Override default library directory path
--prefix-exe-dir [path]      Override default executable directory path
--prefix-include-dir [path]  Override …
```
> ci: Use summary for zig test to fix build

- bindings/haskell/haskell-src/OpenDAL.hs
- bindings/haskell/opendal-hs.cabal
- bindings/haskell/test/BasicTest.hs
Update:
- add `MonadOperation` typeclass to provide flexible API
- add `OpMonad` to provide basic `Monad` for user
- add tests `testMonad` and `testError`
> feat(bindings/haskell): add `Monad` wrapper

- examples/rust/01-init-operator/README.md
the output in README.md is 
```
:) cargo run
Compiling init-operator v0.1.0 (/home/xuanwo/Code/apache/incubator-opendal/examples/rust/01-init-operator)
Finished dev [unoptimized + debuginfo] target(s) in 0.38s
Running `target/debug/init-operator`
operator from builder: Operator { accessor: S3Backend { core: S3Core { bucket: "example", endpoint: "https://s3.us-east-1.amazonaws.com/example", root: "/", .. } }, limit: 1000 }
operator from map: Operator { accessor: S3Backend { core: S3Core { bucket: "example", endpoint: "https://s3.us-east-1.amazonaws.com/example", root: "/", .. } }, limit: 1000 }
```
ref: [lets-go](https://github.com/apache/incubator-opendal/blob/main/examples/rust/01-init-operator/README.md#lets-go)
> docs: update readme.md to match the output

- bindings/c/Makefile
- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/result.rs
- bindings/c/src/types.rs
- bindings/c/tests/bdd.cpp
Previously the C bindings API is a little bit confusing by mixing the pointers and the wrapping types, now it uses pointers for all APIs.
Related: #2488 #2462 
This would probably break some bindings that depend on the C binding.
> refactor(bindings/C): refactor c bindings to call all APIs using pointer

- core/Cargo.toml
- core/src/services/dropbox/backend.rs
- core/src/services/dropbox/builder.rs
- core/src/services/dropbox/core.rs
- core/src/services/dropbox/error.rs
- core/src/services/dropbox/mod.rs
- core/src/services/dropbox/writer.rs
- core/src/services/mod.rs
- core/src/types/scheme.rs
> feat(services/dropbox): Support create/read/delete for Dropbox

- bindings/java/pom.xml
- bindings/java/src/main/java/org/apache/opendal/NativeObject.java
This closes https://github.com/apache/incubator-opendal/issues/2361.
I noticed that we don't need to add an argument for users to pass path to lib. But `java.library.path` can already change the search path.
Also, get rid of unnecessary jar-jni dependency.
> feat(bindings/java): support load system lib

- bindings/zig/test/bdd.zig
- core/src/raw/adapters/typed_kv/backend.rs
add rename and copy support to kv adapters, it will bring kv base services to rename and copy capability
> feat(adapters-kv): add rename and copy support to kv adapters

- core/src/services/webhdfs/backend.rs
In my recent PR, I tried to avoid compiler else error and I accidentally [miss-used map condition flow](https://github.com/apache/incubator-opendal/pull/2499/commits/b2231f6d1377006e01f4b427129bfdc7777aa705). So current code will always execute `disable_list_batch`. I apologize for the mistake, and here's a PR fix for it.
> fix(service/webhdfs): fix webhdfs config builder for disable_list_batch

- .github/workflows/service_test_hdfs.yml
- .github/workflows/service_test_rocksdb.yml
- .github/workflows/service_test_sled.yml
- Cargo.lock
- bindings/haskell/Cargo.toml
- bindings/lua/Cargo.toml
- core/Cargo.toml
- core/src/services/memory/backend.rs
- core/tests/behavior/append.rs
- core/tests/behavior/blocking_copy.rs
- core/tests/behavior/blocking_list.rs
- core/tests/behavior/blocking_read.rs
- core/tests/behavior/blocking_read_only.rs
- core/tests/behavior/blocking_rename.rs
- core/tests/behavior/blocking_write.rs
- core/tests/behavior/copy.rs
- core/tests/behavior/list.rs
- core/tests/behavior/list_only.rs
- core/tests/behavior/main.rs
- core/tests/behavior/presign.rs
- core/tests/behavior/read_only.rs
- core/tests/behavior/rename.rs
- core/tests/behavior/utils.rs
- core/tests/behavior/write.rs
This PR implement the test harness via [libtest-mimic](https://github.com/LukasKalbertodt/libtest-mimic).
In the future, we will re-org our tests based on our new test harness. But in this PR, we just change the runner.
> feat: Implement test harness via libtest-mimic instead

- .env.example
- .github/workflows/service_test_sled.yml
- core/src/services/sled/backend.rs
introduce tree support https://github.com/apache/incubator-opendal/issues/2498
> feat(service/sled): introduce tree support

- bindings/haskell/haskell-src/OpenDAL.hs
- bindings/haskell/haskell-src/OpenDAL/FFI.hs
- bindings/haskell/opendal-hs.cabal
- bindings/haskell/src/lib.rs
- bindings/haskell/src/types.rs
- bindings/haskell/test/BasicTest.hs
Update:
- export `list` and `scan`
- add tests for `copy`, `rename`, `list`, `scan`
- fix error of trailling `\0` in `leak_str`
- refactor `OpMonad` from custom type to type synonym in order to provide more available ways
I imitate `DirStream` in `unix` library to design `Lister` API. However, it doesn't seem very native and useful. I havn't came up with other solutions about it yet. Maybe we can improve it in the future.
> feat(bindings/haskell): support list and scan

- core/src/types/operator/operator.rs
base on comment https://github.com/apache/incubator-opendal/blob/main/core/src/types/operator/operator.rs#L102, default limit size must be 1000.
> fix(types/operator): fix operation limit error default size

- README.md
- website/src/components/HomepageFeatures/_feature_services.mdx
add missing doc for https://github.com/apache/incubator-opendal/pull/2526
> doc(services/redb): add doc for redb service backend

- CONTRIBUTING.md
- website/docs/contributing/reference/generate_release_note.md
- website/docs/contributing/reference/setup_gpg.md
- website/docs/contributing/reference/verify_a_release_candidate.md
- website/docs/contributing/release.md
- Fix some typos.
- Add a verify-a-release-candidate doc.
> doc: polish release doc

- core/src/raw/oio/into_stream/from_futures_reader.rs
- core/src/raw/oio/into_stream/mod.rs
- core/src/types/writer.rs
- core/tests/behavior/write.rs
Part of https://github.com/apache/incubator-opendal/issues/2084
> feat: Implement Writer::copy so user can copy from AsyncRead

- core/Cargo.toml
I'm not sure what happened, but configuring `tests.path` should at least ensure that opendal core enters the publish workflow.
Other changes are caused by `taplo fmt` and can be ignored.
fix https://github.com/apache/incubator-opendal/actions/runs/5391859099/jobs/9789526157
> chore: add tests path to make publish workflow work

- bindings/haskell/CONTRIBUTING.md
- bindings/haskell/README.md
- bindings/haskell/haskell-src/OpenDAL.hs
- bindings/haskell/opendal-hs.cabal
- bindings/haskell/test/BasicTest.hs
Update:
- add some module documents in `OpenDAL.hs`
- apply `hlint` suggestions
> doc(bindings/haskell): add module document

- website/docusaurus.config.js
I forgot to update `docusaurus.config.js` to add a link for haskell binding in #2569
> chore: add haskell binding link to website

- core/src/raw/http_util/body.rs
- core/src/services/memcached/backend.rs
Made changes to the comments as mentioned in the issue (#2572)
> docs: Update license related comments

- core/src/services/oss/backend.rs
- core/src/services/oss/core.rs
- core/src/services/oss/writer.rs
> feat(services/oss): support sink

- core/src/services/obs/backend.rs
- core/src/services/obs/core.rs
- core/src/services/obs/writer.rs
> feat(services/obs): support sink

- .github/workflows/ci.yml
- licenserc.toml
- website/src/components/HomepageFeatures/styles.module.css
- website/src/css/custom.css
- website/src/pages/index.module.css
This closes https://github.com/apache/incubator-opendal/pull/2584.
It actually comes from the idea to follow the previous suggestion in C header style, lol.
> ci: upgrade hawkeye to v3

- Cargo.toml
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
As a library, this isn't important as end-user application decides the resolver finally. Just remove the warning.
ref:
- https://github.com/rust-lang/cargo/issues/10112
- https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
> chore: fix cargo warning for resolver

- Cargo.lock
e.g., `cargo doc --all-features` will failed to compile on latest nightly due to value-bag.
ref: https://github.com/rust-lang/log/issues/500
> chore: bump log to 0.4.19

- core/src/services/hdfs/docs.md
> docs: add hdfs namenode High Availability related troubleshoot

- website/docs/contributing/release.md
- add more examples
- proper usage of opendal_version and release_version
> docs: polish release doc

- bin/oli/tests/cat.rs
- bin/oli/tests/ls.rs
- bin/oli/tests/rm.rs
- bin/oli/tests/stat.rs
add `cat` `stat` `ls` `rm` sub command test.
> test(oli): add oli related tests

- core/src/raw/oio/cursor.rs
- core/src/raw/oio/into_blocking_reader/from_fd.rs
- core/src/raw/oio/into_reader/by_range.rs
- core/src/raw/oio/into_reader/from_fd.rs
- core/src/types/error.rs
If user try to seek for a invalid position, we will give an `Unexpected` Error. `Unexpected` Error used to represent `OpenDAL don't know what happened here`. I think it may be better to use a new error kind `InvalidInput` to represent this situation.
```
/// OpenDAL don't know what happened here, and no actions other than just
/// returning it back. For example, s3 returns an internal service error.
Unexpected,
```
before:
```
2023-07-14T06:37:19.152933Z ERROR opendal::services: service=memory operation=Reader::seek path=bfae56eb-ae99-4ca6-b000-4bdad69c85e1 read=0 -> data read failed: Unexpected (permanent) at Reader::seek => invalid seek to a negative or overflowing position
Context:
service: memory
path: bfae56eb-ae99-4ca6-b000-4bdad69c85e1
at core/src/layers/logging.rs:1108
```
after: …
> refactor(core): Add ErrorKind InvalidInput to indicate users input error

- bindings/c/CONTRIBUTING.md
- bindings/c/Makefile
- bindings/c/README.md
- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/result.rs
- bindings/c/src/types.rs
- bindings/c/tests/bdd.cpp
- bindings/c/tests/common.hpp
- bindings/c/tests/list.cpp
- bindings/c/tests/test_list.cpp
~~The PR will first be marked as WIP~~
This PR implements the `list()` method of the opendal in C binding.
note: we don't need to review the `opendal.h`, it is auto generated by the rust code.
- The functionality of `list()`
- A separate unit test for `list()`
- Fix some of the frees, previously it did not free the inner pointer, which is heap allocated.
todo:
- Maybe we should use macro to unify the implementation the `freeing` of the types, since the patterns are almost the same.
- Upon development, I found that multiple types and operations living in one single file is becoming more and more messy. Maybe a refactoring is needed as well.
> feat(bindings/C): add support for list in C binding

- core/src/services/s3/backend.rs
refactor(services/s3): Add more detect logic for detect_region
> refactor(services/s3): Add more detect logic for detect_region

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/java/pom.xml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
* feat(binding/lua): add rename and create_dir operator function by @oowl in https://github.com/apache/incubator-opendal/pull/2564
* feat(services/azblob): support sink by @suyanhanx in https://github.com/apache/incubator-opendal/pull/2574
* feat(services/gcs): support sink by @suyanhanx in https://github.com/apache/incubator-opendal/pull/2576
* feat(services/oss): support sink by @suyanhanx in https://github.com/apache/incubator-opendal/pull/2577
* feat(services/obs): support sink by @suyanhanx in https://github.com/apache/incubator-opendal/pull/2578
* feat(services/cos): impl sink by @suyanhanx in https://github.com/apache/incubator-opendal/pull/2587
* feat(service): Support stat for Dropbox by @Zheaoli in https://github.com/apache/incubator-opendal/pull/2588
* feat(services/dropbox): …
> Bump to version 0.38.1

- core/src/raw/oio/read.rs
- core/src/types/error.rs
- core/tests/behavior/write.rs
related: https://github.com/apache/incubator-opendal/pull/2637#issuecomment-1635465681
add a behaviour test for InvalidInput https://github.com/apache/incubator-opendal/pull/2637
> test: add a behaviour test for InvalidInput

- .env.example
- .github/workflows/service_test_persy.yml
- Cargo.lock
- README.md
- core/Cargo.toml
- core/README.md
- core/src/services/mod.rs
- core/src/services/persy/backend.rs
- core/src/services/persy/docs.md
- core/src/services/persy/mod.rs
- core/src/types/operator/builder.rs
- core/src/types/scheme.rs
- core/tests/behavior/main.rs
- website/src/components/HomepageFeatures/_feature_services.mdx
This PR has initially implemented support for the persy backend, and added corresponding CI and documentation.
```
OPENDAL_PERSY_TEST=false
OPENDAL_PERSY_DATAFILE=/tmp/opendal/test.persy
OPENDAL_PERSY_SEGMENT=data
OPENDAL_PERSY_INDEX=index
```
Fixes: #2522
> feat(services/persy): add a basic persy service impl

- core/fuzz/Cargo.toml
I found that https://github.com/apache/incubator-opendal/actions/runs/5573356275/jobs/10180524092  made cargo give our a warning 
```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /githubProjects/incubator-opendal/core/fuzz/Cargo.toml
workspace: /githubProjects/incubator-opendal/Cargo.toml
```
**This pr remove the profile setting to fix this warning.**
> fix(test): profile setting warning

- .github/workflows/service_test_webdav.yml
> ci(services/webdav): Setup integration test for owncloud

- core/src/raw/http_util/error.rs
- core/src/raw/http_util/mod.rs
- core/src/services/azblob/error.rs
- core/src/services/azdfs/error.rs
- core/src/services/cos/error.rs
- core/src/services/dropbox/error.rs
- core/src/services/gcs/error.rs
- core/src/services/gdrive/error.rs
- core/src/services/ghac/error.rs
- core/src/services/http/error.rs
- core/src/services/ipfs/error.rs
- core/src/services/ipmfs/error.rs
- core/src/services/obs/error.rs
- core/src/services/onedrive/error.rs
- core/src/services/oss/error.rs
- core/src/services/s3/error.rs
- core/src/services/supabase/error.rs
- core/src/services/vercel_artifacts/error.rs
- core/src/services/wasabi/error.rs
- core/src/services/webdav/error.rs
- core/src/services/webhdfs/error.rs
Fix https://github.com/apache/incubator-opendal/issues/2661
> feat(core/http_util): Remove sensitive header like Set-Cookie

- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/types.rs
- bindings/c/tests/list.cpp
This PR fix the memory leak found in the tests in #2653.
I believe the memory leak is not completely fixed and it could be bettered through more tests on the C binding functionalities.
> fix(bindings/C): fix the memory found in valgrind.

- .github/actions/setup/action.yaml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/publish.yml
- core/src/services/oss/backend.rs
Add a step in the rust environment setup action to set up the protoc compiler. Currently used by tikv and etcd services.
> ci: Setup protoc in rust builder

- .github/workflows/bindings_c.yml
- bindings/c/Makefile
This is for issue #2495 
Note that it currently breaks the ci testing because it has found memory leaks
> test(bindings/c): Implement valgrind check in test and ci

- Cargo.lock
- bin/oli/Cargo.toml
- bin/oli/src/config/mod.rs
- core/Cargo.toml
- core/src/services/etcd/backend.rs
- core/src/services/etcd/docs.md
- core/src/services/etcd/mod.rs
- core/src/services/mod.rs
- core/src/types/operator/builder.rs
- core/src/types/scheme.rs
> feat(services/etcd): introduce new service backend etcd

- website/docs/contributing/release.md
Originally post in discord:
https://discord.com/channels/1081052318650339399/1129336445967007744/1131824700306231396
> If you made some mistakes in those phases, what might happen, and how should do you evict your mistakes...
> docs: add instructions to fix wrong vote mail and uploads

- .github/workflows/service_test_webdav.yml
Our integration test for owncloud has chance to fail
We try to solve this by reducing concurrency  https://github.com/apache/incubator-opendal/pull/2667
but it fail again, so this PR try to add redis to make owncloud happy
> I found a related discussion https://central.owncloud.org/t/file-is-locked-how-to-unlock/985.
Maybe we can try to use redis to reduce the unexpected lock happen?
https://github.com/apache/incubator-opendal/actions/runs/5606271748/jobs/10256268444
> fix: owncloud test sometimes fail

- Cargo.lock
- core/Cargo.toml
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/services/wasabi/backend.rs
- core/src/services/wasabi/core.rs
I know this PR is complex, but this is how AWS works.
> feat(services/s3): Add assume role support

- core/src/services/cos/backend.rs
- core/src/services/cos/core.rs
- core/src/services/cos/writer.rs
Add multipart upload api support for service obs
close issue #2651 
To test the changes, follow the setup specified in https://github.com/apache/incubator-opendal/tree/main/core/tests/behavior#setup , then run `cargo test services_cos::test_fuzz_unsized_writer`.
> feat(service/cos): add multipart upload function support

- core/src/raw/oio/write/mod.rs
- core/src/raw/oio/write/multipart_upload_write.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/services/s3/writer.rs
This PR will add `MultipartUploadWrite` to easier the work of implementing `Writer`.
It's an internal API that users can't use directly. We add this to simplify the work to implement `Writer` for services like s3, cos and oss. And align the behavior of buffering and available options.
This PR just migrated the implement of `s3` and we will start a migrate issue for other services.
> feat(oio): Add MultipartUploadWrite to easier the work for Writer

- core/fuzz/Cargo.toml
- core/fuzz/fuzz_range_reader.rs
- core/fuzz/fuzz_reader.rs
- core/fuzz/fuzz_writer.rs
part of: https://github.com/apache/incubator-opendal/issues/2551
also split `reader` and `range reader`, ref: https://github.com/apache/incubator-opendal/pull/2609#discussion_r1259234655
> feat(test): add fuzz target for writer

- core/src/services/hdfs/docs.md
Sorry just make a mistake, the previous command will cause ` java.net.UnknownHostException`.
I have verified the new command, it is correct.
> fix: fix `HADOOP_CONF_DIR` setting in guidance document

- core/src/services/cos/backend.rs
- core/src/services/cos/core.rs
- core/src/services/cos/writer.rs
> feat: cos multipart uploads write

- core/src/raw/oio/read/into_read_from_file.rs
Fix https://github.com/apache/incubator-opendal/issues/2717
The crash case has been fixed.
```shell
:) RUST_LOG=debug cargo +nightly fuzz run fuzz_range_reader /tmp/crash-4526ccffa285c58ef8c7731d4a5dfef69d38cfff
Compiling opendal v0.38.1 (/home/xuanwo/Code/apache/incubator-opendal/core)
Compiling opendal-fuzz v0.0.0 (/home/xuanwo/Code/apache/incubator-opendal/core/fuzz)
Finished release [optimized] target(s) in 2m 06s
Finished release [optimized] target(s) in 0.09s
Running `/home/xuanwo/Code/apache/incubator-opendal/target/x86_64-unknown-linux-gnu/release/fuzz_range_reader -artifact_prefix=/home/xuanwo/Code/apache/incubator-opendal/core/fuzz/artifacts/fuzz_range_reader/ /tmp/crash-4526ccffa285c58ef8c7731d4a5dfef69d38cfff`
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: …
```
> fix: Seek before the start of file should be invalid

- core/src/services/oss/backend.rs
- core/src/services/oss/core.rs
- core/src/services/oss/writer.rs
> feat: oss multipart uploads write

- core/src/raw/ops.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/types/capability.rs
- core/src/types/operator/operator_futures.rs
- core/tests/behavior/write.rs
> feat: add override_content_type

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/java/pom.xml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- core/src/docs/upgrade.md
* feat: add a behaviour test for InvalidInput by @dqhl76 in https://github.com/apache/incubator-opendal/pull/2644
* feat(services/persy): add a basic persy service impl by @PsiACE in https://github.com/apache/incubator-opendal/pull/2648
* feat(services/vercel_artifacts): Impl `stat` by @suyanhanx in https://github.com/apache/incubator-opendal/pull/2649
* feat(test): add fuzz test for range_reader by @dqhl76 in https://github.com/apache/incubator-opendal/pull/2609
* feat(core/http_util): Remove sensitive header like Set-Cookie by @Xuanwo in https://github.com/apache/incubator-opendal/pull/2664
* feat: Add RetryInterceptor support for RetryLayer by @Xuanwo in https://github.com/apache/incubator-opendal/pull/2666
* feat: support kerberos for hdfs service by @zuston in …
> Bump to version 0.39.0

- bindings/php/.cargo/config.toml
- bindings/php/.gitignore
- bindings/php/Cargo.toml
- bindings/php/README.md
- bindings/php/composer.json
- bindings/php/opendal-php.stubs.php
- bindings/php/phpunit.xml
- bindings/php/src/lib.rs
- bindings/php/tests/Unit/BasicTest.php
see https://github.com/apache/incubator-opendal/issues/2716
A new subdirectory `bindings/php` has been created in order to have PHP bindings for the OpenDAL library. This includes new PHP tests, stdlib stubs for the PHP interface, and addition of composer configuration for dependency management. as well as the initial source code written in Rust to provide PHP bindings. The 'debug' function is used as a test to check the binding. The README has been added to guide users and developers in building and testing the PHP bindings.
> feat: setup the integrate with PHP binding

- Cargo.lock
- core/Cargo.toml
- core/src/layers/async_backtrace.rs
- core/src/layers/mod.rs
close https://github.com/apache/incubator-opendal/issues/2617
> feat: add async backtrace layer

- bin/oay/src/services/webdav/webdav_file.rs
> feat(oay): add write for oay webdav

- core/Cargo.toml
Update:
- bump backon to 0.4.1
https://github.com/Xuanwo/backon/pull/54 feature can only be used in 0.4.1. As result, if backon version is 0.4.0, it won't pass compile.
Compiler Output:
```
error[E0308]: mismatched types
--> /Volumes/haha/code/project/incubator-opendal/core/src/layers/retry.rs:300:21
|
300 |               .notify(|err, dur: Duration| {
|  ______________------_^
| |              |
| |              arguments to this method are incorrect
301 | |                 self.notify.intercept(
302 | |                     err,
303 | |                     dur,
...   |
308 | |                 )
309 | |             })
| |_____________^ expected fn pointer, found closure
|
= note: expected fn pointer `for<'a> fn(&'a types::error::Error, std::time::Duration)`
found closure …
```
> fix: fix compile error by low version of backon in old project

- core/Cargo.toml
Fix https://github.com/apache/incubator-opendal/issues/2783
> chore: Bump bytes to 1.4 to allow the usage of spare_capacity_mut

- core/Cargo.toml
`chrono` enables the `oldtime` feature for backwards compatibility but this project doesn't make use of it. Disabling it avoids the dependency on `time` v0.1
> chore: disable oldtime feature of chrono

- core/src/raw/oio/read/into_seekable_read_by_range.rs
We used to have an optimize that using `read` instead of `seek` in `into_seekable_read_by_range`. But it not works in most case, let's remove them.
> refactor: Remove optimize in into_seekable_read_by_range

- Cargo.lock
- core/Cargo.toml
We found a problem with the older version while adding the blocking layer, bump this to fix it.
See details at #2780
> fix: Bump openssh-sftp-client from 0.13.5 to 0.13.7

- core/src/layers/complete.rs
- core/src/raw/oio/read/into_seekable_read_by_range.rs
Fix https://github.com/apache/incubator-opendal/issues/2791
We don't have this support since there is all blocking services support seek. But with the addition of blocking layer, we should fill this gap.
> feat: Add into_seekable_read_by_range support for blocking read

- .github/workflows/service_test_webdav.yml
close: https://github.com/apache/incubator-opendal/issues/2804
Reference:
https://hub.docker.com/_/nextcloud/
> If you want to use Redis you have to create a separate [Redis](https://hub.docker.com/_/redis/) container in your setup / in your docker-compose file. To inform Nextcloud about the Redis container, pass in the following parameters:
REDIS_HOST (not set by default) Name of Redis container
The use of Redis is recommended to prevent file locking problems. See the examples for further instructions.
> fix: add redis for nextcloud to solve file locking problem

- bin/oay/src/services/s3/service.rs
- bin/oli/src/commands/cp.rs
- bindings/c/include/opendal.h
- bindings/object_store/src/lib.rs
- core/src/layers/async_backtrace.rs
- core/src/layers/await_tree.rs
- core/src/layers/immutable_index.rs
- core/src/raw/oio/entry.rs
- core/src/raw/oio/read/into_seekable_read_by_range.rs
- core/src/raw/oio/write/multipart_upload_write.rs
- core/src/raw/ops.rs
- core/src/services/tikv/backend.rs
- core/src/types/entry.rs
- core/src/types/list.rs
- core/src/types/metadata.rs
- core/src/types/operator/blocking_operator.rs
- core/src/types/operator/operator.rs
- core/src/types/operator/operator_futures.rs
- core/tests/behavior/fuzz.rs
- core/tests/behavior/list.rs
Add metakey support for async list.
> feat: Add async list with metakey support

- .github/workflows/service_test_webdav.yml
- core/src/layers/blocking.rs
- core/src/layers/retry.rs
- core/src/services/dropbox/error.rs
- core/src/services/webdav/backend.rs
- core/tests/behavior/blocking_write.rs
- core/tests/behavior/utils.rs
fix https://github.com/apache/incubator-opendal/issues/2807
> fix: Fix behaivor tests for blocking layer

- .github/workflows/fuzz_test.yml
- .github/workflows/service_test_s3.yml
- core/src/services/s3/backend.rs
> fix(services/s3): remove default region `us-east-1` for non-aws s3

- bin/oli/README.md
Related issue: #2818 
This PR aims to fixe an issue that the examples of profiles in `bin/oli/README.md`.
> fix(oli, doc): Fix examples of config.toml for oli

- Cargo.lock
- bin/oli/Cargo.toml
- bin/oli/src/config/mod.rs
- bin/oli/tests/cat.rs
- bin/oli/tests/cp.rs
- bin/oli/tests/ls.rs
- bin/oli/tests/rm.rs
- bin/oli/tests/stat.rs
As I mentioned at  #2822,  temporary files generated in tests are not deleted automatically.
To fix this issue, this PR introduces `tempfile` crate.
https://docs.rs/tempfile/latest/tempfile/index.html
A temporary directory created using `tempfile` crate and files in the temporary directory will be automatically deleted when the corresponding `TempDir` object is dropped.
This PR affects the tests in `bin/oli` and  confirmed all the tests passed with `cargo test --tests --package oli`
> fix: Cleanup temporary files generated in tests automatically

- core/src/services/rocksdb/backend.rs
for https://github.com/apache/incubator-opendal/issues/2826
> feat(services/rocksdb): Add scan support

- bindings/ocaml/README.md
Add a document describing how to configure the development environment of `bindings/ocaml`
> chore(bindings/ocaml): Add contributing document to readme

- Cargo.lock
- core/Cargo.toml
Bump openssh-sftp-client to fix the failed test https://github.com/apache/incubator-opendal/actions/runs/5798363627/job/15715936917
> fix(services/sftp): bump openssh-sftp-client to 0.13.9

- bin/oay/src/services/webdav/webdav_file.rs
- bin/oay/src/services/webdav/webdavfs.rs
Here add `create_dir`, `remove`, `copy` and `rename` for oay-webdav.
> feat: Add create_dir, remove, copy and rename API for oay-webdav

- bin/oli/src/config/mod.rs
- bin/oli/tests/cat.rs
- bin/oli/tests/cp.rs
- bin/oli/tests/rm.rs
- bin/oli/tests/stat.rs
Related issue: #2834 
Given we have a directory `d` and a file `d/f`, and the current working directory is `d`.
If we run `oli stat` for `f` like as follows, it works.
```
$ oli stat ./f
```
But if we omit `./`, it doesn't work.
```
$ oli stat f
Error: ConfigInvalid (permanent) at  => root is not specified
```
The cause is that root directory is not set to `fs_builder` as the error message says.
> fix(oli): oli commands don't work properly for files in CWD

- core/src/services/mini_moka/backend.rs
- core/src/services/mini_moka/docs.md
- core/src/services/moka/backend.rs
- core/src/services/moka/docs.md
Fix https://github.com/apache/incubator-opendal/issues/2849
> feat(services/moka, services/mini-moka): Add scan support

- bindings/c/examples/basicrw.c
This PR fixes an issue that building examples/basicrw.c fails.
> fix(bindings/c): Fix an example of the C binding

- bindings/c/README.md
Related issue #2855 
This PR aims to updates the requirements for building the C binding.
I confirmed this instructions work with a docker image of Ubuntu 22.04.
> fix(doc): Update instructions for building the C binding in README.md

- core/README.md
Related issue: #2865 
This PR fixes an issue that the link to the Rust example is missing.
> docs: Fix missing link for rust example

- core/src/services/dropbox/backend.rs
- core/src/services/dropbox/core.rs
> feat(services/dropbox): read support range

- bindings/nodejs/README.md
This PR fixes an issue explained in #2875.
Confirmed this change fixes the issue by building the doc with `yarn run docs`.
> docs: Fix missing link to the contribution guide for the Node.js binding

- bindings/ocaml/src/operator/mod.rs
- bindings/ocaml/src/operator/reader.rs
- core/src/layers/retry.rs
- core/src/raw/oio/stream/api.rs
- core/src/raw/oio/stream/into_stream.rs
- core/src/raw/oio/stream/into_stream_from_reader.rs
- core/src/raw/oio/stream/mod.rs
This PR will add retry for sink operations.
> feat: Add retry for Writer::sink operation

- bin/oay/src/services/webdav/webdav_file.rs
- core/benches/ops/read.rs
- core/fuzz/fuzz_reader.rs
- core/src/layers/logging.rs
- core/src/types/operator/operator.rs
- core/tests/behavior/fuzz.rs
- core/tests/behavior/read_only.rs
- core/tests/behavior/write.rs
- integrations/object_store/src/lib.rs
part of https://github.com/apache/incubator-opendal/issues/2885
> feat: remove operator range_read and range_reader API

- bindings/java/src/main/resources/META-INF/NOTICE
This closes https://github.com/apache/incubator-opendal/issues/2916.
Verified locally. And yes, opendal-java contains built without any compile dependency on Maven Central.
FYI @markt-asf this should address the issue you spot :D
> fix(binding/java): Overwrite default NOTICE file with correct years

- core/Cargo.toml
- core/benches/oio/main.rs
- core/benches/oio/utils.rs
- core/benches/oio/write.rs
- core/src/raw/oio/cursor.rs
- core/src/raw/oio/write/exact_buf_write.rs
```rust
at_least_buf_write/4.00 KiB
time:   [149.96 ns 150.10 ns 150.25 ns]
thrpt:  [25.388 GiB/s 25.415 GiB/s 25.438 GiB/s]
at_least_buf_write/256 KiB
time:   [127.08 ns 127.17 ns 127.28 ns]
thrpt:  [1918.2 GiB/s 1919.8 GiB/s 1921.2 GiB/s]
at_least_buf_write/4.00 MiB
time:   [124.63 ns 125.06 ns 125.72 ns]
thrpt:  [ 31072 GiB/s  31234 GiB/s  31342 GiB/s]
at_least_buf_write/16.0 MiB
time:   [125.82 ns 126.05 ns 126.34 ns]
thrpt:  [123677 GiB/s 123955 GiB/s 124186 GiB/s]
exact_buf_write/4.00 KiB
time:   [245.48 ns 245.68 ns 245.88 ns]
thrpt:  [15.515 GiB/s 15.527 GiB/s 15.540 GiB/s]
exact_buf_write/256 KiB time:   [215.33 ns 215.43 ns 215.53 ns]
thrpt:  [1132.7 GiB/s 1133.3 GiB/s 1133.8 GiB/s]
exact_buf_write/4.00 MiB
time:   [1.6147 µs 1.6155 µs 1.6163 µs]
thrpt:  [2416.8 GiB/s 2418.0 …
```
> feat: Add benchmark for buf write

- .github/workflows/service_test_gcs.yml
- core/src/services/gcs/core.rs
Fix #2837 
`test_writer_sink` and `test_writer_copy` will be failed because we can't put stream body into multipart. Is there any way to solve it?
> fix(services/gcs): migrate to new multipart impl for gcs_insert_object_request

- core/src/services/gcs/backend.rs
- core/src/services/gcs/docs.md
- website/docs/services/azblob.mdx
- website/docs/services/azdfs.mdx
- website/docs/services/cos.mdx
- website/docs/services/fs.mdx
- website/docs/services/ftp.mdx
- website/docs/services/gcs.mdx
- website/docs/services/hdfs.mdx
- website/docs/services/ipfs.mdx
- website/docs/services/memory.mdx
- website/docs/services/oss.mdx
- website/docs/services/redis.mdx
- website/docs/services/rocksdb.mdx
- website/docs/services/s3.mdx
- website/docs/services/sftp.mdx
- website/docs/services/sled.mdx
- website/docs/services/webhdfs.mdx
Update #2304
All examples of Via Config written in Rust have unused import `Arc` and missing import `HashMap`. I update it for all service docs and format them with `cargo fmt`.
> docs: add service doc for gcs

- core/src/services/gcs/backend.rs
https://opendal.apache.org/docs/rust/opendal/services/struct.Gcs.html
Currently, the doc of gcs in the rust core's docs is missing.
> docs(services/gcs): fix rust core doc include

- bin/oay/src/services/webdav/webdavfs.rs
This PR fix litmus copymove test `copy_overwrite`, `move` and `move_coll`. Refer to [`dav-server-rs::LocalFs::rename`](https://github.com/messense/dav-server-rs/blob/1346f52007aab7c701288b4c3e99b5e4d44369c3/src/localfs.rs#L414-L425)
```txt
-> running `copymove':
0. init.................. pass
1. begin................. pass
2. copy_init............. pass
3. copy_simple........... pass
4. copy_overwrite........ pass
5. copy_nodestcoll....... pass
6. copy_cleanup.......... pass
7. copy_coll............. pass
8. copy_shallow.......... pass
9. move.................. pass
10. move_coll............. pass
11. move_cleanup.......... pass
12. finish................ pass
<- summary for `copymove': of 13 tests run: 13 passed, 0 failed. 100.0%
``` …
> fix(oay): pass litmus copymove test

- .github/workflows/oay_test_webdav.yml
> CI(oay): add CI for oay-webdav

- bindings/java/src/test/java/org/apache/opendal/AsyncStepsTest.java
- bindings/nodejs/tests/binding.js
Fix https://github.com/apache/incubator-opendal/issues/2960
> fix(nodejsjava): Add place holder for BDD test

- Cargo.lock
- bindings/cpp/.gitignore
- bindings/cpp/CMakeLists.txt
- bindings/cpp/Cargo.toml
- bindings/cpp/README.md
- bindings/cpp/build.rs
- bindings/cpp/include/opendal.hpp
- bindings/cpp/src/lib.rs
- bindings/cpp/src/opendal.cpp
- bindings/cpp/tests/basic_test.cpp
We use [`cxx`](https://cxx.rs/) to interop between Rust and C++.
About build system, rust side still use `cargo`. For better integration with google test, we use [`cmake`](https://cmake.org/) and [`ninja`](https://ninja-build.org/) to build c++ code. All build scripts are written in `cmake`, so `ninja` can be replaced by [`make`](https://www.gnu.org/software/make/manual/make.html) or [`bazel`](https://bazel.build/). I choose it just because it looks like faster.
```cpp
#include "opendal.hpp"
#include <vector>
int main() {
auto op = opendal::Operator("memory");
std::vector<uint8_t> data = {1, 2, 3, 4, 5};
op.write("test", data);
auto result = op.read("test");  // result == data
}
```
Now I can only build static library, failed to build dynamic library.
> feat(bindings/cpp): init cpp binding

- core/src/raw/adapters/kv/backend.rs
Fixed the issue that when using KV Backend, it cannot be read or written because the capability setting is incorrect
> fix(core): Fix capability of services is not set correctly

- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
- core/src/services/gcs/writer.rs
#1962  multipart upload support cache control parameter
> feat: gcs insert object support cache control

- .github/workflows/oay_test_webdav.yml
part of https://github.com/apache/incubator-opendal/pull/2957
tracked in https://github.com/apache/incubator-opendal/issues/2586
> ci(oay): Polish oay webdav test

- .github/workflows/bindings_cpp.yml
- .github/workflows/docs.yml
- Cargo.lock
- bindings/cpp/CMakeLists.txt
- bindings/cpp/CONTRIBUTING.md
- bindings/cpp/Cargo.toml
- bindings/cpp/include/opendal.hpp
- bindings/cpp/src/lib.rs
- bindings/cpp/src/opendal.cpp
- bindings/cpp/tests/basic_test.cpp
Update:
1. expose `is_exist`, `create_dir`, `copy`, `rename`, `remove`, `stat`, `list`.
Now it only remains `reader`, `writer`, `lister`.
2. add valgrind in test ci to check more memory leak occasion
3. add docs-only option to avoid install dependency in docs ci
About `Operator::read`, I changed impl in #2984 because `address sanitizer` outputs `container overflow`. But I found that this is a misinformation caused by missing sanitize option for `libopendal_cpp`. As result, I revert previous impl. However, we still can't avoid copy because all `std::vector` pointer constructor use copy to hide internal structure.
> feat(bindings/cpp): expose all api returned by value

- CONTRIBUTING.md
- bindings/cpp/CONTRIBUTING.md
https://en.wikipedia.org/wiki/MacOS
> docs: fix spelling - change `MacOS` to `macOS`

- core/src/types/writer.rs
This adjusts the trait bounds on the input stream (for `sink`) or reader (for `copy`) for the `opendal::Writer` type to be less strict, and thus allow more types to be passed in. 
In particular, the current implementations of these functions do not use any of the additional "information"/requirements that `Send + Sync + Unpin + 'static` imply. The `'static` bound is particularly restrictive, as it stops one being able to pass in any borrowed data, such as a `&mut dyn AsyncRead` object or similar. Without these bounds, one can pass in more readers or more streams, more simply.
There is a downside to this change: if these _implementations_ wanted to change in future to use any of these (e.g. a threaded implementation of `copy` or something), that becomes a breaking change. I would suggest …
> refactor: Relax bounds on Writer::{sink, copy}

- .github/workflows/bindings_cpp.yml
- .github/workflows/docs.yml
- bindings/cpp/CMakeLists.txt
- bindings/cpp/CONTRIBUTING.md
- bindings/cpp/README.md
Update:
- set test and docs as an option in CMakeLists.txt so that library users don't have to build test binary and documents.
- run `cargo build --release` when setting `CMAKE_BUILD_TYPE` to `Release`
- fix missing headers when using it as external library
> chore(bindings/cpp): update CMakeLists.txt to prepare release

- core/src/services/fs/writer.rs
According to https://github.com/tokio-rs/tokio/issues/6005#issuecomment-1717310982, We should call `flush` before `sync_all`
Related: #3052
> fix: call `flush` before `sync_all`

- core/src/services/azblob/backend.rs
- core/src/services/azblob/core.rs
- core/src/services/azblob/writer.rs
Respect issue: #3064 .
Rewrote the service `azblob`.
> feat(services/azblob): Rewrite the method signatures using OpWrite

- .github/workflows/bindings_haskell.yml
- .github/workflows/docs.yml
- bindings/haskell/Setup.hs
Update:
- make cargo build type same with cabal
- save cabal build cache in ci, previously only saved installation package cache
> chore(bindings/haskell): make cargo build type same with cabal

- core/src/services/azdls/backend.rs
- core/src/services/azdls/core.rs
- core/src/services/azdls/writer.rs
Refactored services/azdls as part of #3064
> refactor(services/azdls): Use OpWrite instead of passing all args as parameters

- core/src/services/webdav/backend.rs
Complete the refactoring code for #3064.
This is a follow-up to #3076.
> refactor(services/webdav): Use OpRead in `webdav_get`.

- core/src/services/oss/backend.rs
- core/src/services/oss/core.rs
- core/src/services/oss/writer.rs
#3064 
- Refactor `oss_put_object` `oss_put_object_request` function in services/oss core.rs
- Usage of `oss_put_object_request` in writer.rs and backend.rs also changed
> refactor(services/oss): Refactor `oss_put_object` signatures by using OpWrite

- .github/workflows/bindings_haskell.yml
- .github/workflows/docs.yml
- bindings/haskell/opendal-hs.cabal
Update:
- add release workflow to package and update it to hackage. It will update a candidate package for rc tags, and update release package for real release.
- Each task saves the build cache, which created a conflict. So I remove the save cache task from the docs ci and now only the test ci saves the build cache to avoid conflicts.
Question:
Whose account should hackage use?
Where should we store the HACKAGE_TOKEN?
> ci(bindings/haskell): add release workflow

- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
> refactor(services/gcs): Rewrite `gcs` methods signature by using OpXxxx

- core/src/services/onedrive/backend.rs
- core/src/services/onedrive/writer.rs
Respect issue: #3064 for onedrive.
> feat(services/onedrive): Rewrite the method signatures using OpWrite

- examples/README.md
- examples/cpp/CMakeLists.txt
- examples/cpp/README.md
- examples/cpp/basic.cpp
update #3106
This is a basic example of c++. I will add more detailed tutorial like rust example in the future. 
And the example has a problem that we havn't set url hash. We should update it after release.
> docs: add basic example for cpp binding

- .github/workflows/bindings_haskell.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/cpp/CMakeLists.txt
- bindings/cpp/Cargo.toml
- bindings/dotnet/Cargo.toml
- bindings/haskell/Cargo.toml
- bindings/java/pom.xml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
As discussed at https://lists.apache.org/thread/8zowmvqsv34ckkk85s53hxzk2vhhf2f8, we are going to release next version as v0.40.
> chore: Bump version to v0.40 to start release process

- .github/workflows/bindings_haskell.yml
- .github/workflows/docs.yml
- bindings/haskell/CONTRIBUTING.md
- bindings/haskell/README.md
- bindings/haskell/opendal.cabal
update #3102, #3104 
Update:
- rename library name from opendal-hs to opendal
- add `source-repository this` in cabal config file.
> chore(bindings/haskell): rename library name from opendal-hs to opendal

- core/src/raw/ops.rs
- core/src/services/webhdfs/backend.rs
- core/src/services/webhdfs/pager.rs
- core/src/services/webhdfs/writer.rs
This PR addressed the `webhdfs` part of the issue: https://github.com/apache/incubator-opendal/issues/3064
**[Note]**
I just ran the unit test by `cargo test` on my local environment.
Please correct me if I missed anything.
> refactor(services/webhdfs): Rewrite `webhdfs` methods signature by using `OpXxxx`

- .github/workflows/bindings_haskell.yml
- .github/workflows/publish.yml
Our CI makes sure that all our projects can be built, so we can ignore the verify for dry run.
Fix https://github.com/apache/incubator-opendal/issues/3110
> ci: Don't verify content for dry run

- core/src/types/list.rs
- core/src/types/operator/blocking_operator.rs
- core/tests/behavior/blocking_list.rs
Fix https://github.com/apache/incubator-opendal/issues/3111
> fix: Metakeys are not propagated with the blocking operators

- CHANGELOG.md
OpenDAL's Round 2 of v0.40.0 release
> chore: Bump to v0.40.0 round 2

- website/docs/contributing/release.md
This closes https://github.com/apache/incubator-opendal/issues/3122.
> docs(release): describe how to close the Nexus staging repo

- core/src/services/dropbox/core.rs
- core/src/services/dropbox/writer.rs
> refactor(services/dropbox): Use OpWrite instead of passing all args as parameters

- .github/workflows/bindings_haskell.yml
- bindings/haskell/CONTRIBUTING.md
- bindings/haskell/README.md
- bindings/haskell/Setup.hs
Now users don't need to specify extra env vars for it. Users' build process is totally same with other common library.
> chore(bindings/haskell): add rpath to haskell linker option

- website/docs/vision.md
Close https://github.com/apache/incubator-opendal/issues/3090
It's ok to use opendal to connect db as a key-value services, but not for structural data.
> docs: Polish VISION to make it more clear

- .github/workflows/bindings_haskell.yml
- .github/workflows/bindings_nodejs.yml
- .github/workflows/bindings_python.yml
- .github/workflows/publish.yml
- .github/workflows/release_java.yml
- scripts/release.sh
- website/docs/contributing/release.md
- website/docs/vision.md
- Close https://github.com/apache/incubator-opendal/issues/3121
- Close https://github.com/apache/incubator-opendal/issues/3120
> ci: Align tags with semver specs

- .github/workflows/service_test_obs.yml
Thanks to @DatabendLabs sponsor and @everpcpc's hard work, OpenDAL can now use bucket maintained by databend labs now.
> ci: Migrate obs to databend labs sponsored bucket

- Cargo.lock
- core/Cargo.toml
- core/src/layers/mod.rs
- core/src/layers/prometheus.rs
- core/src/layers/prometheus_client.rs
I'm currently working on switching to prometheus from metrics-rs in databend at https://github.com/datafuselabs/databend/pull/12787 , but unfortunately the PrometheusLayer in opendal uses the `tikv/prometheus-rs` crate, but databend uses `prometheus-client` from the prometheus official.
This PR addes a feature option `use-prometheus-client` to allow switching to `prometheus-client` with the PrometheusLayer. When `use-prometheus-client` is enabled, we can pass a `prometheus_client::registry::Registry` to a `PrometheusLayer`.
To support both of the prometheus client, this PR also make a small refactor to collect the metrics writing logics into a trait `PrometheusLayerMetrics`.
I believe the official prometheus may have longer term of support, maybe we can have a schedule to migrate to it …
> feat: allow using `prometheus-client` crate with PrometheusClientLayer

- .github/workflows/service_test_s3.yml
- fix: https://github.com/apache/incubator-opendal/issues/2690
> chore(ci): add test for aws s3 assume role

- .github/workflows/bindings_java.yml
- bindings/java/pom.xml
> build(bindings/java): support develop with JDK 21

- .github/workflows/service_test_s3.yml
should be fixed: https://github.com/everpcpc/opendal/actions/runs/6245359203/job/16953864225?pr=1
> chore(ci): fix web identity token path for aws s3 assume role test

- .github/workflows/service_test_gcs.yml
- .github/workflows/service_test_s3.yml
Thanks to @databendlabs sponsor and @everpcpc's hard work, OpenDAL can now use bucket maintained by databend labs now.
> ci: Migrate GCS to Databend Labs sponsored bucket

- bindings/java/src/blocking_operator.rs
- bindings/java/src/lib.rs
- bindings/java/src/main/java/org/apache/opendal/BlockingOperator.java
- bindings/java/src/main/java/org/apache/opendal/Capability.java
- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/main/java/org/apache/opendal/OperatorInfo.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/OperatorInfoTest.java
Related: https://github.com/apache/incubator-opendal/pull/3129#discussion_r1332696002
> feat(binding/java): support info ops

- core/src/services/ghac/backend.rs
- core/src/services/ghac/writer.rs
This adjusts the GitHub Action Cache service to handle multi-part uploads correctly: each upload part needs to specify exactly the range it is for, e.g. to upload an 11 byte file with parts <= 8 bytes, the two requests should set:
1. `Content-Range: bytes 0-8/*` (first 8 bytes)
2. `Content-Range: bytes 9-10/*` (final 3 bytes)
Previously, the second request would be `Content-Range: 0-2/*`. This would leave the file not-fully written, and GitHub would reject it with an error when committing (`close()`-ing the writer).
Fixes #3162
> feat: Include starting offset for GHAC upload Content-Range

- bindings/cpp/include/opendal.hpp
- bindings/cpp/tests/basic_test.cpp
Original API seperates the lifetime of `Reader` and `ReaderStream`. Users cannot easily manage them. For example, following code will be wrong previously because of `stack-use-after-scope`.
```cpp
opendal::ReaderStream return_stream(opendal::Operator &op, std::string_view path) {
return op.reader(path);
}
```
With this update, `ReaderStream` will take the ownership of `Reader`. Users can ignore `Reader` when using `ReaderStream`.
> feat(bindings/cpp): make ReaderStream manage the lifetime of Reader

- .github/workflows/service_test_redis.yml
- .github/workflows/service_test_s3.yml
- bindings/java/.mvn/wrapper/maven-wrapper.properties
Resolve the false-positive warnings:
```
[WARNING] 
[WARNING] Plugin validation issues were detected in 5 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-site-plugin:3.12.1
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[WARNING]  * org.apache.maven.plugins:maven-enforcer-plugin:3.1.0
[WARNING]  * org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 
```
> build(bindings/java): upgrade maven wrapper version

- .github/workflows/bindings_java.yml
- bindings/java/.cargo/config
- bindings/java/pom.xml
- bindings/java/tools/build.py
This closes https://github.com/apache/incubator-opendal/issues/3160.
With this patch, it's expected to fix the original issue with:
```
./mvnw verify -Dcargo-build.target=x86_64-unknown-linux-musl
```
@G-XD please give it a try.
> build(bindings/java): support explicit cargo build target

- Cargo.lock
- core/Cargo.toml
- core/src/services/postgresql/backend.rs
Support #3175 
The following step is to cache the statement by using custom managed connection
> feat(service/postgresql): support connection pool

- README.md
This fixes #3179 by noting that https://www.pantsbuild.org uses OpenDAL, as of https://github.com/pantsbuild/pants/pull/19827, with usage going to expand to GHAC (https://github.com/pantsbuild/pants/pull/19831) soon, and potentially blob stores like S3 after that.
> docs: Add pants as a user

- core/src/services/ghac/backend.rs
This adjusts the GitHub Actions Cache service to allow explicitly setting the URL (via `.endpoint(...)`) and the runtime token (via `.runtime_token(...)`), in addition to the defaults of reading the `ACTIONS_CACHE_URL` and `ACTIONS_RUNTIME_TOKEN` environment variables.
This gives more control over the use of this service, such as in the Pants build system (I'm adding support in https://github.com/pantsbuild/pants/pull/19831): for Pants, the caching system runs in a background daemon that is passed some configuration by a client, and it's nice to not have to propagate environment variables into the daemon, instead, it's nicer for the client to read the environment and pass the values as 'normal' configuration.
> feat(services/ghac): Allow explicitly setting ghac endpoint/token, not just env vars

- core/src/services/azdls/backend.rs
- core/src/services/azdls/core.rs
- core/src/services/azdls/writer.rs
close: https://github.com/apache/incubator-opendal/issues/2977
> feat(service/azdls): add append support for azdls

- .github/workflows/service_test_redis.yml
> ci: Pin Kvrocks docker image to 2.5.1 to avoid test failure

- bindings/java/src/blocking_operator.rs
- bindings/java/src/lib.rs
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/test/behavior/AbstractBehaviorTest.java
> fix(binding/java): decode Java’s modified UTF-8 format

- bindings/java/src/main/java/org/apache/opendal/NativeObject.java
Align with `System.loadLibrary` and simplify code.
> chore(bindings/java): simplify library path resolution

- bindings/python/src/asyncio.rs
- bindings/python/src/lib.rs
Not sure why but it doesn't really work currently.
```python
Python 3.11.0 (main, Oct 25 2022, 16:25:24) [Clang 14.0.0 (clang-1400.0.29.102)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.9.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import opendal
In [2]: op = opendal.Operator("s3", bucket="test", region="us-east-1")
In [3]: op.list("/")
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In[3], line 1
----> 1 op.list("/")
Error: Unsupported (permanent) at blocking_list, context: { service: s3, path: / } => operation is not supported
```
> feat(bindings/python): Enable `BlockingLayer` for non-blocking services that don't support blocking

- core/src/raw/adapters/kv/backend.rs
- core/src/raw/adapters/typed_kv/backend.rs
- core/src/raw/oio/write/multipart_upload_write.rs
- core/src/raw/oio/write/range_write.rs
- core/src/services/azblob/backend.rs
- core/src/services/cos/backend.rs
- core/src/services/fs/backend.rs
- core/src/services/gcs/backend.rs
- core/src/services/obs/backend.rs
- core/src/services/oss/backend.rs
- core/src/services/s3/backend.rs
- core/src/services/webdav/backend.rs
- core/src/types/capability.rs
- core/tests/behavior/write.rs
fix https://github.com/apache/incubator-opendal/issues/3014
> feat: Add write_can_empty in Capability and related tests

- bindings/go/build_dynamic.go
- bindings/go/go.mod
- bindings/go/go.sum
- bindings/go/opendal.go
- bindings/go/opendal_test.go
This demo attempts to provide Go bindings by CGO, referring to the writing style of https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/build_dynamic.go.
To run the test, follow these steps:
1. Write an opendal_c.pc file, for example:
```
libdir=/path/to/opendal/target/debug/
includedir=/path/to/opendal/bindings/c/include/
Name: opendal_c
Description: opendal c binding
Version:
Libs: -L${libdir} -lopendal_c
Cflags: -I${includedir}
```
2. Set the PKG_CONFIG_PATH environment variable to include the path of opendal_c.pc, for example:
```
export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/path/to/opendal_c.pc/"
```
3. Run go test:
```
go test -tags dynamic .
```
> feat: Add basic support for bindings/go using CGO

- bindings/c/.gitignore
- bindings/c/examples/.gitignore
- bindings/go/.gitignore
- bindings/go/README.md
- bindings/go/opendal.go
- bindings/go/opendal_test.go
This PR adds the very basic setup for go binding to allow contributors to join in.
> docs: Add basic readme for go binding

- .github/workflows/docs.yml
Use odoc to generate OCaml binding documentation
> ci(bindings/ocaml): add doc

- bindings/java/src/blocking_operator.rs
- bindings/java/src/main/java/org/apache/opendal/BlockingOperator.java
- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/test/behavior/AbstractBehaviorTest.java
> feat(binding/java): add `copy` test

- website/docs/contributing/_category_.yml
- website/docs/getting-started.md
- website/docs/overview.md
- website/docs/services/_category_.yml
- website/docs/vision.md
- website/docusaurus.config.js
- website/src/pages/download.md
This close https://github.com/apache/incubator-opendal/issues/3210.
I realize that the Download page should contain only for our source releases and move how to add dependencies (use binary releases) along with multilingual getting start page.
> docs: add multilingual getting started 

- core/src/services/sqlite/backend.rs
> feat(services/sqlite): Support blocking_get/set/delete in sqlite service

- core/src/docs/rfcs/0000_align_list_api.md
- core/src/docs/rfcs/3232_align_list_api.md
- core/src/docs/rfcs/mod.rs
This PR added a new RFC to align our list API by replacing the `oio::Page` API with poll based `oio::List` API.
> RFC-3232: Align List API

- scripts/README.md
- scripts/verify.py
- website/community/committers/release.md
Fix https://github.com/apache/incubator-opendal/issues/3147
For now, verify.py only includes rust core and java binding. We plan to expand its coverage to include more components in the future.
> docs: Add verify script

- core/src/layers/prometheus_client.rs
in the previous PR I converted the metrics in PrometheusLayer as it into PrometheusClientLayer, but I missed an important metric not included in the PrometheusLayer before is the bytes total metrics.
we already have a histogram about the bytes which is useful for us to find out the distribution of the size on different IO requests. however, a bytes metric in counter is more useful for us to get the IO bandwidth infomation, which is important for us to diagnose the issues on IO.
this PR also fixed a naming issue about counters in PrometheusClientLayer, the prometheus-client tend to append a `_total` suffix in a dump way for every counters, if we name a counter as `opendal_errors_total` what we finally get is `opendal_errors_total_total`, which is bad :(
> feat(prometheus): add bytes metrics as counter

- core/src/services/persy/backend.rs
> feat(services/persy): change blocking_x in async_x call to tokio::task::blocking_spawn

- .github/workflows/service_test_redis.yml
- .github/workflows/service_test_s3.yml
- bindings/java/README.md
- bindings/java/src/test/java/org/apache/opendal/test/behavior/ServiceBehaviorTests.java
> test(binding/java): grouping tests with tag

- core/src/services/redb/backend.rs
feat(services/redb): change blocking_x in async_x call to tokio::task::blocking_spawn
> feat(services/redb): change blocking_x in async_x call to tokio::task::blocking_spawn

- Cargo.lock
- bindings/c/Cargo.toml
- bindings/c/src/lib.rs
Add a blocking layer to C just like the way of Python binding
> Add blocking layer for C bindings

- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/result.rs
- bindings/c/src/types.rs
- bindings/c/tests/bdd.cpp
issue: https://github.com/apache/incubator-opendal/issues/3257
> feat(binding/c): Add blocking_reader for C binding

- core/src/services/rocksdb/backend.rs
feat(services/rocksdb): change blocking_x in async_x call to tokio::task::blocking_spawn
> feat(services/rocksdb): change blocking_x in async_x call to tokio::task::blocking_spawn

- bindings/java/src/error.rs
I'm not sure if it's better to expose a method said `display(force_backtrace: bool)` in `opendal::Error`.
Without backtrace, it's very hard to debug across binding (language) boundary.
Before -
```
org.apache.camel.FailedToCreateRouteException: Failed to create route route1: Route(route1)[From[opendal://foo] -> [To[opendal://bar], To[... because of Failed to resolve endpoint: opendal://foo due to: Unexpected (permanent) at  => Null pointer in get_object_class, source: Null pointer in get_object_class
at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:82)
at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
```
After with `RUST_BACKTRACE=1` -
```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.479 …
```
> feat(bindings/java): convey backtrace on exception

- bindings/java/src/error.rs
- bindings/java/src/lib.rs
Per https://github.com/apache/incubator-opendal/pull/3286#discussion_r1359896784.
cc @Xuanwo @G-XD
> refactor(bindings/java): explict error handling

- bindings/java/src/main/java/org/apache/opendal/Capability.java
- bindings/java/src/main/java/org/apache/opendal/OperatorInfo.java
Per https://github.com/apache/incubator-opendal/pull/3277#discussion_r1359079181
Align the POJO style -
1. Generate getters for `public final` field to satisfy where only methods are accepted.
2. Always overwrite the RequiredArgsConstructor for ensure the parameter order.
cc @Xuanwo @G-XD
> chore(bindings/java): align mapping POJO pattern

- core/src/services/sqlite/docs.md
- website/docs/services/mysql.mdx
- website/docs/services/postgresql.mdx
- website/docs/services/sqlite.mdx
> docs: Add docs in website for sqlite/mysql/postgresql services

- .github/workflows/test_planner.yml
- scripts/workflow_planner.py
Fix https://github.com/apache/incubator-opendal/issues/3326
> ci: Fix plan not generated correctly for PR from forked repo

- .github/workflows/bindings_python.yml
- Cargo.lock
- core/Cargo.toml
Test run: https://github.com/apache/incubator-opendal/actions/runs/6549415727?pr=3325
Closes #3311 cc @Zheaoli
> feat(bindings/python): build and publish aarch64 and armv7l wheels

- bindings/java/src/blocking_operator.rs
- bindings/java/src/main/java/org/apache/opendal/BlockingOperator.java
- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/test/OperatorDuplicateTest.java
Clone a new operator that is identical to this one. The new operator has its own lifecycle.
Since an operator will release all its resource and "flush" on lifecycle end, this method is suitable to create a narrowed "scope" while avoiding creating a brand-new operator for each scope.
> feat(bindings/java): support duplicate operator

- bindings/java/src/lib.rs
- bindings/java/src/main/java/org/apache/opendal/NativeLibrary.java
- bindings/java/src/main/java/org/apache/opendal/NativeObject.java
- bindings/java/src/main/java/org/apache/opendal/OpenDAL.java
- bindings/java/src/test/java/org/apache/opendal/test/UtilityTest.java
- bindings/java/src/utility.rs
* This refers to #3331.
* This refers to #3329.
> feat(bindings/java): support get enabled services

- .gitattributes
Archive this by modifying `.gitattributes` file.
Close #3287
> chore: do not export unreleased bindings

- bindings/README.md
- bindings/c/README.md
- bindings/cpp/README.md
- bindings/dotnet/README.md
- bindings/go/README.md
- bindings/haskell/README.md
- bindings/java/README.md
- bindings/lua/README.md
- bindings/nodejs/README.md
- bindings/ocaml/README.md
- bindings/php/README.md
- bindings/python/README.md
- bindings/ruby/README.md
- bindings/swift/README.md
- bindings/zig/README.md
This PR contains the following:
- Add a readme for bindings.
- Give every binding a release status badge.
- For released bindings, give them the badge of version & package info and documentation site link.
> docs(bindings): bindings README and binding release status

- core/src/services/s3/backend.rs
- integrations/object_store/src/lib.rs
This PR contains two small updates, hope can help a little bit:
- add actual bytes comparing at object_store
- add Cloudflare R2 endpoint, [ref](https://developers.cloudflare.com/r2/api/s3/api/#:~:text=https%3A//%3CACCOUNT_ID%3E.r2.cloudflarestorage.com)
> chore: update object_store unit tests and s3 endpoint docs

- bindings/c/src/types.rs
After actual testing, it was found that using `self.inner.read` will read data based on the size of internal bytes. By using `self.inner.read_exact`, can read the input buffer size directly.
> Fix read result not full

- core/src/layers/prometheus.rs
For now, we already have basic metric output in the Prometheus layer.
1. requests_total
2. requests_duration_seconds
3. bytes_total
All the metrics are grouped by scheme and operation for now.
For now, in some circumstances, we need to group by the metric by an extra path. Here's an example: if we choose to write to different devices in Linux using OpenDAL, and one of the devices has some problem, the write and read action becomes slow and slow. We can't monitor and alert for the specific device if we don't have a path label.
But on the other hand, if we output all the paths as a label in metric, the final metric we get will be extremely massive. So I chose to introduce a new config option for the people to choose how many path levels they want to export
> feat(layer/prometheus): Support output path as a metric label

- core/src/layers/prometheus_client.rs
we met an issue in https://github.com/datafuselabs/databend/pull/13373 , as sometimes we'd call `build_operator()` on some queries, this causes duplicated metrics get registered into the registry, which finally produced millions of metrics.
the solution is to make the PrometheusClientLayer a singleton, but currently the PrometheusClientLayer have to be moved. we need allow it passing a reference before making the singleton in the `layer()` call.
> feat: Make PrometheusClientLayer Clonable

- .github/workflows/docs.yml
- core/src/docs/rfcs/0000_lazy_reader.md
- core/src/docs/rfcs/3356_lazy_reader.md
- core/src/docs/rfcs/mod.rs
Close https://github.com/apache/incubator-opendal/issues/2929
> RFC-3356: Lazy Reader

- core/Cargo.toml
- core/src/services/cloudflare_kv/backend.rs
- core/src/services/cloudflare_kv/docs.md
- core/src/services/cloudflare_kv/error.rs
- core/src/services/cloudflare_kv/mod.rs
- core/src/services/mod.rs
- core/src/types/scheme.rs
close #3217
Implement cloudflare kv support via our KV adaptor.
> feat(service/cloudflare_kv): support cloudflare KV

- core/src/layers/complete.rs
- core/src/types/list.rs
- core/src/types/metadata.rs
Related: https://github.com/apache/incubator-opendal/pull/3333#discussion_r1369493076
> feat(core): exposing `Metadata::metakey()` api

- core/src/services/cos/core.rs
> fix(services/cos): fix prefix param

- core/Cargo.toml
- core/src/services/d1/backend.rs
- core/src/types/capability.rs
- core/src/types/operator/builder.rs
- core/tests/behavior/append.rs
- core/tests/behavior/blocking_append.rs
- core/tests/behavior/blocking_copy.rs
- core/tests/behavior/blocking_list.rs
- core/tests/behavior/blocking_rename.rs
- core/tests/behavior/blocking_write.rs
- core/tests/behavior/copy.rs
- core/tests/behavior/list.rs
- core/tests/behavior/presign.rs
- core/tests/behavior/rename.rs
- core/tests/behavior/utils.rs
- core/tests/behavior/write.rs
For #3216 , D1 limited the [Maximum string, BLOB or table row size](https://developers.cloudflare.com/d1/platform/limits/#:~:text=1%2C000%2C000%20bytes%20(1%20MB)) to 1M, but [gen_bytes()](https://github.com/realtaobo/incubator-opendal/blob/efc9879a29ef3d0d804dbde02740491b9e4706e4/core/tests/behavior/utils.rs#L109) randomly generates `1~4M` content. It will result in the following error:
```
D1Response { result: [], success: false, errors: [D1Error { message: "string or blob too big", code: 7500 }], messages: [] }
```
Maybe we can support configuring max_size via environment variable?
> feat: Add write_total_max_size in Capability

- core/Cargo.toml
- core/src/raw/http_util/client.rs
- core/src/services/dbfs/backend.rs
- core/src/services/dbfs/core.rs
- core/src/services/dbfs/docs.md
- core/src/services/dbfs/error.rs
- core/src/services/dbfs/mod.rs
- core/src/services/dbfs/pager.rs
- core/src/services/dbfs/reader.rs
- core/src/services/dbfs/writer.rs
- core/src/services/mod.rs
- core/src/types/scheme.rs
- resolve: #2550
(Sorry for the late PR, I've been so busy recently.)
- Read operation is a bit tricky, as discussed [here](https://github.com/apache/incubator-opendal/issues/2550#issuecomment-1676688432). As for now, it can read whole object and read for specific range, but  `reqwest::Body::bytes_stream()` in `poll_next()` will not return whole response at once if the file is too big, which causes serde json failed. Will need to discuss for possible implementation.
- Append write need to add new oio write trait, as we discuss [here](https://github.com/apache/incubator-opendal/issues/2550#issuecomment-1754341937).
- Add new GitHub Action e2e test workflow, but we need to setup Databricks cluster for this purpose.
- Add necessary unit tests based on PR review.
> feat(core): service add DBFS API 2.0 support

- core/src/services/mysql/docs.md
docs: update mysql `connection_string` config description in doc #3387 
Fix #3387
> docs: Update mysql `connection_string` config description in doc

- fixtures/webdav/config/nginx/http.conf
- fixtures/webdav/docker-compose-webdav-with-auth.yml
- fixtures/webdav/docker-compose-webdav-with-empty-passwd.yml
- fixtures/webdav/docker-compose-webdav.yml
> ci(test): Add health check for WebDAV docker compose config

- .editorconfig
- .github/actions/behavior_test_binding_nodejs/action.yaml
- .github/services/azdls/azdls/action.yml
- .github/workflows/bindings_nodejs.yml
- bindings/nodejs/.env.example
- bindings/nodejs/package.json
- bindings/nodejs/tests/service.test.mjs
- bindings/nodejs/tests/suites/async.suite.mjs
- bindings/nodejs/tests/suites/index.mjs
- bindings/nodejs/tests/suites/sync.suite.mjs
- bindings/nodejs/tests/utils.mjs
- fixtures/sftp/docker-compose-sftp-with-default-root.yml
- fixtures/sftp/docker-compose-sftp.yml
> fix: nodejs test adapt `OPENDAL_DISABLE_RANDOM_ROOT`

- core/src/services/onedrive/backend.rs
- core/src/services/s3/backend.rs
- core/src/services/webhdfs/backend.rs
- core/src/services/webhdfs/writer.rs
1. Hide token info in OneDrive
2. Format import sequence and path
3. Drop async as there's no await inside
> feat(core): fix token leak in OneDrive

- core/src/services/s3/pager.rs
This allows the S3 logic to accept response for path listings that don't contain the optional `<ETag>` xml element.
The bug was originally observed when connecting to an S3 compatible server: `s3s-fs` (https://crates.io/crates/s3s-fs).
I believe s3s-fs's behaviour is correct, given that the AWS S3 request/response docs state that the `Etag` field is optional: https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html.
Closes https://github.com/apache/incubator-opendal/issues/3477.
> fix(services/s3): Accept List responses without ETag

- README.md
I think it's a better choice to capitalize absf, and it can also correspond to HDFS capitalization below.
I think it is also possible to remove As known as
> docs(readme): Fix capitalization about the ABFS service in README.md

- core/src/raw/serde_util.rs
- core/src/services/mod.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/mod.rs
Part of https://github.com/apache/incubator-opendal/issues/3240
> feat(services): Implement ConfigDeserializer and add S3Config as example

- core/src/services/mod.rs
- core/src/services/sqlite/backend.rs
- core/src/services/sqlite/mod.rs
> feat(services): add SqliteConfig

- bindings/c/Makefile
- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/metadata.rs
- bindings/c/src/operator_info.rs
- bindings/c/tests/opinfo.cpp
After implementing capability, the test framework for C is easier to implement. #3472 
Two concerns along with this:
- I think we need more documentions on the difference between full capabilities and native capabilities, the difference between them is not obvious to users. i.e. If they want to check the capabilities, should they use full/native?
- Further work: we should replace all currently `opendal_byte` backed string like error message to leaked CString, which is more conventional for C. (This is my mistake at the very beginning 😢). I think this break the current API, so my plan would be changing this after our first release.
> feat(bindings/C): implement capability

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/cpp/CMakeLists.txt
- bindings/haskell/opendal.cabal
- bindings/java/pom.xml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- bindings/python/upgrade.md
- core/src/docs/upgrade.md
- website/community/committers/release.md
part of #3503
---
* feat(binding/java): add `rename` support by @G-XD in https://github.com/apache/incubator-opendal/pull/3238
* feat(prometheus): add bytes metrics as counter by @flaneur2020 in https://github.com/apache/incubator-opendal/pull/3246
* feat(binding/python): new behavior testing for python by @laipz8200 in https://github.com/apache/incubator-opendal/pull/3245
* feat(binding/python): Support AsyncOperator tests. by @laipz8200 in https://github.com/apache/incubator-opendal/pull/3254
* feat(service/libsql): support libsql by @G-XD in https://github.com/apache/incubator-opendal/pull/3233
* feat(binding/python): allow setting append/buffer/more in write() call by @jokester in https://github.com/apache/incubator-opendal/pull/3256
* feat(services/persy): change blocking_x in …
> chore: Bump to v0.42.0 to start release process

- core/src/services/mod.rs
- core/src/services/tikv/backend.rs
- core/src/services/tikv/mod.rs
Part of https://github.com/apache/incubator-opendal/issues/3240
> refactor(service/tikv): Add TikvConfig to implement ConfigDeserializer

- bindings/java/tools/build.py
Allow building the Java bindings on Linux ARM64.
Additionally allows the script to run with older Python versions that require strings in `subprocess` calls.
> build(bindings/java): Allow building on `linux-aarch_64`

- bindings/java/tools/build.py
https://github.com/apache/incubator-opendal/pull/3527 infers me that we can improve this script so that users on other arch can simply use `-Dcargo-build.target=aarch64-unknown-linux-gnu` instead of having to modify the script.
Ref - https://github.com/trustin/os-maven-plugin/blob/43ed4d4bdc647ec369d152bfd18698f0997aa65b/README.md?plain=1#L9-L23
I don't have environment to test other OSes, so leave them blank for anyone encounters it to fix.
cc @Xuanwo @amunra
> chore(bindings/java): improve build.py script

- .github/services/gridfs/gridfs/action.yml
- .github/services/gridfs/gridfs_with_basic_auth/action.yml
- .github/services/gridfs/gridfs_with_no_auth/action.yml
- bindings/java/Cargo.toml
- bindings/nodejs/Cargo.toml
- bindings/python/Cargo.toml
close #3502. It seems we can use MongoDB docker-compose files directly, how do you think?
> ci: support behavior test for gridfs

- bindings/python/CONTRIBUTING.md
- bindings/python/README.md
> fix(bindings/python): Fix the test command in doc

- .github/workflows/bindings_nodejs.yml
- bindings/nodejs/.cargo/config.toml
- bindings/nodejs/npm/linux-arm64-gnu/README.md
- bindings/nodejs/npm/linux-arm64-gnu/package.json
- bindings/nodejs/npm/linux-arm64-musl/README.md
- bindings/nodejs/npm/linux-arm64-musl/package.json
- bindings/nodejs/npm/win32-arm64-msvc/README.md
- bindings/nodejs/npm/win32-arm64-msvc/package.json
- bindings/nodejs/package.json
This PR adds support for aarch64 build on Linux and win32 systems.
- aarch64-unknown-linux-gnu
- aarch64-unknown-linux-musl
- aarch64-pc-windows-msvc
All the job steps have been tested except publish.
> ci(bindings/nodejs): add aarch64 build support

- bindings/nodejs/index.js
> chore: removed dotenv in bindings/nodejs/index.js

- core/src/services/alluxio/backend.rs
- core/src/services/alluxio/core.rs
- core/src/services/alluxio/writer.rs
> feat(service): alluxio support write

- bindings/cpp/.clang-format
- bindings/cpp/include/opendal.hpp
- bindings/cpp/src/opendal.cpp
- bindings/cpp/tests/basic_test.cpp
Add cpp binding Google style clang-format && format the code
> chore: Add cpp binding Google style clang-format && format the code

- .github/services/redis/redis_with_cluster_tls/action.yml
- .github/workflows/behavior_test_binding_nodejs.yml
- .github/workflows/docs.yml
- bindings/nodejs/src/lib.rs
close #3607 
Advanced the `corepack enable` step. 
I'm not sure if it's fully resolved. I have checked to see if anyone else has raised this issue, but found nothing.
> fix(ci): try enable corepack before setup-node action

- .github/workflows/service_test_hdfs.yml
- core/src/services/hdfs/backend.rs
- core/src/services/hdfs/docs.md
- core/tests/behavior/append.rs
- fixtures/hdfs/hdfs-site.xml
support append in block_write 
close https://github.com/apache/incubator-opendal/issues/2500
> fix(service/hdfs): enable hdfs append support

- .github/workflows/bindings_nodejs.yml
- .github/workflows/docs.yml
- .github/workflows/service_test_hdfs.yml
close #3607 
Apply advancing `corepack enable` step to all node.js jobs
> fix(ci): fix setup node

- Cargo.lock
- core/benches/vs_s3/Cargo.toml
- core/benches/vs_s3/README.md
- core/benches/vs_s3/src/main.rs
- core/src/layers/complete.rs
- core/src/raw/http_util/body.rs
- core/src/types/reader.rs
The case that `Reader` been used as tokio::AsyncRead will be improved up to 10%.
> feat: Improve the performance of s3 services

- Cargo.lock
- core/Cargo.toml
Remove `native-tls` dependency from the `services-mysql` feature.
This helps towards https://github.com/apache/incubator-opendal/issues/3612
> chore(core): Have mysql_async use rustls instead of native-tls

- fixtures/etcd/docker-compose-standalone-tls.yml
Workaround for https://github.com/bitnami/containers/issues/53068
> ci: Fix etcd with tls and auth failed to start

- .github/workflows/bindings_python.yml
`pypa/gh-action-pypi-publish` dose not have a dryrun option, so we just list package files.
- Part of: #3603
cc @suyanhanx
> ci: dry run publish on rc tags for python binding

- .github/workflows/behavior_test_binding_nodejs.yml
- .github/workflows/bindings_nodejs.yml
- .github/workflows/docs.yml
- bindings/nodejs/Cargo.toml
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-arm64-gnu/package.json
- bindings/nodejs/npm/linux-arm64-musl/package.json
- bindings/nodejs/npm/win32-arm64-msvc/package.json
- bindings/nodejs/upgrade.md
This pr adds a publish dry run for the nodejs binding.
> chore(ci): nodejs binding publish dry run

- bindings/java/Cargo.toml
- bindings/java/upgrade.md
- bindings/nodejs/upgrade.md
- bindings/python/Cargo.toml
- bindings/python/upgrade.md
- core/src/services/azfile/core.rs
> feat: disable `ftp` for python and java binding

- bindings/python/README.md
💦
It's better to use s3 as an example in the documentation than fs.
> chore: clearer doc for python binding

- .github/workflows/release_java.yml
- bindings/java/Cargo.toml
- bindings/java/pom.xml
- bindings/java/tools/build.py
Fix https://github.com/apache/incubator-opendal/issues/3663
> ci(java/binding): Use zigbuild for glibc 2.17 support

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bindings/cpp/CMakeLists.txt
- bindings/haskell/opendal.cabal
- bindings/java/pom.xml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-arm64-gnu/package.json
- bindings/nodejs/npm/linux-arm64-musl/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-arm64-msvc/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- bindings/python/upgrade.md
- core/src/docs/upgrade.md
- website/community/committers/release.md
part of #3668
* feat(bindings/C): Add opendal_operator_rename and opendal_operator_copy by @jiaoew1991 in https://github.com/apache/incubator-opendal/pull/3517
* feat(binding/python): Add new API to convert between AsyncOperator and Operator by @Zheaoli in https://github.com/apache/incubator-opendal/pull/3514
* feat: Implement RFC-3526: List Recursive by @Xuanwo in https://github.com/apache/incubator-opendal/pull/3556
* feat(service): add alluxio rest api support by @hoslo in https://github.com/apache/incubator-opendal/pull/3564
* feat(bindings/python): add OPENDAL_DISABLE_RANDOM_ROOT support by @Justin-Xiang in https://github.com/apache/incubator-opendal/pull/3550
* feat(core): add Alluxio e2e test by @hoslo in https://github.com/apache/incubator-opendal/pull/3573
* feat(service): …
> chore: Bump to v0.43.0 to start release process

- core/edge/file_write_on_full_disk/Cargo.toml
- core/fuzz/Cargo.toml
> chore: add license.workspace to help cargo deny reports

- bin/oli/src/commands/cp.rs
FIx https://github.com/apache/incubator-opendal/issues/3686
> fix(oli): Fix cp -r command returns invalid path error

- Cargo.lock
- core/benches/vs_s3/Cargo.toml
It's my first pr , I want to update aws-sdk-s3 from 0.38.0 to 1.4.0, but I don't know it's right or not.  #3701
> chore: bump aws-sdk-s3 from 0.38.0 to 1.4.0

- website/community/committers/release.md
Update `OpenDAL Community Vote` step of release.
> docs(website): only VOTEs from PPMC members are binding
