bindings/nodejs/index.d.ts
bindings/nodejs/src/lib.rs

Fix some example code errors for Node.js binding docs

docs(nodejs): fix some example code errors

---

core/src/types/capability.rs
core/src/types/operator/metadata.rs
core/tests/behavior/append.rs
core/tests/behavior/main.rs
core/tests/behavior/write.rs

test(core): test for append

---

core/src/layers/complete.rs
core/src/services/oss/backend.rs

fix the appender complete check when drop.

fix(core): appender complete check

---

core/src/services/azblob/appender.rs
core/src/services/azblob/backend.rs
core/src/services/azblob/core.rs
core/src/services/azblob/docs.md
core/src/services/azblob/mod.rs
core/tests/behavior/append.rs

Add append support for azblob.

feat(services/azblob): add append support

---

bindings/java/pom.xml

WORKING IN PROGRESS
Push it here for sharing publicly and you can try it out.
Ref - https://issues.apache.org/jira/browse/INFRA-24630 for cannot deploy snapshot issue.

build(bindings/java): prepare for snapshot release

---

core/src/services/cos/appender.rs
core/src/services/cos/backend.rs
core/src/services/cos/core.rs
core/src/services/cos/mod.rs
core/src/services/oss/core.rs

feat(services/cos): append support

---

bindings/java/README.md

All TODOs are implemented. After we release the first formal version, we can reduce the SNAPSHOT related docs further.

docs(bindings/java): update the README file

---

bindings/java/src/lib.rs
bindings/java/src/operator.rs

This refers to https://github.com/apache/incubator-opendal/issues/2339.
Code tidy a bit - I suppose it's the last commit before I work for a formal 0.1.0 release.

refactor(bindings/java): narrow unsafe boundary

---

.github/workflows/bindings_python.yml
bindings/python/pyproject.toml

chore(bindings/python): upgrade maturin to 1.0

---

website/docusaurus.config.js

docs: add link for c binding

---

core/src/services/memory/backend.rs
core/src/services/memory/docs.md
core/src/services/redis/backend.rs
core/src/services/redis/docs.md
core/src/services/rocksdb/backend.rs
core/src/services/rocksdb/docs.md
core/src/services/sled/backend.rs
core/src/services/sled/docs.md
website/docs/services/memory.mdx
website/docs/services/redis.mdx
website/docs/services/rocksdb.mdx
website/docs/services/sled.mdx

Includes:
- memory
- redis
- rocksdb
- sled

docs: docs for kv services

---

website/docs/overview.md
website/docs/services/oss.mdx

1. fix missing import
2. fix syntax error in oss example

docs improvement of Python binding

---

core/src/types/operator/operator_futures.rs

Fix https://github.com/apache/incubator-opendal/issues/2412

fix(core): Don't wake up operator futures while not ready

---

core/src/services/obs/appender.rs
core/src/services/obs/backend.rs
core/src/services/obs/core.rs
core/src/services/obs/mod.rs

feat(services/obs): add append support

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bindings/java/pom.xml
bindings/nodejs/npm/darwin-arm64/package.json
bindings/nodejs/npm/darwin-x64/package.json
bindings/nodejs/npm/linux-x64-gnu/package.json
bindings/nodejs/npm/win32-x64-msvc/package.json
bindings/nodejs/package.json
core/src/docs/upgrade.md

* feat(services/webdav): support redirection when get 302/307 response during read operation by @Yansongsongsong in https://github.com/apache/incubator-opendal/pull/2256
* feat: Add Zig Bindings Module by @kassane in https://github.com/apache/incubator-opendal/pull/2374
* feat: Implement Timeout Layer by @Xuanwo in https://github.com/apache/incubator-opendal/pull/2395
* feat(bindings/c): add  opendal_operator_blocking_delete method by @jiaoew1991 in https://github.com/apache/incubator-opendal/pull/2416
* feat(services/obs): add append support by @infdahai in https://github.com/apache/incubator-opendal/pull/2422
* refactor(bindings/zig): enable tests and more by @tisonkun in https://github.com/apache/incubator-opendal/pull/2375
* refactor(bindings/zig): add errors handler and module test …

Bump to version 0.37.0

---

core/src/raw/http_util/client.rs
core/src/services/s3/backend.rs
core/src/services/s3/error.rs
core/src/services/wasabi/backend.rs
core/src/services/wasabi/error.rs

Fix https://github.com/apache/incubator-opendal/issues/2452

feat(services/s3): Allow retry for unexpected 499 error

---

bindings/nodejs/index.d.ts

chore(bindings/nodejs): update index.d.ts

---

core/src/services/sled/docs.md

Fix https://github.com/apache/incubator-opendal/issues/2497

docs: Fix scan not checked for sled services

---

core/src/raw/adapters/kv/backend.rs
core/src/raw/adapters/typed_kv/backend.rs
core/src/services/dashmap/docs.md
core/src/services/memory/docs.md
core/src/services/redis/docs.md
core/src/services/rocksdb/docs.md
core/src/services/sled/docs.md

as same as https://github.com/apache/incubator-opendal/pull/2513

feat(adapters-kv): add rename and copy support to non typed kv adapters

---

.github/workflows/bindings_java.yml

We are addressing the CI issues at https://github.com/apache/incubator-opendal/pull/2525. Disable the stage snapshot CI will give us more time without blocking existing develop.

ci: Disable the stage snapshot CI

---

CONTRIBUTING.md

docs: Fix link for CONTRIBUTING.md 

---

.github/workflows/bindings_swift.yml
bindings/swift/Makefile

ci(bindings/swift): optimize time consumption of CI pipeline

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bindings/java/pom.xml
bindings/nodejs/npm/darwin-arm64/package.json
bindings/nodejs/npm/darwin-x64/package.json
bindings/nodejs/npm/linux-x64-gnu/package.json
bindings/nodejs/npm/win32-x64-msvc/package.json
bindings/nodejs/package.json
core/src/docs/upgrade.md

* feat(raw/http_util): Implement mixed multipart parser by @Xuanwo in https://github.com/apache/incubator-opendal/pull/2430
* feat(services/gcs): Add batch delete support by @wcy-fdu in https://github.com/apache/incubator-opendal/pull/2142
* feat(core): Add Write::sink API by @Xuanwo in https://github.com/apache/incubator-opendal/pull/2440
* feat(services/s3): Allow retry for unexpected 499 error by @Xuanwo in https://github.com/apache/incubator-opendal/pull/2453
* feat(layer): add throttle layer by @morristai in https://github.com/apache/incubator-opendal/pull/2444
* feat(bindings/haskell): init haskell binding by @silver-ymz in https://github.com/apache/incubator-opendal/pull/2463
* feat(core): add capability check by @unixzii in https://github.com/apache/incubator-opendal/pull/2461
* …

Bump to version 0.38.0

---

.github/workflows/bindings_java.yml
bindings/java/pom.xml
scripts/merge_local_staging.sh

@Xuanwo if you agree with it, I'm going to push a test tags to trigger the workflow for testing. You can check if such actions corrupt other bindings.

ci: automatic java binding release

---

core/src/services/azblob/backend.rs
core/src/services/azblob/core.rs
core/src/services/azblob/writer.rs

Add support of sink for azblob

feat(services/azblob): support sink

---

core/src/services/gcs/backend.rs
core/src/services/gcs/core.rs
core/src/services/gcs/writer.rs

feat(services/gcs): support sink

---

core/src/services/cos/backend.rs
core/src/services/cos/core.rs
core/src/services/cos/writer.rs

feat(services/cos): impl sink

---

.github/workflows/service_test_redis.yml

feat(CI): set Kvrocks test for service redis

---

core/src/services/cos/backend.rs

fix(services/cos): fix cos service comments

---

.github/workflows/service_test_webdav.yml
core/src/services/webdav/backend.rs
core/src/services/webdav/error.rs

Fix https://github.com/apache/incubator-opendal/issues/2660

ci: Fix unexpected error in owncloud

---

.github/workflows/ci.yml
bindings/python/python/opendal/layers.pyi

ci: upgrade hawkeye action

---

bindings/haskell/src/types.rs
core/fuzz/fuzz_reader.rs
core/fuzz/utils.rs
core/src/layers/mod.rs
core/src/layers/retry.rs
core/src/raw/layer.rs
core/src/services/s3/backend.rs
core/src/types/operator/blocking_operator.rs
core/src/types/writer.rs
core/tests/behavior/main.rs

Fix https://github.com/apache/incubator-opendal/issues/2529
cc @wcy-fdu

feat: Add RetryInterceptor support for RetryLayer

---

bin/oay/Cargo.toml
bin/oay/src/bin/oay.rs
bin/oay/src/bin/webdav.rs
bin/oay/src/config.rs
bin/oay/src/services/mod.rs
bin/oay/src/services/webdav/mod.rs
bin/oay/src/services/webdav/service.rs
bin/oay/src/services/webdav/webdav_dir_entry.rs
bin/oay/src/services/webdav/webdav_file.rs
bin/oay/src/services/webdav/webdav_metadata.rs
bin/oay/src/services/webdav/webdavfs.rs

This PR add oay_webdav basic `read` impl, just show the basic impl idea.

feat(oay): Add webdav basic read impl

---

.github/workflows/ci.yml
Cargo.lock

This PR fixed the cargo.lock not updated and also add a check to prevent again.

ci: Fix Cargo.lock not updated

---

core/src/services/obs/backend.rs
core/src/services/obs/core.rs
core/src/services/obs/writer.rs

Add multipart upload api support for service obs
close issue #2652

feat(service/obs):add multipart upload function support

---

core/src/services/obs/backend.rs

fix(services/obs): remove content-length check in backend

---

Cargo.lock
bindings/python/Cargo.toml

Changelog: https://pyo3.rs/v0.19.1/changelog

chore(bindings/python): upgrade pyo3 to 0.19

---

core/tests/behavior/fuzz.rs
core/tests/behavior/main.rs

This PR adds a new behavior test that repro fuzz issue #2717.

feat(tests): Extract fuzz test of #2717

---

bin/oli/README.md

docs: create README.md for oli

---

core/src/services/etcd/backend.rs

https://github.com/apache/incubator-opendal/pull/2719#discussion_r1274959676

feat(service/etcd): support list

---

Cargo.lock
core/Cargo.toml
core/src/services/obs/backend.rs

- ref: https://github.com/Xuanwo/reqsign/pull/361
- fix: https://github.com/apache/incubator-opendal/issues/2754

feat(obs): support loading credential from env

---

.github/workflows/bindings_zig.yml

fix(ci): pin zig version to 0.11.0

---

core/src/services/postgresql/docs.md

This PR proposed to add an example of the usage for PostgreSQL service which is recently added.
Fix https://github.com/apache/incubator-opendal/issues/2846

docs: Add an example for PostgreSQL service

---

bin/oay/src/services/webdav/webdav_metadata.rs

feat(oay): impl some method for `WebdavMetaData`

---

.github/workflows/service_test_postgresql.yml
core/src/services/postgresql/fixtures/docker-compose.yml
core/src/services/postgresql/fixtures/init.sql

ci(services/postgresql): add docker-compose to simplify the CI

---

bin/oay/src/services/webdav/webdav_dir_entry.rs
bin/oay/src/services/webdav/webdav_file.rs
bin/oay/src/services/webdav/webdavfs.rs

fix(oay): add some error handle

---

core/src/docs/rfcs/2884_merge_range_read_into_read.md

RFC-2884: Merge Range Read Into Read

---

.github/workflows/service_test_s3.yml
core/src/services/s3/fixtures/docker-compose-minio.yml

part of https://github.com/apache/incubator-opendal/issues/2860

ci(service/s3): Add docker-compose-minio file to simplify the CI

---

.github/workflows/service_test_s3.yml

close https://github.com/apache/incubator-opendal/issues/2897

chore: add health check for docker-compose minio

---

bindings/java/README.md
bindings/java/pom.xml
bindings/java/src/main/java/org/apache/opendal/Environment.java
bindings/java/src/main/java/org/apache/opendal/NativeObject.java
bindings/java/src/main/resources/bindings.properties

This closes https://github.com/apache/incubator-opendal/issues/2731.

build(bindings/java): bundle bare binaries in JARs with classifier

---

core/tests/behavior/README.md

doc(tests): fix test command

---

.github/workflows/bindings_java.yml
bindings/java/Cargo.toml
bindings/java/src/lib.rs

This closes https://github.com/apache/incubator-opendal/issues/2732.

feat(bindings/java): bundled services

---

core/src/types/operator/blocking_operator.rs
core/src/types/operator/operator.rs

implement https://github.com/apache/incubator-opendal/issues/2940

fix(doc): use crate::docs::rfc to replace relative path in doc

---

core/src/services/s3/compatible_services.md
core/src/services/s3/docs.md

as mentioned in https://github.com/apache/incubator-opendal/issues/2891

fix(doc): add GCS api reference and known issues to service/s3 doc

---

.github/actions/setup/action.yaml
.github/workflows/service_test_rocksdb.yml

implement https://github.com/apache/incubator-opendal/issues/2970

ci(fix): Add PORTABLE to make sure rocksdb compiled with the same CPU feature set

---

.devcontainer/post_create.sh
bindings/cpp/.gitignore
bindings/cpp/CMakeLists.txt
bindings/cpp/CONTRIBUTING.md
bindings/cpp/include/opendal.hpp
bindings/cpp/src/opendal.cpp

Update:
- add CONTRIBUTING.md 
- add address sanitizer to check memory error
- fix memory overflow in `Operator::read`

docs(bindings/cpp): add CONTRIBUTING.md 

---

website/docs/contributing/podling-report.md

Hi, everyone! I have written a simple guide on Podling Status Report.
Fixes: #2911

docs(contributing): add podling status report guide

---

core/src/raw/http_util/mod.rs
core/src/raw/http_util/uri.rs
core/src/services/webdav/pager.rs

fix(services/webdav): decode path before set Entry

---

core/src/services/gdrive/builder.rs
core/src/services/gdrive/docs.md
core/src/services/onedrive/builder.rs
core/src/services/onedrive/docs.md
website/docs/services/gdrive.mdx
website/docs/services/onedrive.mdx

Related: https://github.com/apache/incubator-opendal/issues/2304
Includes:
- gdrive
- onedrive

docs: add service doc for gdrive & onedrive

---

.github/workflows/service_test_azblob.yml
.github/workflows/service_test_cos.yml
.github/workflows/service_test_dropbox.yml
.github/workflows/service_test_gdrive.yml
.github/workflows/service_test_s3.yml
.github/workflows/service_test_supabase.yml
.github/workflows/service_test_wasabi.yml

fix: https://github.com/apache/incubator-opendal/issues/2598

ci: restrict workflow that need password

---

core/src/services/oss/pager.rs

fix(services/oss): set content_md5 in lister

---

core/src/layers/complete.rs
core/src/services/cos/backend.rs
core/src/services/gcs/backend.rs
core/src/services/gcs/core.rs
core/src/services/obs/backend.rs
core/src/services/oss/backend.rs
core/src/services/s3/backend.rs
core/src/types/capability.rs
core/src/types/operator/operator_futures.rs

This PR will add buffer for all services.

feat: Add buffer support for all services

---

bindings/java/src/test/java/org/apache/opendal/RedisServiceTest.java

test(bindings/java): fix mapped port

---

.github/workflows/bindings_php.yml

Related to https://github.com/apache/incubator-opendal/issues/3055

ci: Disable PHP build until we fix it 

---

core/src/services/obs/backend.rs
core/src/services/obs/core.rs
core/src/services/obs/writer.rs

Complete the refactoring code for the obs part of this issue: https://github.com/apache/incubator-opendal/issues/3064 .

feat(services/obs): Rewrite method signatures using OpWrite

---

core/src/services/webdav/backend.rs
core/src/services/webdav/writer.rs

Complete the refactoring code for #3064

refactor(services/webdav): Refactor `webdav_put` signatures by using `OpWrite`.

---

core/src/services/cos/backend.rs
core/src/services/cos/core.rs
core/src/services/cos/writer.rs

feat(services/cos): Rewrite the methods signature using OpStat/OpRead

---

core/src/services/azblob/backend.rs
core/src/services/azblob/core.rs
core/src/services/azblob/writer.rs

feat(services/azblob): Rewrite azblob methods signature using OpRead/OpStat

---

core/src/services/obs/backend.rs
core/src/services/obs/core.rs
core/src/services/obs/writer.rs

Continue modifying the signatures of some functions: https://github.com/apache/incubator-opendal/issues/3064

feat(services/obs): Rewrite methods signature in obs using OpRead/OpStat

---

core/src/services/gdrive/backend.rs

tests passed locally
```txt
running 112 tests
test services_gdrive::test_blocking_list_non_exist_dir            ... ok
test services_gdrive::test_blocking_copy_non_existing_source      ... ok
test services_gdrive::test_blocking_rename_non_existing_source    ... ok
test services_gdrive::test_blocking_rename_source_dir             ... ok
test services_gdrive::test_blocking_copy_source_dir               ... ok
test services_gdrive::test_blocking_rename_self                   ... ok
test services_gdrive::test_blocking_write_with_dir_path           ... ok
test services_gdrive::test_blocking_create_dir                    ... ok
test services_gdrive::test_blocking_list_dir                      ... ok
test services_gdrive::test_blocking_copy_self                     ... ok
test …
```

feat(service/gdrive): add gdrive copy

---

bindings/c/include/opendal.h
bindings/java/src/lib.rs
bindings/java/src/operator.rs
core/src/layers/blocking.rs
core/src/services/atomicserver/backend.rs
core/src/types/operator/blocking_operator.rs
core/tests/behavior/blocking_append.rs

Fix https://github.com/apache/incubator-opendal/issues/3114

docs: Add comments for blocking layer

---

bindings/java/src/blocking_operator.rs
bindings/java/src/main/java/org/apache/opendal/BlockingOperator.java
bindings/java/src/main/java/org/apache/opendal/Operator.java
bindings/java/src/operator.rs
bindings/java/src/test/java/org/apache/opendal/AsyncStepsTest.java
bindings/java/src/test/java/org/apache/opendal/BlockingOperatorTest.java
bindings/java/src/test/java/org/apache/opendal/OperatorTest.java
bindings/java/src/test/java/org/apache/opendal/RedisServiceTest.java
bindings/java/src/test/java/org/apache/opendal/StepsTest.java

This refers to https://github.com/apache/incubator-opendal/pull/3129#discussion_r1332649985.

refactor(binding/java): read should return bytes

---

website/docs/contributing/release.md

docs: include disclaimer in announcement template

---

bindings/java/src/blocking_operator.rs
bindings/java/src/main/java/org/apache/opendal/BlockingOperator.java
bindings/java/src/main/java/org/apache/opendal/Operator.java
bindings/java/src/operator.rs
bindings/java/src/test/java/org/apache/opendal/test/behavior/AbstractBehaviorTest.java

test(binding/java): add create_dir test

---

Cargo.lock
core/Cargo.toml

fix https://github.com/apache/incubator-opendal/issues/3189

chore: bump quick-xml version to 0.30

---

.asf.yaml

For more information: https://hacktoberfest.com/participation

chore: Let's welcome the contributors from hacktoberfest!

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bindings/cpp/CMakeLists.txt
bindings/java/pom.xml
bindings/nodejs/npm/darwin-arm64/package.json
bindings/nodejs/npm/darwin-x64/package.json
bindings/nodejs/npm/linux-x64-gnu/package.json
bindings/nodejs/npm/win32-x64-msvc/package.json
bindings/nodejs/package.json
core/src/docs/upgrade.md
scripts/verify.py
website/community/committers/release.md

part of #3237 
---
* feat: allow using `prometheus-client` crate with PrometheusClientLayer by @flaneur2020 in https://github.com/apache/incubator-opendal/pull/3134
* feat(binding/java): support info ops by @G-XD in https://github.com/apache/incubator-opendal/pull/3154
* test(binding/java): add behavior test framework by @G-XD in https://github.com/apache/incubator-opendal/pull/3129
* feat: Include starting offset for GHAC upload Content-Range by @huonw in https://github.com/apache/incubator-opendal/pull/3163
* feat(bindings/cpp): make ReaderStream manage the lifetime of Reader by @silver-ymz in https://github.com/apache/incubator-opendal/pull/3164
* feat: Enable multi write for ghac by @Xuanwo in https://github.com/apache/incubator-opendal/pull/3165
* feat: Add mysql support for OpenDAL …

chore: Bump to v0.41.0 to start release process

---

bindings/java/src/blocking_operator.rs
bindings/java/src/main/java/org/apache/opendal/BlockingOperator.java
bindings/java/src/main/java/org/apache/opendal/Operator.java
bindings/java/src/operator.rs
bindings/java/src/test/java/org/apache/opendal/test/behavior/AbstractBehaviorTest.java

feat(binding/java): add `rename` support

---

.github/workflows/bindings_python.yml

chore(ci): publish to pypi with github OIDC credential

---

.github/workflows/bindings_go.yml

ci: Add bindings_go workflow

---

.github/actions/setup/action.yaml
.github/workflows/core_test.yml

Fix https://github.com/apache/incubator-opendal/issues/3270

ci: Passing GITHUB_TOKEN to avoid rate limit

---

.github/workflows/edge_test.yml
Cargo.lock
Cargo.toml
core/edge/README.md
core/edge/file_write_on_full_disk/Cargo.toml
core/edge/file_write_on_full_disk/README.md
core/edge/file_write_on_full_disk/src/main.rs

Fix https://github.com/apache/incubator-opendal/issues/3273

feat: Add edge test cases for OpenDAL Core

---

core/src/services/mysql/backend.rs
core/src/services/postgresql/backend.rs

reafctor: Polish error process code for mysql/postgresql services

---

core/src/services/sled/backend.rs

feat(services/sled): change blocking_x in async_x call to tokio::task::blocking_spawn

feat(services/sled): change blocking_x in async_x call to tokio::task::blocking_spawn

---

website/docs/services/atomicserver.mdx

docs: add docs in website for atomicserver

---

website/docs/services/cacache.mdx
website/docs/services/cacahe.mdx

docs: Add docs on website for cacache services

---

website/docs/services/libsql.mdx

docs: Add docs on website for libsql services

---

website/docs/services/persy.mdx

docs: Add docs on website for persy service

---

core/src/services/d1/docs.md
website/docs/services/d1.mdx

docs: Add docs on website for d1 services

---

website/docs/services/redb.mdx

docs: Add docs on website for redb service

---

website/docs/services/tikv.mdx

docs: Add docs on website for tikv service

---

.github/workflows/service_test_hdfs.yml

Fix https://github.com/apache/incubator-opendal/issues/3307

ci(services/hdfs): Use dlcdn.apache.org instead

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
bin/oay/Cargo.toml
core/Cargo.toml
core/src/docs/upgrade.md
integrations/dav-server/Cargo.toml

This PR will bump and update MSRV to 1.67

refactor(!): Bump and update MSRV to 1.67

---

core/src/types/scheme.rs

Close https://github.com/apache/incubator-opendal/issues/3329

feat(core): Add enabled for Scheme

---

core/src/docs/internals/accessor.rs
core/src/services/tikv/backend.rs

I think there maybe some errors in docs.

docs: fix something in docs

---

.github/services/mongodb/mongodb_with_basic_auth/action.yml
.github/services/mongodb/mongodb_with_no_auth/action.yml
Cargo.lock
bindings/java/Cargo.toml
core/Cargo.toml
core/src/services/mod.rs
core/src/services/mongodb/backend.rs
core/src/services/mongodb/docs.md
core/src/services/mongodb/mod.rs
core/src/types/operator/builder.rs
core/src/types/scheme.rs
fixtures/mongodb/docker-compose-basic-auth.yml
fixtures/mongodb/docker-compose-no-auth.yml
website/docs/services/mongodb.mdx

feat(service/mongodb): Support mongodb service

---

bindings/java/src/blocking_operator.rs
bindings/java/src/convert.rs
bindings/java/src/lib.rs
bindings/java/src/operator.rs
bindings/java/src/utility.rs

chore(bindings/java): move out convert fns

---

.github/services/memory/memory/action.yml
.github/workflows/service_test_memory.yml

refactor(services/memory): migrate to test planner

---

core/src/docs/upgrade.md

doc: apply `range_reader` change in upgrade doc 

---

bindings/java/src/test/java/org/apache/opendal/test/behavior/BehaviorExtension.java

feat(bindings/java): use random root for behavior tests

---

website/docusaurus.config.js

See https://lists.apache.org/thread/vtf382zrmj1c87h38l1ly1924brsrxj8.

fix: ASF event URL

---

.github/scripts/behavior_test/plan.py
bindings/python/tests/test_write.py

Related to https://github.com/apache/incubator-opendal/issues/3429
We should add those tests back after #3429 addressed.

ci(bindings/python): Remove not passing test cases until we addressed

---

.github/scripts/behavior_test/plan.py
.github/services/azblob/azurite_azblob/action.yml
.github/services/etcd/etcd-cluster/action.yml
.github/services/etcd/etcd-tls/action.yml
.github/services/etcd/etcd/action.yml
.github/services/http/caddy/action.yml
.github/services/http/nginx/action.yml
.github/services/memcached/memcached/action.yml
.github/services/mongodb/mongodb_with_basic_auth/action.yml
.github/services/mongodb/mongodb_with_no_auth/action.yml
.github/services/mysql/mysql/action.yml
.github/services/postgresql/postgresql/action.yml
.github/services/redis/dragonfly/action.yml
.github/services/redis/kvrocks/action.yml
.github/services/redis/redis/action.yml
.github/services/redis/redis_with_cluster/action.yml
.github/services/s3/minio_s3/action.yml
.github/services/s3/minio_s3_with_anonymous/action.yml
.github/services/sftp/sftp/action.yml
.github/services/sftp/sftp_with_default_root/action.yml
fixtures/sftp/docker-compose-sftp-with-default-root.yml
fixtures/sftp/docker-compose-sftp.yml
fixtures/sftp/health-check.sh

chore(test): Fix sftp test failed in python

---

.github/services/azblob/azurite_azblob/action.yml
.github/services/etcd/etcd-cluster/action.yml
.github/services/etcd/etcd-tls/action.yml
.github/services/etcd/etcd/action.yml
.github/services/http/caddy/action.yml
.github/services/http/nginx/action.yml
.github/services/memcached/memcached/action.yml
.github/services/mongodb/mongodb_with_basic_auth/action.yml
.github/services/mongodb/mongodb_with_no_auth/action.yml
.github/services/mysql/mysql/action.yml
.github/services/postgresql/postgresql/action.yml
.github/services/redis/dragonfly/action.yml
.github/services/redis/kvrocks/action.yml
.github/services/redis/redis/action.yml
.github/services/redis/redis_with_cluster/action.yml
.github/services/s3/minio_s3/action.yml
.github/services/s3/minio_s3_with_anonymous/action.yml
.github/services/sftp/sftp/action.yml
.github/services/sftp/sftp_with_default_root/action.yml

ci(test): Remove wait timeout for docker compose

---

bindings/java/pom.xml
bindings/java/src/main/java/org/apache/opendal/Operator.java
bindings/java/src/test/java/org/apache/opendal/test/behavior/AsyncPresignTest.java

Fix error and add behavior test for `presign`.

fix(binding/java): fix return value of presign-related method

---

fixtures/sftp/health-check.sh

Update file header

---

.github/scripts/behavior_test/plan.py
.github/scripts/behavior_test/test_plan.py

refactor(ci): Polish the test planner code

---

bindings/java/src/test/java/org/apache/opendal/test/behavior/AsyncReadOnlyTest.java
bindings/java/src/test/java/org/apache/opendal/test/behavior/BehaviorTestBase.java
bindings/java/src/test/java/org/apache/opendal/test/behavior/BlockingReadOnlyTest.java

test(binding/java): add read_only test

---

.github/workflows/ci.yml
.github/workflows/service_test_redis.yml
bindings/java/Cargo.toml
bindings/nodejs/Cargo.toml
bindings/python/Cargo.toml
core/Cargo.toml

Close https://github.com/apache/incubator-opendal/issues/3427

refactor(services/redis): Enable rustls support by default for redis

---

website/docs/services/swift.mdx

- Adding documents to the website based on PR: #3461 and #3493

feat(doc): add OpenStack Swift document for the website

---

core/src/services/libsql/backend.rs

chore(services/libsql): Fix typos in backend

---

core/src/services/dropbox/backend.rs

Fix https://github.com/apache/incubator-opendal/issues/3463

fix(services/dropbox): Check if folder exists before calling create dir

---

Cargo.lock
core/Cargo.toml

#3466 
bugfix ref: https://github.com/openssh-rust/openssh-sftp-client/issues/111

chore(servies/sftp): Upgrade openssh-sftp-client to 0.14

---

README.md

close:https://github.com/apache/incubator-opendal/issues/3530

docs: Add questdb in users list

---

core/src/services/hdfs/docs.md

fix https://github.com/apache/incubator-opendal/issues/3557
Additional steps documented to run hdfs service on macos

docs: Add macos specific doc updates for hdfs

---

core/src/services/azblob/backend.rs
core/src/services/azblob/mod.rs
core/src/services/mod.rs

Impl Azblob support for #3240 .

refactor(services/azblob): add AzblobConfig

---

Cargo.lock
core/Cargo.toml

chore: update opentelemetry to v0.21.x

---

.github/workflows/bindings_python.yml

- fix: https://github.com/apache/incubator-opendal/issues/3596

chore(ci): fix artifacts path for publish pypi

---

core/Cargo.toml

Fix https://github.com/apache/incubator-opendal/issues/3618

chore: Fix `raw::tests` been excluded unexpectedly

---

.github/workflows/publish.yml

Part of https://github.com/apache/incubator-opendal/issues/3603

ci(core): Add dry run for rc tags

---

core/src/services/azfile/core.rs

find the api from https://learn.microsoft.com/en-us/rest/api/storageservices/get-directory-properties
fix #3646

refactor(services/azfile): Check if dir exists before create

---

core/src/types/operator/operator.rs
core/tests/behavior/write.rs

Fix https://github.com/apache/incubator-opendal/issues/3669

fix(core): Path in remove not normalized

---

.github/workflows/bindings_python.yml

ci(bindings/python): remove aarch support

---

CHANGELOG.md

chore: Bump to v0.43.0 to start release process (Round 2)

---

CHANGELOG.md
website/community/committers/release.md

chore: Bump to v0.43.0 to start release process (Round 3)

---

core/src/services/etcd/backend.rs

refactor(service/etcd): use EtcdConfig in from_map

---

.github/workflows/docs.yml

Part of https://github.com/apache/incubator-opendal/issues/3319
We still need some frontend work, but I think it should not be a blocker.

docs: Deploy website to nightlies for every tags

---

.github/services/persy/persy/action.yml
Cargo.lock
core/Cargo.toml

Close https://github.com/apache/incubator-opendal/issues/3630

chore: Bring persy CI back

---

Cargo.lock
bindings/python/Cargo.toml
bindings/python/src/operator.rs
bindings/python/src/utils.rs

https://github.com/PyO3/pyo3/releases/tag/v0.20.0

chore(bindings/python): upgrade pyo3 to 0.20

---

Cargo.lock
core/Cargo.toml
core/src/layers/throttle.rs

chore: Bump governor from 0.5.1 to 0.6.0

---

website/community/index.mdx

docs: add event calendar in community page

---

Cargo.lock
Cargo.toml
bin/ofs/Cargo.toml
bin/ofs/DEPENDENCIES.md
bin/ofs/DEPENDENCIES.rust.tsv
bin/ofs/README.md
bin/ofs/src/lib.rs
scripts/dependencies.py

As discussed in https://github.com/apache/incubator-opendal/issues/3411, [DalFs](https://github.com/Inokinoki/DalFs)'s owner is intereted in contribute dalfs back into OpenDAL.
This PR is used to add the basic project layout so @Inokinoki, @ho-229, @oowl can get their hand dirty to do some real work.

feat: Add project layout for ofs

---

core/src/services/gcs/backend.rs
core/src/services/gcs/mod.rs

Fix https://github.com/apache/incubator-opendal/pull/3785

refactor: Migrate gcs builder to config based

---

bindings/ruby/README.md

This closes https://github.com/apache/incubator-opendal/issues/3795

docs(bindings/ruby): reflect test framework refactor

---

core/src/raw/http_util/header.rs

refactor(raw): refactor APIs like parse_content_disposition

---

website/community/committers/release.md

docs: update release docs to add cargo-deny setup

---

core/src/services/memcached/backend.rs
core/src/services/memcached/mod.rs
core/src/services/mod.rs

…ializer
add feat for memcached as mentioned in #3240

feat(service/memcached): Add MemCachedConfig

---

core/src/services/upyun/backend.rs
core/src/services/upyun/lister.rs

fix upyun list api for these behavior test:
```shell
behavior::test_list_empty_dir
behavior::test_list_prefix
behavior::test_list_sub_dir
behavior::test_list_with_recursive
behavior::test_list_dir_with_file_path
```

fix(services/upyun): fix list api

---

core/src/services/atomicserver/backend.rs
core/src/services/atomicserver/mod.rs
core/src/services/mod.rs

For #3240 
@Xuanwo Please review

feat: Adding Atomicserver config

---

core/src/raw/oio/read/buffer_reader.rs

Fix a bypass seek relative bug in `BufferReader`
#3735

fix: fix a bypass seek relative bug in `BufferReader`

---

core/src/raw/oio/read/buffer_reader.rs

Fix the bypass read does not sync the `cur` of `BufferReader`
#3735

fix: fix the bypass read does not sync the `cur` of `BufferReader`

---

Cargo.lock
bindings/python/Cargo.toml
bindings/python/src/lib.rs

Related to https://github.com/rust-lang/rust-clippy/issues/12039

fix: Bump pyo3 to fix false positive of unnecessary_fallible_conversions

---

Cargo.lock
bindings/lua/Cargo.toml
bindings/lua/src/lib.rs

close https://github.com/apache/incubator-opendal/issues/3886

build(deps): bump mlua from 0.8.10 to 0.9.2

---

core/src/raw/oio/write/range_write.rs
core/src/services/gcs/backend.rs

feat: implement concurrent `RangeWriter`

---

.github/workflows/fuzz_test.yml
fixtures/azblob/docker-compose-azurite.yml

feat(fuzz): add azblob as test service

---

core/src/services/redis/backend.rs

refactor(services/redis): Impl parse_error instead of From<Error>

---

Cargo.lock
bindings/c/Cargo.lock
core/Cargo.toml

Close https://github.com/apache/incubator-opendal/issues/3946

chore: Remove unused dep async-compat

---

core/src/services/dropbox/builder.rs
core/src/services/dropbox/mod.rs
core/src/services/mod.rs

refactor(service/dropbox): Add DropboxConfig

---

bindings/java/pom.xml
bindings/java/src/main/java/org/apache/opendal/layer/package-info.java

Something like the Apache HBase project was told to do - https://github.com/apache/hbase/pull/5600

chore: add more information for javadocs

---

website/src/pages/download.md

Close https://github.com/apache/incubator-opendal/issues/3992

docs: Fix missing word in download

---

bindings/python/Cargo.toml

chore(bindings/python): Enable sftp service by default for unix platform

---

core/src/raw/oio/write/multipart_write.rs

Fix https://github.com/apache/incubator-opendal/issues/4012

fix: async fn resumed after initiate part failed

---

.github/scripts/assign_reviewers.js

close: https://github.com/apache/opendal/issues/4022

fix(ci): remove pr author from review candidates

---

website/src/pages/download.md

chore(website): Bump download link for 0.44.2 release

---

website/community/committers/release.md

Address comment https://github.com/apache/opendal/pull/4036#discussion_r1460725336

docs: Remove not needed actions in release guide

---

doap.rdf

This closes #3749.
This refers to https://projects.apache.org/create.html.

chore: add doap file

---

website/community/committers/release.md

chore(website): Add extra artifacts check process in release document

---

core/src/services/seafile/writer.rs

fix(seafile): test_list_dir_with_metakey

---

core/src/raw/oio/list/prefix_list.rs
core/tests/behavior/async_list.rs
core/tests/behavior/blocking_list.rs

Fix https://github.com/apache/opendal/issues/4066

fix: list path recursive should not return path itself

---

website/community/committers/onboarding.md
website/community/news.md

Based on our discussion here: https://github.com/apache/opendal/pull/4056, I have added a pull request for the new guide in the onboarding SOP.

feat(website): add missing news and organize the onboarding guide

---

Cargo.lock
core/Cargo.toml

Close https://github.com/apache/opendal/issues/4090

fix: Upgrade suppaftp to address build failure

---

README.md

As title sayas, this pr add apache iceberg-rust as user of opendal.

docs: Add apache iceberg-rust as user

---

core/src/services/chainsafe/error.rs

fix(services/chainsafe): fix 423 http status

---

.github/workflows/release_rust.yml
bin/oay/Cargo.toml

ci: Add support for releasing all rust packages

---

core/benches/ops/README.md

chore: update benchmark doc

---

core/src/services/webdav/backend.rs
core/src/services/webdav/lister.rs

fix(services/webdav): remove base_dir component

---

core/src/services/webdav/backend.rs
core/src/services/webdav/lister.rs

Fix https://github.com/apache/opendal/issues/4255

fix(services/webdav): Fix endpoint suffix not handled

---

.github/services/yandex_disk/yandex_disk/action.yml
bindings/java/Cargo.toml
bindings/nodejs/Cargo.toml
bindings/python/Cargo.toml
core/src/services/yandex_disk/error.rs

feat(services/yandex_disk): setup test for yandex disk

---

CHANGELOG.md

rc2 failed for java's release workflow failed.

Bump version to 0.45.1 (Round 3)

---

.github/workflows/ci_bindings_c.yml
.github/workflows/ci_bindings_cpp.yml
.github/workflows/ci_bindings_dotnet.yml
.github/workflows/ci_bindings_go.yml
.github/workflows/ci_bindings_haskell.yml
.github/workflows/ci_bindings_java.yml
.github/workflows/ci_bindings_lua.yml
.github/workflows/ci_bindings_nodejs.yml
.github/workflows/ci_bindings_ocaml.yml
.github/workflows/ci_bindings_python.yml
.github/workflows/ci_bindings_ruby.yml
.github/workflows/ci_bindings_swift.yml
.github/workflows/ci_bindings_zig.yml
bindings/python/pyproject.toml

Related to https://github.com/apache/opendal/issues/4268

ci: Mark python 3.13 is not supported

---

CHANGELOG.md

rc3 build failed for https://github.com/apache/opendal/issues/4268

Bump version to 0.45.1 (Round 4)

---

website/community/events/_category_.yml
website/community/events/gsoc-proposal-guide.md
website/community/pmc_members/_category_.yml

This PR adds a gsoc proposal guide.

docs: Add gsoc proposal guide

---

core/src/services/azblob/core.rs
core/src/services/azdls/backend.rs
core/src/services/memcached/binary.rs
core/src/services/vercel_blob/core.rs
core/src/services/vercel_blob/writer.rs
core/src/services/webdav/core.rs
core/src/services/webdav/lister.rs
core/src/services/webdav/writer.rs
core/src/types/operator/operator.rs

Fix https://github.com/apache/opendal/issues/4291

docs: Fix and improve docs for presign operations

---

.github/workflows/service_test_ghac.yml

fix: fix ghac CI

---

website/docusaurus.config.js

a potential error in https://github.com/apache/opendal/pull/4328

docs: fix redirect error in object-store-opendal

---

bin/ofs/Cargo.lock
bin/ofs/Cargo.toml

fix(bin/ofs): only memory backend available

---

core/src/services/gcs/backend.rs
core/src/services/gcs/docs.md

docs(services/gcs): update gcs credentials description

---

.github/workflows/ci_core.yml
core/Cargo.lock
core/Cargo.toml
core/benches/README.md
core/src/docs/upgrade.md
core/src/raw/http_util/client.rs

Leave those decisions to the users.

refactor: Remove reqwest related features

---

core/Cargo.lock
core/Cargo.toml
core/src/services/mod.rs
core/src/services/surrealdb/backend.rs
core/src/services/surrealdb/docs.md
core/src/services/surrealdb/mod.rs
core/src/types/scheme.rs

implemented https://github.com/apache/opendal/issues/2753

feat(services/surrealdb): support surrealdb service

---

bin/ofs/src/bin/ofs.rs
bin/ofs/src/config.rs
bin/ofs/src/fuse.rs
bin/ofs/src/lib.rs

- make `ofs` API public to test fuse adapter #4373

refactor(bin/ofs): make `ofs` API public

---

core/src/raw/oio/buf/mod.rs
core/src/raw/oio/buf/readable_buf.rs

This PRs add readable buf for opendal.
This is a raw only API that opendal deveopers should make sure using it correctly. Users should never touch this.

feat(core/oio): Add readable buf

---

core/src/types/scheme.rs

this PR is to correct the doc for `Scheme`

docs(core): correct the doc for icloud and memcached

---

website/community/committers/release.md
website/community/committers/verify.md

Add some content about how RM mentions voters in the voting result email.

docs: polish release doc for vote result

---

fixtures/redis/docker-compose-dragonfly.yml

fix: https://github.com/apache/opendal/actions/runs/8554405156/job/23439759353
background: https://github.com/dragonflydb/dragonfly/issues/2841#issuecomment-2036920402

ci: fix dragonflydb docker-compose healthcheck broken

---

core/src/services/gdrive/core.rs

Fix https://github.com/apache/opendal/issues/4432

fix(core/services/gdrive): Fix gdrive test failed for refresh token

---

core/src/raw/http_util/client.rs

Closes https://github.com/apache/opendal/issues/4446

feat: add `HttpClient::with()` constructor

---

.github/scripts/test_behavior/plan.py
.github/scripts/test_behavior/test_plan.py

ci: fix planner for bin ofs

---

examples/rust/00-setup/Cargo.toml
examples/rust/01-init-operator/Cargo.toml
examples/rust/03-add-layers/.gitignore
examples/rust/03-add-layers/Cargo.toml
examples/rust/03-add-layers/README.md
examples/rust/03-add-layers/src/main.rs
examples/rust/README.md

docs: add layers example

---

core/src/services/cos/core.rs

Please don't update this branch nor delete it, we have users pin commit on this branch. We can remove it after 0.46 released.

fix(core/services/cos): Don't allow empty credential

---

core/src/types/buffer.rs

This PR adds `FromIterator` for buffer to make it easier to use.

feat(core): Implement FromIterator for Buffer

---

.github/workflows/ci_bin_oay.yml
integrations/dav-server/src/file.rs
integrations/dav-server/src/opendalfs.rs
integrations/dav-server/tests/test.rs

https://github.com/apache/opendal/pull/4374 is incorrect, we can't implement read/write in this way. Need discussin with upstream.

ci: Revert oay changes to fix CI

---

core/src/services/ftp/backend.rs
core/src/services/ftp/writer.rs

close https://github.com/apache/opendal/issues/4400

feat(services/ftp): Support multiple write

---

core/src/raw/oio/write/block_write.rs

feat(raw/oio): block write change to buffer

---

core/benches/ops/read.rs
core/src/types/buffer.rs
core/src/types/reader.rs

This PR tunes buffer operations based on benchmark results. There are other works to do, result will paste before releasing.

feat(core): Tune buffer operations  based on benchmark results

---

core/src/raw/adapters/kv/api.rs
core/src/raw/adapters/kv/backend.rs
core/src/raw/oio/read/api.rs
core/src/services/atomicserver/backend.rs
core/src/services/cacache/backend.rs
core/src/services/cloudflare_kv/backend.rs
core/src/services/d1/backend.rs
core/src/services/d1/model.rs
core/src/services/etcd/backend.rs
core/src/services/foundationdb/backend.rs
core/src/services/gridfs/backend.rs
core/src/services/libsql/backend.rs
core/src/services/memcached/backend.rs
core/src/services/mongodb/backend.rs
core/src/services/mysql/backend.rs
core/src/services/persy/backend.rs
core/src/services/postgresql/backend.rs
core/src/services/redb/backend.rs
core/src/services/redis/backend.rs
core/src/services/rocksdb/backend.rs
core/src/services/sled/backend.rs
core/src/services/sqlite/backend.rs
core/src/services/surrealdb/backend.rs
core/src/services/tikv/backend.rs

This is the read part for #4479.

refactor: kv::adapter should use Buffer (read part)

---

core/src/raw/adapters/typed_kv/api.rs
core/src/raw/adapters/typed_kv/backend.rs
core/src/raw/oio/buf/queue_buf.rs
core/src/raw/oio/write/exact_buf_write.rs

refactor: typed_kv::adapter should use Buffer

---

.github/workflows/docs.yml
integrations/dav-server/README.md
website/docs/integrations/dav-server-opendalfs.mdx
website/docusaurus.config.js

docs: publish docs for dav-server-opendalfs

---

core/src/types/reader.rs
core/tests/behavior/async_read.rs

Close https://github.com/apache/opendal/issues/4490

refactor: Migrate FuturesAsyncReader to stream based

---

core/src/types/operator/operator.rs

This PR fixes some minor issues introduced in #4516.

fix: minor doc issue

---

core/Cargo.lock
core/Cargo.toml
core/src/services/compfs/mod.rs
core/src/services/mod.rs

This PR initializes `services-compfs`, include its feature gate, dependency and mod.

feat(services/compfs): init compfs

---

.github/workflows/docs.yml
core/Cargo.lock
core/Cargo.toml

This PR updates compio version to v0.10.0

build(core): bump compio version to v0.10.0

---

.github/workflows/docs.yml

Confirmed by manually pushing to `site/main-staging` https://opendal-main.staged.apache.org/.

build: fixup follow asfyaml rules

---

core/src/services/gcs/docs.md

See https://github.com/apache/opendal/issues/4669

doc: explain GCS authentication options

---

bin/oay/Cargo.lock
bin/ofs/Cargo.lock
bin/oli/Cargo.lock
core/Cargo.toml
core/src/layers/retry.rs
core/src/raw/futures_util.rs
core/src/raw/http_util/bytes_range.rs
core/src/raw/ops.rs

Implement retry logic for streaming based read.

feat: Implement retry for streaming based read

---

core/benches/types/concurrent_tasks.rs
core/src/layers/timeout.rs
core/src/raw/futures_util.rs
core/src/raw/oio/write/multipart_write.rs
core/src/types/execute/api.rs
core/src/types/execute/executor.rs
core/src/types/read/buffer_stream.rs

Implement timeout layer for concurrent tasks

feat(core): Implement TimeoutLayer for concurrent tasks

---

core/src/raw/oio/write/block_write.rs
core/src/raw/oio/write/multipart_write.rs
core/src/services/azblob/backend.rs
core/src/services/webhdfs/backend.rs

Part of https://github.com/apache/opendal/issues/4639

refactor(core): Use concurrent tasks to refactor block write

---

core/src/raw/oio/write/range_write.rs
core/src/services/gcs/backend.rs

Migrate RangeWrite to ConcurrentTasks
Part of https://github.com/apache/opendal/issues/4639

refactor(core): Migrate RangeWrite to ConcurrentTasks

---

bin/ofs/Cargo.lock
bin/oli/Cargo.lock
core/Cargo.lock
core/Cargo.toml
core/src/services/azblob/backend.rs

Close https://github.com/apache/opendal/issues/4704

feat(core): Azblob supports azure workload identity

---

CHANGELOG.md
bin/oay/Cargo.lock
bin/oay/DEPENDENCIES.rust.tsv
bin/ofs/Cargo.lock
bin/ofs/DEPENDENCIES.rust.tsv
bin/oli/Cargo.lock
bin/oli/DEPENDENCIES.rust.tsv
bin/ovfs/Cargo.lock
bin/ovfs/DEPENDENCIES.rust.tsv
bindings/c/DEPENDENCIES.rust.tsv
bindings/cpp/DEPENDENCIES.rust.tsv
bindings/dotnet/DEPENDENCIES.rust.tsv
bindings/haskell/DEPENDENCIES.rust.tsv
bindings/java/DEPENDENCIES.rust.tsv
bindings/lua/DEPENDENCIES.rust.tsv
bindings/nodejs/DEPENDENCIES.rust.tsv
bindings/ocaml/DEPENDENCIES.rust.tsv
bindings/php/DEPENDENCIES.rust.tsv
bindings/python/DEPENDENCIES.rust.tsv
bindings/ruby/DEPENDENCIES.rust.tsv
core/Cargo.lock
core/DEPENDENCIES.rust.tsv
integrations/dav-server/DEPENDENCIES.rust.tsv
integrations/object_store/DEPENDENCIES.rust.tsv

Part of https://github.com/apache/opendal/issues/4640

chore: Update changelogs for v0.47

---

CHANGELOG.md

chore: Bump to 0.47.1-rc.2

---

core/src/layers/async_backtrace.rs

feat: make AsyncBacktraceLayer covers oio::Read and oio::Write

---

.github/workflows/ci_bindings_nodejs.yml

Close https://github.com/apache/opendal/issues/4797

ci: Fix lib-darwin-x64 no released

---

bindings/nodejs/upgrade.md

doc(nodejs): update upgrade.md

---

.github/workflows/ci_integration_unftp_sbe.yml

This PR inits CI workflow for unftp sbe integration

ci(unftp-sbe): init

---

core/src/types/operator/operator_futures.rs

fix(core): write concurrent doesn't set correctly

---

core/tests/behavior/async_write.rs

fix(tests/behavior): skip test of write_with_overwrite for ghac

---

core/Cargo.lock
core/Cargo.toml
core/src/layers/metrics.rs

Resolve #4837 
ref: https://github.com/metrics-rs/metrics/pull/394

chore(deps): bump metrics from 0.20.1 to 0.23.0 in /core

---

integrations/object_store/Cargo.toml
integrations/object_store/src/store.rs

object_store uses more metadata than requrested, let's make sure they are aligned.

fix(integration/object_store): Fix metakey requested is incomplete

---

fixtures/sftp/health-check.sh
fixtures/webdav/health-check-nextcloud.sh

https://en.wikipedia.org/wiki/Shebang_(Unix)

Fix shebang in shell files

---

integrations/cloudfilter/Cargo.toml
integrations/cloudfilter/examples/readonly.rs
integrations/cloudfilter/src/file.rs
integrations/cloudfilter/src/lib.rs

This PR introduces a read only Cloud Filter implementation for access OpenDAL services on Windows.

feat(integrations/cloudfilter): read only cloud filter

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml
.github/ISSUE_TEMPLATE/3-new-release.md
.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md

The OpenDAL community has grown significantly; let's introduce issue and PR templates to enhance communication.

ci: Add issue template and pr template for opendal

---

core/src/services/oss/backend.rs

Closes #4898 
add port if possible to `full_host`
No

fix: oss will not use the port

---

core/README.md

See: https://github.com/apache/opendal/pull/4912#issuecomment-2240894661

docs(core): update README to add `MimeGuessLayer`.

---

.github/ISSUE_TEMPLATE/3-new-release.md
website/community/release/release.md

docs: fix spelling

---

CHANGELOG.md
bin/oay/DEPENDENCIES.rust.tsv
bin/ofs/DEPENDENCIES.rust.tsv
bin/oli/Cargo.lock
bin/oli/DEPENDENCIES.rust.tsv
bindings/c/DEPENDENCIES.rust.tsv
bindings/cpp/DEPENDENCIES.rust.tsv
bindings/dotnet/DEPENDENCIES.rust.tsv
bindings/haskell/DEPENDENCIES.rust.tsv
bindings/java/DEPENDENCIES.rust.tsv
bindings/lua/DEPENDENCIES.rust.tsv
bindings/nodejs/DEPENDENCIES.rust.tsv
bindings/ocaml/DEPENDENCIES.rust.tsv
bindings/php/DEPENDENCIES.rust.tsv
bindings/python/DEPENDENCIES.rust.tsv
bindings/ruby/DEPENDENCIES.rust.tsv
core/DEPENDENCIES.rust.tsv
integrations/cloudfilter/DEPENDENCIES.rust.tsv
integrations/dav-server/DEPENDENCIES.rust.tsv
integrations/fuse3/DEPENDENCIES.rust.tsv
integrations/object_store/DEPENDENCIES.rust.tsv
integrations/unftp-sbe/DEPENDENCIES.rust.tsv
integrations/virtiofs/DEPENDENCIES.rust.tsv

Part of https://github.com/apache/opendal/issues/4923
New Release of OpenDAL.
Version bump
New Release.

Bump to version 0.48.0 - Round 1

---

.github/actions/setup/action.yaml

Fix https://github.com/rust-lang/cargo/issues/14307.
old nextest will crash with our current `Cargo.lock`
Bump nextest to latest version.
No user-facing change.

ci: Bump nextest to 0.9.72

---

bindings/lua/opendal-0.1.3-1.rockspec

Part of https://github.com/mlua-rs/luarocks-build-rust-mlua/issues/12
0.2.1 seems broken.
Manually set to 0.2.
No

ci: Try fix opendal-lua build

---

website/community/pmc_members/nominate-committer.md

docs: nominate-committer add announcement template

---

bindings/python/pyproject.toml

feat(bindings/python): strip the library for minimum file size

---

website/docusaurus.config.js

Closes https://github.com/apache/opendal/issues/5002

docs: Fix version detect in website

---

bindings/python/Cargo.toml

Try #5000
- https://github.com/rustls/rustls/issues/1788
- https://github.com/aws/aws-lc-rs/issues/342
Add direct usage of aws-lc.
No

ci(bindings/python): Fix aws-lc-rs build on arm platforms

---

integrations/cloudfilter/README.md
integrations/virtiofs/README.md

Closes #.
Unify the style of readme content
Add branding, license and trademarks to integrations
No

docs: add branding, license and trademarks to integrations

---

CHANGELOG.md

Part of https://github.com/apache/opendal/issues/5011

chore: Bump version to 0.49.1 - Round 2

---

.github/workflows/docs.yml

None
Fix website build failed.

ci: Add contents write permission for build-website

---

.github/workflows/service_test_ghac.yml

None.
Fix test for service ghac.

ci: Fix test for service ghac

---

website/community/release/release.md

chore: fix path typo in release docs

---

.github/workflows/ci_integration_spring.yml
integrations/spring/opendal-spring-boot-starter-reactive/src/test/java/org/apache/opendal/spring/TestReactiveApplication.java
integrations/spring/opendal-spring-boot-starter-reactive/src/test/java/org/apache/opendal/spring/config/OpenDALReactiveAutoConfigurationTest.java
integrations/spring/opendal-spring-boot-starter-reactive/src/test/resources/application.yml
integrations/spring/opendal-spring-boot-starter/src/test/java/org/apache/opendal/spring/TestApplication.java
integrations/spring/opendal-spring-boot-starter/src/test/java/org/apache/opendal/spring/config/OpenDALAutoConfigurationTest.java
integrations/spring/opendal-spring-boot-starter/src/test/resources/application.yml
integrations/spring/pom.xml

ci(integrations/spring): add spring boot bean load test

---

core/Cargo.lock
core/Cargo.toml
core/src/layers/retry.rs
core/src/services/dropbox/backend.rs
core/src/services/gcs/core.rs

chore: Bump backon to 1.0.0

---

bin/ofs/Cargo.lock
bindings/c/src/operator.rs
bindings/cpp/src/lib.rs
bindings/dotnet/src/lib.rs
bindings/haskell/src/lib.rs
bindings/java/src/async_operator.rs
bindings/lua/src/lib.rs
bindings/nodejs/src/lib.rs
bindings/ocaml/src/lib.rs
bindings/php/src/lib.rs
bindings/ruby/src/lib.rs
core/Cargo.lock
core/Cargo.toml
core/src/docs/upgrade.md
core/src/services/mysql/backend.rs
core/src/services/mysql/config.rs
core/src/services/postgresql/backend.rs
core/src/services/postgresql/config.rs
core/src/services/sqlite/backend.rs
core/src/services/sqlite/config.rs
integrations/cloudfilter/src/lib.rs

refactor: use sqlx for sql services 

---

core/src/raw/path.rs
core/src/services/memory/backend.rs

None
the right range in blocking_scan of services/memory is not right

fix(services/memory): blocking_scan right range

---

core/src/services/mysql/backend.rs

mysql have delete Capability
Closes #.

fix(core/services/mysql): Fix mysql Capability

---

core/src/services/fs/lister.rs

related #5061 & #5071.
Fix compiler error

fix(service/fs): error due to temporary value being dropped

---

website/docs/binding-java.md

docs: Update binding-java.md

---

.github/workflows/ci_bindings_zig.yml
bindings/zig/.gitignore
bindings/zig/README.md
bindings/zig/build.zig
bindings/zig/build.zig.zon
bindings/zig/test/bdd.zig

Signed-off-by: Xuanwo <github@xuanwo.io># Which issue does this PR close?
Fix build and test of zig on 0.13

ci(bindings/zig): Fix build and test of zig on 0.13

---

website/blog/2024-09-09-apache-opendal-meetup-beijing-1st/index.md

Announcement of the First OpenDAL Beijing Meetup.

website: OpenDAL Beijing Meetup 1st

---

.github/workflows/release_rust.yml

Don't publish with all features to avoid depends on features that need windows.

ci: Don't publish with all features

---

integrations/parquet/Cargo.toml

chore(integrations/parquet): Bump parquet to 53

---

CHANGELOG.md
core/src/docs/upgrade.md

Part of https://github.com/apache/opendal/issues/5105

Bump to version 0.50.0 - Round 1

---

CHANGELOG.md

Part of https://github.com/apache/opendal/issues/5105

Bump to version v0.50.0 - Round 2

---

bindings/nodejs/generated.d.ts

ci(bindings/nodejs): Fix diff introduced by napi

---

.github/services/s3/aws_s3_with_versioning/action.yml

follow up to: https://github.com/apache/opendal/pull/5106

test(services/s3): add Github workflow for AWS with versioning

---

bindings/java/README.md

chore: update binding java artifact name in README

---

bindings/python/README.md
bindings/python/python/opendal/layers.pyi
bindings/python/src/layers.rs
bindings/python/src/lib.rs
bindings/python/tests/conftest.py

The change export https://docs.rs/opendal/latest/opendal/layers/struct.ConcurrentLimitLayer.html via Python binding.

feat(bindings/python): export ConcurrentLimitLayer

---

fixtures/s3/docker-compose-minio.yml

Closes #5097 
Upgrade MinIO version (support S3 write option `if_none_match`)

chore(fixtures/s3): Upgrade MinIO version

---

core/Cargo.toml
core/src/services/nebula_graph/backend.rs
core/src/services/nebula_graph/config.rs
core/src/services/nebula_graph/docs.md
core/src/services/nebula_graph/mod.rs

Closes #4553.
The NebulaGraph client `rust-nebula` still needs time to be perfected, so it can merge the NebulaGraph config section first. Ref to https://github.com/apache/opendal/pull/5116.

feat: add NebulaGraph config

---

integrations/spring/opendal-spring-boot-starter-reactive/pom.xml
integrations/spring/opendal-spring-boot-starter-reactive/src/main/java/org/apache/opendal/spring/config/OpenDALReactiveAutoConfiguration.java
integrations/spring/opendal-spring-boot-starter-reactive/src/test/java/org/apache/opendal/spring/config/OpenDALReactiveTemplateTest.java
integrations/spring/opendal-spring-boot-starter-reactive/src/test/java/org/apache/opendal/spring/config/Person.java
integrations/spring/opendal-spring-boot-starter/src/main/java/org/apache/opendal/spring/config/OpenDALAutoConfiguration.java
integrations/spring/opendal-spring-boot-starter/src/test/java/org/apache/opendal/spring/config/OpenDALAutoConfigurationTest.java
integrations/spring/opendal-spring-boot-starter/src/test/java/org/apache/opendal/spring/config/OpenDALTemplateTest.java
integrations/spring/opendal-spring-boot-starter/src/test/java/org/apache/opendal/spring/config/Person.java
integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/OpenDALOperations.java
integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/OpenDALOperationsImpl.java
integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/ReactiveOpenDALOperationsImpl.java
integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/ReactiveOpenDALTemplate.java
integrations/spring/pom.xml

feat: support write,read,delete with template

---

bindings/java/src/test/java/org/apache/opendal/test/behavior/BehaviorExtension.java

Instead of saying nothing that can confuse developers (previous me :D)

chore: hint when java tests are skipped

---

bindings/nodejs/README.md
bindings/nodejs/generated.d.ts
bindings/nodejs/package.json
bindings/nodejs/pnpm-lock.yaml
bindings/nodejs/tests/service.test.mjs
bindings/nodejs/vitest.config.mjs
bindings/python/README.md

docs: improve Node.js binding's test doc

---

.github/workflows/docs.yml

Releated #5172 , update build-haskell-doc

ci: add package cache for build-haskell-doc

---

.github/workflows/ci_bindings_ocaml.yml
.github/workflows/docs.yml

Releated #5172 
add cache action for 
- test at [ci_bindings_ocaml.yml](https://github.com/apache/opendal/actions/workflows/.github/workflows/ci_bindings_ocaml.yml)
- build-ocaml-doc at [docs.yml](https://github.com/apache/opendal/actions/workflows/.github/workflows/docs.yml)
No

ci: add cache action for ci_bindings_ocaml & build-ocaml-doc

---

.github/workflows/ci_bindings_ocaml.yml
.github/workflows/ci_bindings_python.yml
.github/workflows/docs.yml

Related to https://github.com/ocaml/setup-ocaml/issues/872
Fix ocaml and python CI.

ci: Fix failing CI on ocaml and python

---

.github/workflows/ci_bindings_python.yml

ci: Remove not needed --break-system-packages

---

bindings/java/src/executor.rs

This refers to https://github.com/apache/opendal/issues/5088.
Let's try to hard code the threads as `format!("opendal-tokio-worker-{}", id)` first.
cc @BaurzhanSakhariev

feat(binding/java): prefix thread name with opendal-tokio-worker

---

bin/oay/Cargo.lock
bin/oay/Cargo.toml
bin/ofs/Cargo.lock
bin/oli/Cargo.lock
core/Cargo.lock
core/Cargo.toml
core/edge/s3_read_on_wasm/src/lib.rs
core/src/services/ftp/reader.rs
core/src/services/ftp/writer.rs
core/src/services/surrealdb/backend.rs

Part of https://github.com/apache/opendal/issues/5203

deps: Bump deps of core to prepare for release

---

website/community/release/release.md

website: Fix format of release docs

---

integrations/compat/Cargo.toml

fix: add all-features flag for opendal_compat doc build

---

integrations/compat/src/v0_50_to_v0_49.rs

Follow up of https://github.com/apache/opendal/issues/5235

fix(integration/compat): Fix opendal 0.50 OpList has new field

---

bindings/c/CMakeLists.txt
bindings/c/README.md

chore: tidy up c binding build and docs

---

bindings/python/Cargo.toml
bindings/python/pyproject.toml
bindings/python/src/file.rs
bindings/python/src/lister.rs
bindings/python/src/operator.rs

build(binding/python): Support Python 3.13

---

bindings/python/tests/test_pickle.py

pickle is a builtin format in Python for object serialization and deserialization.
The PR add a test to ensure the `File` implementation is compatible with `pickle.[dump/load]`

test(bindings/python): add test for pickle streaming load/write

---

.asf.yaml

Follow up of https://github.com/apache/opendal/pull/5288

ci: Allow force push for `gh-pages`

---

bindings/java/pom.xml

build(bindings/java): fix lombok process

---

core/src/services/s3/backend.rs

None
According to https://github.com/apache/opendal/issues/5219, we'll add CapabilityCheckLayer to resolve similar issues.

chore(services/s3): remove versioning check for s3

---

website/community/maturity.md

chore: Update maturity.md

---

integrations/unftp-sbe/src/lib.rs

fix(services/unftp): add `/` when not presented

---

core/src/services/obs/backend.rs

Closes #5398.
add huawei.com to obs host
no

fix(services/obs): support huawei.com

---

website/community/committers/onboarding.md

None
`news.md` has been dropped in https://github.com/apache/opendal/pull/4578

chore(website): remove outdated description

---

bindings/go/README.md

docs(golang): remove unused pkg

---

core/src/layers/otelmetrics.rs

- Allow user to designate meter name

feat(layer/otelmetrics): take meter when register

---

README.md

docs: Add docs on how to pronounce opendal

---

.github/scripts/test_behavior/plan.py

None
Skip running behavior tests when adding or modifying documentation.
None

ci: skip running behavior tests when adding or modifying documentation

---

.vscode/settings.json

Signed-off-by: xxchan <xxchan22f@gmail.com>
Closes #.

chore: add oli/oay/ofs to rust-analyzer.linkedProjects

---

core/src/layers/logging.rs

Signed-off-by: xxchan <xxchan22f@gmail.com>
Closes #.

fix(logging): remove additional space

---

README.md

Inadvertently put CrateDB under wrong section
Minor change to reflect actual usage, moving to the correct section
No

Move CrateDB to the correct section

---

CHANGELOG.md

chore: add changelog for 0.51.2

---

.github/workflows/ci_bindings_haskell.yml
.github/workflows/release_python.yml
website/community/release/release.md

https://github.com/apache/opendal/actions/runs/13099438434/job/36545844546

ci: upgrade upload and download artifact actions

---

.github/workflows/ci_bindings_nodejs.yml
.github/workflows/ci_check.yml
.github/workflows/docs.yml
.github/workflows/test_behavior_binding_nodejs.yml

Related to:
- https://github.com/nodejs/corepack/issues/612#issuecomment-2631462297
- https://vercel.com/guides/corepack-errors-github-actions
- https://github.com/actions/setup-node/issues/1222

ci: Fix bad corepack cannot find matching keyid

---

core/src/services/gcs/core.rs

Closes https://github.com/apache/opendal/issues/5613

fix(services/gcs): Fix content encoding can't be used alone

---

.github/workflows/ci_bindings_go.yml
bin/ofs/Cargo.lock
bin/oli/Cargo.lock
core/Cargo.lock
core/Cargo.toml
core/src/layers/tracing.rs

build: upgrade opentelemetry dependencies to 0.28.0

---

core/src/docs/upgrade.md

Add upgrade docs for upcoming 0.52

docs: Add upgrade docs for upcoming 0.52

---

.github/workflows/ci_bindings_nodejs.yml

Follow up of https://github.com/apache/opendal/issues/5640

ci: Try fix nodejs CI

---

.github/workflows/ci_bindings_nodejs.yml

Fix failed CI: https://github.com/apache/opendal/actions/runs/13405730987/job/37445224396

ci: Skip corepack checks until next nodejs version

---

bindings/python/src/errors.rs

Closes #5511.
better error message.

feat(bindings/python) detailed error message

---

integrations/virtiofs/src/virtiofs.rs

chore: Fix clippy for rust edition 2024

---

bindings/python/src/operator.rs
bindings/python/src/options.rs
core/src/types/operator/operator_functions.rs

Add user metadata support for write so python users can use user metadata too.

feat(bindings/python): Add user metadata support for write

---

core/src/services/gcs/backend.rs

Follow up https://github.com/apache/opendal/pull/5658

fix(services/gcs): Fix cache control not present in object meta

---

bindings/python/python/opendal/__init__.pyi
bindings/python/src/capability.rs
bindings/python/src/operator.rs

Closes <https://github.com/apache/opendal/discussions/5423>.
add python binding for presign_delete
user now can use presign_delete

feat(bindings/python): add python presign_delete

---

core/src/services/s3/backend.rs
core/src/services/s3/core.rs

Part of https://github.com/apache/opendal/issues/5480

refactor: Migrate s3 services to context based http client

---

core/src/services/oss/backend.rs
core/src/services/oss/core.rs

refactor: Migrate oss services to context based http client

---

core/src/services/oss/core.rs
core/src/services/oss/delete.rs

fix(services/oss): fix batch delete with version for oss

---

core/src/services/obs/backend.rs
core/src/services/obs/core.rs

refactor: Migrate obs services to context based http client

---

core/src/services/cos/backend.rs
core/src/services/cos/core.rs

refactor: Migrate cos services to context based http client

---

core/src/services/oss/backend.rs
core/src/services/oss/core.rs
core/src/services/oss/writer.rs
core/src/types/capability.rs
core/tests/behavior/async_write.rs
core/tests/behavior/blocking_write.rs

feat(services/oss): Implement `Write Returns Metadata` for oss

---

.github/workflows/ci_bindings_zig.yml
bindings/zig/.gitignore
bindings/zig/CONTRIBUTING.md
bindings/zig/README.md
bindings/zig/build.zig
bindings/zig/build.zig.zon

None
Port to latest zig version: https://ziglang.org/download/0.14.0/release-notes.html
No

ci(bindings/zig): update to zig version 0.14.0

---

core/Cargo.lock
core/Cargo.toml

chore: update mongodb version drop the fixme comments

---

core/src/services/cos/backend.rs
core/src/services/cos/core.rs
core/src/services/cos/writer.rs

Part of https://github.com/apache/opendal/issues/5557

services/cos: Implement Write Returns Metadata for cos

---

.github/actions/test_behavior_binding_python/action.yaml
.github/workflows/test_behavior_binding_python.yml
bin/oli/dev/config.toml
bin/oli/dev/suite.toml
bindings/python/CONTRIBUTING.md
bindings/python/README.md
bindings/python/pyproject.toml
bindings/python/uv.lock

feat: adopt uv for python binding

---

core/src/services/cos/backend.rs
core/src/services/cos/core.rs
core/src/services/cos/writer.rs

This reverts commit 5194625a5389d3af4ee41130e90d51b587c1a020.
This commit doesn't work well on real cos services, let's revert it and bring it back after fix.

chore: revert "services/cos: Implement Write Returns Metadata for cos"

---

.github/workflows/ci_bindings_c.yml
.github/workflows/ci_bindings_cpp.yml
.github/workflows/ci_bindings_dotnet.yml
.github/workflows/ci_bindings_lua.yml
.github/workflows/ci_bindings_nodejs.yml
.github/workflows/ci_bindings_python.yml
bindings/c/src/operator.rs
bindings/lua/src/lib.rs
bindings/nodejs/src/lib.rs

Follow the comment in https://github.com/apache/opendal/pull/5708#pullrequestreview-2669216589
this patch add clippy to some of the bindings
and make the clippy happy of them
Also found some api had changed for them, this patch does not change them instead of add `FIXME` comment
for later discuss or fix
---
update, the comment drop maybe fix them later

ci: add clippy to some of the binding check ci

---

bindings/java/src/test/java/org/apache/opendal/test/behavior/RegressionTest.java

test(java): avoid run heavy RegressionTest always

---

website/DEPENDENCIES.node.csv
website/docusaurus.config.js
website/package.json
website/plugins/image-ssr-plugin.js
website/pnpm-lock.yaml

ASF INFRA don't allow us to refer external images.
This plugin will download all images locally and rewrite HTML while building.

website: Download all images to local and rewrite the url in html

---

website/plugins/image-ssr-plugin.js

This PR will fix the svg images not downloaded correctly.

fix(website): Handling svg image correctly

---

bindings/java/README.md
bindings/python/README.md

website: Fix links of bindings user

---

.github/workflows/ci_bindings_dart.yml
bindings/dart/rust/Cargo.toml

Closes #5728.
pin the version
no

fix(binding/dart): pin version to avoid generator/runtime version mismatch

---

bindings/java/README.md
bindings/nodejs/README.md
bindings/python/README.md
core/README.md

None
Add useful links in docs.

docs: Add useful links

---

.github/workflows/ci_bindings_dart.yml
bindings/dart/README.md
bindings/dart/examples/basic.dart
bindings/dart/lib/opendal.dart
bindings/dart/tests/opendal_test.dart

part of https://github.com/apache/opendal/issues/5722#issuecomment-2713000972 .
change the api name.

feat(binding/dart): hide init && change to init

---

bindings/java/src/executor.rs

bring back the code by false delete, add ignore for mut.

fix(bindings/java): bring back false delete code

---

dev/Cargo.lock
dev/Cargo.toml

follow this article which is faster and not depend cmake 
https://trifectatech.org/blog/zlib-rs-is-faster-than-c/

chore: update flate2 version

---

core/src/services/b2/backend.rs
core/src/services/b2/core.rs
core/src/services/b2/writer.rs
core/src/types/capability.rs
core/tests/behavior/async_write.rs
core/tests/behavior/blocking_write.rs

feat(core): Implement write returns metadata for b2

---

website/community/pmc_members/nominate-committer.md
website/community/pmc_members/nominate-pmc-member.md

docs: Update nominate-committer.md

---

core/src/services/github/backend.rs
core/src/services/github/core.rs

refactor: Migrate github services to context based http client

---

bindings/c/README.md
bindings/cpp/README.md
bindings/d/README.md
bindings/dotnet/README.md
bindings/go/README.md
bindings/haskell/README.md
bindings/java/README.md
bindings/lua/README.md
bindings/nodejs/README.md
bindings/ocaml/README.md
bindings/php/README.md
bindings/python/README.md
bindings/ruby/README.md
bindings/swift/README.md
bindings/zig/README.md
website/docs/20-bindings/c.mdx
website/docs/20-bindings/cpp.mdx
website/docs/20-bindings/d.mdx
website/docs/20-bindings/dart.mdx
website/docs/20-bindings/dotnet.mdx
website/docs/20-bindings/haskell.mdx
website/docs/20-bindings/lua.mdx
website/docs/20-bindings/ocaml.mdx
website/docs/20-bindings/php.mdx
website/docs/20-bindings/ruby.mdx
website/docs/20-bindings/swift.mdx
website/docs/20-bindings/zig.mdx

Closes #5749
- Adding a WIP icon to the list
- Modify the url of the status-unreleased icon to point to the current page to prevent scaling
- Modify the url of the status-released icon to point to its corresponding package address

feat(website): Adding a WIP to the list of bingdings

---

website/docusaurus.config.js

Closes #5757
- Added `try...catch` block to handle potential errors from `git describe`.

fix(website): docusaurus build on windows

---

website/docusaurus.config.js

website: Add trailing slash to fix images not showed up correctly

---

core/src/services/onedrive/core.rs

fix(services/onedrive): add scope for the refresh token

---

core/src/services/gcs/backend.rs
core/src/services/gcs/core.rs

refactor(gcs): Migrate to context based http client

---

core/src/services/obs/lister.rs

services/obs: make list return the path itself

---

bindings/python/benchmark/async_opendal_benchmark.py
bindings/python/benchmark/async_origin_s3_benchmark_with_gevent.py
bindings/python/pyproject.toml
bindings/python/uv.lock

Closes #5785
also chore the dependencies versions

fix: py binding benchmark can not run

---

core/examples/README.md

Closes #5781 by adding the / to the dir if do not have one

doc: fix README root wrong for example close issue #5871 by correct README

---

core/src/layers/await_tree.rs
core/src/layers/capability_check.rs
core/src/layers/correctness_check.rs
core/src/layers/error_context.rs
core/src/layers/fastrace.rs
core/src/layers/logging.rs
core/src/layers/observe/metrics.rs
core/src/layers/timeout.rs
core/src/raw/operation.rs
core/src/services/ftp/backend.rs
core/src/services/ftp/delete.rs

Closes https://github.com/apache/opendal/issues/5788
See https://github.com/apache/opendal/issues/5788

refactor(core/raw)!: Merge blocking and async operations

---

core/src/services/s3/core.rs

Part of https://github.com/apache/opendal/issues/5774
See https://github.com/apache/opendal/issues/5774
Add operation in http context
None.

feat(services/s3): Add operation in http context

---

core/src/services/onedrive/docs.md

Closes #4715.
Add documentation for how to get onedrive tokens as a quick start.
Add docs of steps to setup Microsoft Entra ID Application.
no

docs(services/onedrive): add how to get tokens

---

core/src/layers/otelmetrics.rs

feat(core): Implement http related metrics support for otel

---

core/Cargo.lock
core/Cargo.toml
core/src/services/compfs/backend.rs
core/src/services/compfs/writer.rs

Closes #5801.
* Fix `behavior::test_write*` tests.
* Also updated compio to the latest version.
Yes.

fix(services/compfs): behavior async write

---

core/src/docs/rfcs/3911_deleter_api.md

doc: fix typo in RFC md

---

core/src/services/compfs/backend.rs
core/src/services/compfs/delete.rs
core/src/services/compfs/lister.rs
core/src/services/compfs/reader.rs

* Recursive path for write, copy, rename: create parent dir before writing.
* Delete: return Ok if not exists.
* Read: fix range calculation logic.
* Lister: follow requirements of the trait.

fix(services/compfs): read, delete, copy, rename

---

website/docusaurus.config.js

Closes https://github.com/apache/opendal/issues/5804
Also fix https://github.com/apache/opendal/pull/5787
See  https://github.com/apache/opendal/issues/5804
Use expaned links of discord.

website: Fix links to join in discord

---

website/plugins/image-ssr-plugin.js

fix https://github.com/apache/opendal/pull/5771

website: Try fix external images in client route

---

core/src/services/azfile/backend.rs
core/src/services/azfile/core.rs

refactor: Migrate azfile services to context based http client

---

.github/workflows/ci_weekly_update.yml

Follow up of https://github.com/apache/opendal/pull/5818

chore(github): Fix uv not installed in weekly-update

---

core/src/services/dropbox/builder.rs
core/src/services/dropbox/core.rs

refactor: Migrate dropbox services to context based http client

---

core/src/services/huggingface/core.rs

Part of https://github.com/apache/opendal/issues/5774

feat(services/huggingface): Add operation in http context

---

core/src/services/upyun/backend.rs
core/src/services/upyun/core.rs

refactor: Migrate upyun services to context based http client

---

.github/workflows/ci_bindings_ruby.yml
bindings/ruby/README.md
bindings/ruby/src/capability.rs
bindings/ruby/src/io.rs
bindings/ruby/src/lib.rs
bindings/ruby/src/lister.rs
bindings/ruby/src/operator.rs

This path try to make ruby binding clippy and do these other things:
- add clippy check to ruby binding like others
- fix build unused import
- fix all the clippy unhappy things
- fix test command is wrong, which should be `bundle exec rake test`

chore: make ruby clippy happy

---

core/src/raw/oio/write/multipart_write.rs
core/src/services/b2/backend.rs
core/src/services/cos/backend.rs
core/src/services/gcs/backend.rs
core/src/services/obs/backend.rs
core/src/services/oss/backend.rs
core/src/services/s3/backend.rs
core/src/services/upyun/backend.rs
core/src/services/vercel_blob/backend.rs

Closes https://github.com/apache/opendal/issues/5832.
Migrate MultipartWrite Executor to context based

refactor(core): Migrate MultipartWrite Executor to context based

---

core/src/raw/oio/write/position_write.rs
core/src/services/fs/backend.rs

Closes https://github.com/apache/opendal/issues/5833
Migrate PositionWrite Executor to context based

refactor(core): Migrate PositionWrite Executor to context based

---

bindings/java/src/async_operator.rs
bindings/java/src/convert.rs
bindings/java/src/main/java/org/apache/opendal/AsyncOperator.java
bindings/java/src/main/java/org/apache/opendal/ListOptions.java
bindings/java/src/main/java/org/apache/opendal/NativeLibrary.java
bindings/java/src/main/java/org/apache/opendal/WriteOptions.java
bindings/java/src/operator.rs

refactor: tidy binding java code

---

core/src/services/yandex_disk/backend.rs
core/src/services/yandex_disk/core.rs

refactor: Migrate yandex_disk services to context based http client

---

core/src/services/alluxio/backend.rs
core/src/services/alluxio/core.rs

refactor: Migrate alluxio services to context based http client

---

core/src/services/b2/backend.rs
core/src/services/b2/core.rs

refactor: Migrate b2 service to context based http client

---

core/src/layers/prometheus.rs

feat(core/layers): implement http related metrics support for prometheus

---

core/src/layers/metrics.rs

feat(core/layers): implement http related metrics support for metrics

---

bindings/README.md
bindings/d/README.md
bindings/dotnet/README.md
bindings/zig/README.md

doc for building .NET binding
also fix two docs(which maybe typo)

doc: dotnet binding wip doc

---

core/src/services/azblob/backend.rs
core/src/services/azblob/core.rs
core/src/services/azblob/writer.rs
core/src/services/ghac/writer.rs

Closes https://github.com/apache/opendal/issues/5480 .

refactor: migrate azblob services to context based http client

---

bin/oli/README.md
bin/oli/dev/config.toml

Closes #5609
this patch follow issue #5609 add doc in oli README.
the oli bench command from https://github.com/apache/opendal/pull/5443
and mention the doc needed in 5609,  this patch support it.
and for users not install from source, bring the example from oli/dev instead of link
also fix a port from 9900 -> 9000

doc: add oli bench command doc

---

core/fuzz/README.md
core/tests/behavior/README.md

Closes #4614
This patch is the same as  #5782
and found not only for behavior but also for fuzz, this patch also fix it

doc: fix all fs env tmp file dir in doc

---

core/src/services/gdrive/backend.rs
core/src/services/gdrive/builder.rs
core/src/services/gdrive/core.rs

refactor: Migrate gdrive service to context based http client

---

core/src/services/pcloud/backend.rs
core/src/services/pcloud/core.rs

refactor: Migrate pcloud service to context based http client

---

core/src/services/vercel_artifacts/backend.rs
core/src/services/vercel_artifacts/builder.rs
core/src/services/vercel_artifacts/core.rs
core/src/services/vercel_artifacts/error.rs
core/src/services/vercel_artifacts/mod.rs
core/src/services/vercel_artifacts/writer.rs

Part of https://github.com/apache/opendal/issues/5702
This pull request refactors the `VercelArtifactsBackend` by introducing a new `VercelArtifactsCore` struct to encapsulate the core functionality and state. The changes aim to improve code organization and maintainability.

refactor: Introduce VercelArtifactsCore for improved service structure

---

core/src/raw/path.rs
core/src/services/onedrive/backend.rs
core/src/services/onedrive/builder.rs
core/src/services/onedrive/config.rs
core/src/services/onedrive/core.rs
core/src/services/onedrive/delete.rs
core/src/services/onedrive/docs.md
core/src/services/onedrive/error.rs
core/src/services/onedrive/graph_model.rs
core/src/services/onedrive/lister.rs
core/src/services/onedrive/writer.rs

Part of #5557.
Part of #2611.
Also, add a few features:
- copy
- stats ETag
- rename
- write returns metadata
- list with limit
- versions
- write with If-Match
Mostly for the issues and to implement:
- General improvements to the OneDrive service
- Weekend learning :)
I implemented features that I found easy to get to. Also, this PR addresses a few nuances about OneDrive API, including:
- Some APIs require a particular `Content-Type`
- A few bug fixes
Added a new option and doc.
Sorry about making many changes across the OneDrive service, which makes this PR difficult to review. I made some efforts in structuring the change in a few commits. Reviewing this PR commit by commit is easier.
Also kudos to Microsoft's services I guess - they didn't ban me. I saw the behavior tests generated a …

feat(services/onedrive): implement additional OneDrive features

---

core/src/raw/accessor.rs

fix: todo list since MSRV is 1.80

---

core/src/services/vercel_artifacts/builder.rs
core/src/services/vercel_artifacts/core.rs

refactor: Migrate vercel_artifacts service to context based http client

---

core/src/services/azdls/backend.rs
core/src/services/azdls/core.rs
core/src/services/ghac/backend.rs
core/src/services/ghac/core.rs
core/src/services/ghac/writer.rs
core/src/services/huggingface/backend.rs
core/src/services/huggingface/core.rs
core/src/services/koofr/backend.rs
core/src/services/koofr/core.rs
core/src/services/lakefs/backend.rs
core/src/services/lakefs/core.rs
core/src/services/seafile/backend.rs
core/src/services/seafile/core.rs
core/src/services/swift/backend.rs
core/src/services/swift/core.rs
core/src/services/vercel_blob/backend.rs
core/src/services/vercel_blob/core.rs
core/src/services/webdav/backend.rs
core/src/services/webdav/core.rs

- ghac
- koofr
- vercel_blob
- huggingface
- lakefs
- seafile
- swift
- webdav
- azdls

refactor: Migrate services to context based http client

---

.github/workflows/ci_bindings_dart.yml
bindings/dart/lib/opendal.dart
bindings/dart/lib/src/rust/api/opendal_api.dart
bindings/dart/lib/src/rust/frb_generated.dart
bindings/dart/rust/src/api/opendal_api.rs
bindings/dart/rust/src/frb_generated.rs

This path is a breaking and do these things:
- clippy and build happy for dart
- add clippy to ci
- support macos
- change api isExists to exists dart is the same more: https://api.flutter.dev/flutter/dart-io/FileSystemEntity/exists.html

refactor(bindings/dart)!: support macos and use exists api

---

bindings/python/python/opendal/__base.pyi

This patch update py binding api using  `just generate python`

chore: update py binding api just

---

core/src/layers/metrics.rs

Closes #5888 
Part of #5883 
Migrate MetricsLayer to support IO metrics

refactor(layer/metrics): Migrate MetricsLayer to support IO metrics

---

core/src/layers/prometheus.rs

Closes #5890 
Part of #5883 
Migrate PrometheusLayer to support IO metrics

refactor(layer/prometheus): Migrate PrometheusLayer to support IO metrics

---

core/src/layers/observe/metrics.rs

Part of #5848 
improve #5883 
- remove some duplicated observations
- add some missing observations
- remove useless clone

refactor(observe): remove duplicated observation

---

examples/cpp/CMakeLists.txt

This patch update cpp example which is kind of out date and can not run success for now.

chore: update cpp example

---

.github/workflows/ci_weekly_update.yml

fix: close issue #5910

---

core/src/layers/complete.rs
core/src/services/b2/backend.rs
core/src/services/cos/backend.rs
core/src/services/fs/backend.rs
core/src/services/monoiofs/core.rs
core/src/services/onedrive/builder.rs
core/src/services/onedrive/writer.rs
core/src/services/oss/backend.rs
core/src/services/s3/backend.rs
core/src/types/capability.rs
core/tests/behavior/async_write.rs
core/tests/behavior/blocking_write.rs

refactor(core): Remove all `write_has_xxx`  capabilities

---

core/src/services/obs/backend.rs
core/src/services/obs/config.rs
core/src/services/obs/core.rs
core/src/services/obs/writer.rs

refactor(services/obs): Implement Write Returns Metadata for obs

---

core/src/docs/upgrade.md
core/src/types/operator/builder.rs
core/src/types/operator/operator.rs
integrations/parquet/upgrade.md

Part of https://github.com/apache/opendal/issues/5917
Add upgrade guide for opendal rust core.

docs: Add docs on how to upgrade to opendal rust core 0.53

---

CHANGELOG.md

Part of https://github.com/apache/opendal/issues/5917

docs: Update changelogs for v0.53.0

---

bin/ofs/tests/file.rs
core/src/layers/capability_check.rs

None
chore: Fix clippy for rust 1.86

chore: Fix clippy for rust 1.86

---

core/CONTRIBUTING.md

doc: add doc for unit tests and doc tests close #5932

---

core/src/services/ipmfs/lister.rs

Improve error handling and directory listing behavior in `lister` to pass behavior tests.
No

fix(services/ipmfs): fix Ipmfs behavior tests

---

core/src/services/azblob/backend.rs
core/src/services/azblob/core.rs
core/src/services/azblob/writer.rs

feat(services/azblob): implement write returns metadata

---

core/src/services/azblob/core.rs

- related to https://github.com/apache/opendal/issues/5976

chore(service/azblob): use QueryPairsWriter for url write

---

core/src/services/ipmfs/backend.rs
core/src/services/ipmfs/builder.rs
core/src/services/ipmfs/core.rs
core/src/services/ipmfs/delete.rs
core/src/services/ipmfs/lister.rs
core/src/services/ipmfs/mod.rs
core/src/services/ipmfs/writer.rs

Part of #5702
Part of #5677 
- This pull request refactors the `IpmfsBackend` by introducing a new `IpmfsCore` struct to encapsulate the core functionality and state. The changes aim to improve code organization and maintainability. 
- Use the http_client from AccessorInfo, instead of directly accessing the backend, to migrate the service to a context-based http client.
No
<details>
<summary>cargo test behavior --features tests,services-ipmfs -- --show-output</summary>
```
Finished `test` profile [unoptimized + debuginfo] target(s) in 1.19s
Running unittests src\lib.rs (target\debug\deps\opendal-bcda60b7dff17fe0.exe)
running 0 tests
successes:
successes:
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 133 filtered out; finished in 0.00s
Running tests\behavior\main.rs …
```

refactor: Introduce IpmfsCore for improved service structure

---

.github/workflows/docs.yml

ci: python doc build also use uv

---

core/src/raw/http_util/uri.rs
core/src/services/cos/core.rs

chore(services/cos): Use QueryPairsWriter for url write

---

core/src/services/azdls/core.rs

- related to https://github.com/apache/opendal/issues/5976

chore(service/azdls): use QueryPairsWriter for url write

---

core/src/services/obs/core.rs

chore(services/obs): Use QueryPairsWriter for url write

---

core/src/services/oss/core.rs

chore(services/oss): Use QueryPairsWriter for url write

---

core/src/services/swift/core.rs

chore(services/swift): Use QueryPairsWriter for url write

---

core/src/services/gdrive/core.rs
core/src/services/oss/core.rs

chore(services/gdrive): Use QueryPairsWriter for url write

---

core/src/services/azfile/core.rs

chore(core): Fix clippy for services azfile

---

bindings/nodejs/generated.d.ts
bindings/nodejs/src/lib.rs
bindings/nodejs/tests/suites/async.suite.mjs
bindings/nodejs/tests/suites/sync.suite.mjs

feat(bindings/nodejs): add check in js

---

core/src/services/b2/core.rs

closes https://github.com/apache/opendal/issues/5997

fix(services/b2): Don't include prefix is it's empty

---

bindings/go/README.md

This PR improves the developer documentation by adding guidelines for Windows platform development and optimizing it for Linux.
P.S. I don't have macOS, so I'm unable to write and test an executable guide for it. Additional details are welcome! :)

doc(bindings/go): Improve developer guide.

---

core/src/layers/tracing.rs

Closes https://github.com/apache/opendal/issues/5999
Implement tracing correctly.
Better DX.

refactor(layers/tracing): Ensure the entire async function been traced

---

bindings/python/pyproject.toml

Follow up of https://github.com/apache/opendal/pull/6003

docs: Fix links to bindings python

---

bindings/python/docs/api.md
bindings/python/docs/api/async_file.md
bindings/python/docs/api/async_operator.md
bindings/python/docs/api/file.md
bindings/python/docs/api/metadata.md
bindings/python/docs/api/operator.md
bindings/python/mkdocs.yml
bindings/python/python/opendal/__init__.pyi

Split API references in multiple files to better discover

docs(bindings/python): Split API in multiple files to better discover

---

bindings/python/README.md
bindings/python/upgrade.md

doc: fix python binding doc which changed

---

bindings/python/README.md
bindings/python/upgrade.md

Closes #.
roll back some mistake https://github.com/apache/opendal/pull/6008#discussion_r2040531716

doc: roll back some wrong format

---

core/src/docs/performance/concurrent_write.md
core/src/docs/performance/mod.rs
core/src/lib.rs

Part of https://github.com/apache/opendal/issues/4121
Add performance guide for concurrently write.

docs(core): Add performance guide for concurrent write

---

CONTRIBUTING.md
bindings/java/README.md

Just obsessive compulsive disorder🥵

docs(bindings/java): improve document format

---

core/src/types/buffer.rs

Closes https://github.com/apache/opendal/issues/5915
Implement `io::{Read,BufRead,Seek}` for Buffer so that Buffer can be used in more places.
Implement `io::Read` for Buffer.

feat(core): Implement io::{Read,Seek,BufRead} for Buffer

---

core/src/docs/performance/concurrent_write.md

In response to https://github.com/apache/opendal/pull/6011#pullrequestreview-2763437066

docs: Polish perf docs for concurrent write

---

core/src/docs/performance/http_optimization.md
core/src/docs/performance/mod.rs

Part of https://github.com/apache/opendal/issues/4121
Add performance guide for http optimization

docs: Add performance guide http optimization

---

bindings/nodejs/index.js
bindings/nodejs/package.json
bindings/nodejs/pnpm-lock.yaml
bindings/nodejs/scripts/header.js
bindings/nodejs/theme/index.tsx
bindings/nodejs/tsconfig.theme.json
bindings/nodejs/typedoc.json

- Fix broken links in nodejs binding docs:
- [Upgrade Guide](https://opendal.apache.org/docs/nodejs/upgrade.md)
- [Contributing Guide](https://opendal.apache.org/docs/nodejs/CONTRIBUTING.md)
- Fix the header for mobile page views
| before| after|
| --- | --- |
|<img src="https://github.com/user-attachments/assets/1e378972-b6b1-4695-b347-eea270e20dd1" width="281" height="500"> | <img src="https://github.com/user-attachments/assets/d9f03478-500d-4091-ae69-c66ea0489144" width="281" height="500">|
- Updated `typedoc` version from `^0.25` to `^0.28`
- Improve `typedoc` config to include the missing docs
- Refactor `FooterWithASFCopyright`

docs(bindings/nodejs): fix broken links

---

NOTICE

doc(chore): update copyright date in NOTICE

---

CHANGELOG.md
bin/oay/Cargo.lock
bin/oay/DEPENDENCIES.rust.tsv
bin/ofs/Cargo.lock
bin/ofs/DEPENDENCIES.rust.tsv
bin/oli/Cargo.lock
bin/oli/DEPENDENCIES.rust.tsv
bindings/c/DEPENDENCIES.rust.tsv
bindings/cpp/DEPENDENCIES.rust.tsv
bindings/dotnet/DEPENDENCIES.rust.tsv
bindings/haskell/DEPENDENCIES.rust.tsv
bindings/java/DEPENDENCIES.rust.tsv
bindings/lua/DEPENDENCIES.rust.tsv
bindings/nodejs/DEPENDENCIES.rust.tsv
bindings/ocaml/DEPENDENCIES.rust.tsv
bindings/php/DEPENDENCIES.rust.tsv
bindings/python/DEPENDENCIES.rust.tsv
bindings/ruby/DEPENDENCIES.rust.tsv
core/DEPENDENCIES.rust.tsv
integrations/cloud_filter/DEPENDENCIES.rust.tsv
integrations/dav-server/DEPENDENCIES.rust.tsv
integrations/fuse3/DEPENDENCIES.rust.tsv
integrations/object_store/DEPENDENCIES.rust.tsv
integrations/parquet/DEPENDENCIES.rust.tsv
integrations/unftp-sbe/DEPENDENCIES.rust.tsv
integrations/virtiofs/DEPENDENCIES.rust.tsv

Part of https://github.com/apache/opendal/issues/6021

Bump to version 0.53.1 Round 2

---

bindings/go/README.md

The build and test script of go binding for Linux is broken. Let's fix it.

doc(bindings/go): fix broken script

---

.github/scripts/test_behavior/plan.py
bindings/c/src/operator.rs

feat(bindings/c): enable RetryLayer by default

---

bindings/python/CONTRIBUTING.md

docs(chore): add a specific python test description

---

core/src/services/gcs/core.rs

feat(services/gcs): Add operation in http context

---

core/src/services/dropbox/core.rs

feat(services/dropbox): Add operation in http context

---

core/src/services/azfile/core.rs

feat(services/azfile): Add operation in http context

---

core/src/services/http/core.rs

feat(services/http): Add operation in http context

---

core/src/services/oss/core.rs

feat(services/oss): Add operation in http context

---

core/src/services/s3/backend.rs

feat: propagate disable_list_objects_v2 to S3Builder

---

core/src/services/cos/core.rs

feat(services/cos): Add operation in http context

---

core/src/services/github/core.rs

Relates to https://github.com/apache/opendal/issues/5774

feat(services/github):  Add operation in http context

---

core/src/services/s3/backend.rs
core/src/services/s3/config.rs
core/src/services/s3/core.rs
core/src/services/s3/docs.md

Closes #5694 .
See the issue.
See the issue.
It exposes a new option in the builder. 
AWS returns `x-amz-request-charged:requester` when the request has been billed to the client.
We don't surface it.

feat(services/s3): Support request payer option

---

bindings/python/Cargo.toml
bindings/python/python/opendal/layers.pyi
bindings/python/src/layers.rs
bindings/python/src/lib.rs
bindings/python/tests/conftest.py

None
The change export [docs.rs/opendal/latest/opendal/layers/struct.MimeGuessLayer.html](https://docs.rs/opendal/latest/opendal/layers/struct.MimeGuessLayer.html) via Python binding.
This pull request export MimeGuessLayer via Python binding
None

feat(bindings/python): export MimeGuessLayer

---

core/src/services/obs/core.rs

Relates to https://github.com/apache/opendal/issues/5774

feat(services/obs): Add operation in http context

---

scripts/constants.py

Closes #.
These code seems unused after https://github.com/apache/opendal/pull/5592

chore: delete unused code in scripts

---

core/src/services/pcloud/core.rs

feat(services/pcloud): Add operation http context

---

core/src/services/vercel_artifacts/core.rs

feat(services/vercel_artifacts): Add operation http context

---

core/src/services/webdav/core.rs

feat(services/webdav): Add operation in http context

---

core/src/services/swift/core.rs

feat(services/swift): Add operation in http context

---

core/src/services/azblob/core.rs
core/src/services/azblob/writer.rs

Refactored some write functions to be consistent with other functions in the service. For example: 
https://github.com/jorgehermo9/opendal/blob/fc2d7a54eebe38cdb79a19420ce3a08e4a008461/core/src/services/azblob/writer.rs#L145

refactor(services/azblob): Refactor raw request send in writer

---

core/src/services/vercel_blob/core.rs
core/src/services/vercel_blob/writer.rs

feat(services/vercel_blob): Add operation in http context

---

core/src/services/koofr/core.rs

feat(services/koofr): Add operation http context

---

core/src/services/webhdfs/core.rs

feat(services/webhdfs): Add operation in http context

---

core/src/services/onedrive/core.rs

feat(services/onedrive): Add operation in http context

---

core/src/services/onedrive/writer.rs

Amends #6087.
Add comment for memo.
A doc comment.
No.

doc(services/onedrive): add a comment about onedrive's writer 

---

core/src/services/azblob/core.rs

Part of #5774.
No.
Inviting @jorgehermo9 for a review since you worked on this just now.

feat(services/azblob): add request context

---

bindings/c/include/opendal.h
bindings/c/src/reader.rs
bindings/c/tests/reader.cpp

Closes #6083.
Add seek support in c-binding.

feat(bindings/c): Add seek support for c-binding 

---

bindings/c/include/opendal.h
bindings/c/src/writer.rs
bindings/c/tests/bdd.cpp
bindings/go/ffi.go
bindings/go/write.go

refactor(bindings/c)!: extract the writer closing logic from opendal_writer_free

---

core/src/services/fs/backend.rs

Closes https://github.com/apache/opendal/issues/6178
As mentioned in issue.

fix(services/fs): Make fs services work on our MSRV

---

core/src/docs/rfcs/0429_init_from_iter.md

fix: typo error in 0429_init_from_iter.md

---

CHANGELOG.md
bin/oay/Cargo.lock
bin/oay/DEPENDENCIES.rust.tsv
bin/ofs/Cargo.lock
bin/ofs/DEPENDENCIES.rust.tsv
bin/oli/Cargo.lock
bin/oli/DEPENDENCIES.rust.tsv
bindings/c/DEPENDENCIES.rust.tsv
bindings/cpp/DEPENDENCIES.rust.tsv
bindings/dotnet/DEPENDENCIES.rust.tsv
bindings/haskell/DEPENDENCIES.rust.tsv
bindings/java/DEPENDENCIES.rust.tsv
bindings/lua/DEPENDENCIES.rust.tsv
bindings/nodejs/DEPENDENCIES.rust.tsv
bindings/ocaml/DEPENDENCIES.rust.tsv
bindings/php/DEPENDENCIES.rust.tsv
bindings/python/DEPENDENCIES.rust.tsv
bindings/ruby/DEPENDENCIES.rust.tsv
core/Cargo.lock
core/DEPENDENCIES.rust.tsv
integrations/cloud_filter/DEPENDENCIES.rust.tsv
integrations/dav-server/DEPENDENCIES.rust.tsv
integrations/fuse3/DEPENDENCIES.rust.tsv
integrations/object_store/DEPENDENCIES.rust.tsv
integrations/parquet/DEPENDENCIES.rust.tsv
integrations/unftp-sbe/DEPENDENCIES.rust.tsv
integrations/virtiofs/DEPENDENCIES.rust.tsv

Part of https://github.com/apache/opendal/issues/6185
Bring some new bug fix in this release.

Bump to opendal 0.53.3 Round 2

---

README.md

Closes #.
Add deepwiki badge to auto refresh the deepwiki weekly with the latest code.

chore: add deepwiki badge into readme to enable auto-refresh

---

bindings/php/Cargo.toml
bindings/php/src/lib.rs

Part of https://github.com/apache/opendal/issues/6190
Fix CI.

refactor: Fix build failure for php binding

---

core/Cargo.lock
core/Cargo.toml
core/src/services/etcd/backend.rs
core/src/services/ftp/core.rs
core/src/services/memcached/backend.rs
core/src/services/redis/core.rs
core/src/services/sftp/core.rs

Fixes #6117
Closes #6117 .
This update bb8 to version 0.9.0 and fixes the API changes to match bb8.
* Update to bb8 0.9.0
* Required code changes to build with bb8 0.9.0
No

chore: Update bb8 to version 0.9.0

---

website/docusaurus.config.js
website/package.json
website/pnpm-lock.yaml

Closes #5895.
- Added and configured my custom `docusaurus-plugin-llms-builder` plugin
- `llms.txt` and ‎`llms-full.txt` are now auto-generated by `docusaurus build`
But currently, I'm using the content from [`README.md`](https://github.com/apache/opendal/blob/main/README.md?plain=1#L1-L9) for the `title`, `description`, and `details`, which might not be comprehensive enough.

feat(website): Auto-generate llms.txt and llms-full.txt

---

bindings/nodejs/.gitignore
bindings/nodejs/benchmark/deno.ts
bindings/nodejs/benchmark/node.js
bindings/nodejs/package.json

Closes #.
Because of previous changes to index.js => index.mjs and index.cjs.
Fix the Node.js and Deno scripts in the bench.

fix(bindings/nodejs): update nodejs and deno bench

---

bin/oli/Cargo.toml
bin/oli/src/commands/edit.rs
bin/oli/src/commands/mod.rs
bin/oli/tests/integration/edit.rs
bin/oli/tests/integration/main.rs

 feat(bin/oli): support oli edit

---

CLAUDE.md

None
By providing CLAUDE.md, we can improve the experience for contributors working on opendal. AI agents will be able to offer more helpful suggestions based on this file.
AI generted CLAUDE.md file. It will maintained by AI Agent themselves.

docs: Add CLAUDE docs to make AI Agents happy

---

CLAUDE.md

docs: Polish claude file after some experiments

---

bin/oay/Cargo.lock
bin/ofs/Cargo.lock
bin/oli/Cargo.lock
core/Cargo.lock
core/Cargo.toml
core/src/services/moka/backend.rs
core/src/services/moka/config.rs
core/src/services/moka/core.rs
core/src/services/moka/docs.md
core/src/services/moka/mod.rs

Closes #.
Expose more moka configurations
add configure method to modify the moka::future::CacheBuilder

feat(services/moka): expose more moka configurations

---

core/src/layers/fastmetrics.rs
core/src/layers/prometheus.rs
core/src/layers/prometheus_client.rs

Close #.
Part of #6304 
- add global instance doc for PrometheusLayer
- add global instance doc for FastmetricsLayer
No

chore(metrics): add more docs about global instance of PrometheusLayer and FastmetricsLayer

---

bindings/nodejs/tests/suites/asyncStatOptions.suite.mjs
bindings/nodejs/tests/suites/syncStatOptions.suite.mjs

fix(nodejs): test stat with version

---

.github/workflows/ci_bindings_zig.yml

Fixes #6309
Use mlugg/setup-zig
No.

chore(ci): use mlugg/setup-zig instead of archvied action

---

core/src/services/mini_moka/backend.rs
core/src/services/mini_moka/config.rs
core/src/services/mini_moka/core.rs
core/src/services/mini_moka/delete.rs
core/src/services/mini_moka/lister.rs
core/src/services/mini_moka/mod.rs
core/src/services/mini_moka/writer.rs

refactor: Migrate mini_moka service to implement Access directly

---

.github/services/compfs/compfs/action.yml
bindings/java/Cargo.toml
bindings/nodejs/Cargo.toml
bindings/python/Cargo.toml

ci(services/compfs): add  integrtation tests for compfs service

---

.github/dependabot.yml

chore: Add npm to dependabot

---

core/src/services/dashmap/backend.rs
core/src/services/dashmap/config.rs
core/src/services/dashmap/core.rs
core/src/services/dashmap/delete.rs
core/src/services/dashmap/docs.md
core/src/services/dashmap/lister.rs
core/src/services/dashmap/writer.rs

refactor: Migrate dashmap service to implement Access directly

---

.github/dependabot.yml

fix #6333
two deps need to update together.

chore: add group dep for dependabot

---

bin/oay/DEPENDENCIES.rust.tsv
bin/ofs/DEPENDENCIES.rust.tsv
bin/oli/DEPENDENCIES.rust.tsv
bindings/c/DEPENDENCIES.rust.tsv
bindings/cpp/DEPENDENCIES.rust.tsv
bindings/dotnet/DEPENDENCIES.rust.tsv
bindings/haskell/DEPENDENCIES.rust.tsv
bindings/java/DEPENDENCIES.rust.tsv
bindings/lua/DEPENDENCIES.rust.tsv
bindings/nodejs/DEPENDENCIES.rust.tsv
bindings/ocaml/DEPENDENCIES.rust.tsv
bindings/php/DEPENDENCIES.rust.tsv
bindings/python/DEPENDENCIES.rust.tsv
bindings/ruby/DEPENDENCIES.rust.tsv
integrations/cloud_filter/DEPENDENCIES.rust.tsv
integrations/dav-server/DEPENDENCIES.rust.tsv
integrations/fuse3/DEPENDENCIES.rust.tsv
integrations/object_store/DEPENDENCIES.rust.tsv
integrations/parquet/DEPENDENCIES.rust.tsv
integrations/unftp-sbe/DEPENDENCIES.rust.tsv
integrations/virtiofs/DEPENDENCIES.rust.tsv
scripts/dependencies.py

chore: update DEPENDENCIES and fater dependencies.py generate

---

bindings/cpp/CMakeLists.txt
bindings/cpp/CONTRIBUTING.md
bindings/cpp/include/async_defs.hpp
bindings/cpp/include/data_structure.hpp
bindings/cpp/include/opendal.hpp
bindings/cpp/include/opendal_async.hpp
bindings/cpp/src/operator.cpp

reduce cpp binding dep
- Remove Boost dependency from CMake configuration and documentation
- Replace Boost.DateTime with std::chrono for timestamp handling
- Replace Boost.IOStreams with custom std::istream implementation for ReaderStream
- Update all header includes and modernize C++ usage

feat(bindings/cpp): remove Boost dependency

---

.github/dependabot.yml
core/Cargo.toml

Closes #6364.
I made some changes deliberately compared to the issues.
Dependabot frequency will take some iterations to adjust. Some criteria for the future:
1. If opened PR by Dependabot fails in CI: consider not to auto-update major version
2. Too many dependencies gets updated: consider breaking into more groups or increase schedule.interval.
No.

chore(dependabot): update OpenDAL dependencies less frequently

---

bin/oay/Cargo.lock
core/src/services/vercel_blob/backend.rs
core/src/services/vercel_blob/core.rs
core/src/services/vercel_blob/delete.rs

Closes #.
Implement delete support for vercel_blob
New feature support

feat(services/vercel_blob): add delete operator

---

.github/services/aliyun_drive/aliyun_drive/disable_action.yml
.github/services/azblob/azure_azblob/action.yml
.github/services/azdls/azdls/action.yml
.github/services/azfile/azfile/action.yml
.github/services/b2/b2/action.yml
.github/services/cos/cos/action.yml
.github/services/dropbox/dropbox/disable_action.yml
.github/services/gcs/gcs/action.yml
.github/services/gcs/gcs_with_default_storage_class/action.yml
.github/services/gdrive/gdrive/action.yml
.github/services/hdfs/hdfs_default_gcs/action.yml
.github/services/koofr/koofr/disable_action.yml
.github/services/oss/oss/action.yml
.github/services/oss/oss_with_versioning/action.yml
.github/services/s3/aws_s3/action.yml
.github/services/s3/aws_s3_with_list_objects_v1/action.yml
.github/services/s3/aws_s3_with_sse_c/action.yml
.github/services/s3/aws_s3_with_versioning/action.yml
.github/services/s3/aws_s3_with_virtual_host/action.yml
.github/services/s3/r2/disabled_action.yml
.github/workflows/ci_bindings_haskell.yml

Fix failed core tests because of a 1password version incompatibility. We have updated 1password configure to v2, but some services tests are using v1.
The CI is failing because of this.

chore(github-actions): update 1password

---

integrations/object_store/src/store.rs

feat(object_store): Implement copy, rename and return metadata after writing

---

.github/dependabot.yml

Closes #6465.
for napi-rs, napi and napi-derive should update together.

add groups for nodejs

---

bin/oli/src/config/mod.rs
bindings/lua/src/lib.rs
bindings/python/src/lister.rs
core/src/raw/accessor.rs
core/src/raw/adapters/kv/api.rs
core/src/raw/adapters/kv/mod.rs
core/src/raw/http_util/client.rs
core/src/raw/oio/delete/api.rs
core/src/raw/oio/list/api.rs
core/src/raw/oio/read/api.rs
core/src/raw/oio/write/api.rs
core/src/raw/path_cache.rs
integrations/dav-server/src/dir.rs
integrations/dav-server/src/file.rs
integrations/fuse3/src/file_system.rs

Closes #.
https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/#mismatched-lifetime-syntaxes-lint
https://github.com/apache/opendal/actions/runs/16802991914/job/47588491929

chore: make clippy happy again

---

.github/workflows/ci_check.yml
.github/workflows/docs.yml
.github/workflows/test_behavior_binding_nodejs.yml

Closes #.
Node.js 18 has reached [EOL](https://nodejs.org/en/about/previous-releases#commercial-support). This PR updates all relevant CI workflows to use Node.js 20 for consistency across the project.

ci: update workflow nodejs version and remove corepack

---

bindings/nodejs/Cargo.toml
bindings/nodejs/generated.d.ts
bindings/nodejs/generated.js
bindings/nodejs/package.json
bindings/nodejs/pnpm-lock.yaml

chore(bindings/nodejs): update generated code comments style due to napi-derive indentation fix

---

core/src/services/azblob/backend.rs
core/src/types/list.rs

fix(services/azblob): Fix azblob base64 validation

---

bindings/cpp/Cargo.toml
bindings/cpp/include/async_defs.hpp
bindings/cpp/include/opendal.hpp
bindings/cpp/include/opendal_async.hpp
bindings/cpp/src/async.rs
bindings/cpp/src/opendal_async.cpp

fix https://github.com/apache/opendal/actions/runs/17062459130/job/48371928070
- fix cxx_async namespace attribute
- make clippy happy
- upgrade cxx-async version

fix(bindings/cpp): correct cxx_async namespace attribute

---

bindings/ruby/Cargo.toml
bindings/ruby/lib/opendal_ruby/entry.rb
bindings/ruby/lib/opendal_ruby/io.rb
bindings/ruby/lib/opendal_ruby/metadata.rb
bindings/ruby/lib/opendal_ruby/operator.rb
bindings/ruby/lib/opendal_ruby/operator_info.rb
bindings/ruby/src/capability.rs
bindings/ruby/src/io.rs
bindings/ruby/src/lib.rs
bindings/ruby/src/lister.rs
bindings/ruby/src/metadata.rs
bindings/ruby/src/middlewares.rs
bindings/ruby/src/operator.rs
bindings/ruby/src/operator_info.rs
bindings/ruby/test/blocking_op_test.rb
bindings/ruby/test/capability_test.rb
bindings/ruby/test/io_test.rb
bindings/ruby/test/lister_test.rb
bindings/ruby/test/middlewares_test.rb
bindings/ruby/test/operator_info_test.rb

Part of #5227
Better to review commit by commit.

feat(bindings/ruby): support file open options

---

.github/workflows/release_dart.yml
.github/workflows/release_nodejs.yml
.github/workflows/release_python.yml

Closes #.
- Add ruby-head for testing
- Align workflow names

chore: adjust CI workflow names for bindings

---

core/src/docs/internals/accessor.rs
core/src/docs/internals/layer.rs

Closes #6552 .
update docs of `Access` and tutorial of building a new storage service

docs(core): update docs of building a storage service

---

.github/services/etcd/etcd-tls/action.yml
fixtures/etcd/docker-compose-standalone-tls.yml

Related #6435.
etcd discussions: https://github.com/etcd-io/etcd/discussions/20601

ci: switches etcd image to official etcd image

---

.github/actions/test_behavior_bin_ofs/action.yaml

Closes #.
`--no-capture` was added in 1.88, with `--nocapture` being soft-deprecated.
https://releases.rs/docs/1.88.0/#libraries

ci: Switch from --nocapture to --no-capture

---

website/blog/2025-09-15-apache-opendal-reqsign/index.md

None
announcement for Apache OpenDAL Reqsign

website: Add announcement for Apache OpenDAL Reqsign

---

core/src/services/cloudflare_kv/model.rs
core/src/services/dropbox/core.rs
core/src/services/oss/core.rs

Related https://github.com/apache/opendal/actions/runs/17953205003/job/51097928746.

chore: make clippy happy when using rust 1.90.0

---

.github/workflows/release_ruby.yml

Missed the patch file embedded in the workflow, so added a fix.

ci: Add patch file to Ruby release workflow

---

core/Cargo.lock
core/Cargo.toml
core/src/services/fs/backend.rs
core/src/services/memory/backend.rs

chore: upgrade opentelemetry to 0.31.0

---

website/docs/02-vision.md

docs: spelling and minor wording change
