apache/opendal

- Cargo.lock
- core/Cargo.toml
- core/src/docs/upgrade.md
- core/src/services/mod.rs
- core/src/services/moka/backend.rs
- core/src/services/moka/docs.md
- core/src/services/moka/mod.rs
> feat(service/moka): bump moka from 0.10.4 to 0.12.1

- Cargo.lock
- integrations/object_store/Cargo.toml
- integrations/object_store/src/lib.rs
1. the api change since 0.6
2. [impl ObjectStore:list_with_offset](https://github.com/apache/incubator-opendal/commit/84bd8bf12602e8b469665d67e7e86600f44071f0) by the way. because delta read need it.
3. disable get_opts for now instead of return wrong result.
> refactor(object_store): upgrade object_store to 0.7.

- bindings/java/src/test/java/org/apache/opendal/test/behavior/AsyncReadOnlyTest.java
- bindings/java/src/test/java/org/apache/opendal/test/behavior/BlockingReadOnlyTest.java
related: https://github.com/apache/incubator-opendal/pull/3712#issuecomment-1841901914
> fix(binding/java): fix SPECIAL_DIR_NAME

- bindings/ocaml/lib/operator.ml
- bindings/ocaml/lib/operator.mli
- bindings/ocaml/src/operator.ml
- bindings/ocaml/src/operator.mli
- bindings/ocaml/src/operator/entry.rs
- bindings/ocaml/src/operator/mod.rs
- bindings/ocaml/test/test.ml
just new to OCaml, appericiate for any review suggestion
cc https://github.com/apache/incubator-opendal/issues/2756
> feat: add operator.list support for OCaml binding

- bindings/ocaml/test/test.ml
close https://github.com/apache/incubator-opendal/issues/3732
> fix(ocaml_binding): sort `actual` & `expected` to pass ci

- website/docusaurus.config.js
Let's hide them until we have better UI/UX to show stable versioned docs and dev docs.
> docs: Remove not released bindings docs from top level header

- Cargo.lock
- core/Cargo.toml
- core/src/services/ftp/backend.rs
close https://github.com/apache/incubator-opendal/issues/3625
> refactor: replace ftp tls impl as rustls

- core/src/raw/http_util/bytes_content_range.rs
- core/src/raw/http_util/bytes_range.rs
- core/src/raw/oio/read/api.rs
- core/src/types/operator/blocking_operator.rs
- core/src/types/operator/operator.rs
The range we calculated in `read_with` is wrong. This PR polished it via build a complete bytes range.
> refactor: Polish operator read_with

- core/src/raw/oio/read/range_read.rs
- core/src/raw/rps.rs
- core/src/services/azblob/backend.rs
- core/src/services/azdls/backend.rs
- core/src/services/azfile/backend.rs
- core/src/services/b2/backend.rs
- core/src/services/cos/backend.rs
- core/src/services/dropbox/backend.rs
- core/src/services/gdrive/backend.rs
- core/src/services/ghac/backend.rs
- core/src/services/http/backend.rs
- core/src/services/huggingface/backend.rs
- core/src/services/obs/backend.rs
- core/src/services/onedrive/backend.rs
- core/src/services/oss/backend.rs
- core/src/services/s3/backend.rs
- core/src/services/seafile/backend.rs
- core/src/services/swift/backend.rs
- core/src/services/webdav/backend.rs
- core/src/services/webhdfs/backend.rs
This PR will add `range` in `RpRead` so that we can calculate the total size correctly.
> feat: Add content range support for RpRead

- .github/workflows/bindings_python.yml
Fix https://github.com/apache/incubator-opendal/issues/3673
> ci: Workaround ring 0.17 build issue, bring aarch64 and armv7l back

- .github/workflows/release_java.yml
- scripts/merge_local_staging.py
Fix https://github.com/apache/incubator-opendal/issues/3787
> fix(ci): Make sure merge_local_staging handles all subdir

- bindings/nodejs/generated.d.ts
- bindings/nodejs/src/lib.rs
- bindings/nodejs/upgrade.md
This pr aligns `list` API with core.
`scan` removed.
`list` returns Array<Entry>.
`list` could pass recursive as a.param.
> feat(binding/nodejs): align list api

- Cargo.lock
- core/edge/s3_read_on_wasm/.gitignore
- core/edge/s3_read_on_wasm/Cargo.toml
- core/edge/s3_read_on_wasm/README.md
- core/edge/s3_read_on_wasm/src/lib.rs
- core/edge/s3_read_on_wasm/webdriver.json
- core/src/services/s3/backend.rs
This PR will add basic edge test for s3 read on wasm.
We can't make it running in CI yet, should be fix later.
> feat: Add edge test s3_read_on_wasm

- website/docs/overview.md
This PR address the review comments from [hacker news](https://news.ycombinator.com/item?id=38732967) contributed by [@contravariant](https://news.ycombinator.com/user?id=contravariant).
Thanks a lot!
> chore: Address comments from hackernews

- core/src/services/gdrive/backend.rs
- core/src/services/gdrive/core.rs
- core/src/services/gdrive/lister.rs
> fix(services/gdrive): fix return value of `get_file_id_by_path`

- core/src/raw/http_util/header.rs
- core/src/raw/http_util/mod.rs
- core/src/services/upyun/core.rs
- core/src/services/upyun/writer.rs
> refactor(raw): add parse_header_to_str fn

- .github/workflows/ci.yml
- core/src/services/gdrive/backend.rs
- core/src/services/gdrive/lister.rs
- core/src/services/gdrive/writer.rs
tracked in https://github.com/apache/incubator-opendal/issues/3803
> feat: make services-gdrive compile for wasm target

- core/src/services/dbfs/docs.md
- core/src/services/huggingface/docs.md
- core/src/services/swift/docs.md
- website/docs/services/huggingface.mdx
close: #3754
- Regarding the issue comment on https://github.com/apache/incubator-opendal/issues/3605#issuecomment-1851782291, we should also mention the scheme name in the README documentation. I have included the naming in the comments in the JS and Python examples.
> docs(website): add service Huggingface to website

- .github/workflows/edge_test.yml
- core/edge/s3_read_on_wasm/src/lib.rs
> ci: Support CI test for s3_read_on_wasm

- .github/workflows/bindings_python.yml
Only run python bindings build test on tag push, workflow dispatch or pull requests that modifies `bindings_python.yml` file.
> refactor: simplify `bindings_python.yml`

- .github/workflows/docs.yml
- bindings/python/README.md
- bindings/python/template/module.html.jinja2
This closes https://github.com/apache/incubator-opendal/issues/3848.
Potential improvement:
* Better footer style (CSS)
* If the logo gets changed to "Apache OpenDAL™" itself [1], we can change the nav_title refers to the logo.
> chore(bindings/python): improve ASF branding

- bindings/haskell/README.md
- bindings/haskell/opendal.cabal
I cannot build it locally so we may wait for CI or the author of Haskell binding to check.
Failure report:
```
$ cabal update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org has been updated.
The index-state is set to 2023-12-29T05:19:00Z.
$ cabal haddock
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: opendal-0.1.0.0 (user goal)
[__1] next goal: base (dependency of opendal)
[__1] rejecting: base-4.19.0.0/installed-inplace (conflict: opendal =>
base>=4.10 && <4.17)
[__1] skipping: base-4.19.0.0, base-4.18.1.0, base-4.18.0.0, base-4.17.2.1,
base-4.17.2.0, base-4.17.1.0, base-4.17.0.0 (has the same characteristics that
caused the previous version to fail: excluded by constraint '>=4.10 && <4.17'
from …
```
> chore(bindings/haskell): improve ASF branding

- .github/workflows/bindings_haskell.yml
- bindings/haskell/opendal.cabal
close #3853
The support for `ghc-9.6` seems to need to bump `mtl`, but it has breaking change.
> chore(bindings/haskell): support co-log-0.6.0 && ghc-9.4

- core/src/raw/oio/read/buffer_reader.rs
- core/src/raw/oio/read/mod.rs
- core/src/raw/ops.rs
- core/src/types/operator/operator_futures.rs
Implement the async buffer reader.
It's a little more complex than I expected.  Maybe I should list each case and write more tests.
#3735
> feat(oio::read): implement the async buffer reader

- core/src/services/mod.rs
- core/src/services/webdav/backend.rs
- core/src/services/webdav/mod.rs
Part of https://github.com/apache/incubator-opendal/issues/3240
> refactor(services/webdav): Add WebdavConfig to implement ConfigDeserializer

- core/src/layers/complete.rs
- core/src/raw/oio/read/compose_read.rs
- core/src/raw/oio/read/mod.rs
1. Add `TwoWaysReader` and `FourWaysReader`
2. Refactor the `CompleteReader`
#3735
> feat: adapt the `CompleteReader`

- core/src/layers/complete.rs
- core/src/raw/enum_utils.rs
- core/src/raw/mod.rs
- core/src/raw/oio/read/compose_read.rs
- core/src/raw/oio/read/mod.rs
- core/src/raw/oio/write/compose_write.rs
- core/src/raw/oio/write/mod.rs
- core/src/services/azblob/writer.rs
- core/src/services/azdls/writer.rs
- core/src/services/azfile/writer.rs
- core/src/services/cos/writer.rs
- core/src/services/obs/writer.rs
- core/src/services/oss/writer.rs
Use `TwoWays` instead of `TwoWaysReader` and `TwoWaysWriter`
> refactor: use TwoWays instead of TwoWaysReader and TwoWaysWriter

- core/tests/behavior/write.rs
Add basic behavior tests for buffer reader  (p.s. I will rebase this PR after #3865 is merged)
#3735
> feat: add basic behavior tests for buffer reader

- Cargo.lock
- bin/ofs/Cargo.toml
- bin/ofs/src/lib.rs
It's really nice to have the built-in `inode` <=> `directory` mapping, so we can leverage the feature and only implement the interactions with OpenDAL, based on `PathFilesystem` trait.
> feat(ofs): implement ofs based on fuse3

- scripts/release.sh
- website/community/committers/release.md
close: #3818
> Tracking issues that need handled after release
[Create Release on the newly created tag](https://opendal.apache.org/community/committers/release#push-release-candidate-tag) (actually don't need any action on GitHub for candidate tag)
./scripts/release.sh cannot work on macOS, we need include it in the release docs
> chore: update release related docs and script

- bindings/python/README.md
Also compatible with zsh (`maturin[patchelf]` needs a quote to escape).
This closes #3874.
> docs(bindings/python): drop unnecessary patchelf

- core/src/services/ftp/backend.rs
- core/src/services/ftp/err.rs
- core/src/services/ftp/util.rs
- core/src/services/ftp/writer.rs
> refactor(services/ftp): Impl parse_error instead of From<Error>

- core/src/raw/http_util/body.rs
"got too little data" sounds more natural than "got too less data"
> docs: very minor English wording fix in error message

- core/src/services/hdfs/backend.rs
wrt #3875 
Missed adding `atomic_write_dir` to HdfsConfig fmt
cc @Xuanwo
> feat(services/hdfs): add atomic_write_dir to hdfsconfig debug

- core/src/services/mod.rs
- core/src/services/mongodb/backend.rs
- core/src/services/mongodb/mod.rs
Part of #3240 .
@Xuanwo Please review. Thanks.
> feat: add MongodbConfig

- core/src/docs/rfcs/3898_concurrent_writer.md
- core/src/docs/rfcs/mod.rs
Add concurrent writer RFC
- #2764
> RFC-3898: Concurrent Writer

- core/src/raw/http_util/client.rs
- core/src/raw/http_util/header.rs
- core/src/raw/http_util/mod.rs
- Fix https://github.com/apache/incubator-opendal/issues/3810
- Maybe close https://github.com/seanmonstar/reqwest/issues/2073
I tested locally with gdrice. We should extend the wasm tests to all available services in the future.
> fix(core): Handling content encoding correctly

- core/src/services/etcd/backend.rs
> refactor(services/etcd): Impl parse_error instead of From<Error>

- core/src/services/sftp/backend.rs
- core/src/services/sftp/error.rs
- core/src/services/sftp/lister.rs
> refactor(services/sftp): Impl parse_error instead of From<Error>

- core/src/raw/futures_util.rs
- core/src/raw/oio/write/multipart_upload_write.rs
- core/src/raw/ops.rs
- core/src/services/b2/backend.rs
- core/src/services/cos/backend.rs
- core/src/services/obs/backend.rs
- core/src/services/oss/backend.rs
- core/src/services/s3/backend.rs
- core/src/services/upyun/backend.rs
- core/src/types/operator/operator_futures.rs
> feat: implement concurrent `MultipartUploadWriter`

- core/src/raw/oio/write/range_write.rs
> fix: fix RangeWriter incorrect `next_offset`

- core/fuzz/fuzz_writer.rs
> feat: add `concurrent` and `buffer` parameters into FuzzInput

- website/community/committers/release.md
cc @suyanhanx 
We can execute these instructions after merging them :D
> docs(release): how to clean up old releases

- .github/workflows/bindings_haskell.yml
- .github/workflows/bindings_nodejs.yml
- .github/workflows/bindings_python.yml
- .github/workflows/docs.yml
- .github/workflows/fuzz_test.yml
- .github/workflows/release_java.yml
Related to https://github.com/actions/download-artifact/issues/249
> ci: Downgrade artifact actions until regression addressed

- core/src/services/webhdfs/backend.rs
- core/src/services/webhdfs/writer.rs
- fixtures/webhdfs/docker-compose-webhdfs.yml
> feat(services/webhdfs): Implement write with append

- core/benches/ops/write.rs
This PR will add benchmark for concurrent write.
Seems cool!
```rust
service_oss_write_with_concurrent/1
time:   [1.3195 s 1.3575 s 1.3909 s]
thrpt:  [57.517 MiB/s 58.932 MiB/s 60.630 MiB/s]
service_oss_write_with_concurrent/2
time:   [754.59 ms 773.29 ms 795.32 ms]
thrpt:  [100.59 MiB/s 103.45 MiB/s 106.02 MiB/s]
service_oss_write_with_concurrent/4
time:   [453.25 ms 465.07 ms 476.84 ms]
thrpt:  [167.77 MiB/s 172.02 MiB/s 176.50 MiB/s]
service_oss_write_with_concurrent/8
time:   [276.45 ms 286.87 ms 300.81 ms]
thrpt:  [265.95 MiB/s 278.87 MiB/s 289.39 MiB/s]
Found 1 outliers among 10 measurements (10.00%)
```
> feat(core/bench): Add benchmark for concurrent write

- website/src/pages/download.md
Wait a bit for @sebbASF's comment. I'm not a native speaker and this is something matters about wording.
The description is copied from https://flink.apache.org/downloads/#verifying-hashes-and-signatures.
> docs: improve user verify words

- core/src/raw/oio/write/block_write.rs
- core/src/raw/oio/write/mod.rs
> feat(oio): add block_write support

- core/src/raw/oio/write/block_write.rs
> fix(oio::BlockWrite): fix write_once case

- .github/workflows/ci.yml
- Cargo.toml
This reverts commit 3edaa8fdbe0b6a5e38a87138c13ef9516da73f12.
See https://github.com/apache/incubator-opendal/pull/3951 for more details.
> refactor!: Revert the bump of MSRV to 1.75

- core/src/raw/oio/write/block_write.rs
- core/src/raw/oio/write/multipart_upload_write.rs
- core/src/raw/oio/write/range_write.rs
Part of https://github.com/apache/incubator-opendal/issues/3956
> fix: Don't retry close if concurrent > 1 to avoid content lost

- core/src/services/mod.rs
- core/src/services/onedrive/builder.rs
- core/src/services/onedrive/mod.rs
Part of https://github.com/apache/incubator-opendal/issues/3240
> refactor(services/onedrive): Add OnedriveConfig to implement ConfigDeserializer

- core/src/docs/rfcs/3911_deleter_api.md
for this [comment](https://github.com/apache/incubator-opendal/issues/3922#issuecomment-1887655690)
> fix(doc): fix rfc typos

- core/src/lib.rs
I suppose that we will use an "Apache OpenDAL™" logo later, so this can improve the OpenDAL branding somehow.
> chore: display project logo on Rust docs

- core/src/services/ghac/backend.rs
Related to https://github.com/mozilla/sccache/issues/2026
> feat(services/ghac): Add workaround for AWS S3 based GHES

- .github/workflows/docs.yml
- bindings/nodejs/package.json
- bindings/nodejs/pnpm-lock.yaml
- bindings/nodejs/theme/index.tsx
- bindings/nodejs/tsconfig.json
- bindings/nodejs/tsconfig.theme.json
- bindings/nodejs/typedoc.json
Add copyright to the doc's footer
> docs(bindings/nodejs): copyright in footer

- bindings/nodejs/README.md
To tell how to build bindings/nodejs docs locally.
> docs(bindings/nodejs): build docs locally doc

- bindings/java/pom.xml
Related: https://github.com/apache/incubator-opendal/pull/3989#issuecomment-1893034384
Add copyright to the java doc's footer.
> docs(bindings/java): copyright in footer

- core/src/services/gdrive/backend.rs
- core/src/services/gdrive/builder.rs
- core/src/services/gdrive/core.rs
- core/src/services/gdrive/error.rs
- core/tests/behavior/async_delete.rs
- core/tests/behavior/async_list.rs
Fix https://github.com/apache/incubator-opendal/issues/3994
> feat(services/gdrive): Use trash instead of permanently deletes

- core/src/raw/http_util/client.rs
- core/src/types/operator/operator_futures.rs
Tokyo might overlook this wake if it's experiencing a high load.
> fix: Don't call wake_by_ref in OperatorFuture

- README.md
- bin/oay/README.md
- bin/ofs/README.md
- bin/oli/README.md
- bindings/c/README.md
- bindings/cpp/README.md
- bindings/dotnet/README.md
- bindings/go/README.md
- bindings/haskell/README.md
- bindings/java/README.md
- bindings/lua/README.md
- bindings/nodejs/README.md
- bindings/ocaml/README.md
- bindings/php/README.md
- bindings/python/README.md
- bindings/ruby/README.md
- bindings/swift/README.md
- bindings/zig/README.md
- core/README.md
- Add trademark information to every README page that may be published or become an entry point. (bin/bindings/core/repo)
- Unified format.
```
Licensed under the Apache License, Version 2.0: http://www.apache.org/licenses/LICENSE-2.0
Apache OpenDAL, OpenDAL, and Apache are either registered trademarks or trademarks of the Apache Software Foundation.
```
> docs: add trademark information to every possible published readme

- website/community/index.mdx
Since we've graduated from ASF, change url from `podling` to `project`. 🎉
> docs(website): replace podling to project in website

- scripts/README.md
- website/community/committers/release.md
This PR should be merged after https://issues.apache.org/jira/projects/INFRA/issues/INFRA-25399
> docs: Update release guide to adapt as a new TLP

- .github/CODEOWNERS
- .github/scripts/assign_reviewers.js
> chore: simplify reviewer candidates logic

- core/src/services/pcloud/core.rs
- core/src/services/seafile/writer.rs
fix seafile and pcloud to use get_basename and get_parent
> fix(pcloud,seafile): use get_basename and get_parent

- website/community/committers/release.md
> chore(website): Update the release tips

- website/community/news.md
Yang Shuai [@hoslo](https://github.com/hoslo) is now an OpenDAL Committer!
Thanks a lot for your contribution!
> docs: New Committer Yang Shuai

- core/src/services/sftp/backend.rs
- core/src/services/sftp/docs.md
close #4043
Update:
- add more explanation for endpoint config
- Since users can set user config in endpoint, we can allow users to ignore the user config
> docs(services/sftp): add more explanation for endpoint config

- core/src/layers/timeout.rs
- core/src/raw/http_util/client.rs
TimeoutLayer is using `tokio::time::timeout` to implement timeout for operations. And IO Operations insides `reader`, `writer` will use `Pin<Box<tokio::time::Sleep>>` to track the timeout.
This might introduce a bit overhead for IO operations, but it's the only way to implement timeout correctly. We used to implement timeout layer in zero cost way that only stores a `std::time::Instant` and check the timeout by comparing the instant with current time. However, it doesn't works for all cases.
For examples, users TCP connection could be in [Busy ESTAB](https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die) state. In this state, no IO event will be emit. The runtime will never poll our future again. From the application side, this future is hanging forever until this TCP connection is …
> fix: Implement timeout layer correctly by using timeout

- core/src/services/koofr/core.rs
When the directory already exists, Koofr returns 400 Bad Request, We should treat it as success.
fixes #4050
> fix(koofr): create_dir when exist

- Cargo.lock
- core/Cargo.toml
- core/src/layers/dtrace.rs
- core/src/layers/mod.rs
**This feature is an experimental feature**
TL;DR;
The PR will make the debug and tracing the opendal process easier in the Linux platform. The people can use so many modern tools like bpftrace to trace the internal state in the process
USDT is a way to allow people to pre-define some static hooks. Those hooks could be used to fetch some internal information when the process runs.
I will use this PR to describe the detailed behavior of the DTrace in the OpenDAL.
When people enabled `layers-dtrace` feature and added the layer to their code like the following code:
```rust
use anyhow::Result;
use opendal::services::Fs;
use opendal::Operator;
use opendal::layers::DTraceLayer;
#[tokio::main]
async fn main() -> Result<()> {
let mut builder = Fs::default();
builder.root("/tmp");
// `Accessor` …
```
> feat(layers/dtrace): Support User Statically-Defined Tracing(aka USDT) on Linux

- .github/scripts/behavior_test/plan.py
- fixtures/s3/docker-compose-minio.yml
Old minio has bug that make https://github.com/apache/opendal/pull/4067 CI failure.
> ci(services/s3): Use minio/minio image instead

- Cargo.lock
- Cargo.toml
the source released on github doesn't include
several bindings. This removes them from the
Cargo.toml to allow building from source
without this change, building from source results in errors like
```
> error: failed to load manifest for workspace member `/private/tmp/nix-build-oli-0.44.2.drv-0/source/bindings/haskell`
>
> Caused by:
>   failed to read `/private/tmp/nix-build-oli-0.44.2.drv-0/source/bindings/haskell/Cargo.toml`
>
```
to give more context, I'm trying to package oli for nixpkgs, this seems like a very useful tool.
thank you for your work on opendal, this looks amazing!
> deps: allow building from source

- bindings/haskell/Cargo.toml
Fix build of haskell package.
Close https://github.com/apache/opendal/issues/4094
> chore: Specify opendal version for haskell binding

- bindings/python/src/file.rs
> fix(bindings/python): missed to call close for the file internally

- bindings/python/src/file.rs
- bindings/python/tests/conftest.py
- bindings/python/tests/test_write.py
> fix(bindings/python): sync writer exit close raise error

- core/src/services/d1/backend.rs
- core/src/services/d1/mod.rs
- core/src/services/mod.rs
Part of https://github.com/apache/opendal/issues/3240
> refactor(service/d1): Add D1Config

- .github/actions/behavior_test_binding_python/action.yaml
- .github/workflows/bindings_python.yml
- bindings/python/benchmark/async_origin_s3_benchmark_with_gevent.py
- bindings/python/pyproject.toml
> feat(bindings/python): add ruff as linter

- core/src/services/gdrive/docs.md
We have already supported the `list`, `copy`, and `rename` commands for Google Drive.
https://github.com/apache/opendal/blob/398d17d45b12a2f01a682d938f8423d023db4324/core/src/services/gdrive/backend.rs#L54-L70
> docs(services/gdrive): Update Google Drive capabilities list docs

- .github/workflows/docs.yml
Part of https://github.com/apache/opendal/issues/4161
> docs: Fix docs build

- .github/services/hdfs/hdfs_default_gcs/action.yml
- core/src/services/hdfs/docs.md
- fixtures/hdfs/gcs-core-site.xml
Issue: #3504 
Adds test case for hdfs over gcs bucket. Tested locally with my own gcs bucket. 
TODO: Need to change how we obtain secret information from the test case (please see comments in code)
> ci: Add test case for hdfs over gcs bucket

- core/src/services/webdav/backend.rs
- core/src/services/webdav/lister.rs
While testing `sccache` with JFrog Artifactory as a WebDAV storage, I found the problem: `sccache` cannot store marker file while the `curl` can do it.
After deeper investigation & debugging I found that Artifactory answers to the `PROPFIND` request with this XML when file is not presented on the remote server:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:ns0="DAV:" />
```
And on the next step `Multistatus` cannot be deserialized => `sccache` was panicked with this logs:
```log
[2024-02-07T14:24:29Z DEBUG opendal::services::webdav::backend] backend stat response bytes (string): "<?xml version=\"1.0\" encoding=\"utf-8\" ?>\n<D:multistatus xmlns:D=\"DAV:\" xmlns:ns0=\"DAV:\"></D:multistatus>\n"
[2024-02-07T14:24:29Z ERROR opendal::services] …
```
> fix(services/webdav): Add possibility to answer without response if file isn't exist

- core/src/services/webdav/backend.rs
Use absolute paths for recreating all directory structure.
Fixes issue #4172.
Test with the `sccache` binary & `bytemark/webdav` WebDAV server docker.
> fix(services/webdav): Recreate root directory if need

- core/src/services/sqlite/backend.rs
- core/src/services/sqlite/docs.md
I implemented kv adapter scan function for sqlite service, so the sqlite backend supports list capability now.
I have a question about the scan function, don't we need to add a cursor to scan? Like the [redis' scan](https://redis.io/commands/scan/)
> feat(services/sqlite): Add list capability supported for sqlite

- .github/services/hdfs/hdfs_default_on_minio_s3/action.yml
- fixtures/hdfs/minio-s3-core-site.xml
Issue: #4168 
Adds test case for hdfs over s3 and azure blob storage. Relevant test passed: `Behavior Test / core / ubuntu-latest / hdfs / hdfs_default_s3`
Original PR: #4183
> ci: Add hdfs test case for s3

- .github/services/hdfs/hdfs_default_on_azurite_azblob/action.yml
- fixtures/hdfs/azurite-azblob-core-site.xml
Issue: #4168 
Adds test case for hdfs over azurite. Relevant test passed: `Behavior Test / core / ubuntu-latest / hdfs / hdfs_default_on_azurite_azblob `
Original PR: #4183
> ci: Add hdfs test case for azurite

- core/src/services/s3/compatible_services.md
docs: add docs for Ceph Rados Gateway S3
fix: https://github.com/apache/opendal/issues/4153
> docs: add docs for Ceph Rados Gateway S3

- .github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
Might help to reduce the flood of new prs being opened at once
> ci: reduce the open pull request limits to 1

- core/src/layers/timeout.rs
Our implementation of `TimeoutLayer` is still wrong in same cases. As suggested by @dantengsky & @zhang2014, we should poll it once to make sure the timer registered.
And we used to wrap our test logic inside a `timeout` call which could result in wrong test resute.
> fix(core): Poll TimeoutLayer::sleep once to make sure timer registered

- .github/workflows/ci_bindings_python.yml
- .github/workflows/release_java.yml
- .github/workflows/release_python.yml
Extract release CI from binding python CI.
> ci: Split python CI into release and checks

- core/src/services/azblob/backend.rs
- core/src/services/azdls/backend.rs
- core/src/services/azfile/backend.rs
- core/src/services/cacache/backend.rs
- core/src/services/cloudflare_kv/backend.rs
- core/src/services/cos/backend.rs
- core/src/services/dashmap/backend.rs
- core/src/services/dbfs/backend.rs
> feat: Implement Config for part of services

- core/Cargo.toml
- core/src/services/github/backend.rs
- core/src/services/github/core.rs
- core/src/services/github/docs.md
- core/src/services/github/error.rs
- core/src/services/github/lister.rs
- core/src/services/github/mod.rs
- core/src/services/github/writer.rs
- core/src/services/mod.rs
- core/src/types/operator/builder.rs
- core/src/types/scheme.rs
> feat(services/github): add github contents support

- core/src/types/operator/operator.rs
Related to https://github.com/apache/opendal/issues/4292
Fix https://github.com/apache/opendal/issues/4282
> docs: Polish the docs for writer

- core/Cargo.lock
- core/Cargo.toml
This is handy for environments such as docker scratch where you may not have a cert chain locally.
> feat: Allow selecting webpki for reqwest

- core/src/services/hdfs/writer.rs
> fix(services/hdfs): fix poll_close when retry

- .github/workflows/service_test_ghac.yml
- bindings/cpp/Cargo.toml
- bindings/dotnet/Cargo.toml
- bindings/haskell/Cargo.toml
- bindings/lua/Cargo.toml
- bindings/ocaml/Cargo.toml
- bindings/php/Cargo.toml
- bindings/ruby/Cargo.toml
- core/Cargo.lock
- core/Cargo.toml
- core/src/docs/upgrade.md
due to https://github.com/apache/opendal/pull/4311
- add previous default features to bindings. (except java, nodejs, python. These services already considered the service features) This is to avoid surprise behavior change and also fix CI. can be decided by bindings maintainers later. 
- fix ghac ci by adding feature flag
- fix oss ci by bumping reqsign
- enable memory service by default.
> fix: fix main CI 

- .github/workflows/docs.yml
- README.md
- website/docs/integrations/_category_.yml
- website/docs/integrations/object_store_opendal.mdx
- website/docusaurus.config.js
> docs: publish docs for object-store-opendal

- core/src/services/dropbox/core.rs
fix: #4314 
related to: https://github.com/apache/opendal/pull/4317
When an error occurs during `batch` call, Dropbox returns an error like this (causing an expect error before):
```json
{
".tag": "failure",
"failure": {
".tag": "path_lookup",
"path_lookup": {
".tag": "not_found",
}
}
}
```
Added `DropboxDeleteBatchFailureResponse` to parse those special errors.
```rust
#[derive(Default, Debug, Deserialize)]
#[serde(default)]
pub struct DropboxDeleteBatchFailureResponse {
#[serde(rename(deserialize = ".tag"))]
pub tag: String,
#[serde(flatten)]
pub failure_cause_map: HashMap<String, DropboxDeleteBatchFailureResponseCause>,
}
#[derive(Default, Debug, Deserialize)]
#[serde(default)]
pub struct DropboxDeleteBatchFailureResponseCause {
#[serde(rename(deserialize = ".tag"))]
pub tag: String,
} …
```
> fix(services/dropbox): fix dropbox batch test panic in ci

- core/src/services/hdfs_native/backend.rs
- core/src/services/hdfs_native/docs.md
I remove unsupported capabilities from the code and documentation of HDFS-native.
I spent a lot of time, but I couldn't use HDFS native to write files on the HSDF cluster I built. I have tried several methods to set up the cluster, but the problem still exists. :sob::sob::sob:
If no one solves this problem, I will come back to look at it again after a while.
> fix(services/hdfs-native): remove unsupported capabilities

- .editorconfig
We have the `doap.rdf` file in the repo root which uses 2 spaces for indent
> chore(editorconfig): add `rdf` file type as `indent_size = 2`

- core/src/layers/chaos.rs
- core/src/layers/concurrent_limit.rs
- core/src/layers/dtrace.rs
- core/src/layers/error_context.rs
- core/src/layers/logging.rs
- core/src/layers/metrics.rs
- core/src/layers/minitrace.rs
- core/src/layers/oteltrace.rs
- core/src/layers/prometheus.rs
- core/src/layers/prometheus_client.rs
- core/src/layers/retry.rs
- core/src/layers/throttle.rs
- core/src/layers/timeout.rs
- core/src/layers/tracing.rs
- core/src/raw/enum_utils.rs
- core/src/raw/http_util/body.rs
- core/src/raw/oio/cursor.rs
- core/src/raw/oio/read/api.rs
- core/src/raw/oio/read/buffer_reader.rs
- core/src/raw/oio/read/file_read.rs
- core/src/raw/oio/read/futures_read.rs
- core/src/raw/oio/read/into_read_from_stream.rs
- core/src/raw/oio/read/into_streamable_read.rs
- core/src/raw/oio/read/lazy_read.rs
- core/src/raw/oio/read/range_read.rs
- core/src/raw/oio/read/tokio_read.rs
- core/src/services/dbfs/reader.rs
- core/src/services/ftp/util.rs
- core/src/services/hdfs_native/reader.rs
- core/src/types/reader.rs
> chore: Cleanup of oio::Read, docs, comments, naming

- bin/ofs/README.md
> docs(bin/ofs): update README

- bindings/python/src/file.rs
- bindings/python/tests/test_read.py
> fix(bindings/python): Fix the semantic of `size` argument for python `File::read`

- bindings/python/src/file.rs
- bindings/python/tests/test_write.py
> fix(bindings/python): `File::write` should return the written bytes

- bindings/python/examples/pandas.ipynb
- bindings/python/examples/polars.ipynb
I have compiled opendal include the change of #4367 locally, and ran the new introduced two `ipynb` examples:
This is the result(output):
for pandas:
```python
read_df:     name  age
0  Alice   20
1    Bob   30
```
for polars:
```python
df: shape: (2, 2)
┌───────┬─────┐
│ name  ┆ age │
│ ---   ┆ --- │
│ str   ┆ i64 │
╞═══════╪═════╡
│ Alice ┆ 20  │
│ Bob   ┆ 30  │
└───────┴─────┘
read_df: shape: (2, 2)
┌───────┬─────┐
│ name  ┆ age │
│ ---   ┆ --- │
│ str   ┆ i64 │
╞═══════╪═════╡
│ Alice ┆ 20  │
│ Bob   ┆ 30  │
└───────┴─────┘
```
This closes #4270.
> docs(bindings/python): ipynb examples for polars and pandas

- bindings/java/.gitignore
- bindings/java/src/blocking_operator.rs
- bindings/java/src/executor.rs
- bindings/java/src/lib.rs
- bindings/java/src/main/java/org/apache/opendal/AsyncExecutor.java
- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/test/AsyncExecutorTest.java
- bindings/java/src/utility.rs
Support customize async executor (runtime)
> feat(bindings/java): explicit async runtime 

- bindings/java/src/executor.rs
- bindings/java/src/main/java/org/apache/opendal/NativeObject.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/test/AsyncExecutorTest.java
Little check overhead trade off huge safety.
NativeObject should be disposed at most once. So with a properly written program, the check is called at most once.
> feat(bindings/java): avoid double dispose NativeObject

- core/src/services/s3/backend.rs
try fix https://github.com/apache/opendal/issues/4249
The default port is omitted by Url::from(xx) when sending request: https://github.com/apache/opendal/blob/4c1752b5a60c9051a686c2e2f9a6af871105d4fe/core/src/raw/http_util/client.rs#L89-L95
They are not ignored when calculating signatures:
https://github.com/apache/opendal/blob/4c1752b5a60c9051a686c2e2f9a6af871105d4fe/core/src/services/s3/core.rs#L382-L384
> fix(services/s3): omit default ports

- bin/ofs/Cargo.lock
- bin/ofs/Cargo.toml
- bin/ofs/src/fuse.rs
- bin/ofs/src/lib.rs
currently, if we stop `ofs` running, it does not unmount fuse3 dir,
```
╭─ouyang@owl-home ~/code/opendal/bin/ofs ‹main› 
╰─$ RUST_LOG=debug ./target/debug/ofs ./exampless "fs://?root=/home/ouyang/tmp" 
[2024-03-25T14:27:05Z DEBUG opendal::services::fs::backend] backend build started: FsBuilder { root: Some("/home/ouyang/tmp"), atomic_write_dir: None }
[2024-03-25T14:27:05Z DEBUG opendal::services::fs::backend] backend use root /home/ouyang/tmp
[2024-03-25T14:27:05Z DEBUG opendal::services::fs::backend] backend build finished: FsBuilder { root: None, atomic_write_dir: None }
^C
╭─ouyang@owl-home ~/code/opendal/bin/ofs ‹main› 
╰─$ ls -al ./exampless …
```
> feat: add ofs ctrl-c exit unmount hook

- core/src/services/github/backend.rs
- core/src/services/github/core.rs
> feat(services/github): make access_token optional

- bin/ofs/Cargo.toml
- bin/ofs/README.md
- bin/ofs/src/config.rs
- bin/ofs/src/lib.rs
1. FreeBSD 13
```
root@freebsd:~/opendal/bin/ofs # echo "Hello OpenDAL ofs From Freebsd 13" > exampless/data.txt
root@freebsd:~/opendal/bin/ofs # cat exampless/data.txt 
Hello OpenDAL ofs From Freebsd 13
root@freebsd:~/opendal/bin/ofs # uname -a
FreeBSD freebsd 13.3-RELEASE FreeBSD 13.3-RELEASE releng/13.3-n257428-80d2b634ddf0 GENERIC amd64
```
```
[root@freebsd ~/opendal/bin/ofs]#  RUST_LOG=info ./target/debug/ofs ./exampless "fs://?root=/tmp" 
[2024-03-27T17:20:46Z INFO  fuse3::raw::session] handle_init; request=Request { unique: 1, uid: 0, gid: 0, pid: 2126 } fuse_connection=FuseConnection { unmount_notify: Notify { count: false, event: Event { listeners_notified: 18446744073709551615, listeners_total: 0 } }, mode: NonBlock(NonBlockFuseConnection { fd: AsyncFd { inner: Some(OwnedFd { …
```
> feat(ofs): add freebsd OS support

- core/src/raw/oio/buf/mod.rs
- core/src/raw/oio/buf/readable_buf.rs
- core/src/raw/oio/buf/writable_buf.rs
This PR adds WritableBuf for oio so that we can write into the buffer provided by users directly without extra allocation.
This API is internal used only and developer should make sure the correct usage.
> feat(core/raw/oio): Add Writable Buf

- core/src/raw/oio/buf/buffer.rs
- core/src/raw/oio/buf/mod.rs
- core/src/raw/oio/buf/queue_buf.rs
- core/src/raw/oio/write/exact_buf_write.rs
> feat(core/raw/buf): Reduce one allocation by `Arc::from_iter`

- README.md
- bindings/nodejs/README.md
- core/README.md
- core/src/docs/rfcs/README.md
- website/blog/2023-03-16-opendal-entered-apache-incubator/index.md
- website/community/events/gsoc-proposal-guide.md
Replace discord links to o.a.o/discord
> docs: Update links to o.a.o/discord

- integrations/dav-server/src/file.rs
- integrations/dav-server/src/opendalfs.rs
- integrations/dav-server/tests/test.rs
fix #3231
Added a `WebdavFileState` structure containing a `Reader` and a `Writer` to support continuous reading and writing of `WebdavFile`.
> fix(oay): support `WebdavFile` continuous reading and writing

- core/Cargo.lock
- core/src/docs/internals/accessor.rs
- core/src/layers/complete.rs
- core/src/layers/minitrace.rs
- core/src/layers/oteltrace.rs
- core/src/layers/tracing.rs
- core/src/layers/type_eraser.rs
- core/src/raw/futures_util.rs
- core/src/raw/http_util/client.rs
- core/src/raw/mod.rs
- core/src/raw/oio/list/api.rs
- core/src/raw/oio/list/page_list.rs
- core/src/raw/oio/read/api.rs
- core/src/raw/oio/read/mod.rs
- core/src/raw/oio/write/api.rs
- core/src/raw/oio/write/append_write.rs
- core/src/raw/oio/write/block_write.rs
- core/src/raw/oio/write/multipart_write.rs
- core/src/raw/oio/write/one_shot_write.rs
- core/src/raw/oio/write/range_write.rs
- core/src/types/reader.rs
- core/tests/behavior/utils.rs
This PR implements into stream for reader. By this stream based read, we can extend it to concurrent read easily!
> feat(core): Implement into_stream for Reader

- core/src/raw/oio/write/range_write.rs
> feat(raw/oio): Use `Buffer` as cache in `RangeWrite`

- core/src/types/buffer.rs
This PR fixes two misuses of `Buffer::offset` in `Buffer::to_io_slice` and `Buf::chunks_vectored`.
> fix(core): Buffer offset misuse

- core/src/raw/oio/write/one_shot_write.rs
- core/src/services/azdls/writer.rs
- core/src/services/azfile/writer.rs
- core/src/services/chainsafe/core.rs
- core/src/services/chainsafe/writer.rs
- core/src/services/dbfs/writer.rs
- core/src/services/dropbox/writer.rs
- core/src/services/gdrive/core.rs
- core/src/services/gdrive/writer.rs
- core/src/services/github/backend.rs
- core/src/services/github/core.rs
- core/src/services/github/writer.rs
- core/src/services/ipmfs/backend.rs
- core/src/services/ipmfs/writer.rs
- core/src/services/koofr/core.rs
- core/src/services/koofr/writer.rs
- core/src/services/onedrive/writer.rs
- core/src/services/pcloud/core.rs
- core/src/services/pcloud/writer.rs
- core/src/services/seafile/writer.rs
- core/src/services/supabase/writer.rs
- core/src/services/swift/writer.rs
- core/src/services/vercel_artifacts/writer.rs
- core/src/services/webdav/writer.rs
- core/src/services/yandex_disk/writer.rs
> feat(raw/oio): Use `Buffer` as cache in `OneshotWrite`

- core/src/raw/oio/write/multipart_write.rs
> refactor: Use Buffer as cache in MultipartWrite

- bin/oli/src/commands/cat.rs
- bin/oli/src/commands/cp.rs
- bindings/c/include/opendal.h
- bindings/c/src/reader.rs
- bindings/cpp/src/lib.rs
- bindings/cpp/src/reader.rs
- bindings/nodejs/src/lib.rs
- bindings/python/src/file.rs
- core/benches/ops/read.rs
- core/src/types/blocking_reader.rs
- core/src/types/mod.rs
- core/src/types/reader.rs
- core/src/types/writer.rs
- core/tests/behavior/async_write.rs
- integrations/object_store/src/lib.rs
Align the Reader and Writer's API design as mentioned in  https://github.com/apache/opendal/issues/4465
- From `into_futures_io_async_read` to `into_futures_async_read`.
- From `into_futures_io_async_write` to `into_futures_async_write`.
- From `into_std_io_read` to `into_std_read`.
The context is clear that we don't need to re-mention `io` in our API.
- From `into_futures_bytes_stream` to `into_bytes_stream`
- From `into_std_bytes_iterator` to `into_bytes_iterator`
There is only one widely used stream API so far. Remove `futures` to make API more clear.
> chore(core): Align Reader and Writer's API design

- core/src/raw/adapters/kv/api.rs
- core/src/raw/adapters/kv/backend.rs
- core/src/services/atomicserver/backend.rs
- core/src/services/cacache/backend.rs
- core/src/services/cloudflare_kv/backend.rs
- core/src/services/d1/backend.rs
- core/src/services/etcd/backend.rs
- core/src/services/foundationdb/backend.rs
- core/src/services/gridfs/backend.rs
- core/src/services/libsql/backend.rs
- core/src/services/memcached/backend.rs
- core/src/services/mongodb/backend.rs
- core/src/services/mysql/backend.rs
- core/src/services/persy/backend.rs
- core/src/services/postgresql/backend.rs
- core/src/services/redb/backend.rs
- core/src/services/redis/backend.rs
- core/src/services/rocksdb/backend.rs
- core/src/services/sled/backend.rs
- core/src/services/sqlite/backend.rs
- core/src/services/surrealdb/backend.rs
- core/src/services/tikv/backend.rs
- core/src/types/buffer.rs
> refactor: kv::adapter should use Buffer (write part)

- core/src/types/reader.rs
This PR makes `BytesStream` using the same implemantation of `Reader::read` that has support for concurrent reading.
> feat(core): Allow concurrent reading on bytes stream

- core/src/types/buffer.rs
This PR adds two new public functions for `Buffer`:
- `count`, get the number of `bytes::Bytes` in `Buffer`
- `current`, get the current buffer, which doesn't alter any state or do any deep copy
> feat(core): add access methods for `Buffer`

- core/src/services/compfs/backend.rs
- core/src/services/compfs/core.rs
- core/src/services/compfs/lister.rs
- core/src/services/compfs/mod.rs
- core/src/services/compfs/reader.rs
- core/src/services/compfs/writer.rs
- core/src/services/mod.rs
- core/src/types/scheme.rs
This PR implements core `compio` runtime wrapper for spawning tasks, and established basic structure for `compfs` service.
> feat(services/compfs): compio runtime and compfs structure

- core/src/types/error.rs
This PR changes `Result<T> = std::result::Result<T, Error>` to `Result<T, E = Error> = std::result::Result<T, E>`, makes it easier for user to use even when they have non-opendal errors. 
```rust
use opendal::Result;
// This still works
let a: Result<T>;
// And this works too
let b: Result<T, MyError>;
```
> feat(core): change Result to default error

- core/src/services/github/backend.rs
- core/src/services/github/core.rs
- core/src/services/github/lister.rs
> feat(services/github): support list recursive

- core/Cargo.lock
- core/Cargo.toml
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
> feat: Add crc32c checksums to S3 Service

- core/src/raw/oio/write/block_write.rs
- core/src/raw/serde_util.rs
- core/src/services/cos/core.rs
- core/src/services/etcd/backend.rs
- core/src/services/ftp/backend.rs
- core/src/services/memcached/backend.rs
- core/src/services/memcached/binary.rs
- core/src/services/obs/core.rs
- core/src/services/persy/backend.rs
- core/src/services/s3/core.rs
- core/src/services/sftp/backend.rs
This PR changes `std::result::Result` to `opendal::Result` in core/.
close #4536
> chore(core): Change std result to opendal result in core

- core/src/services/postgresql/backend.rs
- website/community/committers/release.md
- website/src/pages/download.md
This PR updates the outdated download link.
Updated the release doc since we have previously moved away from adding the core version to the version number.
> docs: update the outdated download link

- website/community/index.mdx
I tried deploying on Vercel. It can be displayed normally.
(I wrote the wrong command in the last PR. 😅)
> fix: community sync calendar iframe load failed

- core/src/raw/accessor.rs
> refactor(core): Align naming for `AccessorDyn`

- core/src/layers/type_eraser.rs
- core/src/raw/oio/read/api.rs
- core/src/types/blocking_read/blocking_reader.rs
> feat(core/types): change oio::BlockingReader to Arc<dyn oio::BlockingReader>

- integrations/object_store/src/lib.rs
Closes #4581 
This was caused by `format_object_meta` querying Metakey values that aren't set.
> fix: format_object_meta should not require metakeys that don't exist

- core/src/raw/oio/write/multipart_write.rs
- core/src/services/b2/writer.rs
- core/src/services/cos/writer.rs
- core/src/services/obs/writer.rs
- core/src/services/oss/writer.rs
- core/src/services/s3/core.rs
- core/src/services/s3/writer.rs
- core/src/services/upyun/writer.rs
- core/src/services/vercel_blob/writer.rs
There was an issue with checksums missing in the `Part`s in [CompleteMultipartUpload](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html). 
The resulting error message was: 
> The upload was created using a crc32c checksum. The complete request must include the checksum for each part. It was missing for part 1 in the request.
I initially missed this because it does not appear to be a problem for very large files.
This PR should address that problem.
> feat: add checksums to MultiPartComplete

- .devcontainer/post_create.sh
#4583 change `corepack prepare pnpm@stable --activate` to `corepack prepare pnpm@latest --activate`, while the former will get `Usage Error: Tag not found (stable)`.
> fix(devcontainer/post_create.sh): change pnpm@stable to pnpm@latest

- README.md
Hi there 👋 
We've recently integrated OpenDAL in ParadeDB, so I figured I'd add ourselves to the list. Thank you for all your work on OpenDAL, it's a phenomenal project.
> chore: Contribute ParadeDB

- integrations/object_store/Cargo.toml
- integrations/object_store/src/lib.rs
> chore(deps): Bump object_store to 0.10

- core/src/raw/http_util/client.rs
- core/src/types/error.rs
We will treat decoding response errors as hard errors, but they are usually safe to retry, similar to connection resets.
> fix(raw): Allow retrying request while decoding response failed

- core/src/types/metadata.rs
> fix(core): return None if metadata unavailable

- integrations/object_store/README.md
Part of: https://github.com/apache/opendal/issues/4599
> feat(doc): update object_store_opendal README

- website/community/index.mdx
Replaced with the following link:
https://calendar.google.com/calendar/embed?src=d32a8b1c08fc40d4230e3ce89145fd0e9a1ea4a374893a23ec7bd28ca646db45%40group.calendar.google.com&ctz=Asia%2FShanghai
> website: replace community sync calendar with link

- bindings/python/Cargo.toml
- bindings/python/pyproject.toml
This PR will use abi3 and increase MSPV to 3.11 to reduce our release size.
> fix(bindings/python): Use abi3 and increase MSPV to 3.11

- .github/services/aliyun_drive/aliyun_drive/disabled_action.yml
- core/Cargo.toml
- core/src/services/aliyun_drive/backend.rs
- core/src/services/aliyun_drive/core.rs
- core/src/services/aliyun_drive/docs.md
- core/src/services/aliyun_drive/error.rs
- core/src/services/aliyun_drive/lister.rs
- core/src/services/aliyun_drive/mod.rs
- core/src/services/aliyun_drive/reader.rs
- core/src/services/aliyun_drive/writer.rs
- core/src/services/mod.rs
- core/src/types/operator/builder.rs
- core/src/types/scheme.rs
Closing #3415. Ready for review.
API documentation reference: https://www.yuque.com/aliyundrive/zpfszx/gogo34oi2gy98w5d
Required Environment Variables:
```bash
export OPENDAL_ALIYUN_DRIVE_CLIENT_ID=
export OPENDAL_ALIYUN_DRIVE_CLIENT_SECRET=
export OPENDAL_ALIYUN_DRIVE_REFRESH_TOKEN=
export OPENDAL_ALIYUN_DRIVE_RAPID_UPLOAD=true
export OPENDAL_TEST=aliyun_drive
```
To run behavior tests, use the following command:
```bash
cd core && cargo test behavior --features tests,services-aliyun-drive -- --test-threads=1
```
Note that the test threads should be set to 1 as it may fail part of the test due to rate limit.
AliyunDrive has a feature called Rapid Upload, but it is difficult to implement completely because the `MultipartWriter` trait design isn't well compatible with this feature at …
> feat(services/aliyun-drive): support AliyunDrive

- bindings/java/pom.xml
- bindings/java/src/blocking_operator.rs
- bindings/java/src/lib.rs
- bindings/java/src/main/java/org/apache/opendal/BlockingOperator.java
- bindings/java/src/main/java/org/apache/opendal/OperatorInputStream.java
- bindings/java/src/main/java/org/apache/opendal/OperatorOutputStream.java
- bindings/java/src/operator_input_stream.rs
- bindings/java/src/operator_output_stream.rs
- bindings/java/src/test/java/org/apache/opendal/test/OperatorInputOutputStreamTest.java
- bindings/java/src/test/java/org/apache/opendal/test/OperatorInputStreamTest.java
- core/src/raw/ops.rs
- core/src/types/blocking_read/blocking_reader.rs
- core/src/types/blocking_read/std_bytes_iterator.rs
This closes https://github.com/apache/opendal/issues/4616.
> feat: implement OperatorInputStream and OperatorOutputStream

- bin/oli/src/commands/cat.rs
- bin/oli/src/commands/cp.rs
- bindings/nodejs/src/lib.rs
- bindings/python/src/file.rs
- bindings/python/src/operator.rs
- core/benches/ops/read.rs
- core/src/layers/retry.rs
- core/src/raw/atomic_util.rs
- core/src/raw/mod.rs
- core/src/types/operator/operator.rs
- core/src/types/read/buffer_stream.rs
- core/src/types/read/futures_bytes_stream.rs
- core/src/types/read/reader.rs
- core/tests/behavior/async_read.rs
- integrations/object_store/src/lib.rs
We used to depends on the behavior that services can handle large range correctly, however, it doesn't. Many services can't handle range correctly like reported in https://github.com/apache/opendal/issues/4618.
Thus we should fetch the content length while end_bound is unknown.
I will start another PR to fix the `read_at`'s API docs.
- Fix https://github.com/apache/opendal/issues/4594
- Fix https://github.com/apache/opendal/issues/4618
> fix: Fetch the content length while end_bound is unknown

- bindings/java/src/error.rs
- bindings/java/src/main/java/org/apache/opendal/OpenDALException.java
- bindings/python/python/opendal/exceptions.pyi
- bindings/python/src/errors.rs
- bindings/python/src/lib.rs
- core/src/raw/std_io_util.rs
- core/src/services/alluxio/error.rs
- core/src/services/gridfs/backend.rs
- core/src/services/hdfs_native/error.rs
- core/src/services/mongodb/backend.rs
- core/src/services/seafile/error.rs
- core/src/services/yandex_disk/error.rs
- core/src/types/error.rs
`InvalidInput` is designed for `oio::Read::seek` only, but we don't provide seek API anymore. And I found some places use this error kind in wrong. This PR fixed them at the same time.
> refactor(core): core doesn't expose invalid input error anymore

- bin/ofs/src/fuse.rs
- bindings/java/src/error.rs
- bindings/python/python/opendal/exceptions.pyi
- bindings/python/src/errors.rs
- bindings/python/src/lib.rs
- core/src/raw/http_util/client.rs
- core/src/types/error.rs
We used to return two different errors, `ContentIncomplete` and `ContentTruncated`, when the HTTP response had too much or too little data. However, these error codes were not helpful to users as they provided no actionable steps.
This PR addresses this issue by returning a generic unexpected error instead.
> refactor(core): Return unexpected error while content incomplete happen

- .github/actions/test_behavior_bin_ofs/action.yaml
- .github/workflows/test_behavior_bin_ofs.yml
- bin/ofs/src/fuse.rs
- bin/ofs/tests/common/mod.rs
- bin/ofs/tests/file.rs
- bin/ofs/tests/path.rs
- Remove unnecessary `lseek` implementation.
- Only continuously truncate writes and continuously append writes are allowed.
- Fix file will be truncate on every `write`.
- Fix panic on debug build caused by incorrect use of `Metadata`.
- Refactor `readdirplus`.
merged #4611
> fix: ofs write behavior

- .github/workflows/ci_check.yml
`create-ci/typos` is whitelisted in https://issues.apache.org/jira/browse/INFRA-25798. I propose to switch
> ci: use official typos github action

- core/Cargo.lock
- core/Cargo.toml
- core/src/types/buffer.rs
See https://github.com/zowens/crc32c/pull/60.
> build(deps): upgrade crc32c to 0.6.6 for nightly toolchain

- core/Cargo.toml
- core/benches/types/concurrent_tasks.rs
- core/benches/types/main.rs
- core/src/raw/futures_util.rs
- core/src/raw/mod.rs
- core/src/raw/oio/write/multipart_write.rs
- core/src/services/aliyun_drive/backend.rs
- core/src/services/b2/backend.rs
- core/src/services/cos/backend.rs
- core/src/services/obs/backend.rs
- core/src/services/oss/backend.rs
- core/src/services/s3/backend.rs
- core/src/services/upyun/backend.rs
- core/src/services/vercel_blob/backend.rs
- core/src/types/execute/api.rs
- core/src/types/execute/executor.rs
- core/src/types/execute/executors/tokio_executor.rs
Part of https://github.com/apache/opendal/issues/4639
This PR implements `ConcurrentTasks` based on existing `Executor` and replace the `ConcurrentFutures` used by multipart write.
> feat: Implement and refactor concurrent tasks for multipart write

- core/src/types/operator/operator.rs
Fix #4654 
The root cause is described in https://github.com/apache/opendal/issues/4654#issuecomment-2140685110
The fix covered several cases in object-store like backend:
1. Both prefix and objects exist, when remove_all("a"), we should not only delete the object "a", e.g.:
* a
* a/b
* a/c
2. Normal case, when remove_all("a"), we should remove all objects under the prefix.
* a/b
* a/c
> fix(core/types): remove_all not work under object-store backend

- core/src/types/operator/blocking_operator.rs
- core/src/types/operator/operator.rs
Follow-up PR to #4659 
We only fixed async API in that PR, the PR fixed the sync one.
In addition, we have also removed the NotFound handling that lister could not possibly return.
> feat(core/types): blocking remove_all for object storage based services

- core/src/layers/error_context.rs
Part of https://github.com/apache/opendal/issues/4672
This PR adds more context in the error.
> feat(core): Add more context in error context

- .github/actions/test_behavior_bin_ofs/action.yaml
- bin/ofs/Cargo.lock
- bin/ofs/Cargo.toml
- bin/ofs/src/fuse/adapter.rs
- bin/ofs/tests/common/mod.rs
We don't want this, but we have to
Fix https://github.com/apache/opendal/issues/4645
> fix(ofs): Close file during flush

- core/src/raw/futures_util.rs
- core/src/raw/oio/write/multipart_write.rs
Fix unit test failure in `test_multipart_upload_writer_with_concurrent_errors`
> chore(core): Fix unit tests

- core/src/layers/prometheus.rs
- core/src/layers/prometheus_client.rs
- Close https://github.com/apache/opendal/issues/4646
- Close https://github.com/apache/opendal/issues/4644
> fix(core/prometheus): Fix metrics from prometheus not correct for reader

- core/src/raw/futures_util.rs
- core/src/raw/oio/write/multipart_write.rs
- core/src/types/execute/api.rs
`ConcurrentTasks` is not cancel safe since it will change states when poll returns Pending. This PR fixed this by only pop task after it returns ready.
> fix(core/oio): Make ConcurrentTasks cancel safe by only pop after ready

- .github/workflows/docs.yml
Figure out why we miss broken links in CI in #4709.
> ci: verify build website on site content changes

- scripts/release.py
- scripts/verify.py
> chore: use more portable binutils 

- bindings/python/Cargo.toml
- bindings/python/src/file.rs
- bindings/python/src/lib.rs
- bindings/python/src/operator.rs
- bindings/python/src/utils.rs
Sorry for the delay, finally have time to do this. :)
---
This closes #4399.
> chore(binding/python): Upgrade pyo3 to 0.21

- core/src/services/s3/core.rs
- core/src/services/s3/error.rs
- core/src/services/s3/writer.rs
S3 may return an error when the HTTP code is 200. Like this https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html#API_CompleteMultipartUpload_Example_4
This patch defines a `MultipartUploadResult` result which only contains error's definition. It will be deserialized on complete multipart upload's 200 result, to check if the body contains any error.
For more background reference to https://github.com/awslabs/aws-sdk-rust/issues/1163
> fix(s3): parse MultipartUploadResponse to check error in body

- core/src/services/aliyun_drive/backend.rs
- core/src/services/aliyun_drive/core.rs
- core/src/services/aliyun_drive/docs.md
> feat(services): add optional access_token for AliyunDrive

- core/Cargo.toml
- core/src/services/aliyun_drive/backend.rs
- core/src/services/aliyun_drive/core.rs
- core/src/services/aliyun_drive/docs.md
- core/src/services/aliyun_drive/error.rs
- core/src/services/aliyun_drive/writer.rs
> refactor(aliyun-drive): rewrite writer part

- core/src/services/aliyun_drive/core.rs
> fix(services/aliyun-drive): unable to list `/`

- core/src/raw/oio/write/range_write.rs
- core/src/services/gcs/writer.rs
> refactor(core): Remove unused `size` for `RangeWrite`.

- .github/workflows/ci_bindings_nodejs.yml
Related to https://github.com/apache/opendal/issues/4761
> ci(nodejs): Disable services-all on windows

- core/Cargo.lock
- core/Cargo.toml
- core/src/services/compfs/backend.rs
- core/src/services/compfs/core.rs
- core/src/services/compfs/lister.rs
- core/src/services/compfs/reader.rs
- core/src/services/compfs/writer.rs
This PR implements basic function of `Access` for `Compfs`, include `CompfsReader`, `CompfsWriter` and `CompfsLister`. 
~~For now, this branch uses git dependency of `compio` to test the lastest updates. Before merging, compio should make a new release (by @George-Miao, me) and update the corresponding `Cargo.toml` entry.~~
New release has been made and updated. Ready to be merged.
> feat(services/compfs): basic `Access` impl

- core/src/services/aliyun_drive/backend.rs
- core/src/services/aliyun_drive/lister.rs
Pending.
I found that CI for AliyunDrive randomly failed. Investigating.
> fix(services/aliyun-drive): list dir without trailing slash

- integrations/unftp-sbe/Cargo.lock
- integrations/unftp-sbe/Cargo.toml
- integrations/unftp-sbe/src/lib.rs
This PR adds `OpendalStorage`, an adapter that wraps around `Operator` to provide `libunftp::storage::StorageBackend` implementation.
> feat(unftp-sbe): impl `OpendalStorage`

- integrations/unftp-sbe/Cargo.lock
- integrations/unftp-sbe/Cargo.toml
- integrations/unftp-sbe/src/lib.rs
This PR returnes a `tokio::io::AsyncRead` instance directly instead of read everything into buffer first and then return it.
> fix(unftp-sbe): remove buffer for get

- .github/scripts/test_behavior/plan.py
- core/src/services/aliyun_drive/backend.rs
- core/src/services/aliyun_drive/core.rs
The current aliyun_drive test may not be stable enough. 
There is a concurrent write limit, so disable it for our bindings.
> chore(ci): disable aliyun_drive for bindings test

- core/src/services/compfs/backend.rs
- core/src/services/compfs/core.rs
- core/src/services/compfs/lister.rs
- core/src/services/compfs/reader.rs
- core/src/services/compfs/writer.rs
This PR impelements auxiliary Access functions for Compfs, include `create_dir`, `stat`, `delete`, `copy` and `rename`, and finished builder logic.
> feat(services/compfs): implement auxiliary functions

- core/src/services/aliyun_drive/backend.rs
- core/src/services/aliyun_drive/core.rs
> fix(services/aliyun-drive): write op cannot overwrite existing files

- core/src/layers/await_tree.rs
> feat: make AwaitTreeLayer covers oio::Read and oio::Write

- bindings/nodejs/CONTRIBUTING.md
- bindings/nodejs/devbox.json
- bindings/nodejs/devbox.lock
[devbox](https://www.jetify.com/devbox) is a nix wrapper, but simpler to use
> feat: Nodejs add devbox

- bindings/nodejs/.prettierignore
- bindings/nodejs/generated.d.ts
- bindings/nodejs/src/lib.rs
- bindings/nodejs/tests/suites/async.suite.mjs
- bindings/nodejs/tests/suites/sync.suite.mjs
> feat(nodejs): add `WriteOptions` for write methods

- core/src/services/onedrive/graph_model.rs
This `@odata.count` does not seem to exist before in their official docs...
Recently I found they don't return this field anymore so all list op would raise errors.
I'm going to remove it.
In this repo, this field does not exist for all the time: https://github.com/sreeise/graph-rs-sdk/blob/afda1dcfbf5d491e56c6753152a1ce7e1c97fb44/test_files/drive_ep/drive_root_child.json#L4
> fix(core/services/onedrive): remove @odata.count for onedrive list op

- core/src/services/gcs/backend.rs
- core/tests/behavior/async_write.rs
We need to find a new way to implement concurrent write for gcs.
> fix(core): Gcs's RangeWrite doesn't support concurrent write

- core/src/raw/oio/write/mod.rs
- core/src/raw/oio/write/position_write.rs
> feat: add position write

- .github/workflows/docs.yml
This PR will build docs for all released integrations.
Part of https://github.com/apache/opendal/issues/4738
> ci: Build docs for all integrations

- core/src/services/sftp/backend.rs
- core/tests/behavior/async_write.rs
> tests(behavior): add test for writer write overwrite

- bindings/nodejs/generated.d.ts
- bindings/nodejs/generated.js
- bindings/nodejs/package.json
- bindings/nodejs/pnpm-lock.yaml
- bindings/nodejs/src/capability.rs
- bindings/nodejs/src/lib.rs
- website/docs/binding-nodejs.md
- website/docs/binding-python.md
- website/docs/overview.md
- website/docs/quickstart.md
Bumped napi-cli to clean the following warning.
> fix(docs): some typos in website and nodejs binding docs

- scripts/constants.py
- scripts/dependencies.py
- scripts/merge_local_staging.py
- scripts/release.py
- scripts/verify.py
- scripts/version.py
- website/community/release/release.md
This PR will add a script to generate version list in markdown.
For example:
```
:) ./scripts/version.py
| Name                      | Version | Next    |
| -                         | -       | -       |
| core                      | 0.47.1  | 0.47.2  |
| bin/oay                   | 0.41.4  | 0.41.5  |
| bin/oli                   | 0.41.4  | 0.41.5  |
| bin/ofs                   | 0.0.5   | 0.0.6   |
| bindings/python           | 0.45.4  | 0.45.5  |
| bindings/nodejs           | 0.46.2  | 0.46.3  |
| bindings/c                | 0.44.6  | 0.44.7  |
| bindings/zig              | 0.0.0   | 0.0.1   |
| bindings/dotnet           | 0.1.2   | 0.1.3   |
| bindings/haskell          | 0.44.4  | 0.44.5  |
| bindings/java             | 0.46.1  | 0.46.2  |
| bindings/lua              | 0.1.2   | …
```
> ci(scripts): Add a script to generate version list

- bin/oay/README.md
- bin/ofs/README.md
- bin/oli/README.md
- integrations/unftp-sbe/README.md
This PR will polish README for all bin like `oli`, `oay` and `ofs`.
> docs(bin): Polish README for all bin

- core/src/services/aliyun_drive/backend.rs
- core/src/services/aliyun_drive/core.rs
- core/src/services/aliyun_drive/writer.rs
Related to #4780
It's better to re-implement the `oio::Write` directly after some discussion with @Xuanwo:
> > Normally, we get the upload_id from `initiate_part` in the first call. When concurrency occurs, Aliyun Drive randomly fails on the method `write_once` which invokes `initiate_part` and has retries.
> 
> Oh, I see. The real issue here is that Aliyun Drive should not be treated as a valid multipart upload service.
> 
> A valid multipart upload service should be exactly the same with s3 that meets:
> 
>     * An API such as `PutObject` can atomically create and upload a file.
> 
>     * And a seperate group of APIs that can upload files in multiple parts: init, upload and complete.
> 
> 
> Those two set of APIs should never be called in mixed. For example, `wirte_once` should never …
> refactor(services/aliyun-drive): directly implement `oio::Write`.

- integrations/object_store/src/store.rs
Calling `op.info()` inside `Debug` might introduce dead lock for logging.
> fix(integration/object_store): Avoid calling  API inside debug

- core/src/services/fs/backend.rs
- core/src/services/fs/mod.rs
- core/src/services/mod.rs
part of https://github.com/apache/opendal/issues/3240
> feat(services/fs): Support fs config

- core/Cargo.lock
- core/Cargo.toml
- core/src/services/mod.rs
- core/src/services/monoiofs/backend.rs
- core/src/services/monoiofs/docs.md
- core/src/services/monoiofs/mod.rs
- core/src/types/operator/builder.rs
- core/src/types/scheme.rs
Part of #4552.
This pr initializes monoiofs service, introduces its feature flag and relevant dependency.
> feat(services): init monoiofs

- core/src/types/buffer.rs
`Buffer::into_bytes` is zero copy if the underlying bytes are contiguous. Also implements `From<Buffer>` for `Bytes`.
Fixes #4857.
> feat(core/types): avoid a copy in `Buffer::to_bytes()` by cloning contiguous bytes

- core/src/docs/rfcs/3243_list_prefix.md
- core/src/services/fs/backend.rs
- core/src/types/list.rs
- core/src/types/scheme.rs
I'm not a native speaker of English, correct me if I'm wrong.
> chore: fix spelling

- core/Cargo.toml
- core/src/raw/oio/write/position_write.rs
- core/src/services/fs/backend.rs
- core/src/services/fs/writer.rs
> feat: fs add concurrent write

- core/src/docs/rfcs/3197_config.md
- core/src/services/s3/backend.rs
- core/src/services/s3/docs.md
Rename `security_token` field in S3Config to `session_token` to be coherent with AWS STS naming, and set `security_token` as deprecated.
Related Issue: https://github.com/apache/opendal/issues/4874
> refactor(services/s3)!: renamed security_token to session_token

- core/src/raw/tests/utils.rs
- core/src/services/compfs/backend.rs
- core/src/services/compfs/reader.rs
- core/src/services/compfs/writer.rs
- core/src/types/operator/builder.rs
This PR will make compfs able to run.
The tests are still failing, but we can make it runnable first.
> chore: Make compfs able to test

- bin/ofs/Cargo.lock
- core/src/services/s3/error.rs
This refers to #4894. It doesn't "fix" the stat part, but fix the `check` method as a workaround.
OpenDAL doesn't
`check` on S3 service will now fail if bucket misconfigured or bucket is yet to be created..
> fix(services/s3): NoSuchBucket is a ConfigInvalid for OpenDAL

- bindings/go/README.md
- bindings/go/benchmark_test.go
- bindings/go/opendal_test.go
Part of https://github.com/apache/opendal/issues/4892. Add a benchmark.
Here is a benchmark between new and old implementations with the same benchmark read and write behavior in backend memory:
**purego+libffi** (as `new.txt`)
```
goos: linux
goarch: arm64
pkg: github.com/apache/opendal/bindings/go
BenchmarkWrite4KiB-10            1000000              2844 ns/op
BenchmarkWrite256KiB-10           163346             10092 ns/op
BenchmarkWrite4MiB-10              12900             99161 ns/op
BenchmarkWrite16MiB-10              1785            658210 ns/op
BenchmarkRead4KiB-10              194529              6387 ns/op
BenchmarkRead256KiB-10             14228             82704 ns/op
BenchmarkRead4MiB-10                 981           1227872 ns/op
BenchmarkRead16MiB-10                328 …
```
> feat(bindings/go): add benchmark.

- core/Cargo.lock
- core/Cargo.toml
- core/README.md
- core/src/layers/fastrace.rs
- core/src/layers/mod.rs
Closes https://github.com/apache/opendal/issues/4904
`MinitraceLayer` -> `FastraceLayer`
`MinitraceWrapper` -> `FastraceWrapper`
`MinitraceAccessor` -> `FastraceAccessor`
> feat(service/fastrace): rename minitrace to fastrace

- core/src/layers/prometheus_client.rs
Closes #4909.
I did not found the bucket value in the accessor, but i found a parameter called `root` might be helpful on this case. To make this PR work as expected, I need to make sure that the bucket should be the prefix of the `root` parameter.
- refactor: seperate registering metrics and helpers to update metrics with the common labels
- feat: add root label to all the labels
this PR adds a new label on the prometheus metrics, if you had an existed dashboard, this change may make additional data lines on your chart. however it would not change your chart if you use `sum(xx) by (op)` or other metric aggregation operations.
to make this change possible, we had to make the type of labels from `(&'static str, &'static str)` to `(&'static str, String)`, this may degrade a bit performance.
> feat(prometheus-client): add metric label about `root` on using PrometheusClientLayer

- core/Cargo.lock
- core/Cargo.toml
- core/src/layers/mime_guess.rs
- core/src/layers/mod.rs
Closes #4902 .
Added a Feature Flag: `layers-mime-guess`
And a Layer type: `MimeGuessLayer`
> feat(layers/mime-guess): add a layer that can automatically set `Content-Type` based on the extension in the path.

- core/src/docs/internals/accessor.rs
- core/src/layers/immutable_index.rs
- core/src/layers/retry.rs
- core/src/services/alluxio/backend.rs
- core/src/types/builder.rs
- core/src/types/operator/builder.rs
- integrations/object_store/README.md
- integrations/object_store/examples/basic.rs
- integrations/object_store/src/lib.rs
- integrations/object_store/src/store.rs
This follows up #4915 and refers to #3240 .
> feat(core)!: from_map is now fallible

- integrations/cloudfilter/Cargo.toml
- integrations/cloudfilter/examples/readonly.rs
- integrations/cloudfilter/src/lib.rs
This PR introduces `cloud-filter v0.0.3` so that we can use OpenDAL Async APIs in Cloud Filter API callbacks.
> refactor(integrations/cloudfilter): implement Filter instead of SyncFilter

- core/src/docs/upgrade.md
Part of https://github.com/apache/opendal/issues/4923.
upgrade docs for 0.48.
No.
> docs(core): Add upgrade docs for 0.48

- .github/workflows/docs.yml
- core/Cargo.toml
- core/src/layers/blocking.rs
- core/src/lib.rs
- core/src/raw/oio/write/multipart_write.rs
- core/src/services/fs/backend.rs
- core/src/services/gdrive/builder.rs
- core/src/services/github/core.rs
- core/src/services/hdfs/backend.rs
- core/src/services/s3/backend.rs
- core/src/types/read/buffer_stream.rs
None.
Clippy is not happy after 1.80
This PR addressed all warnings.
No.
> chore: Make rust 1.80 clippy happy

- core/src/services/cacache/backend.rs
- core/src/services/memcached/backend.rs
- core/src/services/memory/backend.rs
- core/src/services/rocksdb/backend.rs
- core/src/types/builder.rs
Fix: https://github.com/apache/opendal/issues/4941
> fix(services/memory): MemoryConfig implement Debug

- core/src/layers/fastrace.rs
- core/src/layers/logging.rs
- core/src/layers/metrics.rs
- core/src/layers/oteltrace.rs
- core/src/layers/prometheus.rs
- core/src/layers/prometheus_client.rs
- core/src/layers/timeout.rs
- core/src/layers/tracing.rs
No
- fix doc link of `layers/promethues-client`
- fix some typo 
No
> fix(layers/promethues-client): doc link

- core/src/services/dropbox/core.rs
- core/src/services/redis/backend.rs
- core/src/services/s3/backend.rs
Closes #.
Lint errors are included in the commit message.
> chore(core): fix nightly lints

- bindings/java/README.md
- bindings/java/pom.xml
- bindings/java/upgrade.md
Closes https://github.com/apache/opendal/issues/4956.
https://lists.apache.org/thread/o5cmk8vsj9c7t8m23q4v8ld49q416smy
Rename artifacts id opendal-java to opendal
Package name changed.
> refactor(java)!: Rename artifacts id opendal-java to opendal

- .github/workflows/ci_integration_parquet.yml
- .github/workflows/docs.yml
- integrations/parquet/.gitignore
- integrations/parquet/Cargo.toml
- integrations/parquet/examples/async_writer.rs
- integrations/parquet/src/async_writer.rs
- integrations/parquet/src/lib.rs
part of #4868
Add parquet arrow async write support
1. Intorduce the `parquet_opendal`(integration/parquet) crate
2. Implement the `OpendalAsyncWriter `
No
> feat: introduce opendal `AsyncWriter` for parquet integrations 

- core/src/services/http/backend.rs
> feat(services/http): implement presigned request for backends without authorization

- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
Closes https://github.com/apache/opendal/issues/4963
Introduction of:
- `allow_anonymous`
- `disable_vm_metadata`
- `disable_config_load`
to `GcsConfig` and their corresponding plumbing within `GcsCore`.
Changes are internal only.
> feat(gcs): allow unauthenticated requests

- core/src/services/gcs/core.rs
Fixes an oversight I made in https://github.com/apache/opendal/pull/4965
`allow_anonymous` is for allowing access when explicitly allowed and credentials are not given (e.g. public buckets) and **not** for skipping signing entirely.
> fix(gcs): do not skip signing with `allow_anonymous`

- integrations/parquet/Cargo.toml
- integrations/parquet/examples/async_reader.rs
- integrations/parquet/src/async_reader.rs
- integrations/parquet/src/async_writer.rs
- integrations/parquet/src/lib.rs
part of #4868
Add parquet arrow async read support
Introduce opendal `AsyncReader` for parquet integrations
No
> feat: introduce opendal `AsyncReader` for parquet integrations

- core/src/services/s3/backend.rs
Closes #4974.
Simple exposure of the `role_session_name` from `reqsign` in opendal's s3 config builder.
No.
> feat(services/s3): add role_session_name in assume roles

- README.md
- integrations/parquet/README.md
- integrations/parquet/src/lib.rs
close #4868
Add README for `integrations/parquet`
No
> chore(integrations/parquet): add README

- core/src/services/dashmap/backend.rs
- core/src/services/mini_moka/backend.rs
- core/src/services/moka/backend.rs
- core/src/types/builder.rs
Closes #.
currently, the root path of service-moka and service-mini-moka can't be set(only has the default value "/").
in this PR, we add root path for moka and mini-moka
1. add root path for moka
2. add root path for mini-moka
3. fix the logic of root path for dashmap
> feat: support root path for moka and mini-moka

- integrations/virtiofs/Cargo.toml
- integrations/virtiofs/src/filesystem.rs
- integrations/virtiofs/src/lib.rs
- integrations/virtiofs/src/virtiofs.rs
- integrations/virtiofs/src/virtiofs_util.rs
None.
This PR exposes a structure in the virtiofs integration. Users can use this structure to use the virtiofs service.
The current integration will be a dummy service that can run but does not implement any file system operations. More features will be added later.
Yes.
> feat(ovfs): export VirtioFs struct

- core/Cargo.lock
- core/Cargo.toml
- core/src/services/redis/backend.rs
Part of https://github.com/apache/opendal/issues/4982
> chore(core): Bump redis version

- bindings/haskell/test/BasicTest.hs
- core/src/layers/logging.rs
- core/src/layers/mod.rs
- core/src/raw/tests/utils.rs
Closes #4918.
Breaking changes: This PR removes `with_error_level()`, `with_failure_level()` and `with_backtrace_output()` from the `DefaultLoggingLayer`.
It adds a new trait `LoggingInterceptor` to log messages.
```rust
pub trait LoggingInterceptor: Debug + Send + Sync + 'static {
fn log(
&self,
scheme: Scheme,
operation: Operation,
path: &str,
context: &str,
message: &str,
err: Option<&Error>,
);
}
```
The `LoggingLayer` has a new method to construct a new layer from an interceptor.
```rust
fn new<I: LoggingInterceptor>(notify: I) -> LoggingLayer<I> {}
```
> feat(core)!: implement an interceptor for the logging layer

- bindings/haskell/test/BasicTest.hs
- core/src/layers/logging.rs
- core/src/raw/operation.rs
- core/src/raw/tests/utils.rs
Followup of https://github.com/apache/opendal/pull/4961
> refactor(core): Use kv based context to avoid allocations

- integrations/virtiofs/Cargo.toml
- integrations/virtiofs/src/error.rs
- integrations/virtiofs/src/filesystem.rs
- integrations/virtiofs/src/filesystem_message.rs
None.
Add getattr and setattr support to virtiofs, add opened file metadata representation and conversion.
None.
> feat(ovfs): support getattr and setattr

- CHANGELOG.md
- core/src/docs/upgrade.md
Part of https://github.com/apache/opendal/issues/4982
> Bump to version 0.49.0 (Round 1)

- integrations/virtiofs/src/filesystem.rs
- integrations/virtiofs/src/filesystem_message.rs
- integrations/virtiofs/src/virtiofs_util.rs
None.
The changes introduced by this PR include:
- Adding a lookup function.
- Add unit tests for Reader and Writer (used to read and write shared memory between host and guest).
None.
> feat(ovfs): add lookup and unit tests

- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
Closes https://github.com/apache/opendal/issues/4876
An OAuth2 token cannot be set directly at the moment, instead other mechanisms are required such as the `credential` or `credential_path`.
Inclusion of a `token` within the `GcsConfig` and corresponding methods so that a bearer token is set within the signed requests to GCP.
Direct `token` being available as a option for authentication
> feat(gcs): allow setting a token directly

- core/examples/basic/src/main.rs
- core/src/services/fs/backend.rs
- core/src/services/fs/lister.rs
> feat(fs): expose the metadata for fs services

- core/Cargo.lock
- core/Cargo.toml
Bump [fastrace](https://crates.io/crates/fastrace) from 0.6 to 0.7.1
> chore(deps): bump fastrace to 0.7.1

- integrations/virtiofs/src/filesystem.rs
- integrations/virtiofs/src/filesystem_message.rs
None.
This PR will enable system calls related to file creation and deletion.
None.
> feat(ovfs): add file creation and deletion

- bindings/python/tests/test_read.py
Closes #4990 
There wasn't any warantee that the entire file would fit inside the size variable therfore read in chunks until EOF in the case that the file size is large
> fix(bindings/python): Make sure read until EOF

- integrations/virtiofs/src/buffer.rs
- integrations/virtiofs/src/filesystem.rs
- integrations/virtiofs/src/filesystem_message.rs
- integrations/virtiofs/src/lib.rs
- integrations/virtiofs/src/virtiofs_util.rs
None.
This PR  will support reading and writing data in files.
None.
> feat(ovfs): support read and write

- integrations/spring/opendal-spring-boot-starter-reactive/pom.xml
- integrations/spring/opendal-spring-boot-starter-reactive/src/main/java/org/apache/opendal/spring/config/OpenDALReactiveAutoConfiguration.java
- integrations/spring/opendal-spring-boot-starter-reactive/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- integrations/spring/opendal-spring-boot-starter/pom.xml
- integrations/spring/opendal-spring-boot-starter/src/main/java/org/apache/opendal/spring/config/OpenDALAutoConfiguration.java
- integrations/spring/opendal-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/OpenDALOperations.java
- integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/OpenDALProperties.java
- integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/OpenDALTemplate.java
- integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/ReactiveOpenDALOperations.java
- integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/ReactiveOpenDALTemplate.java
- integrations/spring/pom.xml
> feat(integrations/spring): add AutoConfiguration class for Spring Mvc and Webflux

- core/src/layers/logging.rs
As https://github.com/apache/opendal/pull/4986#discussion_r1716530358 mentioned, the default interceptor always requires some small allocations to print the log context.
Adds a new type `LoggingContext` to print context. It may reduce some allocations.
> refactor(core): new type to print context and reduce allocations

- core/src/layers/prometheus_client.rs
No
Repeatedly record the `requests_total` of the `write` operation.
- Remove duplicated `increment_request_total` metric of write operation.
- Update the example of prometheus-client layer doc
No
> fix(layers/prometheus-client): remove duplicated `increment_request_total` of write operation

- core/src/layers/prometheus_client.rs
No
simplify the code
- remove useless `scheme` field from `PrometheusAccessor` and `PrometheusMetricWrapper` type
- add help for some metrics
No
> refactor(layers/prometheus-client): remove useless `scheme` field from `PrometheusAccessor` and `PrometheusMetricWrapper` type

- core/src/layers/prometheus_client.rs
No
- optimize metrics performance
- unify the format of logic code to avoid unexpected errors
- avoid multiple clone of labels
- remove duplicated record of `errors_total` in `stat` operation
- rename `PrometheusAccessor` => `PrometheusClientAccessor`, `PrometheusMetricWrapper` => `PrometheusClientMetricWrapper`
IMO, semantically, this is a breaking change, because `PrometheusAccessor` and `PrometheusMetricWrapper` type is public types, but from a user perspective, this PR will not break existing code.
> refactor(layers/prometheus-client): avoid multiple clone of labels

- core/src/services/monoiofs/core.rs
Fixes failed [workflow run #1912](https://github.com/apache/opendal/actions/runs/10164646889/job/28110621089) and [workflow run #1913](https://github.com/apache/opendal/actions/runs/10165079139/job/28112122892) as mentioned in https://github.com/apache/opendal/pull/4944#issuecomment-2258704233, which are caused by a race condition bug in monoio.
> fix(services/monoiofs): drop JoinHandle in worker thread

- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
Support user defined metadata for `services-s3`.
Part of #4842.
> feat(core/services-s3): support user defined metadata

- core/src/services/oss/core.rs
The `strip_prefix()` method returns `None` if the string doesn't start with the prefix, so we don't need to check the prefix before stripping.
This change removes the `starts_with()` and simplifies codes.
> refactor(core/services-oss): remove the `starts_with`

- core/src/services/monoiofs/backend.rs
- core/src/services/monoiofs/core.rs
- core/src/services/monoiofs/docs.md
- core/src/services/monoiofs/writer.rs
Part of #4552.
This PR implements write append, create_dir, copy and rename operations for `monoiofs`.
> feat(services/monoiofs): append, create_dir, copy and rename

- core/src/services/github/backend.rs
- core/src/services/http/backend.rs
- core/src/services/vercel_blob/backend.rs
- core/src/services/vercel_blob/config.rs
- core/src/services/webdav/backend.rs
> chore: align the `token` method semantics

- bindings/go/go.mod
- bindings/go/go.sum
- bindings/go/tests/go.work.sum
Main Issue #5051 
This is part of #5051. I prefer to bump the version first, followed by adding Golang Windows CI to continuously monitor this feature.
> chore(bindings/go): bump ffi and sys version

- core/src/raw/oio/entry.rs
- core/src/services/aliyun_drive/lister.rs
- core/src/services/azdls/lister.rs
- core/src/services/azfile/lister.rs
- core/src/services/b2/lister.rs
- core/src/services/cos/lister.rs
- core/src/services/gdrive/lister.rs
- core/src/services/sqlite/backend.rs
Follow up of https://github.com/apache/opendal/pull/4959
> fix(core): Fix failed list related tests

- .github/workflows/ci_bindings_go.yml
- bindings/go/ffi.go
- bindings/go/opendal.go
- bindings/go/operator.go
- bindings/go/types.go
part of #4892
Add a CI linter for Go binding and fix with respective CI check.
> ci(bindings/go): add golangci-lint

- core/src/services/rocksdb/backend.rs
None
According to https://github.com/facebook/rocksdb/wiki/Prefix-Seek#transition-to-the-new-usage. rocksdb will return keys equal or larger than the prefix
> chore(services/rocksdb): fix misuse rocksdb prefix iterator

- bin/ofs/Cargo.lock
- core/src/services/oss/backend.rs
- core/src/services/oss/config.rs
> feat(services/oss): support role_arn and oidc_provider_arn

- core/src/layers/mod.rs
- core/src/layers/observe/metrics.rs
- core/src/layers/observe/mod.rs
- core/src/layers/prometheus_client.rs
Related to https://github.com/apache/opendal/pull/5049
Add a new mod called `opendal::layers::observe`. In which we will provide:
- `observe::MetricsIntercept`: A trait that users can implement metrics intercept.
- `observe::MetricsLayer`: A layer that based on `MetricsIntercept`.
Based on `observe` mod, all our existing metrics related crates can implement:
- `MetricsLayer = observe::MetricsLayer<MetricsInterceptor>`
- `PrometheusClientLayer = observe::MetricsLayer<PrometheusClientInterceptor>`
- `PrometheusLayer = observe::MetricsLayer<PrometheusInterceptor>`
All of them will share the exactly same behavior. Users only need to configure the `Interceptor` directly.
API Breaking Changes
> refactor(core)!: Add observe layer as building block

- core/src/services/fs/lister.rs
Closes #5061.
The compiler error kills the CD of rustic. We hope you can include this fix soon in a release.
no
> fix: fix rust 1.76 error due to temporary value being dropped

- README.md
- bindings/go/README.md
It seems that the Shields.io badge doesn't support the Go package subdir.
So I change to Fury.io.
> chore(README): add Go binding badge

- bindings/java/Cargo.toml
- bindings/java/src/executor.rs
Closes #5078.
replace `num_cpus` with `std::thread::available_parallelism`
> refactor(bindings/java): replace `num_cpus` with `std::thread::available_parallelism`

- core/src/services/icloud/core.rs
https://github.com/apache/opendal/pull/5072#issuecomment-2326644773
- adjust the error handling code
No
> fix(services/icloud): adjust error handling code to avoid having to write out result type explicitly

- core/src/layers/mod.rs
I forgot to export the `PrometheusClientLayerBuilder` type in #5073 
export `PrometheusClientLayerBuilder` type
> chore(layers/prometheus-client): export `PrometheusClientLayerBuilder` type

- core/src/services/monoiofs/core.rs
- core/src/services/monoiofs/reader.rs
- core/src/services/monoiofs/writer.rs
Async cancellation during file open is not handled in monoiofs that worker thread tries to send result back even if main task cancelled.
Exit worker task if main task cancelled, instead of panic.
None.
> fix(services/monoiofs): handle async cancel during file open

- core/src/services/lakefs/backend.rs
- core/src/services/lakefs/core.rs
- core/src/services/lakefs/docs.md
- core/src/services/lakefs/lister.rs
- core/src/services/lakefs/mod.rs
> feat: add list api for lakefs service.

- core/src/layers/metrics.rs
Related PR: #5064 
- rewrite metrics layer using observe layer
- add more labels
API breaking changes
> refactor(layers/metrics): rewrite metrics layer using observe layer

- core/src/services/lakefs/backend.rs
- core/src/services/lakefs/core.rs
- core/src/services/lakefs/docs.md
- core/src/services/lakefs/writer.rs
Closes #.
Refer to https://docs.lakefs.io/reference/api.html#/objects/uploadObject
> feat: add write api for lakefs service.

- core/Cargo.lock
- core/Cargo.toml
- core/src/layers/async_backtrace.rs
- core/src/layers/await_tree.rs
- core/src/layers/blocking.rs
- core/src/layers/chaos.rs
- core/src/layers/concurrent_limit.rs
- core/src/layers/dtrace.rs
- core/src/layers/error_context.rs
- core/src/layers/fastrace.rs
- core/src/layers/immutable_index.rs
- core/src/layers/logging.rs
- core/src/layers/metrics.rs
- core/src/layers/mime_guess.rs
- core/src/layers/oteltrace.rs
- core/src/layers/prometheus.rs
- core/src/layers/prometheus_client.rs
- core/src/layers/retry.rs
- core/src/layers/throttle.rs
- core/src/layers/timeout.rs
- core/src/layers/tracing.rs
- integrations/cloudfilter/Cargo.toml
Check the doc examples when running tests to avoid cases where the example does not match the current implementation.
- update docs of `layers/*`
No
> chore(layers): check the examples when running tests

- core/src/services/lakefs/backend.rs
- core/src/services/lakefs/core.rs
- core/src/services/lakefs/docs.md
> feat: add delete api for lakefs service.

- .github/workflows/release_java.yml
Part of https://github.com/apache/opendal/issues/5105
> ci: Fix upload-artifacts doesn't include hidden files

- README.md
CrateDB uses OpenDAL since version 5.9.0 for COPY TO/FROM to the Azure Blob Storage. 
We are looking forward to using it for more storage providers.
> Add CrateDB

- core/src/services/huggingface/core.rs
Closes #5122.
Example for latest response:
```json
[
{
"type": "directory",
"oid": "d564d0bc3dd917926892c55e3706cc116d5b165e",
"size": 0,
"path": "testdata/normal_dir",
"lastCommit": {
"id": "d836cf493b05f550c469d9c5cd553a3571372f17",
"title": "Add testdata",
"date": "2023-11-27T09:12:40.000Z"
}
},
{
"type": "directory",
"oid": "d564d0bc3dd917926892c55e3706cc116d5b165e",
"size": 0,
"path": "testdata/special_dir  !@#$%^&()_+-=;',",
"lastCommit": {
"id": "d836cf493b05f550c469d9c5cd553a3571372f17",
"title": "Add testdata",
"date": "2023-11-27T09:12:40.000Z"
}
},
{
"type": "file",
"oid": "9f37f432f4f882512be8e29529eb7b68a9ca7b3f",
"size": 30482,
"path": "testdata/normal_file.txt",
"lastCommit": {
"id": "d836cf493b05f550c469d9c5cd553a3571372f17",
"title": "Add testdata",
"date": …
```
> fix(services/huggingface): Align with latest HuggingFace API

- core/src/services/lakefs/backend.rs
- core/src/services/lakefs/core.rs
- core/src/services/lakefs/docs.md
> feat: add copy api for lakefs service. 

- core/src/services/cloudflare_kv/backend.rs
- core/src/services/cloudflare_kv/error.rs
- No need for parse_error to be async
- No need to return a Result, since everything that can fail has a fallback (`unwrap_or`, `unwrap_or_else`)
removes unneeded async and Result from parse_error()
No
> refactor(services/cloudflare-kv): remove unneeded async and result on parse_error

- bindings/python/src/operator.rs
The API is deprecated from #4921
> chore(bindings/python): deprecate via_map method

- bin/ofs/Cargo.lock
- bin/ofs/Cargo.toml
- bin/ofs/src/main.rs
- integrations/fuse3/Cargo.toml
- integrations/fuse3/src/file_system.rs
Closes https://github.com/apache/opendal/issues/4409
> feat(ofs): introduce ofs macos support

- core/src/services/sftp/backend.rs
- core/src/services/sftp/reader.rs
- core/src/types/blocking_read/buffer_iterator.rs
- core/src/types/context/read.rs
- core/src/types/read/buffer_stream.rs
- core/src/types/read/futures_async_reader.rs
- core/src/types/read/futures_bytes_stream.rs
- core/src/types/read/reader.rs
None
We used to perform a `stat` operation to make sure we have the read size known. But in the `read_all` cases, we don't need to care about that.
This PR refactor the internal range parse logic so that we can read all without fetching it's metadata first.
> feat: Reduce stat operation if we are reading all

- integrations/spring/opendal-spring-boot-starter-reactive/src/main/java/org/apache/opendal/spring/config/OpenDALReactiveAutoConfiguration.java
- integrations/spring/opendal-spring-boot-starter-reactive/src/test/java/org/apache/opendal/spring/config/OpenDALReactiveAutoConfigurationTest.java
- integrations/spring/opendal-spring-boot-starter/src/main/java/org/apache/opendal/spring/config/OpenDALAutoConfiguration.java
- integrations/spring/opendal-spring-boot-starter/src/test/java/org/apache/opendal/spring/config/OpenDALAutoConfigurationTest.java
- integrations/spring/opendal-spring/pom.xml
- integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/DefaultOpenDALSerializer.java
- integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/DefaultOpenDALSerializerFactory.java
- integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/OpenDALSerializer.java
- integrations/spring/opendal-spring/src/main/java/org/apache/opendal/spring/core/OpenDALSerializerFactory.java
- integrations/spring/opendal-spring/src/test/java/org/apache/opendal/spring/core/DefaultOpenDALSerializerFactoryTest.java
> feat(integrations/spring): add spring serialize method

- core/src/types/execute/executors/tokio_executor.rs
> chore: fix typos in tokio_executor.rs

- bindings/c/include/opendal.h
- bindings/c/src/entry.rs
- bindings/c/src/error.rs
- bindings/c/src/lister.rs
- bindings/c/src/metadata.rs
- bindings/c/src/operator.rs
- bindings/c/src/operator_info.rs
- bindings/c/src/reader.rs
- bindings/c/src/types.rs
- bindings/c/src/writer.rs
> refactor: more consistent C binding pattern

- bindings/c/include/opendal.h
- bindings/c/src/types.rs
- bindings/go/types.go
Closes #5165.
> `forget` does not guarantee that pointers to this memory will remain valid. The need comes up in some specialized use cases for FFI or unsafe code, but even then, [ManuallyDrop](https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html) is typically preferred.
refer to https://doc.rust-lang.org/std/mem/fn.forget.html
the implementation of `Vec::into_raw_parts`
https://doc.rust-lang.org/1.81.0/src/alloc/vec/mod.rs.html#883
Also, transmute `*const _` to `* mut _` is an undefined behavior in any cases, it is fixed in this commit.
> fix(bindings/c): use `ManuallyDrop` instead of `forget` to make sure pointer is valid

- bindings/java/src/layer.rs
- bindings/java/src/main/java/org/apache/opendal/layer/ConcurrentLimitLayer.java
- bindings/java/src/main/java/org/apache/opendal/layer/RetryLayer.java
- bindings/java/src/test/java/org/apache/opendal/test/LayerTest.java
> feat(bindings/java): support ConcurrentLimitLayer

- integrations/parquet/Cargo.toml
- integrations/parquet/src/async_reader.rs
None.
Use newly added ParquetMetaDataReader to replace our own metadata parse logic.
ref: https://github.com/apache/arrow-rs/issues/6002
None
> refactor(integration/parquet): Use ParquetMetaDataReader instead

- core/src/raw/ops.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/types/capability.rs
- core/src/types/operator/operator.rs
- core/src/types/operator/operator_futures.rs
- core/tests/behavior/async_write.rs
Closes #5097
Yes, add an option`if_none_match` for `write_with`.
> feat: Add if_none_match for write

- core/src/services/s3/lister.rs
None
This PR will mark xml deserialize error as temporary during list
```
// Allow S3 list to retry on XML deserialization errors.
//
// This is because the S3 list API may return incomplete XML data under high load.
// We are confident that our XML decoding logic is correct. When this error occurs,
// we allow retries to obtain the correct data.
```
Also from: https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html
> A 200 OK response can contain valid or invalid XML. Make sure to design your application to parse the contents of the response and handle it appropriately.
> fix(services/s3): Mark xml deserialize error as temporary during list

- .github/workflows/ci_bindings_go.yml
- bindings/go/README.md
- bindings/go/tests/go.work
- bindings/go/tests/go.work.sum
Part of #4892 
Add contributing docs for Golang.
Currently, it is hard for community members to maintain the Go binding, see: https://github.com/apache/opendal/pull/5171#issuecomment-2399225899
> Add contributing docs for Golang

- .github/workflows/ci_bindings_c.yml
- bindings/c/CMakeLists.txt
- bindings/c/Makefile
- bindings/c/examples/basic.c
- bindings/c/tests/bdd.cpp
- bindings/c/tests/error_msg.cpp
- bindings/c/tests/list.cpp
- bindings/c/tests/opinfo.cpp
- bindings/zig/build.zig
Closes #3516.
As state in #3516, CMake works well for large project than makefile.
Also in CMake we can fetch the gtest from web and use it simply than depending on a system-level gtest.
- Added a new CMakeLists.txt for the C binding part.
- Also fixed a build issue (compiler error) inside `examples/basic.c`.
- Remove useless part of Makefile.
- Change the zig build since it depends on c build.
Note that Valgrind part is removed and replaced by AddressSanitizer.
Users of C binding should be aware of this change, and should build from CMake instead of Makefile from now on.
cc @tisonkun
> build(bindings/c): replace the build system with CMake

- bindings/c/CMakeLists.txt
- bindings/c/CONTRIBUTING.md
- bindings/c/README.md
None.
After #5182, we need to update docs to reflect our new changes.
- update README and CONTRIBUTING of C binding.
- replace `.a` `.so` by more generalized variables.
None.
> docs(bindings/c): update docs for CMake replacing

- core/src/raw/http_util/client.rs
- core/src/raw/http_util/mod.rs
- core/src/services/cos/backend.rs
- core/src/services/gcs/backend.rs
- core/src/services/oss/backend.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
> feat(core): abstract HttpFetch trait for raw http client

- bindings/cpp/CMakeLists.txt
- bindings/cpp/CONTRIBUTING.md
- bindings/cpp/README.md
Closes #5187.
Currently C++ binding uses find_package to locate system-wide libraries like GTest and Boost.
We can replace them by FetchContent to fetch them online and build them by needs (just like cargo) instead of using system libraries (which we cannot control versions and optional features.)
- replace find_package with FetchContent (but still leave a fallback to find_package for dep-reusing purpose)
- docs for the changes
None.
> build(bindings/cpp): fetch and build dependencies instead of finding system libs

- core/Cargo.lock
- core/Cargo.toml
- core/src/services/mod.rs
- core/src/services/nebula_graph/backend.rs
- core/src/types/operator/builder.rs
- core/src/types/scheme.rs
Closes #4553.
Support `read`, `write`, `list`, `delete` ops on NebulaGraph.
To access NebulaGraph, users must provide the `username` and `password` for NebulaGraph, as well as specify the `space`, `tag`, and the `key field` and `value field` of the `tag`.
Since each `vertex` in NebulaGraph must have a unique ID(called VID), but NebulaGraph lacks a self-incrementing ID, the unique IDs are generated using the Snowflake algorithm. Additionally, the `set` operation involves first `delete` existing original `vertex`, followed by inserting a new `vertex`.
NebulaGraph does not support the Blob type, hence `Base64+string` type is employed for file access. If it's supported in the future, just remove `Base64`.
No(?)
> feat: Support NebulaGraph

- core/edge/s3_aws_assume_role_with_web_identity/src/main.rs
- core/src/docs/rfcs/3243_list_prefix.md
- core/src/types/operator/blocking_operator.rs
- core/src/types/operator/operator.rs
- core/tests/behavior/async_delete.rs
- core/tests/behavior/async_list.rs
- core/tests/behavior/async_write.rs
- core/tests/behavior/blocking_delete.rs
- core/tests/behavior/blocking_list.rs
- integrations/dav-server/src/fs.rs
- integrations/parquet/src/async_writer.rs
Closes #5192.
Rename it to `exists` for consistence with `std::fs::exists`
Introduces `exists` and deprecate `is_exist` in `core/types/operator`
Yes, it is a breaking change.
> refactor(types/operator): rename is_exist to exists

- bindings/cpp/include/opendal.hpp
- bindings/cpp/src/lib.rs
- bindings/cpp/src/opendal.cpp
- bindings/cpp/tests/basic_test.cpp
Closes #.
Since `opendal::types::operator::blocking_operator::BlockingOperator::is_exist` is deprecated and renamed to `exists`, we should also rename it in c++ binding.
Add `Operator::exists` and mark `Operator::is_exist` deprecated.
Users who still use `is_exist` will receive deprecated warnings issued by compilers.
> feat(bindings/cpp): rename is_exist to exists as core did

- bindings/c/cbindgen.toml
- bindings/c/include/opendal.h
- bindings/c/src/lib.rs
- bindings/c/src/operator.rs
- bindings/c/src/result.rs
- bindings/c/tests/bdd.cpp
Closes #.
Just like #5198, we need to do it in C binding as well.
- Fixed rustc deprecated warning in C binding
- Add `opendal_operator_exists` and `opendal_result_exists`
- Mark `opendal_operator_is_exist` deprecated
Users will receive deprecated warnings by the C compiler if they're still using `opendal_operator_is_exist`.
> feat(bindings/c): add opendal_operator_exists and mark is_exist deprecated

- .asf.yaml
As discussed at https://lists.apache.org/thread/d9nz51qvy59y2vnqcrrr1skgomhcl11f
---
Hello, everyone
I'm initiating this thread to explore the feasibility of integrating GitHub discussions into dev@o.a.o.
There is a growing number of discussions[1] regarding whether the ASF should continue to rely on mailing lists. Provided that all our discussions remain public, searchable, and archivable, it might be worthwhile to consider adopting new methods.
Personally, I would like to establish a discourse for OpenDAL, but we currently lack the necessary resources. Therefore, I am considering the use of GitHub discussions as an alternative.
Currently, we are utilizing GitHub discussions. The primary difference is that we do not yet recognize it as our official main channel. By redirecting GitHub …
> ci: Send discussions to dev@o.a.o

- .asf.yaml
None
Remove the `[DISCUSS]` prefix so that we can start voting like normal.
> ci(asf): Don't add `[DISCUSS]` prefix for discussion

- bin/oay/Cargo.lock
- bin/oay/Cargo.toml
- bin/ofs/Cargo.lock
- bin/ofs/Cargo.toml
- bin/oli/Cargo.lock
- bin/oli/Cargo.toml
No
Remove useless deps of `bin/oay`, `bin/ofs` and `bin/oli`
```
➜  bin git:(remove-useless-deps) cargo machete
Analyzing dependencies of crates in this directory...
cargo-machete didn't find any unused dependencies in this directory. Good job!
Done!
```
No
> chore(bin/*): remove useless deps

- core/src/services/ftp/lister.rs
Part of #4746.
ftp service will also return last modified timestamp.
Nope.
I found other problems that I want to change but they are not part of the issue.
1. I also found the underlying crate `suppaftp` supports async. I want to support it. This might be a breaking change for FTP service. Do you consider support async for ftp?
2. I also see sftp implementation uses another crate `openssh_sftp_client`. I have skimmed through these crates documentation and code. I don't want to expand this comparasion too much. In short, `suppaftp` depends tls implementation in Rust while `openssh_sftp_client` depends on OpenSSH. `suppaftp` has slightly less code. I am considering using `suppaftp` if that fulfill the current implementation. Happy to discuss more.
3. I tested this locally by using a FTP …
> feat(services/ftp): List dir shows last modified timestamp

- README.md
- website/community/release/release.md
Follow up of https://github.com/apache/opendal/pull/5201
This PR will change our docs for release process.
> docs: Move our release process to github discussions

- bindings/java/Cargo.toml
- bindings/python/Cargo.toml
Follow up https://github.com/apache/opendal/issues/5000 and https://github.com/apache/opendal/pull/5013
We're now using sqlx so that as long as services-postgres works, MySQL may be fine.
> build: enable services-mysql for Java and Python bindings

- integrations/compat/Cargo.toml
- integrations/compat/src/v0_50_to_v0_49.rs
Closes https://github.com/apache/opendal/issues/5235
opendal v0.50's `Capability` has a new field called `write_with_if_none_match`, we can't transmute it.
Add convert between `Capability`.
> fix(integrations/compat): Capability has different fields

- integrations/compat/src/v0_50_to_v0_49.rs
Follow up of https://github.com/apache/opendal/issues/5235
> fix(integrations/compat): Fix dead loop happened during list

- website/community/pmc_members/nominate-committer.md
It's a typo fix.
This is the proper way to spell the GitHub brand name.
Fixed a typo in the description.
No, there are no user-facing or API changes.
> docs: change "Github" to "GitHub"

- core/src/layers/async_backtrace.rs
- core/src/layers/await_tree.rs
- core/src/layers/chaos.rs
- core/src/layers/error_context.rs
- core/src/layers/fastrace.rs
- core/src/layers/logging.rs
- core/src/layers/oteltrace.rs
- core/src/layers/retry.rs
- core/src/layers/tracing.rs
No
Enter the await point before processing `Result` to simplify the combination code
No
> chore(core/layers): adjust await point to simplify combinator code

- core/src/types/operator/blocking_operator.rs
Closes #5260
The logic for `is_exist` has been kept in place, although it is deprecated and the new method `exists` has been created. To keep it DRY and I think it makes sense, to let `is_exist` call `exists` internally.
We call `exists` from `is_exist`.
No.
> chore(core/blocking_operator): deduplicate deprecated `is_exist` logic

- .github/workflows/ci_integration_object_store.yml
- integrations/object_store/src/lib.rs
- integrations/object_store/src/store.rs
Closes #5237
Based on other integration CI: https://github.com/apache/opendal/blob/b9e06bf7297aa9fbf5bc0c5c0a569283af44dfb3/.github/workflows/ci_integration_parquet.yml#L49
> chore: run object_store tests in CI

- core/Cargo.toml
- core/src/services/s3/backend.rs
- core/src/services/s3/config.rs
Close #5275 
For S3 compatible service, try load endpoint_url from config file or environment
> feat(core/services-s3): try load endpoint from config

- .github/workflows/test_benchmark.yml
None
Publib repo doesn't need a token. We can allow forked repo to upload data by remove the token.
> ci: Remove the token of codspeed

- core/src/layers/blocking.rs
- core/src/layers/complete.rs
- core/src/layers/error_context.rs
- core/src/layers/fastrace.rs
- core/src/layers/immutable_index.rs
- core/src/layers/logging.rs
- core/src/layers/oteltrace.rs
- core/src/layers/tracing.rs
- core/src/raw/layer.rs
No
The `metadata` method of `LayeredAccess` and `info` method of `LayeredAccess` is misaligned.
we used to use `metadata` and changed it to `info`.
- rename `metadata` method of `trait LayeredAccess`:
`fn metadata(&self) -> Arc<AccessorInfo>` => `fn info(&self) -> Arc<AccessorInfo>`
`LayeredAccess::metadata` => `LayeredAccess::info`
> chore(core/layers): align `info` method of `trait Access` and `trait LayeredAccess`

- core/src/layers/oteltrace.rs
No
- rename tracer span name of info method in `oteltrace` layer: `metadata` => `info`
No
> chore(layers/oteltrace): adjust tracer span name of info method

- .github/workflows/ci_bindings_ruby.yml
- bindings/ruby/.gitignore
- bindings/ruby/.rspec
- bindings/ruby/.standard.yml
- bindings/ruby/Cargo.toml
- bindings/ruby/Gemfile
- bindings/ruby/README.md
- bindings/ruby/Rakefile
- bindings/ruby/extconf.rb
- bindings/ruby/opendal.gemspec
- bindings/ruby/src/capability.rs
- bindings/ruby/src/lib.rs
- bindings/ruby/src/metadata.rs
- bindings/ruby/src/operator.rs
- bindings/ruby/test/blocking_op_test.rb
- bindings/ruby/test/capability_test.rb
- bindings/ruby/test/test_helper.rb
Part of #5227.
* This builds a few operations for testing.
* More features for Ruby binding and testing on GitHub.
I would suggest to review this commit by commit. I also noticed the options to initialize `Operator` can only be a dictionary. Keyword arguments would be better.
> feat(bindings/ruby): Add simple operators to Ruby binding

- core/src/docs/rfcs/3911_deleter_api.md
Part of #3911
While revisit this idea, I found that there is no need for `deleter` to have `recursive`. Users who want remove dir recursively can just use `op.lister_with(path).recursive(true)` and pass to `deleter`.
Remove `recursive` from deleter
RFC Changes.
> RFC-3911: Remove recursive from deleter

- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
Relates to https://github.com/apache/opendal/issues/4842
Please do not merge yet, I'm not sure this works.
I didn't see the CI for GCS behaviour tests. Im not sure that this PR is ok, as I do not have a GCP account and couldn't find out how to test it locally. Tried it with https://github.com/fsouza/fake-gcs-server and I also couldn't figure it out. Also, I can't get the gcs behavior tests running in local
Is the behaviour test plan ok? https://github.com/apache/opendal/actions/runs/11652657364/job/32444123433#step:3:39
It seems that the gcs service is being filtered out in this condition https://github.com/apache/opendal/blob/330bd74f3ace74f15966dfb2465191aa7c1ae5a6/.github/scripts/test_behavior/plan.py#L59
Maybe a maintainer has to manually run that check?
> feat(core/services-gcs): support user defined metadata

- bindings/zig/build.zig
- bindings/zig/build.zig.zon
- bindings/zig/src/opendal.zig
N/D
It tends to be usable and testable.
* Operator wrapper added
* more unittests
* wip: add stackful-async ([zigcoro library](https://github.com/rsepassi/zigcoro)) support
* replace `@cImport/@cInclude` to `translate-c` only (see: [zig#20875])
* add custom test-runner output ([more info](https://www.openmymind.net/Using-A-Custom-Test-Runner-In-Zig/))
>[!NOTE]
> `zig build [run|test] --summary [all|new|failures|none]` show build-runner tree-output, not test output.
[zig#20875]: https://github.com/ziglang/zig/issues/20875
testable and easy to use.
> refactor (bindings/zig): Improvements

- bindings/c/CMakeLists.txt
Closes #5307 
Currently the build is broken and leads to an error
Bumps the min version of CMake required to build the code
No
> fix(bindings/c): Bump min CMake version to support CMP0135

- core/src/raw/ops.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/types/capability.rs
- core/src/types/operator/operator.rs
- core/src/types/operator/operator_futures.rs
- core/tests/behavior/async_write.rs
Closes #5286.
Add `op.write_with(path, bs).if_not_exists(true)`
> feat(core): add `if_not_exist` in `OpWrite`

- core/src/docs/rfcs/0000_remove_metakey.md
- core/src/docs/rfcs/5314_remove_metakey.md
- core/src/docs/rfcs/mod.rs
Result of https://github.com/apache/opendal/discussions/5287
New RFC.
Not yet.
> RFC-5313: Remove Metakey

- core/src/types/capability.rs
Nope
The old debug output of capability requires multiple alloc.
This PR makes it zero cost and removes some not useful debug output.
> chore: Polish the debug output of capability

- core/src/types/capability.rs
- core/src/types/metadata.rs
Part of https://github.com/apache/opendal/issues/5314
Allow users to know which metadata will exist in `stat` and `list` before calling.
This PR is bit misalign with the RFC, will update back.
This PR adds the `{stat,list}_has_*` in capability to carry the metadata that backend returns
> feat: Add {stat,list}_has_* to carry the metadata that backend returns

- bin/oay/src/services/s3/service.rs
- bindings/java/src/error.rs
- bindings/java/src/lib.rs
- bindings/java/src/operator_input_stream.rs
- core/Cargo.lock
- core/Cargo.toml
- core/src/layers/complete.rs
- core/src/layers/mime_guess.rs
- core/src/lib.rs
- core/src/raw/ops.rs
- core/src/services/fs/backend.rs
- core/src/services/fs/lister.rs
- core/src/services/webdav/core.rs
- core/src/types/entry.rs
- core/src/types/list.rs
- core/src/types/metadata.rs
- core/src/types/mod.rs
- core/src/types/operator/blocking_operator.rs
- core/src/types/operator/operator.rs
- core/src/types/operator/operator_functions.rs
- core/src/types/operator/operator_futures.rs
- core/tests/behavior/async_list.rs
- core/tests/behavior/blocking_list.rs
- integrations/cloud_filter/src/lib.rs
- integrations/compat/Cargo.toml
- integrations/fuse3/src/file_system.rs
- integrations/object_store/src/store.rs
- integrations/object_store/src/utils.rs
Part of https://github.com/apache/opendal/issues/5314
To make `Lister` behavior more predictable.
Remove the metakey concept.
> refactor: Remove metakey concept

- core/src/types/operator/blocking_operator.rs
- core/src/types/operator/operator.rs
None
Improve docs
Make the behavior of different options more clear.
No, just docs change.
> docs: Polish docs for write with if not exists

- core/src/raw/futures_util.rs
Remove `unsafe` from trait `unsafe trait MaybeSend`
Closes #.
A safe trait provides the same functionality as its unsafe counterpart but requires no safety guarantees from the implementor, making the unsafe keyword unnecessary.
Remove `unsafe` from the trait declaration.
This change is backward compatible
> refactor(core): MaybeSend does not need to be unsafe

- core/src/services/webhdfs/backend.rs
Closes #5267.
Renames the auth value from "delegation_token" to "delegation" based on [doc](https://hadoop.apache.org/docs/r3.3.2/hadoop-project-dist/hadoop-hdfs/WebHDFS.html#Authentication)
> fix(services/webhdfs): rename auth value

- .github/scripts/test_go_binding/matrix.yaml
- .github/workflows/ci_bindings_go.yml
- bindings/go/tests/behavior_tests/go.mod
- bindings/go/tests/behavior_tests/opendal_test.go
Part of https://github.com/apache/opendal/issues/5326.
> feat(bindings/go): support darwin

- bindings/python/pyproject.toml
Closes #.
`version` should be defined or it should be included in `project.dynamic`
> build(python): fix pyproject meta file

- .github/workflows/release_python.yml
- bindings/python/Cargo.toml
- bindings/python/pyproject.toml
https://github.com/apache/opendal/discussions/5335
Closes https://github.com/apache/opendal/discussions/5335
build cp310 wheel with non-abi3 flags
no
> build(bindings/python): add python 3.10 back and remove pypy

- core/src/layers/complete.rs
- core/src/services/gdrive/backend.rs
- core/src/services/gdrive/lister.rs
> feat(services/gdrive): List shows modified timestamp gdrive

- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
Hi, first-time contribution, let me know if there is anything I am missing!
close: #5329 
user need to pass `Vec<(String, OpDelete)>` when deleting objects
> feat(service/s3): support delete with version

- bin/oay/Cargo.lock
- bin/ofs/Cargo.lock
- bin/oli/Cargo.lock
None
It seems `flagset` is no longer used by `oay`, `ofs`, and `oli` but still exists in their `cargo.lock`. They get deleted automatically in the local environment.
> chore: remove flagset in cargo.lock

- .github/workflows/ci_bindings_nodejs.yml
- .github/workflows/docs.yml
I can create a ticket if required.
GitHub will deprecate `upload-artifact@v3` in coming weeks. v3 will no longer work. Read annocument [here](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). This PR bumps the `upload-artifact` to v4.
No.
> Update to upload-artifact@v4

- core/src/types/operator/operator.rs
Part of https://github.com/apache/opendal/issues/2611.
> docs(core): add the description of version parameter for operator

- integrations/cloud_filter/tests/behavior/main.rs
- integrations/dav-server/src/fs.rs
- integrations/virtiofs/src/buffer.rs
- integrations/virtiofs/src/virtiofs_util.rs
None
Rust has been to upgraded to 1.83.0, which has caused some issues related to Clippy. such as:
https://github.com/apache/opendal/actions/runs/12097756740/job/33733480298?pr=5370
https://github.com/apache/opendal/actions/runs/12097756774/job/33733479648?pr=5370
https://github.com/apache/opendal/actions/runs/12097756741/job/33733480352?pr=5370
> chore: fix cargo clippy

- bindings/python/CONTRIBUTING.md
- bindings/python/Cargo.toml
- bindings/python/src/file.rs
- bindings/python/src/lib.rs
- bindings/python/src/lister.rs
- bindings/python/src/operator.rs
- bindings/python/src/utils.rs
Closes #5336.
Sorry, my skills are limited and I may not have made the changes correctly. 
However, all the tests have passed, but I still don't know how to make the changes here. Can someone help me?
opendal/bindings/python/src/lister.rs
```rs
#[pymethods]
impl AsyncLister {
fn __aiter__(slf: PyRef<'_, Self>) -> PyRef<Self> {
slf
}
fn __anext__(slf: PyRefMut<'_, Self>) -> PyResult<Option<PyObject>> {
let lister = slf.0.clone();
let fut = future_into_py(slf.py(), async move {
let mut lister = lister.lock().await;
let entry = lister.try_next().await.map_err(format_pyerr)?;
match entry {
Some(entry) => Ok(Python::with_gil(|py| Entry::new(entry).into_py(py))),
None => Err(PyStopAsyncIteration::new_err("stream exhausted")),
}
})?;
Ok(Some(fut.into()))
}
}
```
> feat: upgrade pyo3 to 0.23

- bindings/ocaml/lib/operator.mli
- bindings/ocaml/src/operator/mod.rs
none
`ocamlformat`  has been upgrade from 0.26.2 to 0.27.0, which has caused some format issues. Here is the link:
https://github.com/apache/opendal/actions/runs/12140156159/job/33849306867?pr=5352
> chore: fix Bindings OCaml CI 

- bin/oli/Cargo.lock
- bin/oli/Cargo.toml
- bin/oli/src/commands/cp.rs
Closes #.
I feel uneasy without seeing the progress bar.
Add progress bar for `oli cp` command. It looks like this (before clear):
No
> feat: add progress bar for oli cp command

- bin/oli/README.md
- bin/oli/src/commands/cat.rs
- bin/oli/src/commands/cp.rs
- bin/oli/src/commands/ls.rs
- bin/oli/src/commands/rm.rs
- bin/oli/src/commands/stat.rs
- bin/oli/src/config/mod.rs
Closes #.
The document about `oli`'s usage is misleading
- Update document
- Add hint to error text
- Add expected format to help text
Yes, some text
> fix: update document against target format check and add hints

- .github/workflows/ci_bin_oli.yml
- bin/oli/src/commands/cp.rs
Closes #.
- Fix Clippy warning introduced in https://github.com/apache/opendal/pull/5369
- Fix GitHub Action file to run CI for `oli` correctly.
CI-related changes
no
> fix: oli clippy and CI file

- core/src/types/buffer.rs
Closes #5385
The `Buffer::to_bytes` method currently performs unnecessary copying when the buffer is NonContiguous but contains only a single Bytes. This results in reduced performance due to redundant data duplication. By optimizing `to_bytes` to return the single `Bytes` directly without copying, we can improve the efficiency of buffer operations.
- Optimized the `Buffer::to_bytes` method to return the single `Bytes` directly when `NonContiguous` contains only one `Bytes`, avoiding unnecessary copying.
No user-facing changes. This optimization improves internal performance without altering the public API or behavior visible to users.
> feat(types/buffer): skip copying in `to_bytes` when `NonContiguous` contains a single `Bytes`

- bin/oli/README.md
- bin/oli/src/bin/oli.rs
- bin/oli/src/commands/mod.rs
- bin/oli/src/commands/mv.rs
- bin/oli/src/config/mod.rs
- bin/oli/tests/mv.rs
- core/src/types/entry.rs
Part of: https://github.com/apache/opendal/issues/422
> feat(bin/oli): support command mv

- core/src/layers/blocking.rs
- core/src/layers/capability_check.rs
- core/src/layers/complete.rs
- core/src/layers/correctness_check.rs
- core/src/layers/mod.rs
- core/src/layers/timeout.rs
- core/src/raw/accessor.rs
- core/src/types/operator/builder.rs
> feat(core/layers): add correctness_check and capability_check layer to verify whether the operation and arguments is supported

- .github/services/s3/r2/disabled_action.yml
- bindings/c/include/opendal.h
- bindings/c/src/operator_info.rs
- bindings/go/operator_info.go
- bindings/go/types.go
- bindings/java/src/lib.rs
- bindings/java/src/main/java/org/apache/opendal/Capability.java
- bindings/java/src/test/java/org/apache/opendal/test/OperatorInfoTest.java
- bindings/java/src/utility.rs
- bindings/nodejs/generated.d.ts
- bindings/nodejs/src/capability.rs
- bindings/python/python/opendal/__init__.pyi
- bindings/python/src/capability.rs
- bindings/ruby/src/capability.rs
- core/src/lib.rs
- core/src/services/gcs/backend.rs
- core/src/services/oss/backend.rs
- core/src/services/oss/config.rs
- core/src/services/oss/core.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/config.rs
- core/src/services/s3/core.rs
- core/src/types/capability.rs
- core/src/types/operator/blocking_operator.rs
- core/src/types/operator/operator.rs
Part of https://github.com/apache/opendal/issues/3922
Batch doesn't exist in opendal anymore.
Remove batch capability.
batch capability has been removed.
> refactor: Remove batch concept from opendal

- core/src/lib.rs
- core/src/raw/http_util/header.rs
- core/src/services/s3/backend.rs
- core/src/types/capability.rs
- core/src/types/metadata.rs
follow #5390, 
> I think we need to add content_encoding to the metadata to properly test it? [docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseSyntax](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseSyntax)
`MetaData` now includes a field `content_encoding`
> feat(core): Add `content_encoding` to `MetaData`

- core/src/raw/ops.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/types/capability.rs
- core/src/types/operator/operator.rs
- core/src/types/operator/operator_futures.rs
- core/tests/behavior/async_write.rs
Closes #5378 
I think we need to add `content_encoding` to the metadata to properly test it? https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseSyntax
Add `op.write_with(path, content).content_encoding("encoding")`
> feat:(core): add `content encoding` to `Opwrite`

- .gitignore
- .vscode/settings.json
For now, our project structure is not similar with default rust project. 
The developer need to extra config the rust-analyzer before they start to write the code.
I would like to make the config right out of the box
> chore: Add default vscode config for more friendly developer experience

- core/src/services/obs/backend.rs
- core/src/services/obs/core.rs
Part of: #4842
Based on: https://support.huaweicloud.com/intl/en-us/ugobs-obs/obs_41_0025.html#section2
> feat(services/obs): support user defined metadata

- integrations/cloud_filter/src/lib.rs
- integrations/cloud_filter/tests/behavior/fetch_data.rs
- integrations/cloud_filter/tests/behavior/utils.rs
The `Operator::lister` will not fetch `Metadata::content_length` implicitly, and the zero `Metadata::content_length` causes `CloudFiler::fetch_data` won't be called.
Related #5414 
Call `Operator:stat` explicitly in `CloudFiler::fetch_placeholders`.
> fix(integrations/cloud_filter): use explicit `stat` instead of `Entry::metadata` in `fetch_placeholders`

- .github/workflows/test_behavior_integration_cloud_filter.yml
- integrations/cloud_filter/tests/behavior/utils.rs
When I try to release the v0.51.0-rc.1, I found "Behavior Test Integration Cloud Filter" failed and it's not been triggered when the file changed.
https://github.com/apache/opendal/actions/runs/12332075431/job/34419665126
Fix the CI first
> chore(ci): fix invalid Behavior Test Integration Cloud Filter trigger

- CHANGELOG.md
Part of #5412 
| Name                      | Version | Next    |
| -                         | -       | -       |
| core                      | 0.50.2  | 0.51.0  |
| integrations/cloud_filter | 0.0.3   | 0.0.4   |
| integrations/compat       |1.0.1      | 1.0.2   |
| integrations/dav-server   | 0.2.2   | 0.2.3   |
| integrations/fuse3        | 0.0.9   | 0.0.10  |
| integrations/object_store | 0.48.2  | 0.48.3  |
| integrations/parquet      | 0.2.2   | 0.2.3   |
| integrations/spring       | -       | -       |
| integrations/unftp-sbe    | 0.0.9   | 0.0.10   |
| integrations/virtiofs     | -       | -       |
| bin/oay                   | 0.41.13 | 0.41.14 |
| bin/ofs                   | 0.0.14  | 0.0.15  |
| bin/oli                   | 0.41.13 | 0.41.14 |
| bindings/c                | …
> Bump version to v0.51.0-rc.2

- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/main/java/org/apache/opendal/OperatorOutputStream.java
- bindings/java/src/test/java/org/apache/opendal/test/behavior/BehaviorExtension.java
- bindings/java/src/test/java/org/apache/opendal/test/behavior/BehaviorTestBase.java
- bindings/java/src/test/java/org/apache/opendal/test/behavior/RegressionTest.java
This closes https://github.com/apache/opendal/issues/5421.
cc @BaurzhanSakhariev
> feat: impl configurable OperatorOutputStream maxBytes

- website/community/release/release.md
@Xuanwo do we have a script to update Cargo.toml's version now? If so, perhaps we can add those bindings' version bump also.
> docs: Update release.md

- core/src/layers/observe/mod.rs
Closes #.
Grand unstoppable panic after switching to the built-in PrometheusLayer 🥲
At least for Prometheus client, we should always provide a label set with the same length. Current implementation will ignore the "path" label if path is empty.
bugfix
> fix: always contains path label if configured

- CHANGELOG.md
- bindings/haskell/opendal.cabal
- bindings/java/pom.xml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-arm64-gnu/package.json
- bindings/nodejs/npm/linux-arm64-musl/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-arm64-msvc/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
Part of #5412 
| Name                      | Version | Next    |
| -                         | -       | -       |
| core                      | 0.50.2  | 0.51.0  |
| integrations/cloud_filter | 0.0.3   | 0.0.4   |
| integrations/compat       |1.0.1      | 1.0.2   |
| integrations/dav-server   | 0.2.2   | 0.2.3   |
| integrations/fuse3        | 0.0.9   | 0.0.10  |
| integrations/object_store | 0.48.2  | 0.48.3  |
| integrations/parquet      | 0.2.2   | 0.2.3   |
| integrations/spring       | -       | -       |
| integrations/unftp-sbe    | 0.0.9   | 0.0.10   |
| integrations/virtiofs     | -       | -       |
| bin/oay                   | 0.41.13 | 0.41.14 |
| bin/ofs                   | 0.0.14  | 0.0.15  |
| bin/oli                   | 0.41.13 | 0.41.14 |
| bindings/c                | …
> Bump version to v0.51.0-rc.3

- bin/oli/Cargo.lock
- bin/oli/Cargo.toml
> refactor: tidy up oli build

- .github/workflows/release_python.yml
free threading build is currently broken on windows
https://github.com/apache/opendal/actions/runs/12470186276
> ci: disable windows free-thread build

- bindings/python/src/errors.rs
- bindings/python/src/lib.rs
- bindings/python/src/operator.rs
Closes https://github.com/apache/opendal/issues/5452
after this patch:
```python
Traceback (most recent call last):
File "C:\Users\Trim21\proj\test\f.py", line 14, in <module>
op.read("non-exists-path")
opendal.exceptions.NotFound: NotFound (permanent) at stat, context: { service: redis, path: non-exists-path } => kv doesn't have this path
```
Yes, name in user exception message
> fix: exception name in python

- dev/Cargo.lock
- dev/Cargo.toml
- dev/README.md
- dev/src/generate/binding_python.rs
- dev/src/generate/mod.rs
- dev/src/generate/parser.rs
Inspired by https://github.com/apache/opendal/pull/5451 from @trim21 and @Zheaoli's suggestion.
Parse config from rust code so that other bindings can generate nice public API.
The ASF parser for rust core services config.
No, dev only.
> feat(dev): Add config parse and generate support

- bindings/python/src/file.rs
- bindings/python/src/operator.rs
Closes #.
before:
```text
warning: `opendal-python` (lib) generated 26 warnings
Finished `dev` profile [unoptimized + debuginfo] target(s) in 7.10s
```
no
> fix rust warning in python binding

- bindings/python/Cargo.toml
- bindings/python/src/operator.rs
- bindings/python/src/options.rs
- bindings/python/tests/test_write.py
Closes #.
kwargs parsing is not correct with default pyo3 derive, it will try to parse from attribute instead of `dict.__getitem__`
```text
Traceback (most recent call last):
File "C:\Users\Trim21\proj\test\f.py", line 15, in <module>
print(s3.write("test", b"tc", content_type="text/html"))
AttributeError: 'dict' object has no attribute 'append'
```
Use `dict_derive` to parse struct from kwargs dict. Didn't find this in pyo3.
another option is to remove `#[pyclass]` from `WriteOptions` and remove `m.add_class::<WriteOptions>()?` which may cause a breaking change and pyo3 doesn't support optional with `#[pyo3(item)]`
Yes, `op.write()` not support kwargs.
> fix: python binding kwargs parsing

- dev/README.md
- justfile
Part of https://github.com/apache/opendal/discussions/5460
See  https://github.com/apache/opendal/discussions/5460
Add `justfile` as a start.
Dev Only.
> chore(dev): Try just instead of xtasks methods

- .github/workflows/ci_odev.yml
- dev/Cargo.lock
- dev/Cargo.toml
- dev/src/generate/binding_python.rs
- dev/src/generate/mod.rs
- dev/src/generate/parser.rs
Closes #.
1. parse `#[deprecated(...)]` field attrubite from Config.
2. make all bool options optional
no
> dev: parse deprecated note from config and make bool optional

- README.md
- core/src/docs/upgrade.md
- core/src/lib.rs
- website/blog/2023-08-15-how-opendal-read-data/index.md
> docs: Fix links to vision

- dev/src/generate/parser.rs
Part of https://github.com/apache/opendal/issues/4279
Parse comments from config so that we can use those comments in bindings.
> feat(dev): Parse comments from config

- .github/workflows/ci_check.yml
- .github/workflows/ci_odev.yml
- core/src/raw/adapters/kv/api.rs
Closes https://github.com/apache/opendal/pull/5373
> ci: Upgrade and fix typos

- core/src/services/ghac/backend.rs
Fix CI failure introduced by https://github.com/apache/opendal/pull/5472
> fix(services/ghac): Fix stat_with_if_none_match been set in wrong

- .github/workflows/ci_bindings_nodejs.yml
None
Our recent nodejs binding failed to release for macOS platform because the version of `@actions/upload-artifact` is wrong.
Upgrade it correctly.
No.
> fix(ci): Correctly upgrade upload-artifact to v4

- core/src/docs/rfcs/0000_context.md
- core/src/docs/rfcs/5479_context.md
- core/src/docs/rfcs/mod.rs
Part of https://github.com/apache/opendal/issues/5325
This RFC will add `Context` in opendal to distribute global resources like http client, runtime, etc.
A new RFC.
New API.
> RFC-5479: Context

- core/src/types/operator/operator_futures.rs
- core/tests/behavior/async_read.rs
> feat: Add if-match & if-none-match support for reader

- core/src/types/metadata.rs
None
None
Polish API docs for `Metadata`
API Docs
> docs(core): Polish API docs for `Metadata`

- core/src/raw/ops.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/services/s3/lister.rs
- core/src/types/capability.rs
- core/src/types/metadata.rs
- core/src/types/operator/operator_futures.rs
- core/tests/behavior/async_list.rs
- core/tests/behavior/utils.rs
Part of https://github.com/apache/opendal/issues/5496
Implement the RFC we need.
- Add deleted in OpList
- Add is_deleted in Metadata
- Implement tests for list with deleted
- Implement list with deleted for `s3` services
Users can now list deleted files from s3 services.
> feat(core): Implement list with deleted for s3 service

- integrations/object_store/src/store.rs
- integrations/object_store/src/utils.rs
None.
Fix object_store support
> fix(integration/object_store): object_store requires metadata in list

- core/src/layers/correctness_check.rs
- core/src/services/s3/core.rs
Closes #5505.
Work-around for S3 allowing only wildcard(`*`) if-none-match requests.
Don't error out if the if-none-match argument is a wildcard and the scheme is S3.
Also hook-up the corresponding client argument.
`if_none_match("*")` and only that should work for S3.
> feat: Return hinted error for S3 wildcard if-none-match

- core/src/types/operator/operator.rs
- core/src/types/operator/operator_futures.rs
None.
Make user happy about our public API.
Docs for all options provided by opendal Reader and Writer.
API Docs
> docs: Polish docs for Operator, Reader and Writer

- .github/workflows/release_python.yml
> chore(ci): upgrade to manylinux_2_28 for aarch64 Python wheels

- core/src/raw/ops.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/core.rs
- core/src/types/capability.rs
- core/src/types/operator/operator.rs
- core/src/types/operator/operator_futures.rs
- core/tests/behavior/async_stat.rs
None
support conditional stat based on modification time.
Yes. we can use `stat_with().if_modified_since()` and `stat().if_unmodified_since()` now.
> feat(core): implement if_modified_since and if_unmodified_since for stat_with

- .github/actions/test_behavior_integration_object_store/action.yml
- .github/scripts/test_behavior/plan.py
- .github/scripts/test_behavior/test_plan.py
- .github/workflows/test_behavior.yml
- .github/workflows/test_behavior_integration_object_store.yml
- core/src/types/read/buffer_stream.rs
- integrations/object_store/Cargo.toml
- integrations/object_store/src/store.rs
- integrations/object_store/tests/behavior/delete.rs
- integrations/object_store/tests/behavior/get.rs
- integrations/object_store/tests/behavior/main.rs
- integrations/object_store/tests/behavior/put.rs
- integrations/object_store/tests/behavior/utils.rs
None
Add integration tests so we can modify the code with confidence.
> ci(integration/object_store): add integration tests for object_store_opendal

- integrations/object_store/src/store.rs
- integrations/object_store/src/utils.rs
- integrations/object_store/tests/behavior/get.rs
- integrations/object_store/tests/behavior/put.rs
Part of: https://github.com/apache/opendal/issues/5115.
1.  implement `put_opts` and `get_opts`
2. add integration tests for `object_store_opendal`
No
> feat(integrations/object_store): implement put_opts and get_opts

- core/src/services/azblob/backend.rs
- core/src/services/azblob/core.rs
- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
- core/src/services/oss/backend.rs
- core/src/services/oss/core.rs
Closes azblob, gcs, oss tasks for #5486.
> feat: Conditional reader for azblob, gcs, oss

- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
Follow up of https://github.com/apache/opendal/pull/5531
> fix(serivces/gcs): Gcs doesn't support read with if_(un)modified_since

- core/src/layers/correctness_check.rs
None
Make sure users can read data correctly.
> feat(core): Add correctness check for read with if_xxx headers

- .github/services/oss/oss_with_versioning/action.yml
- core/src/services/oss/backend.rs
- core/src/services/oss/config.rs
- core/src/services/oss/core.rs
- core/src/services/oss/lister.rs
Part of #5496 
Implement the oss in RFC we need.
Implement list with deleted for oss services
Implement versions for oss services
Users can now list deleted files and user versions from oss services.
> feat(core): Implement list with deleted and versions for oss

- core/Cargo.toml
- core/README.md
> docs: Fix opendal rust core's README not align with new vision

- integrations/object_store/Cargo.toml
- integrations/object_store/README.md
- integrations/object_store/examples/datafusion.rs
Part of: https://github.com/apache/opendal/issues/4599
add an example to demonstrate querying data in a S3 bucket using DataFusion and `object_store_opendal`
> docs(integration/object_store): add example for datafusion

- .github/actions/fuzz_test/action.yaml
- .github/workflows/test_fuzz.yml
Workaround for https://github.com/rust-lang/rust/issues/135515
The latest rustc failed to build.
> ci: Pin the nightly version to rust 1.84 for fuzz

- core/src/services/gcs/error.rs
gcs's returning TOO_MANY_REQUESTS should be treated at retryable Ratelimited instead.
None
> feat(gcs): Convert TOO_MANY_REQUESTS to retryable Ratelimited

- core/src/docs/rfcs/0000_write_returns_metadata.md
- core/src/docs/rfcs/5556_write_returns_metadata.md
- core/src/docs/rfcs/mod.rs
> RFC-5556: Write Returns Metadata

- core/benches/vs_s3/src/main.rs
- core/src/raw/http_util/header.rs
- core/src/raw/path.rs
- core/src/services/azblob/error.rs
- core/src/services/s3/error.rs
This patch do not close any issues, just drop some un necessary clone to make a little better performance
and only check the `core` for now, if it is useful will check all others dir in separate pull request
Closes #.
This patch do not close anything
no Rationale for this change
using static check to understand if we can drop some clone, and found 4 of them,
No
> refactor: refactor some unnecessary clone and use next_back to make clippy happy

- core/Cargo.toml
- core/src/layers/otelmetrics.rs
Workaround for https://github.com/apache/opendal/issues/5559
> chore(core): Avoid using mongodb 3.2.0

- .github/workflows/ci_core.yml
- core/Cargo.lock
```
> cargo build --locked
error: the lock file /Users/xxchan/Projects/opendal/core/Cargo.lock needs to be updated but --locked was passed to prevent this If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```
Closes #.
> build: fix Cargo.lock and pass --locked in CI

- .github/services/webhdfs/webhdfs_with_user_name/action.yml
- core/src/services/webhdfs/backend.rs
- core/src/services/webhdfs/config.rs
This PR will add user.name support for webhdfs.
> feat(services/webdfs): Add user.name support for webhdfs

- bindings/java/src/main/java/org/apache/opendal/ServiceConfig.java
- core/src/services/mysql/config.rs
- core/src/services/s3/config.rs
- core/src/services/sqlite/config.rs
- dev/src/generate/java.rs
> docs(bindings/java): better javadoc 

- core/src/types/error.rs
https://github.com/apache/opendal/discussions/5569
Signed-off-by: xxchan <xxchan22f@gmail.com>
Closes #.
> feat: disable backtrace for NotFound error

- bin/oay/Cargo.lock
- bin/oay/Cargo.toml
- bin/oay/src/bin/oay.rs
- bin/oay/src/bin/webdav.rs
- bin/oay/src/services/s3/service.rs
- bin/ofs/Cargo.lock
- bin/ofs/Cargo.toml
- bin/ofs/src/main.rs
- bin/ofs/tests/common/mod.rs
- core/Cargo.lock
- core/benches/vs_fs/Cargo.toml
- core/benches/vs_s3/Cargo.toml
- core/benches/vs_s3/src/main.rs
- core/fuzz/Cargo.toml
- core/fuzz/fuzz_reader.rs
- core/fuzz/fuzz_writer.rs
- dev/Cargo.lock
- dev/Cargo.toml
- dev/src/main.rs
- integrations/cloud_filter/Cargo.toml
- integrations/cloud_filter/examples/readonly.rs
- integrations/cloud_filter/tests/behavior/main.rs
Somehow self-promoted. More affinity to the log crate.
> chore: try use logforth 

- core/Cargo.lock
- core/Cargo.toml
- core/src/services/s3/backend.rs
- core/src/services/s3/config.rs
- core/src/services/s3/core.rs
- core/src/services/s3/writer.rs
> feat(services/s3): Added crc64nvme for s3

- website/docusaurus.config.js
This follows up https://github.com/apache/opendal/commit/e15d3147e0d660cda19ec88e5495e5676cd590fc.
Otherwise, when we're under a voting release, the version calculate is wrong. For example,
* When we have `v0.51.3-rc.1` and `v0.51.2`
* The current `git describe --tags --abbrev=0 --match 'v*'` gives `v0.51.3-rc.1`
> ci(website): avoid including rc when calculate the latest version

- core/src/services/fs/backend.rs
Closes #5606.
Explained in issue
Explained in issue
No. Adds support of existing capability for existing backend
> feat(services-fs): Support write-if-not-exists in fs backend

- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
- core/src/types/operator/operator_futures.rs
Closes https://github.com/apache/opendal/issues/5607
Explained in the issue
- Implements `content_encoding` support for Gcs for `stat`, `write` and `presign`.
- Adds `stat_has_content_encoding: true` and `write_with_content_encoding: true` to capabilities of `GcsBackend`
- Added `contentEncoding` check to `test_deserialize_get_object_json_response`
NOTE: I haven't tested `presign` yet with these changes yet, which is why I added `WIP`.
If the users were relying on `Gcs` service to ignore `content_encoding`, then they might have to update their code.
> feat(services/gcs): Impl content-encoding support for GCS stat, write and presign

- bindings/ruby/lib/opendal_ruby/entry.rb
- bindings/ruby/src/lib.rs
- bindings/ruby/src/lister.rs
- bindings/ruby/src/operator.rs
- bindings/ruby/test/lister_test.rb
> feat(bindings/ruby): add lister

- bin/ofs/Cargo.lock
- bin/oli/Cargo.lock
- core/Cargo.lock
- core/Cargo.toml
- core/src/services/s3/backend.rs
- core/src/services/s3/config.rs
- core/src/services/s3/core.rs
- core/src/services/s3/writer.rs
This reverts https://github.com/apache/opendal/pull/5580, where `crc64fast-nvme` pulls in cbindgen deps and seems less reliable.
> revert: added crc64nvme for s3

- core/src/raw/path_cache.rs
- core/src/services/gdrive/core.rs
> fix(services/gdrive): skip the trailing slash when creating and querying the directory

- integrations/dav-server/Cargo.toml
- integrations/dav-server/src/file.rs
- integrations/dav-server/src/fs.rs
- integrations/dav-server/tests/test.rs
Closes #5649 
Fixed the issue, and added some tests.
**Added a dependency `tempfile` for testing.**
No.
-----
**This is the first time I've used rust to contribute code to the community, so please review carefully!**
**If I'm violating some rules or best practice, I'll fix it ASAP.**
test log:
```
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running tests\test.rs (target\debug\deps\test-ca736229979e9ab0.exe)
running 5 tests
test test ... ok
test test_create_dir_metadata ... ok
test test_remove_dir ... ok
test test_read_dir ... ok
test test_file ... ok
test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
Doc-tests dav_server_opendalfs
running 2 tests
test src\fs.rs - fs::OpendalFs …
```
> fix(integrations/dav-server): handle encoded path correctly.

- core/src/services/onedrive/backend.rs
- core/src/services/onedrive/lister.rs
Per the reviewer comment from #5632.
OpenDAL's OneDrive service doesn't pass the behavior tests.
Bug fixes to conform with the behavior tests.
No
Before:
<details>
<summary>OPENDAL_TEST=onedrive cargo test behavior  --features tests,services-onedrive -- --show-output</summary>
```
Compiling opendal v0.52.0 (/home/erickg/Dev/opendal/core)
Finished `test` profile [unoptimized + debuginfo] target(s) in 10.98s
Running unittests src/lib.rs (target/debug/deps/opendal-9022af4dd162386a)
running 0 tests
successes:
successes:
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 134 filtered out; finished in 0.00s
Running tests/behavior/main.rs (target/debug/deps/behavior-c8073076fdb6f2e9)
running 102 tests
test behavior::test_delete_with_not_existing_version          ... ok
test …
```
> fix(services/onedrive): fix OneDrive behavior tests

- core/src/services/gcs/backend.rs
https://github.com/apache/opendal/issues/5611
Explained in the issue.
It seems that when `write_with_cache_control` was implemented for `Gcs`, the author of the PR forgot to set `write_with_cache_control` to true.
`write_with_cache_control`  is added to `GcsBackend`'s native capabilities
If the user decides to check whether `Gcs` has `write_with_cache_control` capability, it will be reported as `true` instead of `false`. But note that the feature itself works already regardless of this flag.
> fix(services/gcs): Advertise `write_with_cache_control` in Gcs

- core/src/services/s3/backend.rs
- core/src/services/s3/config.rs
- core/src/services/s3/core.rs
- core/src/services/s3/docs.md
- core/src/services/s3/writer.rs
Close: #5351
when writing to S3 Express One Zone, user can: 
```rust
let writer = op.writer_with(path).append(true).await?;
writer.write(bs).await?;
writer.close().await?;
```
> feat(services/s3): add append support

- integrations/object_store/Cargo.toml
- integrations/parquet/Cargo.toml
> feat(!): Bump arrow version of parquet_opendal to 54.x

- core/src/layers/blocking.rs
- core/src/layers/complete.rs
- core/src/layers/immutable_index.rs
- core/src/raw/accessor.rs
- core/src/raw/http_util/client.rs
- core/src/raw/oio/list/flat_list.rs
Part of https://github.com/apache/opendal/issues/5480
Polish context related API to make they are easier to use.
> feat: Polish context related APIs

- core/src/raw/chrono_util.rs
- core/src/services/onedrive/backend.rs
- core/src/services/onedrive/graph_model.rs
- core/src/services/onedrive/lister.rs
Part of #4746.
Supports OneDrive lister with metadata.
> feat(services/onedrive): List dir shows metadata

- core/src/raw/accessor.rs
- core/src/services/s3/core.rs
- core/src/services/s3/delete.rs
- core/src/types/delete/deleter.rs
- core/src/types/operator/operator.rs
- core/tests/behavior/async_delete.rs
None
In #5349, we didn't handle the return values of batch delete, which could cause multiple batch delete operations to fail.
1. fix batch delete with version
2. add behavior tests for batch delete
3. fix some typos
> fix(services/s3): fix batch delete with version

- bindings/ruby/src/lib.rs
- bindings/ruby/src/operator.rs
- bindings/ruby/src/operator_info.rs
- bindings/ruby/test/operator_info_test.rb
Part of #5227
Add `OperatorInfo`.
No
I want to expose what configured layers are in an operator. Is there an API or issue about it? This is not useful in Rust core but is convenient for Python/Ruby users.
> feat(bindings/ruby): add operator info

- bindings/python/CONTRIBUTING.md
This patch fix python version is wrong in `bindings/python/CONTRIBUTING.md`
and seems use `pip install maturin` is better than `pip install 'maturin[patchelf]'` for now
cause pip install 'maturin[patchelf]'  needs Ninja which is not so kindly for user install
> doc: py binding version is wrong for now

- bindings/python/src/operator.rs
For now py binding for clippy are not happy, this patch drop useless clone and fix some other clippy things
make clippy happy again, and maybe can better a little benchmark.
> fix: drop useless clone for py binding and make clippy happy

- core/src/raw/http_util/mod.rs
- core/src/raw/http_util/multipart.rs
- core/src/services/gcs/core.rs
The status of this PR:
With this PR applied, I am able to set metadata such as `content_encoding` and `content_type` in write operations with `Gcs`. I have tested it with the official Storage emulator provided by `firebase-tools`.
What's missing:
- ~I haven't tested this with the actual GCS yet~ EDIT: Tested in our project
- ~Unit tests for `RelatedPart`~ EDIT: There's now a simple unit test
Closes https://github.com/apache/opendal/issues/5624
TL;DR: Improves GCS API compliance
The rationale for the change is discussed in the issue.
- Implement support for `multipart/related` (`RelatedPart`)
- Use `RelatedPart` in `gcs_insert_object_request` instead of `FormDataPart`
None
> feat(services/gcs): Implement multipart/related and use it with Gcs

- bindings/lua/.cargo/config.toml
This path fix macOS can not build lua binding by adding config(which is like other binding))
refer doc: for mlua https://github.com/mlua-rs/mlua
> On macOS, you need to set additional linker arguments. One option is to compile with cargo rustc --release -- -C link-arg=-undefined -C link-arg=dynamic_lookup, the other is to create a .cargo/config.toml with the following content:
```
[target.x86_64-apple-darwin]
rustflags = [
"-C", "link-arg=-undefined",
"-C", "link-arg=dynamic_lookup",
]
[target.aarch64-apple-darwin]
rustflags = [
"-C", "link-arg=-undefined",
"-C", "link-arg=dynamic_lookup",
]
```
if without this patch build on macOS error:
```cli
rror: linking with `cc` failed: exit status: 1
|
= note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET -u XROS_DEPLOYMENT_TARGET …
```
> fix: mac can not build lua binding

- website/docusaurus.config.js
Images inside links (such as badges in the README) were being captured by the image zoom plugin ( `docusaurus-plugin-image-zoom` ), which interfered with their expected click behavior.
Updated the image zoom plugin configuration to exclude images inside anchor tags by modifying the CSS selector to `img:not(a img)`. 
no
https://github.com/user-attachments/assets/f6881de4-bdea-40c6-9c45-5978249e455f
> fix(website): Handling badges click behavior correctly

- core/src/services/onedrive/backend.rs
- core/src/services/onedrive/builder.rs
- core/src/services/onedrive/config.rs
- core/src/services/onedrive/core.rs
- core/src/services/onedrive/delete.rs
- core/src/services/onedrive/docs.md
- core/src/services/onedrive/error.rs
- core/src/services/onedrive/graph_model.rs
- core/src/services/onedrive/lister.rs
- core/src/services/onedrive/mod.rs
- core/src/services/onedrive/writer.rs
Closes #5653.
Part of #5677.
Part of #5702.
This is a somewhat large PR. Reviewing it commit by commit is easier.
1. This PR extracts the OneDrive service into the "core" structure. Minor changes to names, how to stat, etc.
2. Uses context for an HTTP client.
3. Adds a signer. This mostly follows the Google Drive service signer implementation.
I added a few more refresh token settings for the OneDrive service. I added the documentation.
> feat(services/onedrive): add signer to utilize the refresh token

- .github/workflows/ci_bindings_java.yml
- bindings/java/src/async_operator.rs
- bindings/java/src/convert.rs
- bindings/java/src/executor.rs
Closes #5745 
This patch do these things for java binding:
- drop useless import
- use latest stable api to the warning -> `Replace once_cell::sync::OnceCell with the standard library's std::sync::OnceLock (available since Rust 1.70)`
- make clippy happy
- add clippy ci for java binding
> fix: drop useless import and clippy happy for java binding

- core/src/raw/oio/list/flat_list.rs
- core/src/services/webdav/lister.rs
- core/tests/behavior/async_list.rs
- core/tests/behavior/blocking_list.rs
None
when performing `list_with_recursive`, if the object doesn't exist and the underlying service does not support `list_with_recursive`, we may incorrectly return the non-existent object.
> fix(core): fix list with recursive when the object doesn't exist

- .github/workflows/ci_bindings_php.yml
- bindings/php/Cargo.toml
- bindings/php/src/lib.rs
Closes #2813
This patch aim to make php binding work and happy and greate again
and do these things
- open php binding ci
- fix binding ci workdir problem
- update ext-php-rs to match latest system and php
- drop php 8.1 and bring php 8.4 for ci test
- add clippy to ci
- fix the compiler error and clippy error
happy ci: https://github.com/yihong0618/opendal/actions/runs/13837386813
> fix: make php binding happy again

- core/src/raw/http_util/body.rs
- core/src/raw/http_util/client.rs
- core/src/services/onedrive/backend.rs
- core/src/services/onedrive/builder.rs
- core/src/services/onedrive/core.rs
- core/src/services/onedrive/error.rs
Part of #5486.
I encountered an issue with the HTTP client when working with OneDrive. Specifically, OneDrive returns a 302 Location response when downloading an item. See `onedrive_get_content`. This has two implications:
1. OpenDAL cannot implement "presign" for OneDrive without controlling or requiring the HTTP client to handle retries. While this is not an urgent issue, it may be worth tracking in an issue to gather requirements for the HTTP client.
2. In my implementation, I must assume that the HTTP client will automatically follow 302 redirects. If redirection does not occur, the OneDrive backend will return an error, which is not ideal. This is also not a good position for developers building services where developers can't predict how http clients will perform with redirections.
> feat(services/onedrive): implement read_with_if_none_match

- .github/workflows/ci_bindings_dart.yml
- .github/workflows/release_dart.yml
- bindings/dart/README.md
- bindings/dart/lib/opendal.dart
- bindings/dart/pubspec.yaml
part of #5722 .
prepare for the publish
user may able to install it through <https://pub.dev/>
ref
1. [How can I use dart ffi properly in a pub package?](https://stackoverflow.com/q/62199556/13040423)
2. https://kazlauskas.dev/blog/publishing-new-flutter-package/
Seems that user need to install rust and build the package themselves.
> feat(binding/dart): add pubspec info

- bindings/python/Cargo.toml
- bindings/python/src/metadata.rs
- bindings/python/tests/test_write.py
Closes #5766
also add two tests
---
update:  drop the tests until we have can have better solution.
and use pyresult as return (for DateTime or None or Pyerr)
learned from this issue https://github.com/PyO3/pyo3/issues/884
and found the PYO3 example for convert 
example:
https://github.com/PyO3/pyo3/blob/fdf62e0e20081a1d5be14b77fd8ac26aa1e8d9dc/src/conversions/chrono.rs#L25-L41
cc @messense
> fix: add missing last_modified for python binding

- core/users.md
The "About" header was accidentally copied when copying the "About" section on the GitHub project page.
Fixes issue with rustic's entry in the users list
It's obviously a mistake
Rustic's entry in the users list has been fixed
No
> docs: Fix rustic users entry

- bindings/python/src/metadata.rs
- bindings/python/tests/test_write.py
… better print and debug
Closes #5768
> feat(bindings/python): Add repr for metadata

- core/Cargo.lock
- core/Cargo.toml
- core/src/services/mod.rs
- core/src/services/opfs/backend.rs
- core/src/services/opfs/config.rs
- core/src/services/opfs/core.rs
- core/src/services/opfs/docs.md
- core/src/services/opfs/mod.rs
close #2442 
read/write support for OPFS
> feat: Add origin private file system scaffold

- core/src/layers/metrics.rs
- core/src/layers/observe/metrics.rs
- core/src/layers/otelmetrics.rs
- core/src/layers/prometheus.rs
- core/src/layers/prometheus_client.rs
- core/src/raw/accessor.rs
- core/src/types/operator/info.rs
Closes https://github.com/apache/opendal/issues/5795
See https://github.com/apache/opendal/issues/5795 for details.
- Use AccessorInfo instead of seperate fields
- Return `Arc<str>` instead of `String` for `name` and `root` to avoid copy.
None. Only raw API been touched.
> refactor(core/raw)!: Use AccessorInfo instead of seperate fields

- core/src/layers/observe/metrics.rs
- core/src/layers/observe/mod.rs
- core/src/layers/prometheus_client.rs
- core/src/raw/http_util/client.rs
- core/src/raw/http_util/mod.rs
Part of https://github.com/apache/opendal/issues/5794
See https://github.com/apache/opendal/issues/5794
- Add http related metrics for `observe::MetricsLayer`
- Implement for `PrometheusClientLayer`
New APIs for `PrometheusClientLayerBuilder` to configure http metrics.
> feat(core): Implement http related metrics support for prom client

- core/src/services/onedrive/core.rs
Closes #5811 .
Fix bug the onedrive chunk upload may fail when PUT upload url.
Remove adding sign (add authorization header) PUT request to upload url
no
> fix(services/onedrive): chunk PUT upload remove auth header

- core/src/services/aliyun_drive/backend.rs
- core/src/services/aliyun_drive/core.rs
<details>
<summary>Behavior tests</summary>
```console
cargo test behavior --features tests,services-aliyun-drive -- --test-threads=3 --show-output   
Finished `test` profile [unoptimized + debuginfo] target(s) in 3.07s
Running unittests src\lib.rs (target\debug\deps\opendal-df0786b0dd63f43c.exe)
running 0 tests
successes:
successes:
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 134 filtered out; finished in 0.00s
Running tests\behavior\main.rs (target\debug\deps\behavior-cd77f07915b9c1f1.exe)
running 141 tests
test behavior::test_copy_non_existing_source                           ... ok
test behavior::test_copy_source_dir                                    ... ok
test behavior::test_copy_target_dir …
```
> refactor: Migrate aliyun_drive services to context based http client

- core/src/services/hdfs_native/backend.rs
None
`hdfs native` supports `create_dir`, but the capability is not enabled.
> chore(services/hdfs_native): enable create_dir capability

- .github/workflows/release_python.yml
Closes #.
This patch open python3.13t release and drop the hint comments
since https://github.com/PyO3/pyo3/pull/4808 had been merged
ci: https://github.com/yihong0618/opendal/actions/runs/13961638383/job/39083903662
> fix(bindings/python): open python3.13t release for windows since upstream had fixed

- core/src/raw/oio/write/block_write.rs
- core/src/services/azblob/backend.rs
- core/src/services/ghac/writer.rs
- core/src/services/webhdfs/backend.rs
Closes https://github.com/apache/opendal/issues/5831
Migrate BlockWriter to use executor from context so that users can inject context in executor instead.
Migrate BlockWriter to use executor from context
No.
> refactor(core): Migrate BlockWriter to use executor from context

- core/src/layers/timeout.rs
- core/src/lib.rs
- core/src/raw/accessor.rs
- core/src/raw/ops.rs
- core/src/types/operator/operator.rs
- core/src/types/operator/operator_futures.rs
- core/src/types/read/buffer_stream.rs
Closes https://github.com/apache/opendal/issues/5808
As part work of https://github.com/apache/opendal/issues/5480
- Migrate TimeoutLayer to context based.
- Remove `executor` from `OpRead` and `OpWrite`
- Change public API of `Operator`
> refactor(core)!: Migrate to context based executor

- .github/actions/setup-ocaml/action.yaml
- .github/workflows/ci_bindings_ocaml.yml
- bindings/ocaml/.cargo/config.toml
- bindings/ocaml/Cargo.toml
- bindings/ocaml/README.md
- bindings/ocaml/src/operator/mod.rs
This patch aim to make ocaml binding a litter happier and do these things
- add clippy to ocaml binding
- add macos support from doc https://github.com/zshipko/ocaml-rs(cargo config)
- chore the ocaml and build rust version from beta to stable
- format some doc
--- error
Error: Bad request - ocaml/setup-ocaml@v3 is not allowed to be used in apache/opendal. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, …
> fix: better ocaml binding and happy clippy

- .github/workflows/ci_bindings_haskell.yml
- bindings/haskell/CONTRIBUTING.md
- bindings/haskell/src/lib.rs
- bindings/haskell/test/BasicTest.hs
This patch do these things
- add clippy to haskell binding ci
- fix warning for exists
- cabal test warning
- update contributing doc for haskell that lock the version, because upper to this can not compile for now
warning:
```
[1 of 2] Compiling BasicTest        ( test/BasicTest.hs, /Users/yihong/repos/opendal/bindings/haskell/dist-newstyle/build/aarch64-osx/ghc-9.4.8/opendal-0.1.0/build/opendal-test/opendal-test-tmp/BasicTest.o ) [Source file changed]
test/BasicTest.hs:20:1: warning: [-Wunused-imports]
The import of ‘Colog’ is redundant
except perhaps to import instances from ‘Colog’
To import instances alone, use: import Colog()
|
20 | import Colog (LogAction (LogAction), Msg (msgText))
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test/BasicTest.hs:22:1: warning: …
```
> fix: make haskell binding happier

- bindings/python/src/file.rs
> fix: drop fixme in py binding since upstream fixed

- bindings/c/include/opendal.h
- bindings/c/src/operator.rs
- bindings/c/tests/bdd.cpp
- core/src/types/operator/blocking_operator.rs
part of #2959.
add opendal_operator_check
> feat(bindings/c): add opendal_operator_check

- core/src/layers/observe/metrics.rs
- core/src/layers/observe/mod.rs
- core/src/types/error.rs
Follow up of https://github.com/apache/opendal/pull/5883
Part of https://github.com/apache/opendal/issues/5878
I found some nice things to added while implementing https://github.com/apache/opendal/issues/5885
It's better to split in to a deidcated PR so that we can have a clean view about how to migrating.
- Remove some counter total metrics since they have been covered by related histogram.
- Add good default histogram buckets for metric impls to use.
- Enrich docs for metrics public types.
No.
> refactor(core): Add good default histogram buckets for metrics

- core/src/services/icloud/backend.rs
- core/src/services/icloud/core.rs
- Added `info` field to  `IcloudSigner` and `IcloudCore` , updated methods to use `AccessorInfo` for HTTP requests.
> refactor: Migrate icloud service to context based http client

- core/src/services/webhdfs/backend.rs
- core/src/services/webhdfs/core.rs
- core/src/services/webhdfs/delete.rs
- core/src/services/webhdfs/lister.rs
- core/src/services/webhdfs/mod.rs
- core/src/services/webhdfs/writer.rs
Closes https://github.com/apache/opendal/issues/5677
Part of https://github.com/apache/opendal/issues/5702
- This pull request refactors the `WebhdfsBackend` by introducing a new `WebhdfsCore` struct to encapsulate the core functionality and state. The changes aim to improve code organization and maintainability.
- Updated methods to use `AccessorInfo` for HTTP requests.
> refactor: Migrate WebHDFS service to context based http client

- core/src/layers/mod.rs
- core/src/layers/observe/metrics.rs
- core/src/layers/observe/mod.rs
- core/src/layers/otelmetrics.rs
- core/src/layers/prometheus.rs
Closes #5889 
Part of #5883 
- Migrate OtelMetricsLayer to support IO metrics
- Cleanup useless thing about path_label_level config
- Remove useless `MetricsIntercept::observe_*` methods
> refactor(layer/otelmetrics): Migrate OtelMetricsLayer to support IO metrics

- core/src/services/sftp/backend.rs
- core/src/services/sftp/core.rs
- core/src/services/sftp/delete.rs
- core/src/services/sftp/mod.rs
- core/src/services/sftp/reader.rs
Part of https://github.com/apache/opendal/issues/5702
This pull request refactors the `SftpBackend` by introducing a new `SftpCore` struct to encapsulate the core functionality and state. The changes aim to improve code organization and maintainability.
> refactor: Introduce SftpCore for improved service structure

- core/src/layers/observe/metrics.rs
- core/src/layers/observe/mod.rs
Closes #5878 
Cleanup useless MetricMetadata type and some static variables
> chore(layer/observe): cleanup useless metric metadata

- core/src/layers/retry.rs
1. Previously, we write `impl RetryLayer` that only implements for the default `RetryLayer<DefaultRetryInterceptor>`. So you cannot write `RetryLayer::new(..).with_notify(..).with_jitter(..)`.
2. We can implement RetryInterceptor for all `Fn(&Error, Duration) + Send + Sync + 'static` for convenient.
> refactor: refine RetryLayer type signature

- core/src/services/gcs/backend.rs
- core/src/services/gcs/core.rs
- core/src/services/gcs/writer.rs
- core/tests/behavior/async_write.rs
- core/tests/behavior/blocking_write.rs
> feat(services/gcs): implement write returns metadata

- examples/cpp/basic.cpp
> chore: sync cpp example

- .github/workflows/ci_check.yml
- .typos.toml
This patch chore typos-cli version
> chore: update typos version

- core/src/services/ipfs/backend.rs
- core/src/services/ipfs/core.rs
- core/src/services/ipfs/mod.rs
Part of https://github.com/apache/opendal/issues/5702
Part of #5677 
- This pull request refactors the `IpfsBackend` by introducing a new `IpfsCore` struct to encapsulate the core functionality and state. The changes aim to improve code organization and maintainability. 
- Use the http_client from AccessorInfo, instead of directly accessing the backend, to migrate the service to a context-based http client.
> refactor: Introduce IpfsCore for improved service structure

- bindings/ruby/Cargo.toml
- bindings/ruby/lib/opendal.rb
- bindings/ruby/lib/opendal_ruby/metadata.rb
- bindings/ruby/lib/opendal_ruby/operator.rb
- bindings/ruby/lib/opendal_ruby/operator_info.rb
- bindings/ruby/src/layers.rs
- bindings/ruby/src/lib.rs
- bindings/ruby/src/lister.rs
- bindings/ruby/src/metadata.rs
- bindings/ruby/src/middlewares.rs
- bindings/ruby/src/operator.rs
- bindings/ruby/test/blocking_op_test.rb
- bindings/ruby/test/layers_test.rb
- bindings/ruby/test/middlewares_test.rb
Part of #5227.
1. 4 Layers and supports for `Operator#layer`.
2. Documentation update
3. A few `#inspect` implementation
> feat(bindings/ruby): support layers

- core/src/services/ftp/backend.rs
- core/src/services/ftp/core.rs
- core/src/services/ftp/delete.rs
- core/src/services/ftp/mod.rs
- core/src/services/ftp/reader.rs
- core/src/services/ftp/writer.rs
Addresses #5702: Split service logic to  `backend` and `core` modules
This pull request refactors the `FtpBackend` by introducing a new `FtpCore` struct to hosting connection functionality and state.
> refactor(ftp): restructure FtpBackend and introduce FtpCore

- .github/services/s3/aws_s3_with_list_objects_v1/action.yml
- .github/services/s3/minio_s3_with_list_objects_v1/action.yml
- core/src/raw/enum_utils.rs
- core/src/raw/http_util/mod.rs
- core/src/raw/http_util/uri.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/config.rs
- core/src/services/s3/core.rs
- core/src/services/s3/lister.rs
Closes https://github.com/apache/opendal/issues/5974
As explained in https://github.com/apache/opendal/issues/5974
- Add ListObjectsV1 support
- A new config `disable_list_objects_v2`.
- Related tests.
A new config `disable_list_objects_v2`.
> feat(services/s3): Add ListObjectsV1 support for better support old storage services 

- .github/scripts/test_go_binding/matrix.yaml
- .github/workflows/ci_bindings_go.yml
- bindings/go/delete.go
- bindings/go/ffi.go
- bindings/go/go.mod
- bindings/go/go.sum
- bindings/go/lister.go
- bindings/go/operator.go
- bindings/go/operator_info.go
- bindings/go/reader.go
- bindings/go/stat.go
- bindings/go/util_unix.go
- bindings/go/util_windows.go
- bindings/go/write.go
Close #5051.
Take over #5066.
Part of #4892.
> feat(bindings/go): Add windows platform support

- core/src/services/ipfs/backend.rs
- core/src/services/ipfs/core.rs
> Could we take it a step further and build a function like `pub async fn IpfsCore::ipfs_stat(name: &str) -> Result<Metadata>`? This would allow you to retrieve metadata for each name directly via the core for `DirStream`.
_Originally posted by @erickguan in https://github.com/apache/opendal/pull/5950#discussion_r2029422349_
This pull request refactors the IPFS backend implementation to simplify the code and improve maintainability. 
The main changes involve moving the `stat` logic from `IpfsBackend` to `IpfsCore`, updating the `DirStream` structure
<details>
<summary>cargo test behavior --features tests,services-ipfs -- --show-output</summary>
```
running 23 tests
test behavior::test_read_only_read_full                    ... ok
test behavior::test_read_only_read_full_with_special_chars …
```
> feat(services/ipfs): implement ipfs_stat

- core/src/layers/concurrent_limit.rs
None
Allow add concurrent limit for in-progress http requests
- Add a new API called `with_http_concurrent_limit`
- Allowing share the same layer across operators.
> feat(core): Allow add concurrent limit for in-progress http requests

- core/Cargo.lock
- core/Cargo.toml
- core/src/raw/http_util/client.rs
Closes https://github.com/apache/opendal/issues/4461
As mentioned in https://github.com/apache/opendal/issues/4461
Use `Buffer` as body directly.
No.
> feat(core): Use Buffer as http_body::Body directly

- .github/workflows/service_test_ghac.yml
None.
GHAC v1 has been shutdown entirely.
```
error: test failed, to rerun pass `--test behavior`
test panicked: write must succeed: Unexpected (persistent) at write => {"$id":"1","innerException":null,"message":"This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset","typeName":"Microsoft.Azure.DevOps.ArtifactCache.WebApi.ArtifactCacheServiceDecommissionedException, Microsoft.Azure.DevOps.ArtifactCache.WebApi","typeKey":"ArtifactCacheServiceDecommissionedException","errorCode":0,"eventId":3000}
Context:
uri: https://acghubeus2.actions.githubusercontent.com/5JidZSUIbXpO2kk5tNBS56uxOnK9OaX8tLwVV8MTgXiDZI5Q5G/_apis/artifactcache/caches
response: Parts { status: 422, version: HTTP/1.1, headers: …
```
> ci: GHAC v1 has been shutdown entirely

- core/src/layers/blocking.rs
- core/tests/behavior/blocking_list.rs
> feat(core): impl Drop for BlockingWrapper

- .github/scripts/test_behavior/plan.py
- .github/scripts/test_go_binding/generate_test_scheme.py
Follow #6036. Now we can enable sliqte for go binding
> ci(bindings/go): include sqlite service into behavior tests

- bindings/cpp/CMakeLists.txt
- bindings/cpp/include/opendal.hpp
- bindings/cpp/src/details/common.hpp
- bindings/cpp/src/details/lister.hpp
- bindings/cpp/src/details/operator.cpp
- bindings/cpp/src/details/operator.hpp
- bindings/cpp/src/details/reader.cpp
- bindings/cpp/src/details/reader.hpp
- bindings/cpp/src/opendal.cpp
- bindings/cpp/tests/basic_test.cpp
- examples/cpp/CMakeLists.txt
- examples/cpp/basic.cpp
nop, but inspired by the discussion https://github.com/apache/opendal/discussions/6035
Remove lib.rs.h from opendal.hpp to make the included source files cleaner for users.
- Using type erasure to remove lib.rs.h from opendal.hpp, but note that this will introduce an additional pointer access overhead, we will fix this in the future.
- Replace macro definitions with template functions to convert C++ containers into Rust containers.
- Change the return type of operator::read from vector<uint8_t> to string.
- Rename Lister::ListerIterator to Lister::Iterator to eliminate naming redundancy.
- Change the return type of operator::read from vector<uint8_t> to string. Since the C++ binding hasn't been officially released yet, I think this change should be acceptable.
- This helps minimize the …
> feat(bindings/cpp) remove lib.rs.h from opendal.hpp

- core/src/raw/ops.rs
> refactor(core): Deprecate not used options in OpList

- bindings/python/docs/examples/pandas.ipynb
Closes #6056
The example code currently attempts to read a file named test123.csv, which was never written.
- Fixed the filename in the file : `bindings/python/docs/examples/pandas.ipynb`  from test123.csv to test.csv to match the file that is written.
No.
> fix(bindings/python): wrong filename used when reading CSV in pandas exemple

- core/src/layers/prometheus_client.rs
none
currently the `root` label might have high cardinality in certain systems, like users may have thousands of different `root` values for something like `stage`s.
this pr addes a `enable_high_cardinality_labels` method to `PrometheusClientLayerBuilder`, if this method set as `false`, the `root` label will not be rendered in the labels encoding.
adds a `enable_high_cardinality_labels` in `PrometheusClientLayerBuilder`. the default behaviour is not changed
> feat(layers/prometheus_client): Add disable_label_root to allow skip root label in metrics

- core/src/types/scheme.rs
- integrations/object_store/Cargo.toml
- integrations/object_store/examples/basic.rs
- integrations/object_store/src/amazon_s3.rs
- integrations/object_store/src/lib.rs
Part of #5190
Yes,  after adding this new feature, users can use the new API. I'll update the document later.
> feat(integrations/object_store): add AmazonS3Builder

- integrations/object_store/Cargo.toml
- integrations/object_store/src/store.rs
- integrations/object_store/src/utils.rs
- integrations/object_store/tests/behavior/get.rs
Closes #.
object_store v0.12.0 released with some breaking changes, notably using `u64` as offset instead of `usize` and some minor lifetime tweaks.
This pr adapts the changes and make it work with lastest DataFusion
> feat(integration/object_store): bump object store version

- integrations/unftp-sbe/Cargo.toml
- integrations/unftp-sbe/README.md
A new version of [libunftp](https://crates.io/crates/libunftp) is out and the integration here (unftp-sbe-opendal) isn't compatible anymore due to an upgrade to the `async-trait` crate.
This change simply bumps `async-trait` and `libunftp` to the latest versions, making it compatible again.
It will be really great if the [unftp-sbe-opendal](https://crates.io/crates/unftp-sbe-opendal) crate can be released after this merge. This is because the [unFTP](https://github.com/bolcom/unFTP) project uses it and currently cannot release with opendal functionality unless a new version of `uftp-sbe-opendal` with these changes are released.
cc @George-Miao
> chore(integrations/unftp): Make compatible with latest libunftp

- core/src/services/aliyun_drive/backend.rs
Relates to #5774. I noticed that in https://github.com/apache/opendal/pull/5880, there was one missing request without `extension`. Note that #5880 included that extension in the functions under `core.rs`, but there was this request that was sent in `backend.rs`.
> feat(services/aliyun_drive): Add operation in http context

- core/src/services/ghac/backend.rs
- core/src/services/ghac/core.rs
- core/src/services/ghac/writer.rs
Prior to https://github.com/apache/opendal/issues/5774 we need `core.rs` to contain all raw `Request::*` calls
> refactor(services/ghac): move raw http calls to core

- core/src/services/yandex_disk/backend.rs
- core/src/services/yandex_disk/core.rs
- core/src/services/yandex_disk/writer.rs
https://github.com/apache/opendal/pull/6064#discussion_r2051735620
> refactor(services/yandex_disk): Move raw request to core

- core/src/services/seafile/core.rs
- core/src/services/seafile/lister.rs
- core/src/services/seafile/writer.rs
Prior to work on #5774 we need all `Request::*` calls in `core.rs`
> refactor(services/seafile): Refactor raw request send in writer and lister

- core/src/services/aliyun_drive/backend.rs
- core/src/services/aliyun_drive/core.rs
Relates to https://github.com/apache/opendal/pull/6063/files#r2051703445
> refactor(services/aliyun_drive): Move raw request to core

- core/src/services/webhdfs/backend.rs
- core/src/services/webhdfs/core.rs
- core/src/services/webhdfs/lister.rs
- core/src/services/webhdfs/writer.rs
Now all `self.info.http_client().send(req).await` happen in `core.rs`. 
---
This is the last one of these PRs, I swear!!
> refactor(services/webhdfs): Refactor raw request send in writer and backend

- .github/workflows/release_python.yml
Release python build distributions for musllinux on PyPI
Closes #6114.
Support install opendal on alpine by pip
Add support for musl linux
no
> feat(bindings/python): build and publish musllinux wheels (#6114)

- core/src/raw/http_util/client.rs
[The expect message produced by this fragment is not ideal](https://github.com/apache/opendal/blob/v0.53.1/core/src/raw/http_util/client.rs#L164-L169).
Here is an example of its presentation.
"input request url must be valid: InvalidIpv4Address"
Closes #6123
It is difficult to correct a defective value if the value is unknown.
This change prints the defective value.
Update to an error message to make correcting the error more tractable.
The message contains information about a defective uri.
> refactor(core): Improve Error Message with Defective Value

- bindings/go/reader.go
- bindings/go/tests/behavior_tests/read_test.go
> fix(bindings/go): Reader returns io.EOF at the end of file

- .github/workflows/docs.yml
- bindings/ruby/Rakefile
None
Try to use new nightly rust to build ruby docs instead of an old nightly.
The current usage of old nightly breaks https://github.com/apache/opendal/pull/6154
None
> docs: Try using new nightly rust to build ruby docs

- bindings/c/include/opendal.h
- bindings/c/src/reader.rs
- bindings/c/src/result.rs
- bindings/c/tests/reader.cpp
- bindings/go/ffi.go
- bindings/go/reader.go
- bindings/go/tests/behavior_tests/opendal_test.go
- bindings/go/tests/behavior_tests/read_test.go
- bindings/go/types.go
Follow #6119.
Part of #4892.
This PR aims to implement the offset-based read operation requested in #5326 by supporting the `io.Seeker` interface.
FYI: https://pkg.go.dev/io#Seeker
In a previous closed PR, I attempted to implement `io.ReaderAt` without a proper design. Now, we can directly use `opendal_reader_seek` to support `io.Seeker`!
The difference between `io.Seeker` and `io.ReaderAt` is that `io.ReaderAt` allows for parallel offset-based reading.
> Clients of ReadAt can execute parallel ReadAt calls on the same input source.
>
> From https://pkg.go.dev/io#ReaderAt
**NOTICE**: I made some changes to the signature of the C seek function.
> feat(bindings/go): implement io.Seeker

- .github/scripts/test_behavior/plan.py
- bindings/go/delete.go
- bindings/go/error.go
- bindings/go/ffi.go
- bindings/go/lister.go
- bindings/go/metadata.go
- bindings/go/operator.go
- bindings/go/operator_info.go
- bindings/go/reader.go
- bindings/go/stat.go
- bindings/go/write.go
Part of #4892.
This PR:
1. Introduces a new type definition for the FFI function signature to enhance code maintainability and readability. This change standardizes FFI call handling across the codebase by replacing inline function signatures with a named type.
2. Enables all service tests for Go binding, which I believe is the final step needed to close #5326, as all feature requests in this issue have been completed.
> refactor(bindings/go): add ffiCall type for FFI function signature

- bindings/java/src/async_operator.rs
- bindings/java/src/convert.rs
- bindings/java/src/executor.rs
- bindings/java/src/main/java/org/apache/opendal/AsyncOperator.java
- bindings/java/src/main/java/org/apache/opendal/Operator.java
- bindings/java/src/main/java/org/apache/opendal/ReadOptions.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/test/behavior/AsyncReadOnlyTest.java
- bindings/java/src/test/java/org/apache/opendal/test/behavior/BlockingReadOnlyTest.java
- core/src/types/operator/blocking_operator.rs
Closes #5825.
Mentioned in the above issue
Support read options for both async and blocking read in java binding
Yes
> feat(java): add ReadOptions for read methods

- .github/actions/setup/action.yaml
- .github/workflows/test_edge.yml
Closes #.
It downloads binary from GitHub Releases, so we don't need to manually do caching or compile
> ci: uses taiki-e/install-action to replace cargo insatll

- bindings/go/go.mod
- bindings/go/go.sum
Closes #.
The dependency `github.com/ebitengine/purego` needs to be upgraded to version 0.8.3 due to a [bug](https://github.com/golang/go/issues/73617) in Go 1.23.9 and 1.24.3.
v0.4.1 of github.com/jupiterrider/ffi is the latest version and has no change, except the purego update: https://github.com/JupiterRider/ffi/compare/v0.4.0...v0.4.1
Only dependency updates for the Golang binding. 
No.
> fix(bindings/go): update dependencies

- core/src/services/redb/backend.rs
- core/src/services/redb/docs.md
Closes #6172 .
- Users got a new method: `opendal::services::Redb::database(self, db: &Arc<redb::Database>) -> Self`
- (breaking change) `OperatorInfo::name` for redb become table name instead of datadir.
> feat(core): support sharing one redb database between different Operators

- integrations/object_store/src/store.rs
Closes #6129.
Performing `percent_decode_path` in `object-store-opendal` before invoking inner operations
No
> fix(integrations/object_store): fix double percent encoding

- .github/workflows/ci_bin_oli.yml
- bin/oli/src/commands/cp.rs
- bin/oli/tests/integration/cp.rs
- bin/oli/tests/integration/ls.rs
- bin/oli/tests/integration/mv.rs
- bin/oli/tests/integration/rm.rs
- bin/oli/tests/integration/stat.rs
- bin/oli/tests/integration/test_utils.rs
> feat(bin/oli): support cp to dir

- .github/workflows/ci_bindings_nodejs.yml
Closes https://github.com/apache/opendal/issues/5957
Nodejs release seem require new permissions.
> ci(bindings/node): Add contents permissions for nodejs release

- .github/workflows/release_java.yml
- Closes https://github.com/apache/opendal/issues/5935
- Closes https://github.com/apache/opendal/issues/6080
The upstream has fixed the zigbuild issues while building java. Let's enable it back.
> ci(bindings/java): Enable zig build for java

- .github/workflows/ci_core.yml
- CHANGELOG.md
- bin/oay/Cargo.lock
- bin/oay/Cargo.toml
- bin/ofs/Cargo.lock
- bin/ofs/Cargo.toml
- bin/oli/Cargo.lock
- bin/oli/Cargo.toml
- bindings/java/pom.xml
- bindings/nodejs/npm/darwin-arm64/package.json
- bindings/nodejs/npm/darwin-x64/package.json
- bindings/nodejs/npm/linux-arm64-gnu/package.json
- bindings/nodejs/npm/linux-arm64-musl/package.json
- bindings/nodejs/npm/linux-x64-gnu/package.json
- bindings/nodejs/npm/win32-arm64-msvc/package.json
- bindings/nodejs/npm/win32-x64-msvc/package.json
- bindings/nodejs/package.json
- bindings/python/Cargo.toml
- core/Cargo.lock
- core/Cargo.toml
- dev/src/release/package.rs
- integrations/cloud_filter/Cargo.toml
- integrations/dav-server/Cargo.toml
- integrations/fuse3/Cargo.toml
- integrations/object_store/Cargo.toml
- integrations/parquet/Cargo.toml
- integrations/unftp-sbe/Cargo.toml
Part of https://github.com/apache/opendal/issues/6185
> Bump opendal to v0.53.3 (Round 1)

- core/src/services/azblob/backend.rs
- core/src/services/azdls/backend.rs
- core/src/types/blocking_write/std_writer.rs
- core/src/types/error.rs
- integrations/virtiofs/src/error.rs
None
This PR will address clippy issues around:
```rust
error: the `Err`-variant returned from this function is very large
--> src/services/oss/core.rs:176:10
|
176 |     ) -> Result<http::request::Builder> {
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 128 bytes
|
= help: try reducing the size of `types::error::Error`, for example by boxing large elements or replacing it with `Box<types::error::Error>`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
```
This PR also fixed other clippy issues at the same time to make CI happy.
> refactor(core): Put Backtrace in a box to reduce error size

- bin/oli/src/commands/mod.rs
- bin/oli/src/commands/tee.rs
- bin/oli/tests/integration/main.rs
- bin/oli/tests/integration/tee.rs
part of #422 .
user can use oli tee now.
```
oli tee file1 file2
```
will copy file1 to file2 and print to stdout.
> feat(bin/oli): support tee

- core/src/types/error.rs
Signed-off-by: xxchan <xxchan22f@gmail.com>
Closes #.
> feat: expose `Error::backtrace()`

- README.md
- bindings/ocaml/DEPENDENCIES.md
- website/blog/2024-01-22-apache-opendal-graduated/index.md
- website/docs/20-bindings/ocaml.mdx
use https://github.com/antfu/case-police to fix Ocaml to OCaml
> doc: case-police Ocaml to OCaml

- core/src/services/azdls/backend.rs
- core/src/services/azdls/config.rs
- core/src/services/azdls/core.rs
Client Credential & SAS Token Authentication is a valid authentication mechanism for ADLS and should be supported by opendal. `reqsign` already supports it.
Add configuration options for the following parameters and pass them to reqsign:
* `client_secret`
* `tenant_id`
* `client_id`
* `sas_token`
* `authority_host`
Yes, but no breaking changes. Just additional config options.
> feat: ADLS Client Credential Authentication

- core/src/services/s3/delete.rs
None
One of opendal users report a panic in opendal:
```rust
2025-05-16T06:55:27.909244+00:00[Etc/UTC]  WARN storage::service: service.rs:103 opendal will retry after 2.563914299s because: RateLimited (temporary) at delete => S3Error { code: "SlowDown", message: "Please reduce your request rate.", resource: "", request_id: "x" }
Context:
uri: http://xxx.s3.cn-northwest-1.amazonaws.com.cn/?delete
response: Parts { status: 503, version: HTTP/1.1, headers: {"x-amz-request-id": "x", "x-amz-id-2": "x", "content-type": "application/xml", "transfer-encoding": "chunked", "date": "Fri, 16 May 2025 06:55:27 GMT", "connection": "close", "server": "AmazonS3"} }
service: s3
deleted: 0
node_id=x nodegroup=x
2025-05-16T06:55:27.921869+00:00[Etc/UTC] ERROR runtime::global: global.rs:105 panic occurred: …
```
> fix(services/s3): Remove not needed check for batch delete

- core/src/services/azblob/backend.rs
- core/src/services/cos/backend.rs
- core/src/services/gcs/core.rs
- core/src/services/obs/backend.rs
- core/src/services/oss/core.rs
- core/src/services/s3/backend.rs
- core/src/services/swift/backend.rs
- core/src/types/metadata.rs
None
Currently, the method signature of `with_user_metadata` in the metadata module has a different signature to the `with_xxx` methods, which is a bit confusing.
None
> refactor(core/types)!: fix `with_user_metadata` signature

- core/src/docs/rfcs/0000_options_api.md
- core/src/docs/rfcs/6213_options_api.md
- core/src/docs/rfcs/mod.rs
Closes https://github.com/apache/opendal/issues/5727
Propose a new API to make our users lives easier.
A new RFC.
None
> RFC-6213: Options API

- core/src/services/hdfs_native/docs.md
> docs(services/hdfs_native): fix outdated capabilities and config option name

- bindings/java/src/async_operator.rs
- bindings/java/src/convert.rs
- bindings/java/src/lib.rs
- bindings/java/src/main/java/org/apache/opendal/WriteOptions.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/test/behavior/AsyncWriteOptionsTest.java
- bindings/java/src/test/java/org/apache/opendal/test/behavior/BlockingWriteOptionTest.java
Related to #6214.
This PR implements WriteOptions support in Java bindings as part of the migration to the new options API outlined in RFC-6213 (#6213). This is the first step in migrating Java bindings to use the new options APIs, starting with write operations. Although if you rather have all options migrated in one go we can close.
Added a complete mapping and conversion of the`opendal::options::WriteOptions` and the Java WriteOptions class. 
no, but I added the ability to handle chunking, and concurrency options to match opt api.
Let me know if this is the right direction!
> feat(bindings/java): Add WriteOptions support for new options API

- bindings/java/src/async_operator.rs
- bindings/java/src/convert.rs
- bindings/java/src/lib.rs
- bindings/java/src/main/java/org/apache/opendal/Capability.java
- bindings/java/src/main/java/org/apache/opendal/ListOptions.java
- bindings/java/src/operator.rs
- bindings/java/src/test/java/org/apache/opendal/test/behavior/AsyncListTest.java
- bindings/java/src/test/java/org/apache/opendal/test/behavior/BlockingListTest.java
Related to #6226.
This PR adds support for the rest of the ListOptions and migrates the rest of them to use the new options API support in Java bindings as part of the migration to the new options API outlined in RFC-6213 (#6213). 
* Extended the java capabilities to include the required listing capabilities for the rest of the list options
* Added a complete mapping and conversion of theopendal::options::ListOptions and the Java ListOptions class. 
Yes, added the rest of ListOptions: `limit, startAfter, versions, deleted`
> feat(bindings/java): Add ListOptions support for new options API

- bin/oli/Cargo.toml
Cheers,
I noticed that oli missed the dropbox support. I added it.
Just added the feature flag in olis Cargo.toml
I don't think so :)
> oli: support dropbox

- core/src/services/moka/backend.rs
- core/src/services/moka/config.rs
- core/src/services/moka/docs.md
Closes #.
Replace `moka::sync::Cache` with `moka::future::Cache`
> refactor(services/moka)!: replace `sync::Cache` with `future::Cache`

- core/Cargo.lock
- core/Cargo.toml
- core/src/layers/fastmetrics.rs
- core/src/layers/mod.rs
Closes #.
Add another metrics layer implementation
[fastmetrics](https://github.com/koushiro/fastmetrics) is another OpenMetrics library I implemented.
Its implementation and APIs are referenced from [prometheus_client](https://github.com/prometheus/client_rust) and [prometheus](https://github.com/tikv/rust-prometheus) library, and it provides a convenient derive macro for registering metrics. It has been used in several of my own projects for a while, and I think it might be possible to push it into the OpenDAL repository.
> feat(layers): add fastmetrics layer

- bindings/go/go.mod
- bindings/go/go.sum
- Update github.com/ebitengine/purego from v0.8.3 to v0.8.4
- Update github.com/jupiterrider/ffi from v0.4.1 to v0.5.0
The v0.5.0 of ffi introduces embed libffi.
Make life easier for Windows and macOS developers :) https://github.com/apache/opendal/issues/6279#issuecomment-2960719317
> chore(bindings/go): update Go dependencies

- core/src/layers/http_client.rs
- core/src/layers/mod.rs
- core/src/types/operator/operator.rs
None
Make OpenDAL's API more consistent.
Add HttpClientLayer to replace `Operator::update_http_client()`
Deprecate existing APIs.
> feat: Add HttpClientLayer to replace `Operator::update_http_client()`

- core/src/services/redis/backend.rs
- core/src/services/redis/core.rs
- core/src/services/redis/delete.rs
- core/src/services/redis/docs.md
- core/src/services/redis/writer.rs
Part https://github.com/apache/opendal/issues/5739
See https://github.com/apache/opendal/issues/5739
Migrate redis from adapter::kv to Access instead
No.
> refactor: Migrate redis from adapter::kv to Access instead

- core/src/services/hdfs/writer.rs
Closes #6288.
This change serves as a temporary workaround. Ideally, the root issue in the `blocking` crate should be addressed.
- call `flush` to detect status of file when `write` return 0.
No user-facing changes.
> fix(hdfs): fix infinite loop in write for HDFS failure

- core/src/services/moka/backend.rs
- core/src/services/moka/core.rs
- core/src/services/moka/delete.rs
- core/src/services/moka/lister.rs
- core/src/services/moka/writer.rs
Part of https://github.com/apache/opendal/issues/5739
Make opendal's core more easy to understand.
> refactor: Migrate moka from adapter::typed_kv to Access instead

- bindings/nodejs/generated.d.ts
- bindings/nodejs/generated.js
- bindings/nodejs/package.json
- bindings/nodejs/pnpm-lock.yaml
- bindings/nodejs/src/capability.rs
- bindings/nodejs/src/lib.rs
- bindings/nodejs/src/options.rs
- bindings/nodejs/tests/suites/asyncStatOptions.suite.mjs
- bindings/nodejs/tests/suites/index.mjs
- bindings/nodejs/tests/suites/syncStatOptions.suite.mjs
- bindings/nodejs/tests/utils.mjs
- bindings/nodejs/vitest.config.mjs
This PR adds support for opendal::options::StatOptions conversion in the nodejs bindings. This is part of the migration to the new options API outlined in RFC-6213 (https://github.com/apache/opendal/pull/6213).
- Added a complete mapping and conversion of opendal::options::StatOptions
- behavior tests mirroring Rust's async_stat.rs test suite
Yes, users can now add options to their stat requests
> feat(bindings/nodejs): Add StatOptions support for new options API

- bindings/nodejs/tests/suites/asyncStatOptions.suite.mjs
- bindings/nodejs/tests/suites/syncStatOptions.suite.mjs
Workaround for https://github.com/apache/opendal/issues/6305
Get CI green.
> ci: Disable failed CI until #6305 been fixed

- bindings/python/src/errors.rs
- bindings/python/src/file.rs
Closes #6235
python bindings users `FuturesWriter` directly which returns rust IO error. This can lead to we return different exceptions compared to `write`.
This PR fixed this by downcast them to the correct error.
No.
> fix(bindings/python): Fix Writer doesn't throw correct error code

- bin/oli/src/commands/ls.rs
- bin/oli/tests/integration/ls.rs
Signed-off-by: Ruihang Xia <waynestxia@gmail.com># Which issue does this PR close?
Related to https://github.com/apache/opendal/issues/422
Tree view is easier to read for deep folders
Implement `oli ls --tree`/`oli ls -T` for listing with tree view. E.g.:
```
> oli ls -T ./src
.
├── bin/
│   └── oli.rs
├── commands/
│   ├── bench/
│   │   ├── mod.rs
│   │   ├── report.rs
│   │   └── suite.rs
│   ├── cat.rs
│   ├── cp.rs
│   ├── edit.rs
│   ├── ls.rs
│   ├── mod.rs
│   ├── mv.rs
│   ├── rm.rs
│   ├── stat.rs
│   └── tee.rs
├── config/
│   └── mod.rs
├── lib.rs
├── params/
│   ├── config.rs
│   └── mod.rs
└── utils/
```
Yes, a new option
> feat: implement --tree option for oli ls subcommand

- .vscode/settings.json
- bindings/nodejs/generated.d.ts
- bindings/nodejs/src/capability.rs
- bindings/nodejs/src/lib.rs
- bindings/nodejs/src/options.rs
- bindings/nodejs/tests/suites/asyncReadOptions.suite.mjs
- bindings/nodejs/tests/suites/index.mjs
- bindings/nodejs/tests/suites/syncReadOptions.suite.mjs
This PR adds support for opendal::options::ReadOptions and opendal::options::ReaderOptions conversion in the nodejs bindings. This is part of the migration to the new options API outlined in RFC-6213 (https://github.com/apache/opendal/pull/6213).
- Added a complete mapping and conversion of opendal::options::ReadOptions and opendal::options::ReaderOptions
- behavior tests mirroring Rust's async_read.rs test suite
Yes, users can now add options to their read and reader requests
> feat(bindings/nodejs): Add ReadOptions and ReaderOptions support for new options API

- core/src/raw/path.rs
- core/src/services/fs/backend.rs
- core/src/services/fs/core.rs
- core/src/services/ftp/backend.rs
- core/src/services/hdfs/backend.rs
The follow-up for a dependency question from #6317.
1. Removes `uuid` dependency for:
* fs
* ftp
* hdfs
2. Uses std when possible compared to using a crate. e.g., fastrand, getrandom.
* refactor `build_tmp_path_of`
* add tests
* minor code cleanup
no.
> refactor: remove uuid dependency when creating a temp path

- core/src/services/fs/core.rs
- core/src/services/ftp/backend.rs
- core/src/services/hdfs/backend.rs
Closes #.
#6324 modified the tmp_path value during append, but the value was inverted.
> fix(fs/ftp/hdfs): correct tmp_path generation for append operations

- integrations/dav-server/src/fs.rs
Closes #.
MKCOL method fails to create folder under nested path in webdav.
for example:
MKCOL /a/
MKCOL /a/b/
I found out it was because of the exists function, adding “/” to the end of the path makes exists think it's a folder instead of a file.
One line of code
hasn't
> fix(dav-server): Fix create_dir to create nested directories

- core/src/services/fs/backend.rs
- core/src/services/fs/core.rs
- core/src/services/fs/writer.rs
Closes #.
While implementing the `WriteOptions`#6322 in Node.js, I found that the `if_not_exists` property test fails without throwing the `ConditionNotMatch` exception.
When `if_not_exists` is true, if the file already exists, a `ConditionNotMatch` exception should be thrown.
https://github.com/apache/opendal/blob/23f01dd545ebd2a7445f08cc5e7de8a19e70fb25/core/tests/behavior/async_write.rs#L773-L778
> fix(service/fs): handle if_not_exists flag to raise ConditionNotMatch error

- bindings/nodejs/generated.d.ts
- bindings/nodejs/src/capability.rs
- bindings/nodejs/src/lib.rs
- bindings/nodejs/src/options.rs
- bindings/nodejs/tests/suites/asyncListOptions.suite.mjs
- bindings/nodejs/tests/suites/index.mjs
- bindings/nodejs/tests/suites/syncListOptions.suite.mjs
This PR adds support for opendal::options::ListOptions conversion in the nodejs bindings. This is part of the migration to the new options API outlined in RFC-6213 (https://github.com/apache/opendal/pull/6213).
- Added a complete mapping and conversion of opendal::options::ListOptions
- behavior tests mirroring Rust's async_list.rs test suite
Yes, users can now add options to their list requests
> feat(bindings/nodejs): Add ListOptions support for new options API

- bindings/nodejs/tests/suites/asyncListOptions.suite.mjs
- bindings/nodejs/tests/suites/syncListOptions.suite.mjs
Related #6320
fix ListOptions list with deleted test
> fix(bindings/nodejs): ListOptions test list with deleted

- core/src/services/azdls/core.rs
- core/src/services/azdls/writer.rs
Part of #5693 
Return metadata for write.
I had copied what @meteorgan did with the `azblob` change (thanks! 😄 ). Just trying to learn some of the internals for services in Opendal
> feat(services/azdls): Implement write returns metadata

- bindings/nodejs/generated.d.ts
- bindings/nodejs/src/capability.rs
- bindings/nodejs/src/lib.rs
- bindings/nodejs/src/options.rs
- bindings/nodejs/tests/suites/asyncDeleteOptions.suite.mjs
- bindings/nodejs/tests/suites/index.mjs
- bindings/nodejs/tests/suites/syncDeleteOptions.suite.mjs
This PR adds support for opendal::options::DeleteOptions conversion in the nodejs bindings. This is part of the migration to the new options API outlined in RFC-6213 (https://github.com/apache/opendal/pull/6213).
- Added a complete mapping and conversion of opendal::options::DeleteOptions
- behavior tests mirroring Rust's async_delete.rs test suite
Yes, users can now add options to their delete requests
> feat(bindings/nodejs): Add DeleteOptions support for new options API

- bindings/nodejs/generated.d.ts
- bindings/nodejs/src/capability.rs
- bindings/nodejs/src/lib.rs
- bindings/nodejs/src/options.rs
- bindings/nodejs/tests/suites/asyncWriteOptions.suite.mjs
- bindings/nodejs/tests/suites/index.mjs
- bindings/nodejs/tests/suites/syncWriteOptions.suite.mjs
This PR adds support for opendal::options::WriteOptions conversion in the nodejs bindings. This is part of the migration to the new options API outlined in RFC-6213 (https://github.com/apache/opendal/pull/6213).
- Added a complete mapping and conversion of opendal::options::WriteOptions
- behavior tests mirroring Rust's async_write.rs test suite
Yes, users can now add options to their write requests
> feat(bindings/nodejs): Add WriteOptions support for new options API

- .github/dependabot.yml
Address comment. https://github.com/apache/opendal/pull/6389#issuecomment-3066615483
I didn't know the API changes. Sorry.
Exclude rand, getrandom crates from the dependabot group.
No.
> chore(dependabot): exclude rand and getrandom crates

- bindings/python/Cargo.toml
Related to https://github.com/NobodyXu/concurrent_arena/issues/25
Get our release first.
> chore: Disable openssh build to allow python release

- bin/oay/Cargo.lock
- bin/ofs/Cargo.lock
- bin/oli/Cargo.lock
- website/DEPENDENCIES.node.csv
- website/package.json
- website/plugins/image-ssr-plugin.js
- website/pnpm-lock.yaml
Closes #.
This update primarily focuses on removing unused dependencies, upgrading the minimum required Node.js version, and refactoring the image SSR plugin for improved maintainability and performance.
- Unused dependencies such as ‎`axios` and ‎`clsx` have been removed from both ‎`package.json` and ‎`DEPENDENCIES.node.csv`.
- The minimum Node.js version requirement is now set to 20.0.0 because Node.js 18 has reached its end of life [EOL](https://nodejs.org/en/about/previous-releases) as of April 2025 and no longer receives security or maintenance updates. Upgrading to Node.js 20 ensures better security and compatibility with dependencies.
- The image SSR plugin (‎`image-ssr-plugin.js`) has been refactored: it now uses modern async APIs (‎`fs/promises` instead of ‎`fs-extra`, and …
> refactor(website): remove unused dependencies and update node engine requirement

- website/community/release/release.md
Closes #.
Fix incorrect CI workflow links in the release documentation.
Updated the workflow links for Python, Java, and Node.js bindings to their correct CI URLs.
No user-facing changes. Documentation links only.
> docs(release): fix CI workflow links for bindings

- .github/workflows/docs.yml
- integrations/object_store/src/store.rs
Closes #6467 .
Summary by copilot
- Implemented put_multipart_opts to support setting object attributes during multipart upload.
- Added copy_if_not_exists with error handling for already existing files.
- Populated GetResult.attributes with user-defined object metadata.
> feat(object_store): Implement copy_if_not_exists, put_multipart_opts and metadata  in GetResult

- .github/workflows/ci_bindings_java.yml
- .github/workflows/release_java.yml
Closes https://github.com/apache/opendal/issues/6485
Build java release on native platforms.
> ci: Use ubuntu-24.04-arm for java release to address glibc issues

- integrations/object_store/src/store.rs
fix https://github.com/apache/opendal/actions/runs/16979213117/job/48135410768
make clippy happy
remove redundant into_iter() call
nope
> fix(integrations/object_store): remove redundant into_iter() call

- core/src/services/oss/backend.rs
- core/src/services/oss/config.rs
Closes #6507.
> Security Token Service (STS) allows you to grant time-limited access to data stored on Object Storage Service (OSS) by using temporary access credentials. After the temporary access credentials expire, they can no longer be used to access the data. This helps improve flexibility and timeliness of access control.
- Add the field `security_token` in `OSSConfig`.
- Add the method `security_token` in `OSSBuilder`.
- Improve the documentation for the `access_key_id` and `access_key_secret` fields in `OssConfig`.
- Add the method `security_token` in `OSSBuilder`.
> feat(services/oss): add support for security token for Aliyun OSS

- bindings/nodejs/tests/suites/asyncReadOptions.suite.mjs
- bindings/nodejs/tests/suites/asyncStatOptions.suite.mjs
- bindings/nodejs/tests/utils.mjs
Use Node.js built-in setTimeout to replace the custom sleep function.
> chore(bindings/nodejs): replace custom sleep with setTimeout in tests

- bindings/d/README.md
- bindings/d/build.d
- bindings/d/source/opendal/package.d
Related #6340.
<b>This PR was primarily authored with Kiro using Claude Sonnet 4 and then hand-reviewed by me. I AM responsible for every change made in this PR. I aimed to keep it aligned with our goals, though I may have missed minor issues. Please flag anything that feels off, I'll fix it quickly.</b>
CI failure: https://github.com/apache/opendal/actions/runs/17574060053/job/49915435369
The original test used the `fs` backend in the test, but the c-bindings do not have the fs backend enabled by default, so the test failed.
https://github.com/apache/opendal/blob/5e074cc49bc7662c790d88fb9be31e7c67899d64/bindings/d/source/opendal/package.d#L56
- Enhanced the D bindings build script (‎`build.d`) to support automatic configuration of test backends and build options via environment variables …
> fix(bindings/d): Enhance D bindings build script and tests for OpenDAL

- .github/workflows/release_ruby.yml
Fixes the default branch name in the workflow
> ci: Fix default branch name in Ruby release workflow

- integrations/unftp-sbe/src/lib.rs
The previous implem was not working: files were not being written to the object
storage, and writing was failing silently, with a warning from opendal.
The compat writer should be shutdown properly after write, as detailed in
https://github.com/apache/opendal/issues/4926.
This is the only simple change this PR proposes.
> fix(integrations/unftp-sbe): properly shutdown after write

- bindings/ruby/README.md
- website/docs/20-bindings/ruby.mdx
Part of #5227
This PR adds documentation for Ruby bindings for newly released gem.
> doc(bindinds/ruby): add examples and links

- core/src/blocking/operator.rs
- core/src/docs/rfcs/5444_operator_from_uri.md
- core/src/services/fs/backend.rs
- core/src/services/fs/mod.rs
- core/src/services/memory/backend.rs
- core/src/services/memory/mod.rs
- core/src/services/mod.rs
- core/src/services/s3/backend.rs
- core/src/services/s3/mod.rs
- core/src/types/builder.rs
- core/src/types/mod.rs
- core/src/types/operator/builder.rs
- core/src/types/operator/mod.rs
- core/src/types/operator/registry.rs
Part of https://github.com/apache/opendal/issues/5445
This PR will allow users to load operator from uri.
Added an `OperatorRegistry` in OpenDAL
Users can now calling `Operator::from_uri("s3://bucket", [("region", "us-east-1")])`
---
**This PR was primarily authored with Codex using GPT-5-Codex and then hand-reviewed by me. I AM responsible for every change made in this PR. I aimed to keep it aligned with our goals, though I may have missed minor issues. Please flag anything that feels off, I'll fix it quickly.**
> feat: Add Operator Registry
