apache/opendal

LICENSE, README.md
=> docs: Update current status

.github/PULL_REQUEST_TEMPLATE.md
=> ci: Introduce CLA in PR template

CHANGELOG.md, Cargo.toml
=> Bump to version 0.0.3

docs/rfcs/0000-error-handle.md, docs/rfcs/0044-error-handle.md
RFC for error handling, demo: https://github.com/datafuselabs/opendal/pull/43
[Rendered](https://github.com/Xuanwo/opendal/blob/error-handle-rfc/docs/rfcs/0044-error-handle.md)
=> RFC-0044: Error Handle

CHANGELOG.md, Cargo.toml
=> Bump to version 0.0.4

README.md
=> docs: Fix outdated README

src/io.rs
=> io: Remove not used debug print

CHANGELOG.md, Cargo.toml
=> Bump to version 0.0.5

src/accessor.rs, src/io.rs, src/lib.rs, src/readers/callback.rs, src/readers/stream.rs, src/services/fs.rs, src/services/s3.rs
=> io: Rename BoxedAsyncRead to BoxedAsyncReader

.env.example, Cargo.toml, benches/ops/s3.rs, src/services/s3.rs, tests/behavior/s3.rs
=> backend/s3: Implement RFC-57 Auto Region

CHANGELOG.md, Cargo.toml
=> Bump to version 0.1.0

.github/workflows/service_test_fs.yml, .github/workflows/service_test_s3.yml, opendal_test/src/services/s3.rs, src/services/s3.rs, tests/behavior/behavior.rs
=> backend/s3: Enable test on AWS S3

CHANGELOG.md, Cargo.toml
=> Bump to version 0.1.1

README.md, examples/basic.rs, src/io.rs, src/object.rs, tests/behavior/behavior.rs
=> object: Polish API for Metadata

.taplo.toml, Cargo.toml, opendal_test/Cargo.toml, rust-toolchain.toml
=> deps: Bump s3 sdk to 0.8

benches/ops/ops.rs
=> bench: Improve logic

CHANGELOG.md, Cargo.toml
=> Bump to version 0.1.3

CHANGELOG.md, Cargo.toml
=> Bump to version 0.2.0

Cargo.toml, src/credential.rs, src/services/fs.rs, src/services/s3/backend.rs, src/services/s3/object_stream.rs, tests/behavior/fs.rs, tests/behavior/main.rs, tests/behavior/s3.rs
Implement https://github.com/datafuselabs/opendal/issues/118
=> *: Implement logging support

src/accessor.rs, src/credential.rs, src/error.rs, src/lib.rs, src/object.rs, src/operator.rs, src/ops.rs, src/readers/mod.rs, src/scheme.rs, src/services/fs.rs, src/services/memory.rs, src/services/mod.rs, src/services/s3/backend.rs, src/services/s3/mod.rs
docs: Cover all public types and functions
=> docs: Cover all public types and functions

examples/fs.rs, examples/s3.rs, src/services/fs/backend.rs, src/services/fs/error.rs, src/services/fs/mod.rs, src/services/fs/object_stream.rs, src/services/memory/backend.rs, src/services/memory/mod.rs, src/services/s3/mod.rs
services: Refactor into directories
=> services: Refactor into directories

.github/workflows/docs.yaml, vercel.json
ci: Generate main docs to opendal.databend.rs
=> ci: Generate main docs to opendal.databend.rs

src/object.rs
=> docs: Add examples for object

CHANGELOG.md, Cargo.toml
=> Bump to version 0.2.1

CHANGELOG.md, Cargo.toml
=> Bump to version 0.2.2

src/accessor.rs, src/lib.rs, src/object.rs
feat: Export BoxedObjectStream so that users can implement Layer
=> feat: Export BoxedObjectStream so that users can implement Layer

CHANGELOG.md, Cargo.toml
=> Bump to version 0.2.3

.github/workflows/service_test_fs.yml, .github/workflows/service_test_memory.yml, .github/workflows/service_test_s3.yml, Cargo.toml, src/object.rs, src/services/fs/backend.rs, src/services/s3/backend.rs
=> feat: Add content_md5 and last_modified in metadata

CHANGELOG.md, Cargo.toml
=> Bump to version 0.2.4

Cargo.toml, src/services/s3/object_stream.rs, tests/behavior/behavior.rs
feat: Adopt quick_xml to parse xml
=> feat: Adopt quick_xml to parse xml

src/services/s3/backend.rs
=> feat: Allow user input region

CHANGELOG.md, Cargo.toml
=> Bump to version 0.2.5

CHANGELOG.md, Cargo.toml, src/lib.rs, src/scheme.rs
=> Bump to version 0.3.0

Cargo.toml, README.md
deps: Bump to reqsign to fix s3 url encode issue
=> deps: Bump to reqsign to fix s3 url encode issue

README.md, benches/ops/write.rs, examples/basic.rs, examples/s3.rs, examples/write.rs, src/accessor.rs, src/io.rs, src/io_util/http_body.rs, src/io_util/mod.rs, src/io_util/read_observer.rs, src/io_util/seekable_reader.rs, src/io_util/write_observer.rs, src/lib.rs, src/object.rs, src/operator.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/memory/backend.rs, src/services/s3/backend.rs, tests/behavior/behavior.rs
refactor: Rollback changes around async streaming io
=> refactor: Rollback changes around async streaming io

README.md, src/io_util/http_body.rs, src/io_util/mod.rs, src/io_util/read_observer.rs, src/lib.rs, src/object.rs, src/ops.rs
docs: Add docs for public types
=> docs: Add docs for public types

CHANGELOG.md, Cargo.toml, docs/rfcs/0191-async-streaming-io.md, docs/upgrade.md, src/services/s3/backend.rs
=> Bump to version 0.4.0

CHANGELOG.md
=> docs: Fix typo in CHANGELOG

src/io_util/mod.rs, src/io_util/seekable_reader.rs
=> feat: Export SeekableReader

CHANGELOG.md, Cargo.toml
=> Bump to version 0.4.1

src/object.rs, tests/behavior/behavior.rs
feat: Add seekable_reader on Object
Address https://github.com/datafuselabs/databend/pull/4678#discussion_r841141934
=> feat: Add seekable_reader on Object

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
=> Bump to version 0.4.2

src/error.rs
=> feat: Improve error message

docs/rfcs/0000-create-dir.md, docs/rfcs/0221-create-dir.md
=> RFC-0221: Create Dir

.github/actions/check/action.yml, .github/workflows/ci.yml, .github/workflows/docs.yaml, .github/workflows/service_test_fs.yml, .github/workflows/service_test_memory.yml, .github/workflows/service_test_s3.yml, Cargo.toml, src/io_util/compress.rs, src/io_util/mod.rs, src/object.rs, tests/behavior/behavior.rs
feat: Implement compress support
Fix #70
=> feat: Implement decompress read support

src/accessor.rs, src/object.rs
docs: Add bahvior docs for create operation
=> docs: Add bahvior docs for create operation

CHANGELOG.md, Cargo.toml
=> Bump to version 0.5.1

Cargo.toml
chore: Build all features for docs.rs
=> chore: Build all features for docs.rs

.github/dependabot.yml, Cargo.toml, opendal_test/Cargo.toml
ci: Enable auto dependence upgrade
=> ci: Enable auto dependence upgrade

CHANGELOG.md, Cargo.toml
=> Bump to version 0.5.2

src/layer.rs, src/object.rs, src/ops.rs, src/scheme.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/memory/backend.rs, src/services/s3/backend.rs
docs: Improve docs to 100% coverage
=> docs: Improve docs to 100% coverage

docs/rfcs/0000-retryable-error.md, docs/rfcs/0247-retryable-error.md
=> RFC-0247: Retryable Error

rustfmt.toml, src/io_util/into_sink.rs, src/io_util/into_writer.rs, src/io_util/seekable_reader.rs, src/io_util/write_observer.rs, src/layers/layer.rs, src/layers/retry.rs, src/lib.rs, src/object.rs, src/operator.rs
docs: Make sure code examples are formatted
=> docs: Make sure code examples are formatted

src/services/azblob/backend.rs, src/services/fs/error.rs, src/services/s3/backend.rs
feat: Implement retryable errors for azblob and s3
Part of https://github.com/datafuselabs/opendal/issues/248
=> feat: Implement retryable errors for azblob and s3

CHANGELOG.md, Cargo.toml
=> Bump to version 0.6.0

CHANGELOG.md, Cargo.toml
=> Bump to version 0.6.1

CHANGELOG.md, Cargo.toml
=> Bump to version 0.6.2

.github/workflows/projects.yml
=> ci: Add all issues into databend-storage project

src/services/azblob/backend.rs, src/services/hdfs/backend.rs, src/services/s3/backend.rs
=> feat(services): Allow endpoint has trailing slash

CHANGELOG.md, Cargo.toml
=> Bump to version 0.6.3

Cargo.toml, src/io.rs, src/io_util/compress.rs, src/object.rs
=> feat: Add support for blocking decompress_read

src/operator.rs, tests/behavior/behavior.rs
=> feat: Add check for operator

.github/workflows/docs.yaml, book.toml, docs/SUMMARY.md, docs/rfcs/README.md, vercel.json
docs: Use mdbook to generate documentation
=> docs: Use mdbook to generate documentation

src/object.rs, tests/behavior/behavior.rs
feat: Implement RFC-0293 Object ID
Fix #294
=> feat: Implement RFC-0293 Object ID

Cargo.toml
fix(services/aws): Increase retry times for AWS STS
=> fix(services/aws): Increase retry times for AWS STS

src/io_util/compress.rs, src/io_util/mod.rs, src/object.rs, tests/behavior/behavior.rs
=> feat(io_util): Refactor decompress decoder 

.github/workflows/docs.yaml
ci: Adopt amondnet/vercel-action
=> ci: Adopt amondnet/vercel-action

CHANGELOG.md, Cargo.toml, book.toml, docs/upgrade.md
=> Bump to version v0.7.0 

Cargo.toml
=> publish: Fix git version not allowed

CHANGELOG.md, Cargo.toml
=> Bump to version 0.7.1

src/io_util/compress.rs
=> feat(io_util): Improve debug logging for compress

Cargo.toml, src/services/s3/backend.rs
feat(services/s3): Add disable_credential_loader support
=> feat(services/s3): Add disable_credential_loader support

src/operator.rs, tests/behavior/behavior.rs
=> feat: Allow check user input

examples/README.md, examples/s3-sse-kms-aws.rs, examples/s3-sse-s3.rs
=> docs: Fix typo in examples

README.md
docs: Update README to reflect current status
=> docs: Update README to reflect current status

src/io_util/compress.rs
fix(io_util/compress): Fix decoder's buf not all consumed
=> fix(io_util/compress): Fix decoder's buf not all consumed

CHANGELOG.md, Cargo.toml, src/services/fs/backend.rs, src/services/hdfs/backend.rs
=> Bump to version 0.7.2

CHANGELOG.md, Cargo.toml
=> Bump to version 0.7.3

docs/SUMMARY.md, docs/rfcs/0000-dir-entry.md, docs/rfcs/0337-dir-entry.md
This proposal will add `DirEntry` in OpenDAL.
=> RFC-0337: Dir Entry

CHANGELOG.md, Cargo.toml, docs/upgrade.md
=> Bump to version 0.8

Cargo.toml, src/layers/retry.rs, src/lib.rs, src/scheme.rs, src/services/http/backend.rs, src/services/http/mod.rs, src/services/mod.rs
=> feat: Implement http service support 

src/io_util/http_header.rs, src/io_util/mod.rs, src/services/azblob/backend.rs, src/services/http/backend.rs, src/services/s3/backend.rs
feat: Add http_header to handle HTTP header parse
=> feat: Add http_header to handle HTTP header parse

.github/workflows/service_test_s3.yml, src/services/s3/backend.rs, src/services/s3/tests.rs
=> feat(services/s3): Add virtual host API style support

CHANGELOG.md, Cargo.toml, README.md, docs/services/s3.md
=> Bump to version 0.9.0

src/io_util/http_header.rs, src/io_util/mod.rs, src/lib.rs, src/object.rs, src/services/azblob/backend.rs, src/services/http/backend.rs, src/services/s3/backend.rs
=> feat(object): Add ETag support

Cargo.toml
=> build: Exclude docs from publish

src/io_util/http_client.rs, src/io_util/mod.rs, src/services/azblob/backend.rs, src/services/http/backend.rs, src/services/s3/backend.rs
=> feat: Convert retryable hyper errors into Interrupted

Cargo.toml, src/io_util/http_client.rs, src/io_util/mod.rs, src/services/azblob/backend.rs, src/services/s3/backend.rs, tests/behavior/behavior.rs
fix: Special chars not handled correctly
=> fix: Special chars not handled correctly

CHANGELOG.md, Cargo.toml
=> Bump to version 0.9.1

docs/SUMMARY.md, docs/rfcs/0000-accessor-capabilities.md, docs/rfcs/0409-accessor-capabilities.md, src/operator.rs
Add rfc accesoor capabilities
Fix https://github.com/datafuselabs/opendal/discussions/406
=> RFC-0409: Accessor Capabilities

Cargo.toml, src/accessor.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/hdfs/backend.rs, src/services/http/backend.rs, src/services/memory/backend.rs, src/services/s3/backend.rs
feat: Implement RFC-0409 Accessor Capabilities
=> feat: Implement RFC-0409 Accessor Capabilities

docs/SUMMARY.md
=> docs: Add new RFCs in list

Cargo.toml, docs/rfcs/0413-presign.md, examples/azblob.rs, examples/fs.rs, examples/hdfs.rs, examples/s3.rs, rustfmt.toml, src/accessor.rs, src/io_util/http_client.rs, src/io_util/seekable_reader.rs, src/layers/retry.rs, src/object.rs, src/ops.rs, src/services/azblob/backend.rs, src/services/s3/backend.rs, tests/behavior/behavior.rs
=> feat: Implement presign support for s3

.github/actions/check/action.yml, .github/workflows/ci.yml, .github/workflows/service_test_azblob.yml, .github/workflows/service_test_fs.yml, .github/workflows/service_test_hdfs.yml, .github/workflows/service_test_memory.yml, .github/workflows/service_test_s3.yml, docs/SUMMARY.md, docs/rfcs/0000-command-line-interface.md, docs/rfcs/0423-command-line-interface.md, docs/rfcs/README.md
This PR will propose a new RFC about adding a command-line interface for opendal.
[Rendered](https://github.com/datafuselabs/opendal/blob/rfc-for-cli/docs/rfcs/0423-command-line-interface.md)
=> RFC-0423: Command Line Interface

src/operator.rs
chore: Cleanup import of operator
=> chore: Cleanup import of operator

Cargo.toml, README.md, src/lib.rs
docs: Update description of OpenDAL
=> docs: Update description of OpenDAL

CHANGELOG.md, Cargo.toml, docs/SUMMARY.md, docs/examples/presign.md, docs/services/README.md, docs/services/azblob.md, docs/services/fs.md, docs/services/hdfs.md, docs/services/s3.md
=> Bump to version 0.11.0

docs/SUMMARY.md, docs/rfcs/0000-multipart.md, docs/rfcs/0438-multipart.md, src/operator.rs
RFC: Multipart
pre-proposal: https://github.com/datafuselabs/opendal/discussions/437
Related ideas: https://note.xuanwo.io/#/page/opendal%20%E5%88%86%E6%AE%B5%E4%B8%8A%E4%BC%A0%E8%AE%BE%E8%AE%A1
=> RFC-0438: Multipart

.github/workflows/docs.yaml, docs/SUMMARY.md, docs/rfcs/0000-gateway.md, docs/rfcs/0443-gateway.md
This proposal intends to add a gateway called `oay` for OpenDAL.
=> RFC-0443: Gateway

oay/Cargo.lock, oay/Cargo.toml, oay/README.md, oay/src/commands/cli.rs, oay/src/env.rs, oay/src/lib.rs, oay/src/services/http/mod.rs, src/ops.rs
feat(oay): Implement range support
=> feat(oay): Implement range support

.github/dependabot.yml, CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.11.1

src/services/http/backend.rs
fix: Service HTTP inserted with wrong key
=> fix: Service HTTP inserted with wrong key

Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
chore: Fix opendal Cargo.toml not updated
=> chore: Fix opendal Cargo.toml not updated

Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock
build: Remove not used features
=> build: Remove not used features

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.11.3

README.md
=> docs: Add downloads in README

.github/workflows/ci.yml, README.md
docs: Update slogan for OpenDAL
=> docs: Update slogan for OpenDAL

CHANGELOG.md, Cargo.toml, oay/Cargo.toml, oli/Cargo.toml
=> Bump to version 0.11.4

docs/SUMMARY.md, docs/rfcs/0000-new-builder.md, docs/rfcs/0501-new-builder.md
=> RFC-0501: New Builder

src/lib.rs
refactor: Remove deprecated struct Metadata
=> refactor: Remove deprecated struct Metadata

Cargo.toml
=> chore: Fix cargo publish

Cargo.toml, src/layers/metrics.rs, src/layers/mod.rs, src/lib.rs, src/operator.rs, src/ops.rs, src/scheme.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/s3/backend.rs
=> feat: Refactor metrics and hide under feature layers-metrics

.github/workflows/ci.yml, .github/workflows/service_test_fs.yml, .github/workflows/service_test_http.yml, Cargo.toml, src/layers/layer.rs, src/layers/mod.rs, src/layers/retry.rs, src/lib.rs, src/operator.rs
refactor: Rewrite retry layer support
=> refactor: Rewrite retry layer support

.github/workflows/ci.yml, Cargo.toml, src/layers/mod.rs, src/layers/tracing.rs, src/lib.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/hdfs/backend.rs, src/services/memory/backend.rs, src/services/s3/backend.rs
feat(layer): Add TracingLayer support
=> feat(layer): Add TracingLayer support

src/layers/tracing.rs, src/services/gcs/backend.rs, src/services/gcs/dir_stream.rs, src/services/s3/backend.rs
=> styles: Make xuanwo happy

src/layers/logging.rs, src/layers/metrics.rs, src/layers/mod.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/gcs/backend.rs, src/services/hdfs/backend.rs, src/services/http/backend.rs, src/services/memory/backend.rs, src/services/s3/backend.rs, tests/behavior/behavior.rs
feat: Add LoggingLayer to replace service internal logs
Fix #482
=> feat: Add LoggingLayer to replace service internal logs

CHANGELOG.md, Cargo.toml, README.md, docs/upgrade.md, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.13

src/operator.rs
=> feat: Add walk for BatchOperator

examples/gcs.rs, src/operator.rs, src/scheme.rs, src/services/gcs/mod.rs
feat: Mark Scheme non_exhaustive and extendable
=> feat: Mark Scheme non_exhaustive and extendable

docs/SUMMARY.md
docs: Fix gcs is missing from index
=> docs: Fix gcs is missing from index

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.13.1

docs/SUMMARY.md, docs/rfcs/0000-write-refactor.md, docs/rfcs/0554-write-refactor.md
=> RFC-0554: Write Refactor

src/services/azblob/backend.rs
=> refactor: Fix typo in azblob backend

Cargo.toml, src/http_util/error.rs, src/services/s3/backend.rs, src/services/s3/dir_stream.rs, src/services/s3/error.rs
feat(services/s3): Implement Multipart support
Close https://github.com/datafuselabs/opendal/issues/566
=> feat(services/s3): Implement Multipart support

src/services/s3/backend.rs, tests/behavior/behavior.rs, tests/behavior/utils.rs
=> feat: Implement integration tests for multipart

CHANGELOG.md, Cargo.toml, docs/upgrade.md, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.14

src/lib.rs
docs: Add obs in OpenDAL lib docs
=> docs: Add obs in OpenDAL lib docs

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.14.1

src/accessor.rs, src/dir.rs, src/io.rs, src/object.rs, src/services/fs/backend.rs
feat: Implement blocking API for fs
=> feat: Implement blocking API for fs

src/dir.rs, src/layers/logging.rs, src/object.rs, src/services/fs/backend.rs, src/services/gcs/dir_stream.rs, tests/behavior/behavior.rs
feat: Add behavior tests for blocking operations
=> feat: Add behavior tests for blocking operations

src/layers/metrics.rs, src/layers/retry.rs, src/layers/tracing.rs
feat: Implement blocking operations for layers
=> feat: Implement blocking operations for layers

oay/Cargo.lock, oli/Cargo.lock
- Fixes https://github.com/datafuselabs/opendal/pull/612
- Fixes https://github.com/datafuselabs/opendal/pull/613
- Fixes https://github.com/datafuselabs/opendal/pull/614
- Fixes https://github.com/datafuselabs/opendal/pull/615
- Fixes https://github.com/datafuselabs/opendal/pull/616
=> deps: Bump versions of oay and oli deps

.env.example, .github/workflows/service_test_ipfs.yml, src/layers/logging.rs, src/services/ipfs/backend.rs, src/services/ipfs/builder.rs, src/services/ipfs/dir_stream.rs, src/services/ipfs/error.rs
feat: Add integration tests for ipfs
Current progress: 
```shell
test result: ok. 59 passed; 0 failed; 0 ignored; 0 measured; 354 filtered out; finished in 1.92s
```
Fix https://github.com/datafuselabs/opendal/issues/609
=> feat: Add integration tests for ipfs

README.md, docs/SUMMARY.md, docs/services/ipfs.md, examples/ipfs.rs, src/services/ipfs/mod.rs
docs: Add detailed docs for ipfs
=> docs: Add detailed docs for ipfs

src/path.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/gcs/backend.rs, src/services/hdfs/backend.rs, src/services/http/backend.rs, src/services/ipfs/builder.rs, src/services/obs/backend.rs, src/services/s3/backend.rs
refactor: Extrace normalize_root functions
=> refactor: Extrace normalize_root functions

docs/SUMMARY.md, docs/rfcs/0000-split-capabilities.md, docs/rfcs/0627-split-capabilities.md
=> RFC-0627: Split Capabilities

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.15

.github/workflows/service_test_http.yml, Cargo.toml, src/operator.rs, src/scheme.rs, src/services/http/backend.rs, src/services/http/fixtures/nginx.conf, src/services/mod.rs
refactor: Remove list support from http service 
Fix #636
=> refactor: Remove list support from http service 

Cargo.toml, oay/Cargo.lock, oli/Cargo.lock, src/layers/retry.rs
=> deps: Bump reqsign to v0.4

Cargo.toml, README.md, docs/SUMMARY.md, docs/services/ipfs.md, docs/services/ipmfs.md, examples/ipmfs.rs, src/services/ipfs/mod.rs, src/services/ipmfs/mod.rs
=> docs: Add docs for ipfs

src/accessor.rs, src/layers/immutable_index.rs, src/layers/mod.rs
=> feat: Add ImmutableIndexLayer

src/scheme.rs
Fixes #652
Adds derive `Hash` for `opendal::Scheme`.
=> feat: derive Hash for Scheme

Cargo.toml, README.md, docs/SUMMARY.md, docs/services/ftp.md, src/layers/immutable_index.rs, src/lib.rs, src/services/azblob/backend.rs, src/services/azblob/dir_stream.rs, src/services/ftp/backend.rs, src/services/ftp/err.rs, src/services/ftp/mod.rs, src/services/ftp/util.rs, src/services/gcs/backend.rs, src/services/gcs/dir_stream.rs, src/services/http/backend.rs, src/services/ipfs/backend.rs, src/services/ipfs/mod.rs, src/services/ipmfs/backend.rs, src/services/ipmfs/dir_stream.rs, src/services/obs/backend.rs, src/services/obs/dir_stream.rs
docs: Add docs for ftp services
=> docs: Add docs for ftp services

Cargo.toml, oay/Cargo.lock, oli/Cargo.lock
deps: Remove not used features
=> deps: Remove not used features

CHANGELOG.md, Cargo.toml, docs/upgrade.md, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.16

docs/SUMMARY.md, docs/rfcs/0000-path-in-accessor.md, docs/rfcs/0661-path-in-accessor.md
=> RFC: Path In Accessor

docs/SUMMARY.md, docs/internal/README.md, docs/internal/implement-service.md, src/accessor.rs, src/services/ftp/dir_stream.rs
=> docs: Add how to implement service docs

src/io_util/walk.rs, src/layers/immutable_index.rs, src/object.rs
=> fix: Immutable Index Layer could return duplicated pathes

src/http_util/client.rs
=> feat: Hide http client internal details from users

oay/Cargo.lock, oli/Cargo.lock, src/layers/immutable_index.rs
=> fix: Remove not needed type parameter for immutable_layer

Cargo.toml, benches/layers.rs, examples/tracing_layer.rs, src/layers/tracing.rs
feat: Add read benches for layer
=> fix: Don't trace buf field in poll_read

src/layers/metrics.rs
update documentation of metrics layer.
fixes: #678
=> docs: update metrics documentation

src/accessor.rs, src/dir.rs, src/services/fs/backend.rs, src/services/hdfs/backend.rs, tests/behavior/blocking_list.rs, tests/behavior/list.rs
Fix https://github.com/datafuselabs/opendal/issues/666
=> fix: List non-exist dir should return empty

src/services/fs/backend.rs
fix https://github.com/datafuselabs/opendal/issues/668
=> fix: Add path validation for fs backend

CHANGELOG.md, Cargo.toml, docs/upgrade.md, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.17

Cargo.toml, examples/s3.rs, oay/Cargo.lock, oli/Cargo.lock, src/services/s3/backend.rs, src/services/s3/mod.rs
This PR enables users to set the temporary credential of S3 service.
Check the AWS official [documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html) for detail.
=> feat: expose security token of s3

Cargo.toml, src/http_util/client.rs, src/services/ipmfs/backend.rs
=> fix: Handle write data in async way for IPMFS

.github/workflows/service_test_ipfs.yml
=> ci: Try make ipfs test stable

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.17.1

oay/Cargo.lock, src/layers/metrics.rs, src/layers/tracing.rs
=> fix: Tracing is too verbose

CHANGELOG.md, Cargo.toml, oay/Cargo.toml, oli/Cargo.toml
Bump the version of OpenDAL to v0.17.2
=> Bump to version 0.17.2

oay/Cargo.lock, oli/Cargo.lock, src/dir.rs, src/layers/mod.rs, src/layers/subdir.rs
Fix https://github.com/datafuselabs/opendal/issues/717
=> feat: Add SubdirLayer to allowing switch directory

src/dir.rs, src/layers/subdir.rs
fix: SubdirLayer should handle dir correctly
=> fix: SubdirLayer should handle dir correctly

src/layers/metrics.rs, src/layers/retry.rs
Fix https://github.com/datafuselabs/opendal/issues/719
=> feat(layers/retry): Add warning log while retry happened

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.17.3

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.17.4

src/http_util/client.rs
fix(http_util): Disable auto compress and enable http proxy
fix https://github.com/datafuselabs/opendal/issues/730
fix https://github.com/datafuselabs/opendal/issues/729
=> fix(http_util): Disable auto compress and enable http proxy

Cargo.toml, src/layers/metadata_cache.rs, src/layers/mod.rs, src/layers/retry.rs, src/object.rs, src/operator.rs, src/services/azblob/dir_stream.rs, src/services/fs/backend.rs, src/services/ftp/err.rs, src/services/http/backend.rs, src/services/ipmfs/backend.rs, src/services/ipmfs/dir_stream.rs, src/services/memory/backend.rs, src/services/obs/backend.rs, src/services/obs/dir_stream.rs, src/services/s3/backend.rs, src/services/s3/dir_stream.rs
=> feat: Add Metadata Cache Layer

docs/SUMMARY.md, docs/comparisons/README.md, docs/comparisons/object_store.md
docs: Add comparison with object_store
=> docs: Add comparison with object_store

docs/comparisons/object_store.md
docs: Add docs for list with prefix
=> docs: Add docs for list with prefix

oay/Cargo.lock, oli/Cargo.lock, src/ops/operation.rs
feat: Derive Hash, Eq, PartialEq for Operation
=> feat: Derive Hash, Eq, PartialEq for Operation

src/lib.rs
feat: Expose AccessorCapability to users
=> feat: Expose AccessorCapability to users

src/io_util/compress.rs
fix https://github.com/datafuselabs/opendal/issues/742
=> chore(compress): log with trace level instead of debug.

src/http_util/body.rs, src/http_util/mod.rs, src/io_util/mod.rs, src/lib.rs
feat: Expose opendal's http util to users
=> feat: Expose opendal's http util to users

src/http_util/body.rs, src/ops/op_presign.rs
feat: Implement convert from PresignedRequest
=> feat: Implement convert from PresignedRequest

src/dir.rs, src/object.rs
feat: Make ObjectMetadata setter public
Fix https://github.com/datafuselabs/opendal/issues/744
=> feat: Make ObjectMetadata setter public

README.md, src/object.rs, src/services/hdfs/dir_stream.rs
=> docs: rename dir entry to object entry

oay/Cargo.lock, oay/Cargo.toml, oay/src/commands/cli.rs, oli/Cargo.lock, oli/Cargo.toml, oli/src/commands/cli.rs, oli/src/commands/cp.rs
deps: Fix build after bump deps of oli and oay
=> deps: Fix build after bump deps of oli and oay

.github/workflows/service_test_http.yml, CHANGELOG.md, Cargo.toml, README.md, docs/upgrade.md, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.18.0

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.18.1

Cargo.toml, docs/examples/retry.md, src/layers/mod.rs, tests/behavior/utils.rs
feat: Enable retry layer by default
=> feat: Enable retry layer by default

src/object.rs
fix: Fix build error under release profile
=> fix: Fix build error under release profile

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oli/Cargo.lock
=> Bump to version 0.18.2

src/services/azblob/backend.rs, src/services/azblob/dir_stream.rs
refactor: Implement azblob dir stream based on ObjectPageStream
=> refactor: Implement azblob dir stream based on ObjectPageStream

src/services/kv/accessor.rs, src/services/kv/backend.rs, src/services/kv/key.rs, src/services/kv/mod.rs
feat(services/kv): Implement Scoped Key
=> feat(services/kv): Implement Scoped Key

docs/rfcs/0793-generic-kv-services.md, src/services/kv/accessor.rs, src/services/kv/backend.rs, src/services/kv/key.rs, src/services/kv/mod.rs
feat: Add scan in KeyValueAccessor
=> feat: Add scan in KeyValueAccessor

Cargo.toml, src/object/metadata.rs, src/object/mode.rs, src/path.rs, src/services/kv/accessor.rs, src/services/kv/backend.rs, src/services/kv/key.rs, src/services/kv/mod.rs
feat: Implement basic kv services support
=> feat: Implement basic kv services support

src/services/kv/accessor.rs, src/services/kv/backend.rs, src/services/kv/mod.rs, src/services/memory/backend.rs
refactor: Implement memory services by generic kv
=> refactor: Implement memory services by generic kv

Cargo.toml, README.md, docs/SUMMARY.md, docs/services/redis.md, src/adapters/kv/api.rs, src/adapters/kv/backend.rs, src/adapters/kv/key.rs, src/adapters/kv/mod.rs, src/lib.rs, src/services/redis/mod.rs
=> docs: Add docs for redis

.github/workflows/service_test_ipfs.yml, src/http_util/client.rs, src/services/ipfs/backend.rs
fix: Disable ipfs redirection
IPFS, it's hard to say I love you
Fix https://github.com/datafuselabs/opendal/issues/798
=> fix: Disable ipfs redirection

.github/workflows/service_test_oss.yml, src/services/oss/backend.rs, src/services/oss/dir_stream.rs
feat: Add integration tests for OSS
=> feat: Add integration tests for OSS

src/lib.rs, src/object/iterate.rs, src/object/mod.rs
refactor: Remove deprecated type aliases
=> refactor: Remove deprecated type aliases

tests/behavior/list.rs
Listing on directories containing a large number of files, force listing with more than one page.
fixes: #813
=> test: list rich dir

CHANGELOG.md, Cargo.toml, README.md, docs/services/oss.md, docs/upgrade.md, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml, src/layers/mod.rs, src/lib.rs, src/object/entry.rs, src/object/iterate.rs, src/object/stream.rs
=> Bump to version 0.19.0

src/layers/retry.rs
feat: Allow retry read and write
=> feat: Allow retry read and write

.github/workflows/service_test_ftp.yml, Cargo.toml, src/services/ftp/backend.rs, src/services/ftp/err.rs, src/services/ftp/util.rs
ci: Set swap for ftp tests
Fix https://github.com/datafuselabs/opendal/issues/830
=> feat(services/ftp): Add connection pool for FTP

src/layers/retry.rs
feat: Implement retry for write operation
Fix https://github.com/datafuselabs/opendal/issues/596
=> feat: Implement retry for write operation

Cargo.toml, oay/Cargo.lock, oli/Cargo.lock, src/services/azblob/backend.rs, src/services/gcs/backend.rs, src/services/obs/backend.rs, src/services/oss/backend.rs, src/services/s3/backend.rs
feat: Bump reqsign to latest version
=> feat: Bump reqsign to latest version

src/services/s3/backend.rs
feat(services/s3): Add role_arn and external_id for asssume_role
=> feat(services/s3): Add role_arn and external_id for assume_role

src/io_util/walk.rs, src/layers/layer.rs, src/layers/logging.rs, src/layers/metadata_cache.rs, src/layers/metrics.rs, src/layers/mod.rs, src/layers/retry.rs, src/layers/tracing.rs, src/layers/util.rs
Fix https://github.com/datafuselabs/opendal/issues/833
=> fix: Accessor in layers not set correctly

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.19.1

src/http_util/client.rs
feat(experiment): Allow user to config http connection pool
=> feat(experiment): Allow user to config http connection pool

src/layers/concurrent_limit.rs, src/layers/mod.rs
feat: Add concurrent limit layer
=> feat: Add concurrent limit layer

README.md, src/adapters/kv/api.rs, src/adapters/kv/backend.rs, src/layers/mod.rs, src/lib.rs, src/services/moka/backend.rs
docs: Add docs for moka service and concurrent limit layer
=> docs: Add docs for moka service and concurrent limit layer

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.19.2

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.19.3

src/io_util/into_stream.rs
feat: Improve into_stream by reduce zero byte fill
=> feat: Improve into_stream by reduce zero byte fill

src/http_util/client.rs
debug: Add log for sync http client
=> debug: Add log for sync http client

src/services/s3/backend.rs
- Introduces X_AMZ_BUCKET_REGION constant
- Replaces the hard code to X_AMZ_BUCKET_REGION constant
=> refactor: replace the hard code to X_AMZ_BUCKET_REGION constant

src/http_util/client.rs, src/layers/logging.rs, src/layers/retry.rs
feat: Add debug log for finishing read
=> feat: Add debug log for finishing read

Cargo.toml, oay/Cargo.lock, oli/Cargo.lock, src/http_util/client.rs
feat: Try to use trust-dns-resolver
=> feat: Try to use trust-dns-resolver

src/layers/logging.rs
feat: Add log for dropping reader and streamer
=> feat: Add log for dropping reader and streamer

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml, src/layers/logging.rs
=> Bump to version 0.19.4

src/object/object.rs
Write with was discribed in RFC0661 but was not realized
This commit implemented this feature in:
1. async write_with
2. blocking_write_with
and also refactored write() and blocking_write()
=> feat: implement write_with

src/accessor.rs, src/layers/concurrent_limit.rs, src/layers/content_cache.rs, src/layers/immutable_index.rs, src/layers/layer.rs, src/layers/logging.rs, src/layers/metadata_cache.rs, src/layers/metrics.rs, src/layers/retry.rs, src/layers/subdir.rs, src/layers/tracing.rs
Fix https://github.com/datafuselabs/opendal/issues/883
=> fix: Allow forward layers' acesser operations to inner

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.19.6

.github/actions/check/action.yml, src/http_util/header.rs, src/http_util/mod.rs, src/lib.rs, src/object/metadata.rs, src/services/azblob/backend.rs, src/services/azblob/dir_stream.rs, src/services/gcs/backend.rs, src/services/gcs/dir_stream.rs, src/services/http/backend.rs, src/services/ipfs/backend.rs, src/services/obs/backend.rs, src/services/oss/backend.rs, src/services/s3/backend.rs, src/services/s3/dir_stream.rs
feat: Implement content type support for stat
=> feat: Implement content type support for stat

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oli/Cargo.lock
=> Bump to version 0.19.7

oay/Cargo.lock, oli/Cargo.lock
=> deps(oay,oli): Update deps

rustfmt.toml, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/ftp/backend.rs, src/services/gcs/backend.rs, src/services/hdfs/backend.rs, src/services/http/backend.rs, src/services/ipfs/backend.rs, src/services/ipmfs/builder.rs, src/services/moka/backend.rs, src/services/obs/backend.rs, src/services/oss/backend.rs, src/services/s3/backend.rs
refactor: Reduce backend builder log level to debug
=> refactor: Reduce backend builder log level to debug

src/adapters/kv/backend.rs, src/services/fs/backend.rs, src/services/s3/backend.rs
ci: Make stable rust clippy happy
=> ci: Make stable rust clippy happy

README.md, docs/SUMMARY.md, docs/services/rocksdb.md, src/lib.rs
Signed-off-by: Wenxuan Zhang <wenxuangm@gmail.com>
Add docs for rocksdb service
=> docs: add docs for rocksdb service

.github/workflows/service_test_azblob.yml, .github/workflows/service_test_fs.yml, .github/workflows/service_test_ftp.yml, .github/workflows/service_test_gcs.yml, .github/workflows/service_test_hdfs.yml, .github/workflows/service_test_http.yml, .github/workflows/service_test_ipfs.yml, .github/workflows/service_test_ipmfs.yml, .github/workflows/service_test_memory.yml, .github/workflows/service_test_moka.yml, .github/workflows/service_test_obs.yml, .github/workflows/service_test_redis.yml, .github/workflows/service_test_rocksdb.yml, .github/workflows/service_test_s3.yml, Cargo.toml
refactor: Remove deprecated features
=> refactor: Remove deprecated features

CHANGELOG.md, Cargo.toml
=> Bump to version 0.19.8

docs/SUMMARY.md, docs/rfcs/0000-object-reader.md, docs/rfcs/0926-object-reader.md
=> RFC-0926: Object Reader

src/lib.rs, src/object/mod.rs, src/object/reader.rs
=> feat: Implement Object Reader

src/services/s3/backend.rs
feat(services/s3): Return Object Meta for Read operation
=> feat(services/s3): Return Object Meta for Read operation

oay/Cargo.lock, oay/src/services/http/mod.rs, src/ops/bytes_content_range.rs, src/ops/bytes_range.rs, src/ops/mod.rs
feat: Implement Bytes Content Range
=> feat: Implement Bytes Content Range

src/http_util/header.rs, src/http_util/mod.rs, src/lib.rs, src/object/metadata.rs, src/ops/bytes_content_range.rs, src/services/s3/backend.rs
feat: Add Content Range support in ObjectMetadata
Fix https://github.com/datafuselabs/opendal/issues/930
=> feat: Add Content Range support in ObjectMetadata

src/layers/content_cache.rs
feat(layers/content_cache): Implement WholeCacheReader
Make space for implementing different policy for cache.
=> feat(layers/content_cache): Implement WholeCacheReader

src/io_util/compress.rs
databend needs to Serialize file Split for distribution.  
https://github.com/datafuselabs/databend/issues/8749
a Split has a CompressAlgorithm
=> feat: CompressAlgorithm derive serde.

src/ops/bytes_range.rs
fix(ops): Fix suffix range behavior of bytes range
Fix https://github.com/datafuselabs/opendal/issues/941
=> fix(ops): Fix suffix range behavior of bytes range

src/lib.rs
Signed-off-by: messense <messense@icloud.com>
Per https://github.com/datafuselabs/opendal/pull/949#issuecomment-1316272997
=> docs: add docs for tls dependencies features

src/io_util/seekable_reader.rs, src/ops/bytes_range.rs, src/ops/op_read.rs
=> refactor: Polish bytes range

src/accessor.rs, src/layers/content_cache.rs, src/layers/mod.rs, src/object/object.rs, src/ops/bytes_content_range.rs, src/ops/bytes_range.rs
feat(layers): Implement fixed content cache
=> feat(layers): Implement fixed content cache

src/layers/content_cache.rs, src/operator.rs
fix: Fix cache path not used correctly
=> fix: Fix cache path not used correctly

src/services/redis/backend.rs
feat: Enable default_ttl support for redis
fix https://github.com/datafuselabs/opendal/issues/845
=> feat: Enable default_ttl support for redis

CHANGELOG.md, Cargo.toml, docs/upgrade.md, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.20.0

src/adapters/kv/api.rs, src/adapters/kv/backend.rs, src/layers/content_cache.rs, src/services/memory/backend.rs, src/services/moka/backend.rs, src/services/redis/backend.rs, src/services/rocksdb/backend.rs
feat: Implement blocking operations for cache services
=> feat: Implement blocking operations for cache services

CHANGELOG.md, Cargo.toml
=> Bump to version 0.20.1

README.md
docs: Add greptimedb and mars into projects
Fix https://github.com/datafuselabs/opendal/issues/964
=> docs: Add greptimedb and mars into projects

docs/SUMMARY.md, docs/rfcs/0000-refactor-error.md, docs/rfcs/0977-refactor-error.md
=> RFC-0977: Refactor Error

src/layers/retry.rs
fix https://github.com/datafuselabs/opendal/issues/978
=> fix: RetryAccessor is too verbose

src/accessor.rs, src/adapters/kv/backend.rs, src/layers/concurrent_limit.rs, src/layers/content_cache.rs, src/layers/logging.rs, src/layers/metadata_cache.rs, src/layers/metrics.rs, src/layers/retry.rs, src/layers/subdir.rs, src/layers/tracing.rs, src/object/object.rs, src/ops/mod.rs, src/ops/op_create.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/ftp/backend.rs, src/services/gcs/backend.rs, src/services/hdfs/backend.rs, src/services/ipmfs/backend.rs, src/services/obs/backend.rs, src/services/oss/backend.rs, src/services/s3/backend.rs, src/wrappers/error_context.rs
refactor: Return ReplyCreate for create operation
=> refactor: Return ReplyCreate for create operation

src/accessor.rs, src/adapters/kv/backend.rs, src/io_util/seekable_reader.rs, src/layers/concurrent_limit.rs, src/layers/content_cache.rs, src/layers/logging.rs, src/layers/metadata_cache.rs, src/layers/metrics.rs, src/layers/retry.rs, src/layers/subdir.rs, src/layers/tracing.rs, src/object/object.rs, src/object/reader.rs, src/ops/mod.rs, src/ops/op_create.rs, src/ops/op_read.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/ftp/backend.rs, src/services/gcs/backend.rs, src/services/hdfs/backend.rs, src/services/http/backend.rs, src/services/ipfs/backend.rs, src/services/ipmfs/backend.rs, src/services/obs/backend.rs, src/services/oss/backend.rs, src/services/s3/backend.rs, src/wrappers/error_context.rs
refactor: Add ReplyRead for read operation
=> refactor: Add ReplyRead for read operation

src/accessor.rs, src/adapters/kv/backend.rs, src/io_util/seekable_reader.rs, src/layers/concurrent_limit.rs, src/layers/content_cache.rs, src/layers/logging.rs, src/layers/metadata_cache.rs, src/layers/metrics.rs, src/layers/retry.rs, src/layers/subdir.rs, src/layers/tracing.rs, src/object/entry.rs, src/object/object.rs, src/ops/mod.rs, src/ops/op_stat.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/ftp/backend.rs, src/services/gcs/backend.rs, src/services/hdfs/backend.rs, src/services/http/backend.rs, src/services/ipfs/backend.rs, src/services/ipmfs/backend.rs, src/services/obs/backend.rs, src/services/oss/backend.rs, src/services/s3/backend.rs, src/wrappers/error_context.rs
refactor: Add RpStat for stat operation
=> refactor: Add RpStat for stat operation

src/accessor.rs, src/adapters/kv/backend.rs, src/layers/concurrent_limit.rs, src/layers/content_cache.rs, src/layers/layer.rs, src/layers/logging.rs, src/layers/metadata_cache.rs, src/layers/metrics.rs, src/layers/retry.rs, src/layers/subdir.rs, src/layers/tracing.rs, src/object/object.rs, src/ops/mod.rs, src/ops/op_delete.rs, src/services/azblob/backend.rs, src/services/fs/backend.rs, src/services/ftp/backend.rs, src/services/gcs/backend.rs, src/services/hdfs/backend.rs, src/services/ipmfs/backend.rs, src/services/obs/backend.rs, src/services/oss/backend.rs, src/services/s3/backend.rs, src/wrappers/error_context.rs
refactor: Add RpDelete for delete operations
=> refactor: Add RpDelete for delete operations

src/accessor.rs, src/layers/concurrent_limit.rs, src/layers/logging.rs, src/layers/metrics.rs, src/layers/subdir.rs, src/layers/tracing.rs, src/object/multipart.rs, src/object/object.rs, src/ops/mod.rs, src/ops/op_presign.rs, src/services/s3/backend.rs, src/wrappers/error_context.rs
refactor: Add RpPresign for presign operation
=> refactor: Add RpPresign for presign operation

src/accessor.rs, src/layers/concurrent_limit.rs, src/layers/logging.rs, src/layers/metadata_cache.rs, src/layers/metrics.rs, src/layers/retry.rs, src/layers/subdir.rs, src/layers/tracing.rs, src/object/multipart.rs, src/object/object.rs, src/ops/mod.rs, src/ops/op_multipart.rs, src/services/s3/backend.rs, src/wrappers/error_context.rs
refactor: Add reply for all multipart operations
=> refactor: Add reply for all multipart operations

src/accessor.rs, src/adapters/kv/backend.rs, src/layers/concurrent_limit.rs, src/layers/logging.rs, src/layers/metadata_cache.rs, src/layers/metrics.rs, src/layers/retry.rs, src/layers/subdir.rs, src/layers/tracing.rs, src/object/entry.rs, src/object/object.rs, src/services/fs/backend.rs, src/wrappers/error_context.rs
refactor: Add Reply for all blocking operations
=> refactor: Add Reply for all blocking operations

oay/src/services/http/mod.rs, src/lib.rs, src/operator.rs, src/raw/accessor.rs
feat: Add OperatorMetadata to avoid expose AccessorMetadata
=> feat: Add OperatorMetadata to avoid expose AccessorMetadata

src/layers/content_cache.rs, src/layers/metadata_cache.rs, src/operator.rs, src/ops.rs, src/raw/object_page.rs, src/raw/rps.rs
refactor: Accept Operator intead of Arc<dyn Accessor>
=> refactor: Accept Operator intead of Arc<dyn Accessor>

src/error.rs
feat: Improve display for error
=> feat: Improve display for error

CHANGELOG.md, Cargo.toml, docs/upgrade.md, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.21

Cargo.toml
deps: Remove not used thiserror and num-trait
=> deps: Remove not used thiserror and num-trait

src/lib.rs, src/object/list.rs
feat: Export ObjectLister as public type
=> feat: Export ObjectLister as public type

CHANGELOG.md, Cargo.toml
=> Bump to version 0.21.1

README.md, src/lib.rs, src/services/azdfs/mod.rs
docs: Fix docs for azdfs service
=> docs: Fix docs for azdfs service

.github/workflows/ci.yml, Cargo.toml, src/object/object.rs
feat: Set MSRV of opendal to 1.60
Fix https://github.com/datafuselabs/opendal/issues/1011
=> feat: Set MSRV of opendal to 1.60

CHANGELOG.md, Cargo.toml
=> Bump to version 0.21.2

book.toml, docs/comparisons/object_store.md, docs/concepts.md, docs/examples/presign.md, docs/examples/walk.md, docs/internal/implement-service.md, docs/rfcs/0977-refactor-error.md
docs: Fix broken links in docs
=> docs: Fix broken links in docs

benches/layers.rs, docs/examples/logging.md, src/layers/immutable_index.rs, src/layers/logging.rs, src/lib.rs, src/raw/io_util/walk.rs, tests/behavior/utils.rs
feat: Allow configure LoggingLayer's level
=> feat: Allow configure LoggingLayer's level

Cargo.toml, src/services/oss/backend.rs, src/services/s3/backend.rs, src/services/s3/dir_stream.rs
Fix https://github.com/datafuselabs/opendal/issues/851
=> feat: Implement presign for oss

src/services/fs/backend.rs
Fix https://github.com/datafuselabs/opendal/issues/922
Thanks @WenyXu
=> fix(services/fs): Make sure writing file is truncated

src/layers/cache/accessor.rs, src/layers/cache/mod.rs, src/layers/cache/policy.rs, src/ops.rs
refactor(layer/cache): Allow users implement cache by themselves
=> refactor(layer/cache): Allow users implement cache by themselves

CHANGELOG.md, Cargo.toml, oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> Bump to version 0.22

Cargo.toml, src/services/s3/backend.rs
fix(services/s3): Allow disable loading from imds_v2 and assume_role
=> fix(services/s3): Allow disable loading from imds_v2 and assume_role

CHANGELOG.md, Cargo.toml
=> Bump to version 0.22.1

CHANGELOG.md, Cargo.toml
=> Bump to version 0.22.2

src/error.rs, src/layers/metrics.rs, src/raw/operation.rs
feat(layers/metrics): Merge error and failure counters together
Fix https://github.com/datafuselabs/opendal/issues/1054
Fix https://github.com/datafuselabs/opendal/issues/1055
=> feat(layers/metrics): Merge error and failure counters together

Cargo.toml
=> feat: Set MSRV to 1.60

Cargo.toml, src/operator.rs
feat: Add unwind safe flag for operator
=> feat: Add unwind safe flag for operator

src/services/azblob/backend.rs
feat(azblob): Add build from connection string support
Fix https://github.com/datafuselabs/opendal/issues/1063
=> feat(azblob): Add build from connection string support

Cargo.toml, src/services/gcs/backend.rs
feat(services/gcs): Fully implement default credential support
Fix https://github.com/datafuselabs/opendal/issues/1062
=> feat(services/gcs): Fully implement default credential support

CHANGELOG.md, Cargo.toml
=> Bump to version 0.22.4

src/scheme.rs, src/services/gcs/backend.rs
feat: Add service account support for gcs
=> feat: Add service account support for gcs

CHANGELOG.md, Cargo.toml
=> Bump to version 0.22.5

src/raw/io.rs
=> feat(io): make BlockingBytesRead Send + Sync

docs/SUMMARY.md, docs/rfcs/0000-object-handler.md, docs/rfcs/1085-object-handler.md
=> RFC-1085: Object Handler

Cargo.toml, README.md, src/services/gcs/backend.rs, src/services/s3/backend.rs
feat(services/s3,gcs): Allow accepting signer directly
=> feat(services/s3,gcs): Allow accepting signer directly

CHANGELOG.md, Cargo.toml
=> Bump to version 0.22.6

src/layers/logging.rs, src/lib.rs, src/object/handler.rs, src/object/mod.rs, src/object/object.rs, src/operator.rs, src/ops.rs, src/raw/accessor.rs, src/raw/io.rs, src/raw/mod.rs, src/raw/operation.rs, src/raw/rps.rs, src/raw/wrappers/error_context.rs, src/services/fs/backend.rs, tests/behavior/blocking_open.rs, tests/behavior/main.rs, tests/behavior/open.rs
feat: Implement object handler so that we can do seek on file
=> feat: Implement object handler so that we can do seek on file

src/services/hdfs/backend.rs, src/services/hdfs/dir_stream.rs
feat: Implement blocking for hdfs
=> feat: Implement blocking for hdfs

Cargo.toml, src/services/hdfs/backend.rs
feat(services/hdfs): Implement open and blocking open
=> feat(services/hdfs): Implement open and blocking open

README.md
docs: Add mozilla/sccache into projects
=> docs: Add mozilla/sccache into projects

CHANGELOG.md, Cargo.toml
=> Bump to version 0.23

oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
=> ci: Fix build for oay and oli

Cargo.toml, src/services/ftp/backend.rs
fix: Fix rustls support for suppaftp
=> fix: Fix rustls support for suppaftp

.github/workflows/ci.yml, .github/workflows/service_test_azblob.yml, .github/workflows/service_test_azdfs.yml, .github/workflows/service_test_fs.yml, .github/workflows/service_test_ftp.yml, .github/workflows/service_test_gcs.yml, .github/workflows/service_test_hdfs.yml, .github/workflows/service_test_http.yml, .github/workflows/service_test_ipfs.yml, .github/workflows/service_test_ipmfs.yml, .github/workflows/service_test_memory.yml, .github/workflows/service_test_moka.yml, .github/workflows/service_test_obs.yml, .github/workflows/service_test_oss.yml, .github/workflows/service_test_redis.yml, .github/workflows/service_test_rocksdb.yml, .github/workflows/service_test_s3.yml, .licenserc.yaml
=> ci: Enable rust cache for CI

oay/Cargo.lock, oay/Cargo.toml, oli/Cargo.lock, oli/Cargo.toml
deps(oay,oli): Update dependences of oay and oli
=> deps(oay,oli): Update dependences of oay and oli

src/object/object.rs
refactor: Only add content length hint if we already know length
=> refactor: Only add content length hint if we already know length

src/raw/mod.rs, src/raw/version.rs, src/services/ghac/backend.rs
fix(services/ghac): Fix pkg version not used correctly
=> fix(services/ghac): Fix pkg version not used correctly

README.md, src/lib.rs, src/raw/accessor.rs, src/raw/io.rs, src/services/azblob/backend.rs, src/services/ghac/mod.rs
docs: Add docs for ghac service
=> docs: Add docs for ghac service

src/layers/logging.rs, src/lib.rs, src/operator.rs, src/ops.rs, src/raw/accessor.rs, src/raw/rps.rs, src/raw/wrappers/error_context.rs, src/services/fs/backend.rs, src/services/hdfs/backend.rs
refactor: Remove open related APIs
=> refactor: Remove open related APIs

src/object/reader.rs, src/raw/accessor.rs, src/raw/io_util/into_seekable_reader/mod.rs, src/raw/io_util/into_seekable_reader/offset.rs, src/raw/operation.rs
feat: Implement offset seekable reader for zero cost read
=> feat: Implement offset seekable reader for zero cost read

src/raw/http_util/body.rs, src/raw/io/output/cursor.rs, src/raw/io/output/into_reader/as_streamable.rs, src/raw/io/output/into_reader/by_offset.rs, src/raw/io/output/into_reader/by_range.rs, tests/behavior/utils.rs, tests/behavior/write.rs
feat: Implement fuzz test on ObjectReader
=> feat: Implement fuzz test on ObjectReader

CHANGELOG.md, Cargo.toml
=> Bump to version 0.24.1

Cargo.toml
refactor: Use `dep:` to make our features more clean
=> refactor: Use `dep:` to make our features more clean

src/object/object.rs
fix: futures read_to_end will lead to performance regression
=> fix: futures read_to_end will lead to performance regression

CHANGELOG.md, Cargo.toml
=> Bump to version 0.24.2

CHANGELOG.md, Cargo.toml
=> Bump to version 0.24.3

Cargo.toml, src/services/memcached/backend.rs
fix: Memcached can't work on windows
=> fix: Memcached can't work on windows

src/raw/io/output/into_reader/by_offset.rs, src/raw/io/output/into_reader/by_range.rs
feat: Reset state while returning error so that we can retry IO
=> feat: Reset state while returning error so that we can retry IO

CHANGELOG.md, Cargo.toml
=> Bump to version 0.24.4

CHANGELOG.md, Cargo.toml
=> Bump to version 0.24.5

Cargo.toml, src/services/hdfs/backend.rs
feat(services/hdfs): Evaluating the new async implementation
=> feat(services/hdfs): Evaluating the new async implementation

benches/ops/utils.rs, src/error.rs, src/object/object.rs, src/raw/io/output/into_reader/by_offset.rs, src/raw/io/output/into_reader/by_range.rs, src/services/fs/backend.rs, src/services/ghac/error.rs, tests/behavior/blocking_write.rs, tests/behavior/read_only.rs, tests/behavior/utils.rs, tests/behavior/write.rs
feat(services/ghac): Handling too many requests error
=> feat(services/ghac): Handling too many requests error

CHANGELOG.md, Cargo.toml
=> Bump to version 0.24.6

Cargo.toml, oay/Cargo.lock, oli/Cargo.lock, src/raw/http_util/client.rs, src/services/s3/backend.rs, src/services/s3/mod.rs
refactor: Avoid calling detect region if we know the region
=> refactor: Avoid calling detect region if we know the region

.github/workflows/service_test_azblob.yml, .github/workflows/service_test_azdfs.yml, .github/workflows/service_test_fs.yml, .github/workflows/service_test_ftp.yml, .github/workflows/service_test_gcs.yml, .github/workflows/service_test_ghac.yml, .github/workflows/service_test_hdfs.yml, .github/workflows/service_test_http.yml, .github/workflows/service_test_ipfs.yml, .github/workflows/service_test_ipmfs.yml, .github/workflows/service_test_memcached.yml, .github/workflows/service_test_memory.yml, .github/workflows/service_test_moka.yml, .github/workflows/service_test_obs.yml, .github/workflows/service_test_oss.yml, .github/workflows/service_test_redis.yml, .github/workflows/service_test_rocksdb.yml, .github/workflows/service_test_s3.yml, Cargo.toml, src/object/reader.rs, src/raw/http_util/client.rs, src/raw/http_util/dns.rs, src/raw/http_util/mod.rs, src/services/s3/backend.rs
feat: Add dns cache for std dns resolver
=> feat: Add dns cache for std dns resolver

src/layers/concurrent_limit.rs, src/layers/logging.rs, src/layers/metrics.rs, src/layers/tracing.rs, src/object/blocking_reader.rs, src/object/object.rs, src/raw/adapters/kv/backend.rs, src/raw/io/output/blocking_read.rs, src/raw/io/output/cursor.rs, src/raw/io/output/into_blocking_reader/as_iterable.rs, src/raw/io/output/into_blocking_reader/from_fd.rs, src/raw/io/output/into_blocking_reader/mod.rs, src/raw/io/output/mod.rs, src/raw/io/output/read.rs, src/services/fs/backend.rs, src/services/hdfs/backend.rs, tests/behavior/blocking_write.rs
feat: Implement BlockingObjectReader
=> feat: Implement BlockingObjectReader

CHANGELOG.md, Cargo.toml, docs/upgrade.md, oay/Cargo.toml, oli/Cargo.toml
=> Bump to version 0.25

.github/workflows/bench.yaml, benches/ops/read.rs, benches/ops/write.rs
=> ci: Setup benchmark workflow

bindings/nodejs/.gitignore, bindings/nodejs/.npmignore, bindings/nodejs/Cargo.toml, bindings/nodejs/README.md, bindings/nodejs/build.rs, bindings/nodejs/index.js, bindings/nodejs/npm/darwin-x64/README.md, bindings/nodejs/npm/darwin-x64/package.json, bindings/nodejs/npm/linux-x64-gnu/README.md, bindings/nodejs/npm/linux-x64-gnu/package.json, bindings/nodejs/package.json, bindings/nodejs/pnpm-lock.yaml, bindings/nodejs/src/lib.rs
feat: Let's try play with Node.js
=> feat: Let's try play with Node.js

bindings/nodejs/index.js
chore: Add license header for nodejs
=> chore: Add license header for nodejs

Cargo.toml, src/operator.rs
refactor: Remove not used unwind safe feature
=> refactor: Remove not used unwind safe feature

README.md, src/raw/http_util/bytes_content_range.rs, src/raw/http_util/bytes_range.rs, src/services/oss/backend.rs
=> docs: Polish README

.cargo/audit.toml, Cargo.toml, bindings/nodejs/Cargo.toml, bindings/python/Cargo.toml, bindings/python/pyproject.toml
chore: Remove not needed files
=> chore: Remove not needed files

.github/actions/check/action.yml
ci: Remove not needed audit checks
=> ci: Remove not needed audit checks

CHANGELOG.md, Cargo.toml
=> Bump to version 0.25.1

src/services/http/mod.rs
Signed-off-by: Chojan Shang <psiace@outlook.com>
Close: #1238
=> docs(http): remove out-dated comments

binaries/oay/Cargo.lock, binaries/oli/Cargo.lock
chore: Make sure oli/oay's cargo.lock is updated
=> chore: Make sure oli/oay's cargo.lock is updated

README.md, bindings/object_store/README.md, bindings/python/README.md
=> docs: Add bindings in README

bindings/object_store/Cargo.toml
chore: Fix binding of object_store
=> chore: Fix binding of object_store

README.md, src/layers/metrics.rs, src/services/ftp/mod.rs, src/services/http/mod.rs, src/services/webdav/mod.rs
Fix https://github.com/datafuselabs/opendal/issues/1109
=> docs: Add docs for webdav and http services

src/lib.rs
=> docs: Add webdav in lib docs

src/layers/logging.rs, src/layers/metrics.rs, src/layers/tracing.rs, src/object/blocking_reader.rs, src/raw/io/output/blocking_read.rs, src/raw/io/output/into_blocking_reader/as_iterable.rs, src/raw/io/output/into_blocking_reader/from_fd.rs
feat: Make sure short functions have been inlined
=> feat: Make sure short functions have been inlined

CHANGELOG.md, Cargo.toml, binaries/oay/Cargo.lock, binaries/oli/Cargo.lock
=> Bump to version 0.25.2

Cargo.toml
just remove the duplicate dependency in dev-dependencies which have already been in dependencies
=> refactor: remove the duplicated dependency in dev-dependencies

.gitignore, Cargo.toml, benches/README.md, benches/io/blocking_seek.rs, benches/io/main.rs
feat: Add benchmarks for blocking_seek operations
=> feat: Add benchmarks for blocking_seek operations

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Signed-off-by: Chojan Shang <psiace@outlook.com>
- add a user named builder to avoid lock git
- add starship
- remove mounts
=> chore: refine devcontainer

src/operator.rs, src/raw/accessor.rs
feat: Allow dynamic dispatch layer
=> feat: Allow dynamic dispatch layer

CHANGELOG.md, Cargo.toml, binaries/oay/Cargo.lock, binaries/oay/Cargo.toml, binaries/oli/Cargo.lock, binaries/oli/Cargo.toml, bindings/nodejs/Cargo.toml, bindings/object_store/Cargo.toml, bindings/python/Cargo.toml
=> Bump to version 0.26.0

docs/upgrade.md
=> docs: Add v0.26 upgrade guide

docs/services/README.md, src/operator.rs
docs: Add feature sets in services
=> docs: Add feature sets in services

.github/workflows/docs.yaml
docs: Fix index page not redirected
=> docs: Fix index page not redirected

CHANGELOG.md, Cargo.toml, binaries/oay/Cargo.lock, binaries/oli/Cargo.lock, src/docs/mod.rs
=> Bump to version 0.26.1

Cargo.toml, src/layers/chaos.rs, src/layers/mod.rs, src/lib.rs
feat: Add ChaosLayer to inject errors into underlying services
=> feat: Add ChaosLayer to inject errors into underlying services

src/services/fs/backend.rs
refactor(services/fs): Remove not needed generic
=> refactor(services/fs): Remove not needed generic

src/raw/io/output/into_reader/by_range.rs
fix: Fix retry happend in seek's read ahead logic
=> fix: Fix retry happened in seek's read ahead logic

.devcontainer/Dockerfile
Signed-off-by: Chojan Shang <psiace@ritelabs.net>
try to fix dockerfile
Close: #1295
=> ci: Fix dev container Dockerfile

src/scheme.rs
fix: Rocksdb's scheme not output correctly
=> fix: Rocksdb's scheme not output correctly

Cargo.toml, binaries/oay/Cargo.lock, binaries/oli/Cargo.lock, src/layers/retry.rs, src/operator.rs, tests/behavior/utils.rs
refactor: Hide backon from our public API
=> refactor: Hide backon from our public API

src/layers/retry.rs
Implemented `RetryPager` as a retriable `ObjectPager` implementation coming along with `RetryLayer`
solves: #810
=> feat: Add Retryable Pager Support

src/ops.rs, src/services/azblob/backend.rs, src/services/azblob/dir_stream.rs, src/services/azdfs/backend.rs, src/services/azdfs/dir_stream.rs, src/services/fs/backend.rs, src/services/fs/dir_stream.rs, src/services/ftp/backend.rs, src/services/ftp/dir_stream.rs, src/services/gcs/backend.rs, src/services/gcs/dir_stream.rs, src/services/hdfs/backend.rs, src/services/hdfs/dir_stream.rs, src/services/obs/backend.rs, src/services/obs/dir_stream.rs, src/services/oss/backend.rs, src/services/oss/dir_stream.rs, src/services/s3/backend.rs, src/services/s3/dir_stream.rs, tests/behavior/list.rs
feat: Add object page size support
Fix https://github.com/datafuselabs/opendal/issues/1071
=> feat: Add object page size support

Cargo.toml, binaries/oay/Cargo.lock, binaries/oli/Cargo.lock
=> deps: remove unused deps

README.md
docs: Add risingwave in projects
=> docs: Add risingwave in projects

binaries/oli/src/utils/location.rs
Previously `oli cp s3://bucket/key /path`  will return `Error: type for profile s3 is not specified`
=> feat(oli): support s3 uri without profile

binaries/oli/src/utils/location.rs
=> chore: Make clippy happy

src/operator.rs, src/raw/adapters/kv/api.rs, src/raw/adapters/kv/backend.rs, src/raw/io/output/to_hierarchy_pager.rs, src/services/memory/backend.rs, tests/behavior/blocking_list.rs, tests/behavior/list.rs
feat: Add scan support for kv adapter
=> feat: Add scan support for kv adapter

src/services/azblob/backend.rs, src/services/azdfs/backend.rs, src/services/fs/backend.rs, src/services/ftp/backend.rs, src/services/gcs/backend.rs, src/services/ghac/backend.rs, src/services/hdfs/backend.rs, src/services/http/backend.rs, src/services/ipfs/backend.rs, src/services/ipmfs/builder.rs, src/services/memcached/backend.rs, src/services/memory/backend.rs, src/services/moka/backend.rs, src/services/obs/backend.rs, src/services/oss/backend.rs, src/services/redis/backend.rs, src/services/rocksdb/backend.rs, src/services/s3/backend.rs, src/services/sled/backend.rs, src/services/webdav/backend.rs, src/services/webhdfs/backend.rs
feat: Add scan support for sled
=> feat: Add scan support for sled

CHANGELOG.md, Cargo.toml, binaries/oay/Cargo.lock, binaries/oli/Cargo.lock
=> Bump to version 0.27.1

src/operator.rs, src/ops.rs, src/raw/accessor.rs, src/raw/layer.rs, src/raw/operation.rs, src/raw/rps.rs
feat: Add batch API for Accessor
=> feat: Add batch API for Accessor

README.md
Fix https://github.com/datafuselabs/opendal/issues/1341
=> docs: Fix broken links

src/services/webdav/backend.rs
webdav support visit by bearer token #1348
=> feat: webdav service support bearer token

src/lib.rs, src/operator.rs, src/ops.rs, src/raw/rps.rs, src/services/s3/backend.rs, src/services/webdav/backend.rs, tests/behavior/write.rs
feat: Add batch delete support
=> feat: Add batch delete support

src/raw/http_util/client.rs
1. no auto redirection
2. examples for disable it
=> docs: clarify about opendal user defined client

src/services/webhdfs/backend.rs
Should fix documentation inconsistency in WebHDFS service.
Fix https://github.com/datafuselabs/opendal/issues/1353
=> fix(webhdfs): should prepend http:// scheme

.github/workflows/service_test_azblob.yml, .github/workflows/service_test_azdfs.yml, .github/workflows/service_test_fs.yml, .github/workflows/service_test_ftp.yml, .github/workflows/service_test_gcs.yml, .github/workflows/service_test_ghac.yml, .github/workflows/service_test_hdfs.yml, .github/workflows/service_test_http.yml, .github/workflows/service_test_ipfs.yml, .github/workflows/service_test_ipmfs.yml, .github/workflows/service_test_memcached.yml, .github/workflows/service_test_memory.yml, .github/workflows/service_test_moka.yml, .github/workflows/service_test_obs.yml, .github/workflows/service_test_oss.yml, .github/workflows/service_test_redis.yml, .github/workflows/service_test_rocksdb.yml, .github/workflows/service_test_s3.yml, .github/workflows/service_test_sled.yml, .github/workflows/service_test_webdav.yml, .github/workflows/service_test_webhdfs.yml
ci: Only run service test on changing
=> ci: Only run service test on changing

src/raw/http_util/client.rs, src/raw/http_util/header.rs, src/raw/http_util/mod.rs, src/services/http/backend.rs, src/services/webdav/backend.rs
refactor: Polish http authorization related logic
=> refactor: Polish http authorization related logic

src/services/webdav/backend.rs, src/services/webdav/dir_stream.rs, src/services/webdav/list_response.rs
refactor: Cleanup some not needed error context
=> refactor: Cleanup some not needed error context

src/layers/concurrent_limit.rs, src/layers/error_context.rs, src/layers/logging.rs, src/layers/metrics.rs, src/layers/retry.rs, src/layers/tracing.rs, src/ops.rs, src/raw/rps.rs
feat: Integrate batch with existing ecosystem better
Fix https://github.com/datafuselabs/opendal/issues/1362
=> feat: Integrate batch with existing ecosystem better

.config/nextest.toml, Cargo.toml, binaries/oay/Cargo.lock, binaries/oli/Cargo.lock, src/raw/http_util/header.rs, src/raw/http_util/mod.rs, src/services/oss/backend.rs, src/services/s3/backend.rs, src/services/webdav/backend.rs, src/services/webdav/dir_stream.rs, src/services/webdav/list_response.rs
feat: Add batch delete support for oss
Fix https://github.com/datafuselabs/opendal/issues/1381
=> feat: Add batch delete support for oss

README.md, src/docs/rfcs/1391_object_metadataer.md, src/docs/rfcs/1398_query_based_metadata.md, src/object/metadata.rs, src/object/object.rs, src/operator.rs, src/services/oss/backend.rs, src/services/s3/backend.rs
refactor: Trigger panic if users try to visit not fetched metadata
=> refactor: Trigger panic if users try to visit not fetched metadata

src/docs/internals/accessor.rs, src/docs/internals/layer.rs
docs: Add more guide for Accessor
=> docs: Add more guide for Accessor

src/docs/internals/accessor.rs
=> chore: typo fix

src/docs/rfcs/0000_object_writer.md, src/docs/rfcs/1420_object_writer.md, src/docs/rfcs/mod.rs
Add RFC: Object Writer
preview: https://opendal-git-rfc-object-writer.vercel.app/opendal/docs/rfcs/rfc_1420_object_writer/index.html
=> RFC-1420: Object Writer

.github/workflows/ci.yml, .github/workflows/typos.yml
- cargo install typos-cli --locked
- typos
=> ci: add typos check

examples/object.rs, src/docs/concepts.rs, src/error.rs, src/raw/http_util/bytes_range.rs
=> chore: typo-fix

src/layers/retry.rs, src/raw/oio/page.rs, src/raw/oio/read.rs, src/raw/oio/write.rs
feat/layers/retry: Add Write Retry support
=> feat/layers/retry: Add Write Retry support

src/services/azblob/backend.rs, src/services/azdfs/backend.rs, src/services/ftp/backend.rs, src/services/gcs/backend.rs, src/services/ghac/backend.rs, src/services/ipmfs/backend.rs, src/services/obs/backend.rs, src/services/oss/backend.rs, src/services/webdav/backend.rs, src/services/webhdfs/backend.rs, tests/behavior/utils.rs, tests/behavior/write.rs
=> feat: Add Write append tests

README.md
docs: Add convert from m*n to m+n
=> docs: Add convert from m*n to m+n

src/builder.rs, src/object/list.rs, src/object/metadata.rs, src/object/mode.rs, src/object/reader.rs, src/object/writer.rs, src/operator.rs
docs: Polish comments for public types
=> docs: Polish comments for public types

src/layers/concurrent_limit.rs, src/layers/type_eraser.rs, src/object/reader.rs
=> chore: fix typo

bindings/python/Cargo.toml, bindings/python/src/lib.rs, bindings/python/tests/main.py
feat(bindings/python): Add basic IO support
=> feat(bindings/python): Add basic IO support

README.md
=> docs: Add discord chat link

bindings/nodejs/index.d.ts, bindings/nodejs/src/lib.rs
remove duplicate attribute & unused comment
=> chore(bindings/nodejs): remove duplicate attribute & unused comment

src/operator/builder.rs, src/operator/metadata.rs, src/operator/mod.rs, src/operator/operator.rs
refactor: Promote operator as a mod for futher refactor
=> refactor: Promote operator as a mod for futher refactor

CHANGELOG.md, Cargo.toml, binaries/oli/Cargo.lock
=> Bump to version 0.29.1

src/services/s3/backend.rs
fix(services/s3): Make sure the ureq's body has been consumed
=> fix(services/s3): Make sure the ureq's body has been consumed

src/services/dashmap/backend.rs
=> feat(service/dashmap): Add scan support

.github/workflows/bindings_nodejs.yml, .github/workflows/bindings_python.yml
ci: Don't run binding tests if only services changes
=> ci: Don't run binding tests if only services changes

bindings/nodejs/__test__/index.spec.ts, bindings/nodejs/index.js, bindings/nodejs/package.json, bindings/nodejs/src/lib.rs, bindings/nodejs/yarn.lock
=> feat(bindings/nodejs): Add Writer Support

src/raw/accessor.rs, src/types/builder.rs
feat: Add dummy implementation fir accessor and builder
=> feat: Add dummy implementation for accessor and builder

Cargo.toml, bindings/nodejs/src/lib.rs, src/docs/features.md
- support `Operator.list`
- append all default services
=> feat(bindings/nodejs): Support List & append all default services

bindings/python/src/lib.rs, bindings/python/tests/main.py
feat(bindings/python): Setup operator init logic
=> feat(bindings/python): Setup operator init logic

bindings/nodejs/README.md
=> docs(bindings/nodejs): update readme

.github/workflows/bindings_nodejs.yml, .github/workflows/bindings_python.yml
ci: Fix bindings CI not running on PR
=> ci: Fix bindings CI not running on PR

src/services/s3/error.rs
Fix https://github.com/datafuselabs/opendal/issues/1531
=> fix(services/s3): Allow retry error RequestTimeout

src/types/operator/blocking_operator.rs, src/types/operator/operator.rs
docs: Add detailed docs for create_dir
Close https://github.com/datafuselabs/opendal/issues/1535
=> docs: Add detailed docs for create_dir

src/types/entry.rs, tests/behavior/blocking_list.rs, tests/behavior/list.rs
=> feat: Append `EntryMode` to `Entry`

bindings/nodejs/npm/darwin-x64/package.json, bindings/nodejs/npm/linux-x64-gnu/package.json, bindings/nodejs/npm/win32-x64-msvc/package.json, bindings/nodejs/package.json
update license in package.json
=> chore(bindings/nodejs): update license in package.json

.github/workflows/bindings_nodejs.yml, .github/workflows/bindings_python.yml, .github/workflows/publish.yml
ci: Fix python & nodejs not released correctly
=> ci: Fix python & nodejs not released correctly

CHANGELOG.md, Cargo.lock, Cargo.toml, bindings/nodejs/Cargo.toml, bindings/object_store/Cargo.toml, bindings/python/Cargo.toml
=> Bump to version 0.30.1

.github/workflows/bindings_nodejs.yml, .github/workflows/bindings_python.yml, bindings/nodejs/npm/darwin-x64/package.json, bindings/nodejs/npm/linux-x64-gnu/package.json, bindings/nodejs/npm/win32-x64-msvc/package.json, bindings/nodejs/package.json
ci(bindings/nodejs): Fix nodejs package can't uploaded
=> ci(bindings/nodejs): Fix nodejs package can't uploaded

CHANGELOG.md, Cargo.lock, Cargo.toml, bindings/nodejs/Cargo.toml, bindings/nodejs/npm/darwin-x64/package.json, bindings/nodejs/npm/linux-x64-gnu/package.json, bindings/nodejs/npm/win32-x64-msvc/package.json, bindings/nodejs/package.json, bindings/object_store/Cargo.toml, bindings/python/Cargo.toml
=> Bump to version 0.30.2

bindings/python/README.md, bindings/python/pyproject.toml
Signed-off-by: Frost Ming <me@frostming.com>
- Fix the metadata for Python binding package
- Add a usage section to the README as well as package description
=> fix(bindings/python): Fix the metadata for Python binding

.github/workflows/bindings_nodejs.yml, bindings/nodejs/README.md, bindings/nodejs/index.js, bindings/nodejs/npm/darwin-x64/README.md, bindings/nodejs/npm/linux-x64-gnu/README.md, bindings/nodejs/npm/win32-x64-msvc/README.md, bindings/nodejs/package.json, licenserc.toml
add some props to readme
And we should generate files to publish
=> chore(bindings/nodejs): fix missing files to publish

src/types/operator/operator.rs
=> fix: Operator::remove_all behaviour on non-existing object fixed

src/layers/logging.rs, src/layers/metrics.rs, src/layers/tracing.rs
feat: Implement logging/metrics/tracing support for Writer/BlockingWriter
- fixes https://github.com/datafuselabs/opendal/issues/1444
- fixes https://github.com/datafuselabs/opendal/issues/1443
- fixes https://github.com/datafuselabs/opendal/issues/1442
=> feat: Implement logging/metrics/tracing support for Writer/BlockingWriter

.github/workflows/docs.yml
=> website: Fix CNAME not set

Cargo.lock, bindings/python/Cargo.toml, bindings/python/src/asyncio.rs, bindings/python/src/layers.rs, bindings/python/src/lib.rs, bindings/python/tests/test_core.py, src/layers/concurrent_limit.rs, src/layers/retry.rs
Expose some useful built-in layers to Python, though there are no ways to implement custom layers in Python yet.
=> feat(bindings/python): expose layers to Python

Cargo.lock, Cargo.toml, bindings/c/.gitignore, bindings/c/Cargo.toml, bindings/c/cbindgen.toml, bindings/c/include/opendal.h, bindings/c/src/lib.rs, bindings/c/tests/Makefile, bindings/c/tests/hello.c
draft: try to integrate with cbindgen
=> feat(bindings/c): Setup the integrate with cbindgen

.github/workflows/bindings_python.yml, bindings/python/README.md, bindings/python/pyproject.toml, bindings/python/test_requirements.txt
I don't think we need to maintain `*-requirements.txt`. `pyproject.toml` is powerful.
=> chore: manage deps with maturin

.asf.yml
=> ci: Setup asf config

.asf.yaml, .asf.yml
=> chore: Rename files to yaml

.asf.yaml, .github/workflows/docs.yml
=> website: Fix website publish

.asf.yaml
=> ci: Update Github homepage

.asf.yaml
ci: Update description for OpenDAL
=> ci: Update description for OpenDAL

README.md
Update the addresses of old issues and discussions (even if you do an address jump), and resize the LICENSE on the page.
=> docs: update the old address and the LICENSE size.

DISCLAIMER, NOTICE
According to ASF policies - https://incubator.apache.org/policy/incubation.html#disclaimers
=> chore: add NOTICE and DISCLAIMER

src/raw/accessor.rs, src/services/oss/backend.rs, src/services/s3/backend.rs, src/types/operator/blocking_operator.rs
This is an experimental PR for https://github.com/datafuselabs/opendal/pull/1610#discussion_r1136898820, feel free to comment.
=> feat: add max_batch_operations for AccessorInfo

website/docusaurus.config.js, website/src/css/custom.css
- fix link in website
- modify font-size of copyright
=> doc: update doc-link

src/raw/adapters/kv/api.rs, src/raw/adapters/kv/backend.rs, src/services/redis/backend.rs
=> services/redis: Implement Write::append with native support

bindings/nodejs/.prettierignore, bindings/nodejs/README.md, bindings/nodejs/cucumber.json, bindings/nodejs/package.json, bindings/nodejs/tests/binding.js, bindings/nodejs/tsconfig.json, bindings/nodejs/yarn.lock, licenserc.toml
Add `prettier` for formatting automatically.
=> ci(bindings/nodejs): Enable formatter

core/src/services/gcs/backend.rs, core/src/services/obs/backend.rs, core/src/services/oss/backend.rs, core/src/services/s3/backend.rs
=> fix: Bucket config related error is misleadling

.devcontainer/devcontainer.json, .github/workflows/service_test_azblob.yml, .github/workflows/service_test_azdfs.yml, .github/workflows/service_test_dashmap.yml, .github/workflows/service_test_fs.yml, .github/workflows/service_test_ftp.yml, .github/workflows/service_test_gcs.yml, .github/workflows/service_test_ghac.yml, .github/workflows/service_test_hdfs.yml, .github/workflows/service_test_http.yml, .github/workflows/service_test_ipfs.yml, .github/workflows/service_test_ipmfs.yml, .github/workflows/service_test_memcached.yml, .github/workflows/service_test_memory.yml, .github/workflows/service_test_moka.yml, .github/workflows/service_test_obs.yml, .github/workflows/service_test_oss.yml, .github/workflows/service_test_redis.yml, .github/workflows/service_test_rocksdb.yml, .github/workflows/service_test_s3.yml, .github/workflows/service_test_sled.yml, .github/workflows/service_test_webdav.yml, .github/workflows/service_test_webhdfs.yml, core/src/services/s3/backend.rs
Some services like R2 could return a upload id with space
Fix https://github.com/apache/incubator-opendal/issues/1689
=> fix(services/s3): UploadId should be percent encoded

.github/workflows/publish.yml, CHANGELOG.md, Cargo.lock, binaries/oli/Cargo.toml
We will release 0.30.3 first and start making ASF release since next minor version (0.31)
=> Bump to 0.30.3 with new changelog

core/src/raw/accessor.rs, core/src/raw/layer.rs, core/src/types/operator/builder.rs
Found a few typos in the comment while reading through the code.
=> Minor: Fix a few typos in code comment

bindings/nodejs/README.md, bindings/nodejs/index.d.ts, bindings/nodejs/src/lib.rs
update bindings/nodejs' README
=> chore(bindins/nodejs): Update README

.github/actions/setup/action.yaml, .github/workflows/service_test_rocksdb.yml, Cargo.lock, core/Cargo.toml
bump rocksdb to 0.18.0 , librocksdb-sys to 0.6.1(+6.28.2)
=> chore: bump rocksdb to resolve dependency conflicts with magnus

core/src/types/operator/blocking_operator.rs, core/src/types/operator/operator.rs
fix https://github.com/apache/incubator-opendal/issues/1732
=> chore: improve NotADirectory error message with ending slash

Cargo.lock
Changelog: https://github.com/PyO3/pyo3/releases/tag/v0.18.2
=> chore(bindings/python): update pyo3 to 0.18.2

bin/oli/Cargo.toml, bin/oli/src/bin/oli.rs, bin/oli/src/commands/cat.rs, bin/oli/src/commands/mod.rs
=> feat(oli): implement `oli cat`

.github/actions/setup/action.yaml, .github/workflows/typos.yml, Cargo.lock
Target is larger and larger....
=> ci: Remove target from cache

bin/oli/src/bin/oli.rs, bin/oli/src/commands/cli.rs, bin/oli/src/commands/mod.rs, bin/oli/src/commands/rm.rs
=> feat(oli): implement `oli rm`

bin/oli/src/commands/ls.rs, bin/oli/src/commands/rm.rs
=> refactor(oli): switch to `Operator::scan` and `Operator::remove_all`

bindings/object_store/src/lib.rs
Also added some simple tests for list and list_with_delimiter.
Ref issue: #1733
https://github.com/apache/incubator-opendal/blob/6f8ab1700bae2b4124f6615ca5fb6ff9d7ffa4b8/bindings/object_store/src/lib.rs#L157
Here our `scan` result does not return path to the error, so I'm putting a empty string here. So for `list_with_delimiter`. Hope what I understand is correct.
=> feat(bindings/object_store): Add support for list and list_with_delimiter

bin/oli/src/bin/oli.rs, bin/oli/src/commands/cat.rs, bin/oli/src/commands/cli.rs, bin/oli/src/commands/cp.rs, bin/oli/src/commands/ls.rs, bin/oli/src/commands/rm.rs, bin/oli/src/commands/stat.rs
=> chore(oli): set cli version in a central place

core/Cargo.toml
=> chore: don't pin time version

bin/oli/src/commands/cp.rs
=> feat(oli): implement `oli cp -r`

.github/workflows/bindings_nodejs.yml, bindings/nodejs/npm/darwin-arm64/README.md, bindings/nodejs/package.json
https://www.apache.org/legal/release-policy.html#licensing-documentation
=> ci(bindings/nodejs): publish with LICENSE & NOTICE

bindings/nodejs/benchmark/read.js
=> fix(bindings/nodejs): fix read benchmark

.github/workflows/bindings_java.yml
I made a wrong operation which closes previous ticket automatically.
Sorry for the inconvenience.
=> feat(bindings/java): setup Java CI

core/src/services/s3/backend.rs, core/src/types/ops.rs
Add  if_none_match to OpStat and OpRead. Close #1749
=> feat: add if_none_match support

core/src/services/fs/backend.rs
Add necessary operations before doing copy
- ensure source file
- ensure target parent path
=> fix(core): Add checks before doing copy

core/tests/behavior/blocking_copy.rs, core/tests/behavior/blocking_list.rs, core/tests/behavior/blocking_read.rs, core/tests/behavior/blocking_write.rs, core/tests/behavior/copy.rs, core/tests/behavior/list.rs, core/tests/behavior/main.rs, core/tests/behavior/presign.rs
=> feat(core): add behavior tests for copy & blocking_copy

core/src/services/s3/backend.rs
=> feat(s3): Support copy

core/src/layers/logging.rs, core/src/raw/accessor.rs, core/src/raw/layer.rs, core/src/raw/operation.rs, core/src/raw/rps.rs, core/src/services/fs/backend.rs, core/src/types/operator/blocking_operator.rs, core/src/types/operator/metadata.rs, core/src/types/operator/operator.rs, core/src/types/ops.rs, core/tests/behavior/blocking_rename.rs, core/tests/behavior/main.rs, core/tests/behavior/rename.rs
=> feat(core): Support rename

core/src/services/obs/backend.rs
=> feat(services/obs): Add Copy Support

core/src/services/webdav/backend.rs, core/src/services/webdav/fixtures/nginx-with-basic-auth.conf, core/src/services/webdav/fixtures/nginx.conf
Add `rename` support for WebDAV
=> feat(services/webdav): Support Rename

bindings/c/src/types.rs
forget to clean up the comments and one more type assertion in the previous PR
=> binding/c: clean up comments and type assertion for BlockingOperator

bindings/nodejs/src/lib.rs
Update example for presign funcs #1900
=> doc(bindings/nodejs): update presign example in doc

.github/workflows/service_test_webhdfs.yml, core/src/services/webhdfs/pager.rs
Fix https://github.com/apache/incubator-opendal/issues/1888
=> ci: Re-enable webhdfs test

bindings/python/pyproject.toml
=> docs(bindings/python): fix wrong doc link

core/src/services/azdfs/backend.rs, core/src/services/azdfs/core.rs
Add `rename` support for azdfs
=> feat(services/azdfs): support rename

bindings/python/pyproject.toml, core/src/services/webhdfs/backend.rs, core/src/services/webhdfs/message.rs, core/src/services/webhdfs/pager.rs, core/src/services/webhdfs/writer.rs
This PR just polish the implementaion of webhdfs, improve the code readability.
=> refactor: Polish the implementaion of webhdfs

core/src/services/azblob/error.rs, core/src/services/azdfs/error.rs, core/src/services/gcs/error.rs, core/src/services/http/error.rs, core/src/services/obs/error.rs, core/src/services/oss/error.rs, core/src/services/s3/error.rs, core/src/types/error.rs
Fix https://github.com/apache/incubator-opendal/issues/1833
=> feat: Add PreconditionFailed Error so users can handle them

core/src/docs/comparisons/mod.rs, core/src/docs/comparisons/vs_object_store.md
This PR is for fixing some typos of opendal docs.
=> docs: fix some typos

README.md, bindings/c/README.md, bindings/c/build.rs
- add Build section to readme to list required dependencies
- optimize c binding build script to guide users to install clang-format
Closes #2020
=> docs: add dev dependency section

core/src/layers/minitrace.rs, core/src/layers/tracing.rs
=> feat: Add missing functions for trace layers

core/src/layers/complete.rs, core/src/raw/http_util/body.rs, core/src/types/error.rs, core/src/types/operator/operator.rs, core/src/types/writer.rs
This PR adds a size check for writer at complete layer.
=> feat: Add size check for sized writer

Cargo.lock, bin/oay/Cargo.toml, bin/oay/README.md, bin/oay/lib.rs, bin/oay/src/bin/oay.rs
oay is an old project that deleted before.
This PR will bring it back to live and build some intereting use cases.
=> feat: Bootstrap new (old) project oay

core/src/services/http/backend.rs
=> feat: add IF_MATCH for http

core/src/services/http/backend.rs
=> feat: add IF_MATCH for http HEAD request

core/src/services/azblob/backend.rs, core/src/services/azblob/core.rs, core/src/services/azblob/writer.rs, core/src/services/obs/backend.rs, core/src/services/obs/core.rs, core/src/services/obs/writer.rs
=> chore: add cache control header for azblob and obs

Cargo.lock, bindings/ruby/Cargo.toml, bindings/ruby/build.rs
=> fix(bindings/ruby): use rb_sys_env to help find ruby for building

core/src/raw/http_util/client.rs
This PR will:
- Add url in error context for better debugging, fix https://github.com/apache/incubator-opendal/issues/1384
- Optimize response build by swap HeaderMap instead of clone.
=> refactor(raw/http_util): Add url in error context

core/src/services/s3/backend.rs
Not sure mentioning COS is suitable, but COS is also a widely used object storage.
Feel free to close/merge this PR. @Xuanwo
=> chore: add tencent COS as a kind of s3 compatible backend in doc

bindings/nodejs/examples/README.md, bindings/nodejs/examples/example_s3.js
close: #2077 
A simple test for s3. Any suggestion? I will try add in the example.
=> chore(bindings/nodejs): Add s3 example

core/src/services/obs/backend.rs, core/src/services/obs/core.rs
This fixes: https://github.com/apache/incubator-opendal/issues/1976
CC @Xuanwo
=> feat: add if_none_match support for obs

core/src/services/oss/backend.rs, core/src/services/oss/core.rs
close #1981 
I am not very familiar with OSS, so I'm not sure if there are any missing pieces. If there are any errors, please let me know.
=> feat(services/oss): Add server side encryption support for oss

core/src/services/azblob/error.rs, core/src/services/azdfs/error.rs, core/src/services/gcs/error.rs, core/src/services/http/error.rs, core/src/services/obs/error.rs, core/src/services/oss/error.rs, core/src/services/s3/error.rs, core/src/services/wasabi/error.rs, core/src/types/error.rs, core/tests/behavior/write.rs
Modify the name of this error category to make its meaning clearer.
=> feat(core): update errorKind `PreconditionFailed` to `ConditionNotMatch`

core/src/docs/comparisons/vs_object_store.md, core/src/docs/concepts.rs, core/src/docs/internals/accessor.rs, core/src/raw/accessor.rs, core/src/raw/adapters/kv/backend.rs, core/src/services/memory/backend.rs, core/src/types/builder.rs, core/src/types/operator/operator.rs
1. give a more detailed description of operator, accessor, and builder.
2. fixed some typos.
=> docs(refactor): Add more detailed description of operator, accessor, and builder

core/src/services/azblob/error.rs, core/src/services/gcs/backend.rs, core/src/services/gcs/core.rs, core/src/services/gcs/error.rs, core/src/services/http/backend.rs, core/src/services/http/error.rs, core/src/services/obs/backend.rs, core/src/services/obs/error.rs, core/src/services/oss/backend.rs, core/src/services/oss/error.rs, core/src/services/wasabi/backend.rs, core/tests/behavior/read_only.rs, core/tests/behavior/write.rs
part of #2060 
- add test for `stat_with_if_none_match`
- enable `stat_with_if_none_match` for several services.
=> feat(core): add test for `stat_with_if_none_match`

.github/workflows/service_test_azdfs.yml, .github/workflows/service_test_gcs.yml, .github/workflows/service_test_ghac.yml, .github/workflows/service_test_obs.yml, .github/workflows/service_test_oss.yml, .github/workflows/service_test_s3.yml
Fix https://github.com/apache/incubator-opendal/issues/2127
=> ci: Mark job as skipped if owner is not apache

core/src/services/gcs/backend.rs, core/src/services/gcs/core.rs
=> feat(services/gcs): Add supporting presign support

core/src/services/hdfs/backend.rs
=> docs: add hdfs classpath related troubleshoot

bindings/java/src/lib.rs
=> fix(clippy): suppress dead_code check

core/src/services/gcs/backend.rs, core/src/services/obs/backend.rs, core/src/services/oss/backend.rs, core/src/services/s3/backend.rs, core/tests/behavior/write.rs
Add test for `write_with_content_type`
=> test(core): test for `write_with_content_type`

CONTRIBUTING.md, Cargo.toml, DEVELOPING.md, README.md, bindings/java/Cargo.toml, bindings/java/src/lib.rs, bindings/ruby/Cargo.toml, core/src/raw/http_util/multipart.rs, core/src/services/gcs/core.rs, core/src/services/mod.rs, core/src/services/onedrive/backend.rs, core/src/services/onedrive/builder.rs, core/src/services/supabase/backend.rs, core/src/services/supabase/error.rs, core/src/types/operator/operator.rs, core/tests/behavior/write.rs, rustfmt.toml
This PR will refactor Contributing and add Developing for a start.
=> docs: Refactor `Contributing` and add `Developing`

core/src/services/s3/backend.rs, core/src/services/s3/error.rs
* set retryable on batch
* add more retryable errors
Close: #2158
=> fix(service/s3): set retryable on batch

core/src/raw/accessor.rs, core/src/services/azblob/backend.rs, core/src/services/azdfs/backend.rs, core/src/services/fs/backend.rs, core/src/services/ftp/backend.rs, core/src/services/gcs/backend.rs, core/src/services/hdfs/backend.rs, core/src/services/ipfs/backend.rs, core/src/services/ipmfs/backend.rs, core/src/services/obs/backend.rs, core/src/services/oss/backend.rs, core/src/services/s3/backend.rs, core/src/services/sftp/backend.rs, core/src/services/wasabi/backend.rs, core/src/services/webdav/backend.rs, core/src/services/webhdfs/backend.rs, core/src/types/capability.rs, core/src/types/ops.rs
Note that this PR does not include any changes to the KV adapter, as I am uncertain about how to implement modifications in that area. If updating the KV adapter is also required for this PR, I kindly request guidance on the appropriate steps to take. 🙇
=> feat(core): merge scan and list

core/src/services/azblob/backend.rs, core/src/services/azdfs/backend.rs, core/src/services/dashmap/backend.rs, core/src/services/fs/backend.rs, core/src/services/ftp/backend.rs, core/src/services/gcs/backend.rs, core/src/services/gdrive/builder.rs, core/src/services/ghac/backend.rs, core/src/services/hdfs/backend.rs, core/src/services/http/backend.rs, core/src/services/ipfs/backend.rs, core/src/services/ipmfs/backend.rs, core/src/services/memcached/backend.rs, core/src/services/memory/backend.rs, core/src/services/moka/backend.rs, core/src/services/obs/backend.rs, core/src/services/oss/backend.rs, core/src/services/redis/backend.rs, core/src/services/rocksdb/backend.rs, core/src/services/s3/backend.rs, core/src/services/sftp/backend.rs, core/src/services/sled/backend.rs, core/src/services/supabase/backend.rs, core/src/services/vercel_artifacts/backend.rs, core/src/services/vercel_artifacts/builder.rs, core/src/services/wasabi/backend.rs, core/src/services/webdav/backend.rs, core/src/services/webhdfs/backend.rs, core/src/types/capability.rs
=> feat(core): check capability

.github/workflows/service_test_supabase.yml
This PR adds integration tests for supabase.
Fix https://github.com/apache/incubator-opendal/issues/2151
=> ci: Add integration tests for supabase
